// GENERATED by scripts/build-faces-spec.py from jarvis-visual-spec.json.
// Do not edit: edit the JSON and re-run `npm run faces:spec`.
//
// This exists so the Faces window and the Rust tray read one spec rather than
// two. `spec.rs` compiles the same JSON in with `include_str!`; the kit this
// window came from had its own pasted copy, which had drifted to seven states
// against the live eight.
window.JARVIS_SPEC = Object.freeze({
  "audit_history": [
    {
      "changes": [
        "colour crossfade 300ms",
        "speech envelope + synthetic fallback",
        "approval waiting clock, tint delay",
        "thinking default cool sweep",
        "speaking default reactive ice",
        "error default rose pulse",
        "gradient: bound colour wins",
        "unified background",
        "depth_gain 1.6",
        "per-state fps",
        "glow sprite bloom (canvas)",
        "tap ack + drag inertia",
        "fit framing",
        "kirkwood sun palette",
        "coreplate never white",
        "spectrum bar cap",
        "iris catchlight",
        "flash governor per surface (bug found by the re-render)"
      ],
      "date": "2026-09-14",
      "kind": "visual (rendered images, six specialists + three cross-talks)"
    }
  ],
  "color_slots": {
    "dim": [
      "col",
      "glow",
      "b"
    ],
    "hot": [
      "hot",
      "a"
    ],
    "note": "Which of a face's colour slots receives the bright bound colour. This is matched BY NAME, not by declaration order. Order was the original rule and it was wrong for half the set: ten faces declare the structural colour first (col/glow), so the dim slot received the bright value and the hot accent received the darkened one. Every one of those faces was drawing its bound colour inside out.",
    "other": "anything else (e.g. `neg`, a second contrasting hue) takes the midpoint"
  },
  "colour_science": {
    "delta_e_2000": {
      "amber-4 vs rose-4": {
        "deuteranopia": 15.6,
        "normal": 36.2
      },
      "ember-4 vs amber-4": {
        "deuteranopia": 4.5,
        "normal": 12.1
      },
      "ember-4 vs rose-4": {
        "deuteranopia": 12.0,
        "normal": 24.8
      },
      "verdant-4 vs ember-4": {
        "deuteranopia": 16.7,
        "normal": 50.1
      },
      "verdant-4 vs rose-4": {
        "deuteranopia": 8.2,
        "normal": 67.7
      }
    },
    "note": "CIE Delta-E 2000 is the standard score for how different two colours look: under 2 indistinguishable, ~10 obviously different at arm's length, 20+ across a room. Deuteranopia simulated with the Machado 2009 matrix. Conclusion: moving listening to green trades the listening/approval collision (4.5) for a listening/error one (8.2), so hue alone cannot separate the warm states for everyone; motion must. Option kept open for the owner: re-bind approval to verdant-5 (the randomiser already sanctions green for approval), which lifts listening/approval to 41 (18.7 deuteranope)."
  },
  "faces": [
    {
      "archived": false,
      "dim": "2d",
      "geometry": "concentric rings",
      "heavy": false,
      "id": "arc",
      "integrates_per_frame": false,
      "name": "Arc",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "5 inclined orbits, depth sorted",
      "heavy": false,
      "id": "orbit",
      "integrates_per_frame": false,
      "name": "Orbit",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "subdivided icosahedron",
      "heavy": false,
      "id": "geodesic",
      "integrates_per_frame": false,
      "name": "Geodesic",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "32 extruded bars in a ring",
      "heavy": false,
      "id": "spectrum",
      "integrates_per_frame": true,
      "name": "Spectrum",
      "render": {
        "fit": 0.86,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "parametric torus, shaded quads",
      "heavy": true,
      "id": "tokamak",
      "integrates_per_frame": false,
      "name": "Tokamak",
      "render": {
        "fit": 1.0,
        "gpu": true,
        "max_px": 1800,
        "note": "parametric torus: drawn as a smooth-shaded mesh with an analytic normal by the GPU. The CPU fallback fills flat quads and is visibly faceted.",
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 3.0,
        "min": 0.1,
        "substeps_max": 3
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "boids with depth",
      "heavy": false,
      "id": "swarm",
      "integrates_per_frame": true,
      "name": "Swarm",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "layered armour plates",
      "heavy": false,
      "id": "coreplate",
      "integrates_per_frame": true,
      "name": "Coreplate",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "exploded assembly",
      "heavy": false,
      "id": "workbench",
      "integrates_per_frame": true,
      "name": "Workbench",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "Verlet spring-mass sheet",
      "heavy": false,
      "id": "membrane",
      "integrates_per_frame": true,
      "name": "Membrane",
      "render": {
        "fit": 1.0,
        "gpu": true,
        "max_px": 1800,
        "note": "spring-mass sheet: simulated on the CPU, drawn as a triangle mesh by the GPU with a depth buffer. The CPU fallback fills one flat quad per cell and is visibly faceted above a thumbnail.",
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "nucleon shell packing",
      "heavy": true,
      "id": "nucleus",
      "integrates_per_frame": false,
      "name": "Nucleus",
      "render": {
        "fit": 0.92,
        "gpu": true,
        "max_px": 1800,
        "note": "ray-marched signed distance field: rendered by a fragment shader at full pixel resolution where WebGL2 / GLES3 is available. The CPU fallback draws into a small buffer and upscales, so it is capped at 460 px there.",
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "render_cpu_fallback": {
        "max_px": 460,
        "target_fps": 45
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 3.0,
        "min": 0.1,
        "substeps_max": 3
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "hex lattice",
      "heavy": false,
      "id": "comb",
      "integrates_per_frame": false,
      "name": "Comb",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "overlapping aperture blades",
      "heavy": false,
      "id": "iris",
      "integrates_per_frame": true,
      "name": "Iris",
      "render": {
        "fit": 0.86,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "schooling agents",
      "heavy": false,
      "id": "shoal",
      "integrates_per_frame": true,
      "name": "Shoal",
      "render": {
        "fit": 0.8,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "random-walk accretion disc",
      "heavy": false,
      "id": "accretion",
      "integrates_per_frame": true,
      "name": "Accretion",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "falling particle columns",
      "heavy": false,
      "id": "cascade",
      "integrates_per_frame": true,
      "name": "Cascade",
      "render": {
        "fit": 0.82,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 4.0,
        "min": 0.1,
        "substeps_max": 4
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "crystal growth",
      "heavy": false,
      "id": "rime",
      "integrates_per_frame": false,
      "name": "Rime",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "electron probability cloud",
      "heavy": false,
      "id": "orbital",
      "integrates_per_frame": false,
      "name": "Orbital",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "truncated icosahedron cage",
      "heavy": false,
      "id": "fullerene",
      "integrates_per_frame": false,
      "name": "Fullerene",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "logarithmic arms",
      "heavy": false,
      "id": "spiral",
      "integrates_per_frame": false,
      "name": "Spiral",
      "render": {
        "fit": 1.0,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    },
    {
      "archived": false,
      "dim": "3d",
      "geometry": "resonance gaps in a belt",
      "heavy": false,
      "id": "kirkwood",
      "integrates_per_frame": false,
      "name": "Kirkwood",
      "render": {
        "fit": 0.9,
        "max_px": 1800,
        "supersample_max": 2.0,
        "target_fps": 60
      },
      "speed": {
        "curve": "log",
        "default": 1.0,
        "max": 6.0,
        "min": 0.05,
        "substeps_max": 1
      }
    }
  ],
  "frame_rate": {
    "android": {
      "cannot_guarantee": [
        "battery saver can cap the display refresh rate",
        "LTPO / Adaptive Refresh Rate panels float the rate by content cadence",
        "many OEMs drop to 60/90Hz at low screen brightness",
        "thermal throttling",
        "a higher-priority surface may have set a different rate",
        "There is no API that reports WHY you did not get the rate you asked for. Detect the outcome with Display.getRefreshRate() and DisplayManager.DisplayListener.onDisplayChanged(), degrade, and never assume the requested rate was granted."
      ],
      "clock": "Compose's frame clock is Choreographer-backed and is NOT capped - withFrameNanos inside a LaunchedEffect fires at whatever rate the system negotiated. Always advance animation by the frameTimeNanos delta, never by an assumed 1/120.",
      "detect": {
        "alternatives": "Display.Mode.getAlternativeRefreshRates(): FloatArray  (API 31)",
        "current_rate": "Display.getRefreshRate(): Float  (API 1)",
        "get_display": "Context.getDisplay()  (API 30). WindowManager.getDefaultDisplay() is deprecated from API 30.",
        "mode_rate": "Display.Mode.getRefreshRate(): Float  (API 23)",
        "supported_modes": "Display.getSupportedModes() -> Display.Mode[]  (API 23)"
      },
      "measure_achieved": "Average the deltas between successive withFrameNanos callbacks. For jank specifically use androidx.metrics JankStats (built on FrameMetrics, API 24+).",
      "request": {
        "compatibility_constant": "FRAME_RATE_COMPATIBILITY_DEFAULT - this is the one for UI and games. FRAME_RATE_COMPATIBILITY_FIXED_SOURCE is for VIDEO players and is the wrong choice here.",
        "legacy": "WindowManager.LayoutParams.preferredDisplayModeId (API 23) still works but has been discouraged by Google since Android 11 - the platform cannot see the app's rendering intent. preferredRefreshRate changed semantics at API 34.",
        "newest": "View.setRequestedFrameRate(Float) / REQUESTED_FRAME_RATE_CATEGORY_* (API 35), and the Compose `preferredFrameRate` Modifier. Feeds Adaptive Refresh Rate rather than pinning a number.",
        "recommended": "Surface.setFrameRate(frameRate, Surface.FRAME_RATE_COMPATIBILITY_DEFAULT, Surface.CHANGE_FRAME_RATE_ONLY_IF_SEAMLESS)  (3-arg: API 31; 2-arg: API 30)"
      }
    },
    "budget": {
      "downgrade_above": 1.45,
      "rule": "budget_ms = 1000 / (hz / stride)",
      "upgrade_below": 0.55,
      "why": "Thresholds are fractions of the measured budget, never fixed milliseconds. At 120Hz the budget is 8.3ms, so a governor tuned to 60Hz thinks a 20ms frame is healthy while the display is running at half rate."
    },
    "default": "auto",
    "note": "High refresh is NOT symmetrical across the two renderers, and that asymmetry is the whole reason this block exists. On the web there is no API to ask for a higher rate - requestAnimationFrame already fires at whatever the display is running at, so the only work is measuring it and budgeting against the real number. On Android the opposite is true: many phones render an app at 60Hz until it explicitly asks for more.",
    "pacing": {
      "min_fps": 30,
      "rule": "divisor",
      "why": "If a face cannot hold the full rate, drop to a whole divisor (120 -> 60 -> 40 -> 30) rather than chasing an uneven number. Every frame then lands on a real vsync. A locked 60 on a 120Hz panel looks better than a floating 75."
    },
    "state_fps": {
      "banked": 2,
      "idle": 30,
      "standby": 15
    },
    "state_fps_why": "Idle, standby and banked are more than nine tenths of screen-on time and every face drew them at the full display rate. The shell accumulates time and skips vsyncs for these states, handing the accumulated dt to the draw so motion covers the same distance. The first 600ms after any state change, and any tap acknowledgement, run at full rate so no transition stutters. Banked at 2fps is just enough to catch a new notch. Active states are untouched.",
    "targets": [
      "auto",
      "60",
      "120",
      "max"
    ],
    "web": {
      "detect": "median of requestAnimationFrame intervals over ~40-90 samples",
      "note": "No shipping browser has a way to request a rate. The W3C VSYNC proposal (w3c/html#375) never shipped. Measure only.",
      "request_api": null,
      "snap_to": [
        60,
        75,
        90,
        100,
        120,
        144,
        165,
        240
      ]
    }
  },
  "framing": {
    "fit_field": "faces[].render.fit - a uniform scale the shell applies around the draw. 1.0 for faces that already sit inside a circle with air around them.",
    "fit_values": {
      "cascade": 0.82,
      "iris": 0.86,
      "kirkwood": 0.9,
      "nucleus": 0.92,
      "shoal": 0.8,
      "spectrum": 0.86
    },
    "rule": "The active silhouette fits inside 70% of the shorter edge, leaving room for the HUD, the rim ring and the notches."
  },
  "interaction": {
    "drag": {
      "inertia_tau_s": 0.45,
      "max_rad_s": 4,
      "pitch_limit_rad": 1.4,
      "pitch_per_px": 0.006,
      "why": "A released face keeps turning and settles instead of stopping dead under the finger.",
      "yaw_per_px": 0.008
    },
    "hover": "Other faces read TOUCH for their own hover cues; Iris does not track the cursor.",
    "planned": [
      "hold = push-to-talk",
      "gyro parallax 2-3px on the rim only (phone)",
      "pinch to minimise to the 44px ring",
      "transcript orbiting the rim while speaking",
      "banked items as particles caught in the outer ring"
    ],
    "tap": {
      "flinch_px_frac": 0.01,
      "flinch_s": 0.15,
      "ring_frac": 0.28,
      "ring_s": 0.15,
      "why": "Within one frame of a touch, before the model has said anything, the face flinches ~1% of its width away from the finger and a thin ring in the state colour leaves the touch point and fades over 150ms. It is the 'I felt that' of a physical object, identical on every face and in every state."
    },
    "wheel_pinch": "zoom 0.45-3x; double-tap resets the view"
  },
  "limits": {
    "flash": {
      "flicker_harmonic": 2.3,
      "flicker_rate_hz_max": 1.3,
      "max_transitions_per_s": 3,
      "min_luma_delta": 0.1,
      "note": "Photosensitive-seizure bounds. The face fills well over a quarter of the visual field at phone reading distance, so the small-area exemption in the guidance does not apply and these are hard limits, not advice. Enforced in three places: the randomiser will not generate parameters that break them, a governor inside resolve() holds the colour when a fourth opposing transition would land inside one second, and a build check replays every pattern at both parameter extremes. resolve() is the only path to a colour, so a hand-written binding cannot get past it.",
      "scope": "per surface",
      "scope_why": "The governor keeps one window per SURFACE (and one for the UI swatches). A single page-wide window, fed by every surface in turn, saw twenty faces with twenty clocks as one face flashing between twenty colours, spent its budget on those cross-surface transitions and then held one face's colour on another. Found 14 Sep by the specimen rig; on the live grid it was the same fault with less contrast. A client that draws several reactors (a picker) must give each its own governor; a client that draws one needs one.",
      "strobe_max_s": 2.0,
      "why_these_numbers": "Three opposing transitions per second is the standard threshold. 0.10 relative luminance is the swing below which a transition is not counted. flicker's implementation adds a harmonic at 2.3x its stated rate, so the stated rate must stay below the limit divided by 2.3."
    }
  },
  "note": "One palette and one pattern vocabulary shared by every renderer. Android (Compose) and the Tauri desktop cannot share drawing code - one is Kotlin, one is JavaScript - so what they share is this DATA. Each renderer implements the 9 pattern kinds below and reads the same colours, so a face looks identical on both without either side owning the other's code.",
  "palette": {
    "colors": [
      {
        "argb": "0xFF0A3A4A",
        "argb_int": -16106934,
        "css": "#0a3a4a",
        "family": "ice",
        "hex": "#0a3a4a",
        "id": "ice-1",
        "name": "Ice Deep",
        "rgb": [
          10,
          58,
          74
        ],
        "step": 1
      },
      {
        "argb": "0xFF12657F",
        "argb_int": -15571585,
        "css": "#12657f",
        "family": "ice",
        "hex": "#12657f",
        "id": "ice-2",
        "name": "Ice Shade",
        "rgb": [
          18,
          101,
          127
        ],
        "step": 2
      },
      {
        "argb": "0xFF2EA8CC",
        "argb_int": -13719348,
        "css": "#2ea8cc",
        "family": "ice",
        "hex": "#2ea8cc",
        "id": "ice-3",
        "name": "Ice Core",
        "rgb": [
          46,
          168,
          204
        ],
        "step": 3
      },
      {
        "argb": "0xFF6FE3FF",
        "argb_int": -9444353,
        "css": "#6fe3ff",
        "family": "ice",
        "hex": "#6fe3ff",
        "id": "ice-4",
        "name": "Ice Bright",
        "rgb": [
          111,
          227,
          255
        ],
        "step": 4
      },
      {
        "argb": "0xFFB8F4FF",
        "argb_int": -4655873,
        "css": "#b8f4ff",
        "family": "ice",
        "hex": "#b8f4ff",
        "id": "ice-5",
        "name": "Ice Mist",
        "rgb": [
          184,
          244,
          255
        ],
        "step": 5
      },
      {
        "argb": "0xFF0C2A55",
        "argb_int": -15979947,
        "css": "#0c2a55",
        "family": "azure",
        "hex": "#0c2a55",
        "id": "azure-1",
        "name": "Azure Deep",
        "rgb": [
          12,
          42,
          85
        ],
        "step": 1
      },
      {
        "argb": "0xFF14479A",
        "argb_int": -15448166,
        "css": "#14479a",
        "family": "azure",
        "hex": "#14479a",
        "id": "azure-2",
        "name": "Azure Shade",
        "rgb": [
          20,
          71,
          154
        ],
        "step": 2
      },
      {
        "argb": "0xFF2F74E0",
        "argb_int": -13667104,
        "css": "#2f74e0",
        "family": "azure",
        "hex": "#2f74e0",
        "id": "azure-3",
        "name": "Azure Core",
        "rgb": [
          47,
          116,
          224
        ],
        "step": 3
      },
      {
        "argb": "0xFF62A3FF",
        "argb_int": -10312705,
        "css": "#62a3ff",
        "family": "azure",
        "hex": "#62a3ff",
        "id": "azure-4",
        "name": "Azure Bright",
        "rgb": [
          98,
          163,
          255
        ],
        "step": 4
      },
      {
        "argb": "0xFFB0D2FF",
        "argb_int": -5188865,
        "css": "#b0d2ff",
        "family": "azure",
        "hex": "#b0d2ff",
        "id": "azure-5",
        "name": "Azure Mist",
        "rgb": [
          176,
          210,
          255
        ],
        "step": 5
      },
      {
        "argb": "0xFF1A1A52",
        "argb_int": -15066542,
        "css": "#1a1a52",
        "family": "indigo",
        "hex": "#1a1a52",
        "id": "indigo-1",
        "name": "Indigo Deep",
        "rgb": [
          26,
          26,
          82
        ],
        "step": 1
      },
      {
        "argb": "0xFF2B2B8F",
        "argb_int": -13948017,
        "css": "#2b2b8f",
        "family": "indigo",
        "hex": "#2b2b8f",
        "id": "indigo-2",
        "name": "Indigo Shade",
        "rgb": [
          43,
          43,
          143
        ],
        "step": 2
      },
      {
        "argb": "0xFF4A4AD4",
        "argb_int": -11908396,
        "css": "#4a4ad4",
        "family": "indigo",
        "hex": "#4a4ad4",
        "id": "indigo-3",
        "name": "Indigo Core",
        "rgb": [
          74,
          74,
          212
        ],
        "step": 3
      },
      {
        "argb": "0xFF7B7BFF",
        "argb_int": -8684545,
        "css": "#7b7bff",
        "family": "indigo",
        "hex": "#7b7bff",
        "id": "indigo-4",
        "name": "Indigo Bright",
        "rgb": [
          123,
          123,
          255
        ],
        "step": 4
      },
      {
        "argb": "0xFFC0C0FF",
        "argb_int": -4144897,
        "css": "#c0c0ff",
        "family": "indigo",
        "hex": "#c0c0ff",
        "id": "indigo-5",
        "name": "Indigo Mist",
        "rgb": [
          192,
          192,
          255
        ],
        "step": 5
      },
      {
        "argb": "0xFF33115C",
        "argb_int": -13430436,
        "css": "#33115c",
        "family": "violet",
        "hex": "#33115c",
        "id": "violet-1",
        "name": "Violet Deep",
        "rgb": [
          51,
          17,
          92
        ],
        "step": 1
      },
      {
        "argb": "0xFF551F9C",
        "argb_int": -11198564,
        "css": "#551f9c",
        "family": "violet",
        "hex": "#551f9c",
        "id": "violet-2",
        "name": "Violet Shade",
        "rgb": [
          85,
          31,
          156
        ],
        "step": 2
      },
      {
        "argb": "0xFF8340E0",
        "argb_int": -8175392,
        "css": "#8340e0",
        "family": "violet",
        "hex": "#8340e0",
        "id": "violet-3",
        "name": "Violet Core",
        "rgb": [
          131,
          64,
          224
        ],
        "step": 3
      },
      {
        "argb": "0xFFAE7BFF",
        "argb_int": -5342209,
        "css": "#ae7bff",
        "family": "violet",
        "hex": "#ae7bff",
        "id": "violet-4",
        "name": "Violet Bright",
        "rgb": [
          174,
          123,
          255
        ],
        "step": 4
      },
      {
        "argb": "0xFFD9C0FF",
        "argb_int": -2506497,
        "css": "#d9c0ff",
        "family": "violet",
        "hex": "#d9c0ff",
        "id": "violet-5",
        "name": "Violet Mist",
        "rgb": [
          217,
          192,
          255
        ],
        "step": 5
      },
      {
        "argb": "0xFF4D0C40",
        "argb_int": -11727808,
        "css": "#4d0c40",
        "family": "magenta",
        "hex": "#4d0c40",
        "id": "magenta-1",
        "name": "Magenta Deep",
        "rgb": [
          77,
          12,
          64
        ],
        "step": 1
      },
      {
        "argb": "0xFF8A1470",
        "argb_int": -7728016,
        "css": "#8a1470",
        "family": "magenta",
        "hex": "#8a1470",
        "id": "magenta-2",
        "name": "Magenta Shade",
        "rgb": [
          138,
          20,
          112
        ],
        "step": 2
      },
      {
        "argb": "0xFFCC2FA8",
        "argb_int": -3395672,
        "css": "#cc2fa8",
        "family": "magenta",
        "hex": "#cc2fa8",
        "id": "magenta-3",
        "name": "Magenta Core",
        "rgb": [
          204,
          47,
          168
        ],
        "step": 3
      },
      {
        "argb": "0xFFFF6FD0",
        "argb_int": -36912,
        "css": "#ff6fd0",
        "family": "magenta",
        "hex": "#ff6fd0",
        "id": "magenta-4",
        "name": "Magenta Bright",
        "rgb": [
          255,
          111,
          208
        ],
        "step": 4
      },
      {
        "argb": "0xFFFFB8EA",
        "argb_int": -18198,
        "css": "#ffb8ea",
        "family": "magenta",
        "hex": "#ffb8ea",
        "id": "magenta-5",
        "name": "Magenta Mist",
        "rgb": [
          255,
          184,
          234
        ],
        "step": 5
      },
      {
        "argb": "0xFF521018",
        "argb_int": -11399144,
        "css": "#521018",
        "family": "rose",
        "hex": "#521018",
        "id": "rose-1",
        "name": "Rose Deep",
        "rgb": [
          82,
          16,
          24
        ],
        "step": 1
      },
      {
        "argb": "0xFF8F1B28",
        "argb_int": -7398616,
        "css": "#8f1b28",
        "family": "rose",
        "hex": "#8f1b28",
        "id": "rose-2",
        "name": "Rose Shade",
        "rgb": [
          143,
          27,
          40
        ],
        "step": 2
      },
      {
        "argb": "0xFFD4384A",
        "argb_int": -2869174,
        "css": "#d4384a",
        "family": "rose",
        "hex": "#d4384a",
        "id": "rose-3",
        "name": "Rose Core",
        "rgb": [
          212,
          56,
          74
        ],
        "step": 3
      },
      {
        "argb": "0xFFFF7B86",
        "argb_int": -33914,
        "css": "#ff7b86",
        "family": "rose",
        "hex": "#ff7b86",
        "id": "rose-4",
        "name": "Rose Bright",
        "rgb": [
          255,
          123,
          134
        ],
        "step": 4
      },
      {
        "argb": "0xFFFFC0C5",
        "argb_int": -16187,
        "css": "#ffc0c5",
        "family": "rose",
        "hex": "#ffc0c5",
        "id": "rose-5",
        "name": "Rose Mist",
        "rgb": [
          255,
          192,
          197
        ],
        "step": 5
      },
      {
        "argb": "0xFF4D1F08",
        "argb_int": -11723000,
        "css": "#4d1f08",
        "family": "ember",
        "hex": "#4d1f08",
        "id": "ember-1",
        "name": "Ember Deep",
        "rgb": [
          77,
          31,
          8
        ],
        "step": 1
      },
      {
        "argb": "0xFF8A3A0E",
        "argb_int": -7718386,
        "css": "#8a3a0e",
        "family": "ember",
        "hex": "#8a3a0e",
        "id": "ember-2",
        "name": "Ember Shade",
        "rgb": [
          138,
          58,
          14
        ],
        "step": 2
      },
      {
        "argb": "0xFFD4661C",
        "argb_int": -2857444,
        "css": "#d4661c",
        "family": "ember",
        "hex": "#d4661c",
        "id": "ember-3",
        "name": "Ember Core",
        "rgb": [
          212,
          102,
          28
        ],
        "step": 3
      },
      {
        "argb": "0xFFFF9B52",
        "argb_int": -25774,
        "css": "#ff9b52",
        "family": "ember",
        "hex": "#ff9b52",
        "id": "ember-4",
        "name": "Ember Bright",
        "rgb": [
          255,
          155,
          82
        ],
        "step": 4
      },
      {
        "argb": "0xFFFFCFA8",
        "argb_int": -12376,
        "css": "#ffcfa8",
        "family": "ember",
        "hex": "#ffcfa8",
        "id": "ember-5",
        "name": "Ember Mist",
        "rgb": [
          255,
          207,
          168
        ],
        "step": 5
      },
      {
        "argb": "0xFF4A3708",
        "argb_int": -11913464,
        "css": "#4a3708",
        "family": "amber",
        "hex": "#4a3708",
        "id": "amber-1",
        "name": "Amber Deep",
        "rgb": [
          74,
          55,
          8
        ],
        "step": 1
      },
      {
        "argb": "0xFF8A680E",
        "argb_int": -7706610,
        "css": "#8a680e",
        "family": "amber",
        "hex": "#8a680e",
        "id": "amber-2",
        "name": "Amber Shade",
        "rgb": [
          138,
          104,
          14
        ],
        "step": 2
      },
      {
        "argb": "0xFFD4A41C",
        "argb_int": -2841572,
        "css": "#d4a41c",
        "family": "amber",
        "hex": "#d4a41c",
        "id": "amber-3",
        "name": "Amber Core",
        "rgb": [
          212,
          164,
          28
        ],
        "step": 3
      },
      {
        "argb": "0xFFFFB648",
        "argb_int": -18872,
        "css": "#ffb648",
        "family": "amber",
        "hex": "#ffb648",
        "id": "amber-4",
        "name": "Amber Bright",
        "rgb": [
          255,
          182,
          72
        ],
        "step": 4
      },
      {
        "argb": "0xFFFFE0A0",
        "argb_int": -8032,
        "css": "#ffe0a0",
        "family": "amber",
        "hex": "#ffe0a0",
        "id": "amber-5",
        "name": "Amber Mist",
        "rgb": [
          255,
          224,
          160
        ],
        "step": 5
      },
      {
        "argb": "0xFF0A3D2A",
        "argb_int": -16106198,
        "css": "#0a3d2a",
        "family": "verdant",
        "hex": "#0a3d2a",
        "id": "verdant-1",
        "name": "Verdant Deep",
        "rgb": [
          10,
          61,
          42
        ],
        "step": 1
      },
      {
        "argb": "0xFF126B47",
        "argb_int": -15570105,
        "css": "#126b47",
        "family": "verdant",
        "hex": "#126b47",
        "id": "verdant-2",
        "name": "Verdant Shade",
        "rgb": [
          18,
          107,
          71
        ],
        "step": 2
      },
      {
        "argb": "0xFF22A874",
        "argb_int": -14505868,
        "css": "#22a874",
        "family": "verdant",
        "hex": "#22a874",
        "id": "verdant-3",
        "name": "Verdant Core",
        "rgb": [
          34,
          168,
          116
        ],
        "step": 3
      },
      {
        "argb": "0xFF5FE0A8",
        "argb_int": -10493784,
        "css": "#5fe0a8",
        "family": "verdant",
        "hex": "#5fe0a8",
        "id": "verdant-4",
        "name": "Verdant Bright",
        "rgb": [
          95,
          224,
          168
        ],
        "step": 4
      },
      {
        "argb": "0xFFB0F4D8",
        "argb_int": -5180200,
        "css": "#b0f4d8",
        "family": "verdant",
        "hex": "#b0f4d8",
        "id": "verdant-5",
        "name": "Verdant Mist",
        "rgb": [
          176,
          244,
          216
        ],
        "step": 5
      },
      {
        "argb": "0xFF0A0E14",
        "argb_int": -16118252,
        "css": "#0a0e14",
        "family": "neutral",
        "hex": "#0a0e14",
        "id": "neutral-1",
        "name": "Neutral Deep",
        "rgb": [
          10,
          14,
          20
        ],
        "step": 1
      },
      {
        "argb": "0xFF1E2833",
        "argb_int": -14800845,
        "css": "#1e2833",
        "family": "neutral",
        "hex": "#1e2833",
        "id": "neutral-2",
        "name": "Neutral Shade",
        "rgb": [
          30,
          40,
          51
        ],
        "step": 2
      },
      {
        "argb": "0xFF46566A",
        "argb_int": -12167574,
        "css": "#46566a",
        "family": "neutral",
        "hex": "#46566a",
        "id": "neutral-3",
        "name": "Neutral Core",
        "rgb": [
          70,
          86,
          106
        ],
        "step": 3
      },
      {
        "argb": "0xFF8FA3B8",
        "argb_int": -7363656,
        "css": "#8fa3b8",
        "family": "neutral",
        "hex": "#8fa3b8",
        "id": "neutral-4",
        "name": "Neutral Bright",
        "rgb": [
          143,
          163,
          184
        ],
        "step": 4
      },
      {
        "argb": "0xFFDDE7F2",
        "argb_int": -2234382,
        "css": "#dde7f2",
        "family": "neutral",
        "hex": "#dde7f2",
        "id": "neutral-5",
        "name": "Neutral Mist",
        "rgb": [
          221,
          231,
          242
        ],
        "step": 5
      }
    ],
    "families": [
      {
        "id": "ice",
        "name": "Ice"
      },
      {
        "id": "azure",
        "name": "Azure"
      },
      {
        "id": "indigo",
        "name": "Indigo"
      },
      {
        "id": "violet",
        "name": "Violet"
      },
      {
        "id": "magenta",
        "name": "Magenta"
      },
      {
        "id": "rose",
        "name": "Rose"
      },
      {
        "id": "ember",
        "name": "Ember"
      },
      {
        "id": "amber",
        "name": "Amber"
      },
      {
        "id": "verdant",
        "name": "Verdant"
      },
      {
        "id": "neutral",
        "name": "Neutral"
      }
    ],
    "steps": [
      "deep",
      "shade",
      "core",
      "bright",
      "mist"
    ]
  },
  "pattern_kinds": [
    "solid",
    "hue_sweep",
    "step_cycle",
    "breathe",
    "pulse",
    "gradient",
    "comet",
    "flicker",
    "reactive",
    "temperature",
    "strobe"
  ],
  "patterns": [
    {
      "desc": "One colour, held. The quiet default.",
      "id": "solid",
      "kind": "solid",
      "name": "Solid",
      "params": {
        "color": "ice-4"
      }
    },
    {
      "desc": "Full hue circle, continuously. Reads as 'working hard' without any text.",
      "id": "rainbow",
      "kind": "hue_sweep",
      "name": "Rainbow",
      "params": {
        "light": 0.62,
        "offset_deg": 0,
        "period_s": 6.0,
        "sat": 0.82,
        "span_deg": 360
      }
    },
    {
      "desc": "Steps through chosen palette colours, holding each. Discrete, not a blend.",
      "id": "cycle",
      "kind": "step_cycle",
      "name": "Cycle",
      "params": {
        "blend_s": 0.45,
        "colors": [
          "ice-4",
          "violet-4",
          "amber-4",
          "verdant-4"
        ],
        "hold_s": 2.0
      }
    },
    {
      "desc": "One colour, brightness rising and falling. Alive but resting.",
      "id": "breathe",
      "kind": "breathe",
      "name": "Breathe",
      "params": {
        "color": "ice-4",
        "depth": 0.45,
        "period_s": 4.5
      }
    },
    {
      "desc": "A single sharp beat, then dark. A turn signal, not a strobe.",
      "id": "pulse",
      "kind": "pulse",
      "name": "Pulse",
      "params": {
        "color": "amber-4",
        "period_s": 1.8,
        "sharpness": 9.0
      }
    },
    {
      "desc": "Slides back and forth between two colours.",
      "id": "gradient",
      "kind": "gradient",
      "name": "Gradient",
      "params": {
        "from": "azure-4",
        "period_s": 7.0,
        "to": "magenta-4"
      }
    },
    {
      "desc": "Rainbow with the leash on — a narrow hue band instead of the whole circle.",
      "id": "sweep",
      "kind": "hue_sweep",
      "name": "Sweep",
      "params": {
        "light": 0.6,
        "offset_deg": 180,
        "period_s": 5.0,
        "sat": 0.7,
        "span_deg": 90
      }
    },
    {
      "desc": "A bright head dragging a dim tail around the face.",
      "id": "comet",
      "kind": "comet",
      "name": "Comet",
      "params": {
        "color": "ice-5",
        "period_s": 2.4,
        "tail": "ice-1"
      }
    },
    {
      "desc": "Irregular drift within one family, like a filament or a fire.",
      "id": "flicker",
      "kind": "flicker",
      "name": "Flicker",
      "params": {
        "depth": 0.25,
        "family": "ember",
        "rate_hz": 1.2
      },
      "safety": "rate_hz is multiplied by 2.3 internally by the second harmonic; keep it under limits.flash.flicker_rate_hz_max."
    },
    {
      "desc": "Colour follows your voice — quiet is cool, loud is hot.",
      "id": "reactive",
      "kind": "reactive",
      "name": "Reactive",
      "params": {
        "gain": 1.6,
        "loud": "rose-4",
        "quiet": "azure-3"
      }
    },
    {
      "desc": "Cool to hot by how busy it is. Reads like a gauge.",
      "id": "temperature",
      "kind": "temperature",
      "name": "Temperature",
      "params": {
        "cold": "ice-2",
        "hot": "rose-4",
        "period_s": 9.0,
        "warm": "amber-4"
      }
    },
    {
      "desc": "Hard alternation between two colours. Use sparingly — it is loud.",
      "id": "strobe",
      "kind": "strobe",
      "name": "Strobe",
      "params": {
        "a": "rose-4",
        "b": "neutral-1",
        "period_s": 0.8
      },
      "safety": "period_s below 0.4 would exceed the transition budget. Never run for more than limits.flash.strobe_max_s at full face width."
    }
  ],
  "picker": {
    "archive_note": "The set audit found one true duplicate on the pixels (geodesic vs fullerene - fullerene's cage survives thinking and speaking, geodesic's nodes smear) and one same-idea pair (kirkwood vs orbit). Archived faces stay selectable behind a 'more faces' toggle, keep their id on every client, and receive every colour and transition fix - the owner's identity face can never vanish. Nothing is archived until the owner chooses; `faces[].archived` is the switch.",
    "archive_recommended": [
      "geodesic",
      "kirkwood"
    ],
    "more_toggle": true,
    "options": {
      "all": "20 visible - framing fixes only",
      "curated": "18 visible - geodesic and kirkwood archived (recommended)",
      "tighter": "16 visible - also spectrum and workbench"
    }
  },
  "randomise": {
    "hue_ring": [
      "ice",
      "azure",
      "indigo",
      "violet",
      "magenta",
      "rose",
      "ember",
      "amber",
      "verdant"
    ],
    "hue_ring_note": "Neutral is deliberately absent: a harmony is built on hues and neutral has none. Distance is measured around the ring, so ice and verdant are neighbours.",
    "note": "The rules the Randomise button follows. They are here rather than in the page's code because Android should offer the same button and produce the same kind of result. Random is seven unrelated colours and a strobing idle - that looks like a fault, not a design.",
    "schemes": [
      {
        "id": "analogous",
        "offsets": [
          0,
          1,
          2,
          -1,
          3
        ]
      },
      {
        "id": "complementary",
        "offsets": [
          0,
          4,
          5,
          1,
          -1
        ]
      },
      {
        "id": "triad",
        "offsets": [
          0,
          3,
          6,
          1,
          4
        ]
      },
      {
        "id": "split",
        "offsets": [
          0,
          4,
          -4,
          1,
          5
        ]
      }
    ],
    "separation": {
      "applies_to": [
        "idle",
        "listening",
        "thinking",
        "speaking"
      ],
      "rule": "hue_ring_distance >= 2 OR abs(step difference) >= 2",
      "why": "The four states you actually watch have to be tellable apart at a glance. The second clause is what makes an analogous scheme work: neighbouring hues ARE similar, so a designer separates them by brightness instead of picking different ones."
    },
    "state_rules": {
      "approval": {
        "families": [
          "amber",
          "verdant"
        ],
        "patterns": [
          "pulse",
          "breathe",
          "flicker"
        ],
        "steps": [
          4
        ],
        "why": "Convention, never randomised: waiting on you is amber or green."
      },
      "error": {
        "families": [
          "rose",
          "ember"
        ],
        "patterns": [
          "strobe",
          "flicker",
          "pulse"
        ],
        "steps": [
          4
        ],
        "why": "Convention, never randomised. A green alarm is a design you have to explain, and an alarm you have to explain is broken."
      },
      "idle": {
        "patterns": [
          "breathe",
          "solid",
          "gradient"
        ],
        "steps": [
          2,
          3
        ],
        "why": "Seen for hours. Never a pattern that demands attention."
      },
      "listening": {
        "patterns": [
          "reactive",
          "solid",
          "breathe",
          "pulse"
        ],
        "steps": [
          3,
          4
        ],
        "why": "Attentive and answering to the microphone."
      },
      "speaking": {
        "patterns": [
          "gradient",
          "sweep",
          "breathe",
          "pulse",
          "comet"
        ],
        "steps": [
          3,
          4
        ],
        "why": "Rhythmic, not frantic."
      },
      "standby": {
        "follows": "idle",
        "patterns": [
          "breathe",
          "solid"
        ],
        "steps": [
          1,
          2
        ],
        "why": "Idle asleep. Keeps idle's hue and only gets quieter - a hue of its own makes waking up look like a fault."
      },
      "thinking": {
        "patterns": [
          "rainbow",
          "cycle",
          "sweep",
          "comet",
          "temperature"
        ],
        "steps": [
          3,
          4
        ],
        "why": "The one state allowed to be busy."
      }
    },
    "timing": {
      "breathe": {
        "active": [
          2.6,
          4.2
        ],
        "calm": [
          5,
          7.5
        ],
        "standby": [
          9,
          13
        ]
      },
      "hue_sweep": {
        "other": [
          4.5,
          8
        ],
        "thinking": [
          3.2,
          5.5
        ]
      },
      "note": "The same pattern does different jobs in different states, so its period is set by the state's energy, not left at the pattern default.",
      "pulse": {
        "error": [
          0.7,
          1.1
        ],
        "other": [
          1.2,
          2.2
        ]
      },
      "strobe": {
        "all": [
          0.45,
          0.8
        ]
      }
    }
  },
  "renderer": {
    "active_states": [
      "listening",
      "thinking",
      "speaking",
      "approval",
      "error"
    ],
    "background": "#04070c",
    "background_why": "One background for all twenty faces. Each used to paint its own (comb #0a0703 warm brown, spectrum #0a0610 purple, iris #090909 neutral, cascade teal-black) which showed as a differently tinted rectangle in every gallery and changed the panel hue when the face changed. Faces' swatch[0] is overwritten with this at boot.",
    "depth_gain": 1.6,
    "depth_gain_why": "Exponent on the perspective depth factor `d` returned by proj(). d is read only for particle size and alpha, never position, so raising it makes the far side of a cloud smaller and fainter and the near side larger and brighter - the one change that makes the most 3D faces read as volumes at once. 1.0 is raw perspective.",
    "fallback": "Every GPU face keeps its CPU path and uses it whenever the context is missing, blocked or lost. A watchdog also gives the GPU back if a shader-rendered frame exceeds three times the frame budget (or 48 ms, whichever is larger) three times running - which is what happens on a software GL driver, where the CPU path is genuinely faster.",
    "gpu_faces": {
      "membrane": {
        "android": "GLES 3.0 indexed mesh; the Verlet step stays in Kotlin.",
        "kind": "cpu_sim_gpu_mesh",
        "web": "WebGL2 indexed triangle mesh, per-pixel normals, depth buffer, MSAA.",
        "why": "The physics is cheap and stays on the CPU. The drawing was the expensive part: one flat-filled quad per cell, so every cell was visible as a facet and the rim as a staircase."
      },
      "nucleus": {
        "android": "RuntimeShader (AGSL) on API 33+, which takes essentially the same source; GLES 3.0 through a GLSurfaceView below that.",
        "kind": "sdf_raymarch",
        "web": "WebGL2 fragment shader, one pass, full display resolution.",
        "why": "One full lighting solve per pixel. On a CPU it can only be computed into a small buffer and stretched, which is what read as low resolution: a 140 px buffer on a 1089 px display is a 7.8x upscale."
      },
      "tokamak": {
        "android": "GLES 3.0 indexed mesh.",
        "kind": "gpu_mesh",
        "web": "WebGL2 indexed triangle mesh with the torus's analytic normal.",
        "why": "Flat-filled quads on a torus read as a disco ball at any grid a CPU can afford."
      }
    },
    "gpu_scale": {
      "high": 1.0,
      "low": 0.62,
      "max": 1.0,
      "medium": 0.8
    },
    "note": "Most faces are meshes of a few thousand quads and a CPU rasteriser draws them fine. Three cannot be drawn sharply that way at phone resolution, and are rendered by a shader instead. The distinction is a property of the face, not of the client, so it is recorded here.",
    "point_batch": {
      "calibration": {
        "how": "The first time a batchable face draws, it runs both ways in alternating blocks of 8 frames, discards the first frame of each block (shader compile, buffer resize, cold cache), takes the median of 3 blocks each way, and keeps the faster. Ties go to canvas: that is the path with no second surface, no blit, and no context to lose. The answer is remembered per face.",
        "per_face_not_global": "The crossover depends on how many sprites a face draws and how large they are, and that differs by an order of magnitude across the kit.",
        "why": "Whether the batch is faster cannot be settled by reasoning, and cannot be measured in a browser with no GPU. Measured in a software-GL container the batch was about 48 ms per frame SLOWER - and that 48 ms was constant whether the field held 500 sprites or 3000, so it was entirely the clear and the blit, nothing to do with the sprites. On a phone with a working GPU those are the parts that are nearly free."
      },
      "composite": "Additive. Every one of these faces already drew its particles with globalCompositeOperation 'lighter', so the pass accumulates the same way and is composited back the same way. The background survives underneath and anything the face draws afterwards still lands on top.",
      "faces": [
        "kirkwood",
        "spiral",
        "orbital"
      ],
      "threshold": 160,
      "threshold_why": "A GPU pass costs one full-surface clear and one blit whatever is in it. Below roughly 160 sprites that fixed cost exceeds the canvas calls it replaces, so small fields stay on canvas. The threshold decides, not the author, which is why a face can carry the batch unconditionally and still be right at every quality tier.",
      "what": "These three are particle fields: several hundred to three thousand additive discs. The per-particle cost is a colour string, a path and a fill. The batched path keeps the face's own projection maths exactly as it was and replaces only the handover - x, y, radius and colour in pixels - so the whole field is one draw call."
    },
    "post": {
      "aberration": {
        "max_ms": 400,
        "max_px": 2,
        "min_tier": "high",
        "states": "transitions",
        "status": "specified, pending",
        "surfaces": "gl"
      },
      "bloom": {
        "canvas_fallback": "glow_sprite",
        "canvas_fallback_why": "A real blur (ctx.filter='blur()') over a canvas face is a full-canvas Gaussian every frame: 0.3-0.5ms desktop, 3-6ms on the phone, unsupported in older WebViews. A cached radial-gradient bitmap in the state colour drawn 'lighter' behind the face costs one drawImage (<0.05 / 0.1-0.2ms) and gives the same halo. Implemented in the shell as drawGlow(); the GL dual-Kawase pass for the three shader faces is specified here and pending.",
        "cost_ms": {
          "desktop": 0.05,
          "phone": "0.3-0.5"
        },
        "intensity": 0.3,
        "min_tier": "medium",
        "passes": 2,
        "res_scale": 0.25,
        "states": "active_states",
        "surfaces": "gl",
        "threshold": 0.6,
        "voice_gain": 0.6
      },
      "grain": {
        "amount": 0.06,
        "max_ms": 400,
        "min_tier": "high",
        "states": "transitions",
        "status": "specified, pending",
        "surfaces": "gl"
      },
      "never": [
        "ctx.filter blur on canvas faces",
        "any full-canvas overlay in idle, standby or banked",
        "grain or aberration on the phone tier"
      ],
      "note": "Post-processing budget, settled by the performance engineer and the 3D director. Nothing runs per frame over the whole canvas in a resting state. Costs assume a ~1100px face; desktop RTX 2080 Super / mid-range phone (Adreno 610 class).",
      "vignette": {
        "baked": true,
        "note": "Painted once into the static layer; zero per-frame cost.",
        "strength": 0.25
      }
    },
    "resolution": "Shader faces render at DEVICE pixels times renderer.gpu_scale, never at the supersampled backing store: past one fragment per screen pixel there is nothing left to see. CPU faces still supersample, because for them it is the only anti-aliasing available.",
    "survey": {
      "finding": "Only three had a rendering defect, and all three are already converted. The other seventeen are line, stroke, point and glow art. Canvas antialiases those correctly at any resolution and draws most of them in well under a millisecond, so moving them to a shader would be a rewrite with no visual gain.",
      "method": "All 20 faces rendered solo at 412x915 @2.75 dpr and timed, then looked at. The question was which ones a rasteriser cannot draw properly - not which ones could theoretically use a GPU.",
      "stays_on_canvas": [
        "arc",
        "orbit",
        "geodesic",
        "spectrum",
        "swarm",
        "coreplate",
        "workbench",
        "comb",
        "iris",
        "shoal",
        "accretion",
        "cascade",
        "rime",
        "fullerene"
      ],
      "stays_on_canvas_why": "Strokes, paths and radial gradients. A GPU port would mean re-expressing each shape as geometry for no sharpness the canvas does not already give.",
      "when": "2026-09-13"
    },
    "tiers_post": {
      "high": true,
      "low": false,
      "max": true,
      "medium": true
    }
  },
  "spec": "jarvis-visual",
  "speech": {
    "api": "setSpeechLevel(level_0_to_1) - call per audio frame while TTS plays. On Android, feed it from the AudioTrack/Visualizer RMS; on the desktop from the Web Audio AnalyserNode of the playback element.",
    "brightness_lift": 0.18,
    "envelope": {
      "attack_s": 0.04,
      "gate": 0.04,
      "release_s": 0.12,
      "why": "A syllable rises in ~40ms and decays in ~120ms; the gate keeps player hiss from animating anything."
    },
    "fallback": "If no level has arrived for 0.5s while speaking, a synthetic envelope stands in: syllables at 4.2Hz with varying weight and a 220ms rest every 2.3s. Speaking is never frozen, even before TTS is wired.",
    "listening_uses_same_path": "The microphone envelope (attack 30ms / release 220ms) drives the same scale push while listening, so the owner's own voice visibly moves the face.",
    "note": "Jarvis's own voice, as distinct from the owner's microphone. The audit's largest finding: nothing talked - the speaking gallery was the idle gallery tinted. The client feeds the 0..1 level of the audio it is playing through setSpeechLevel(); the shell smooths it with a speech-shaped envelope and applies it to EVERY face as a scale push and a brightness lift, so all twenty talk without any face knowing how.",
    "scale": 0.035,
    "scale_why": "Up to 3.5% growth on a loud syllable. Positional, not luminance, so it is not a flash.",
    "speak_floor": 0.18,
    "speak_floor_why": "A speaking face in the gap between words still glows above idle."
  },
  "state_transforms": {
    "amp_envelope": {
      "attack_s": 0.03,
      "gate": 0.04,
      "release_s": 0.22,
      "why": "Raw microphone level is unusable: noisy at the top, and it falls off a cliff between syllables. Rise fast so the face confirms it heard you, fall slow so it holds through the gaps, gate underneath so room hum animates nothing. The constants are in SECONDS and converted per frame, so a 120Hz screen smooths by the same amount as a 60Hz one - a fixed per-frame lerp does not, and the feel of the thing changed with the refresh rate."
    },
    "approval_clock_s": 20,
    "approval_overlay": "clock: a rim arc from twelve o'clock closing clockwise over approval_clock_s then held, drawn over the knock ping; the first 220ms sweep to 12% so the ring is on screen before the tint. Approval is thereby legible with no colour at all.",
    "color_ease_s": 0.3,
    "color_ease_why": "Every state change used to cut in colour on the frame of the switch (the destination hue at +50ms in every row of every transition strip). The shell now fades from the colour actually being shown to the new state's colour over 300ms with a smoothstep. A face that changes hue in one frame reads as a different object; one that fades reads as the same object changing its mind.",
    "dim_rule": {
      "how": "blend toward the face's own background colour, never multiply toward zero",
      "why": "A multiply lands banked's already-dark colour around 0.002 relative luminance, which many OLED panels quantise to black - so the state that means 'something is waiting' would vanish on the device most likely to show it."
    },
    "listen_floor": {
      "value": 0.28,
      "why": "What `listening` is worth with a silent microphone. Silence is not absence of attention: a person pauses between words, and a face that drops below idle during the pause reads as 'it stopped listening' at exactly the moment they check. The microphone level adds to this floor rather than replacing it."
    },
    "note": "A face has FOUR motion tables and the product has EIGHT states, so four of them borrow. Borrowing alone was not enough, and for two states it was worse than nothing. These transforms are applied by the SHELL on top of a borrowed table - a clock multiplier, a direction, a dim, and at most one overlay - so all twenty faces behave identically and each client implements this once instead of twenty times.",
    "phase": {
      "applies_to": "spin only; a camera drift or a slow pitch oscillation stays on the raw clock",
      "rule": "angle += dt * speed(state)",
      "why": "Never angle = clock * speed. Multiplying the absolute clock by a per-state speed makes the angle jump by clock * (new - old) the instant the state changes. Measured on this build before the fix: 434, 590, 773 and 255 radians on the four common transitions after fifteen minutes of uptime - between 40 and 123 full revolutions, on a single frame, at exactly the moment the owner is looking at the face. Integrating the rate is also what makes the eased ramp above continuous for free."
    },
    "rate_ease_s": 0.22,
    "speech_modulation": "see `speech`",
    "states": {
      "approval": {
        "borrow": "idle",
        "dim": 1.0,
        "dir": 1,
        "overlay": "ping",
        "overlay_spec": {
          "ease": "out-cubic",
          "expand_s": 0.4,
          "from_r": 0.12,
          "peak_alpha": 0.55,
          "period_s": 1.6,
          "to_r": 0.94
        },
        "rate": 1.0,
        "why": "It used to borrow LISTENING, and a dozen faces do not merely read listening's parameters - they branch on the state name and multiply by the microphone level. During an approval the mic is not live, so those faces drew LESS than idle: the one state that has to pull the eye across a room was the deadest thing on the screen. It now borrows idle's pace and gets a ring that leaves the core every 1.6 seconds. That is a knock at a door - it repeats, it is directional, and it stops the moment you answer."
      },
      "banked": {
        "borrow": "idle",
        "dim": 0.45,
        "dir": 1,
        "overlay": "notches",
        "overlay_spec": {
          "direction": "clockwise",
          "max_notches": 12,
          "notch_from_r": 0.86,
          "notch_to_r": 0.99,
          "note": "Radii are fractions of the radius basis above. A ring at the full half-width sits outside the artwork and clips against the canvas edge once the stroke width is added.",
          "overflow_mark": true,
          "radius_basis": "0.44 * min(w,h) - the rim of the FACE, not of the buffer",
          "ring_r": 0.93,
          "source": "the number of items waiting in the digest (jarvis_arbiter.pending_count)",
          "start": "12 o'clock"
        },
        "rate": 0.0,
        "why": "Still - not slow, STOPPED. It means 'there are things waiting and I am not going to say them out loud', and the number of things is the one piece of information the state exists to carry, so it is drawn as notches around the rim. On Android the frame clock should actually stop rather than redrawing an unchanging frame 120 times a second; a change in the notch count wakes it for exactly one frame."
      },
      "error": {
        "borrow": "thinking",
        "dim": 0.9,
        "dir": -1,
        "envelope_s": {
          "hitch": 0.06,
          "hold": 0.25,
          "shake": 0.3
        },
        "overlay": "hitch",
        "rate": 0.3,
        "shake": {
          "amplitude_frac": 0.015,
          "hz": 8,
          "kind": "positional",
          "why_positional": "a brightness shake at 8Hz is a flash; moving the face a pixel or two is just as legible and carries no photosensitivity risk"
        },
        "why": "It used to borrow THINKING, so an error looked like harder thinking - the same fast agitated motion, distinguished only by colour. Colour alone fails for the one man in twelve with a red-green deficiency, at a glance from across a room, and in any frozen frame or thumbnail. Error now HITCHES: the spin stops dead in 60ms, holds, shakes, then crawls BACKWARDS at 0.3x idle. Nothing else in this product ever runs backwards, so the direction is the signal - and direction survives colour blindness, a still frame and peripheral vision."
      },
      "standby": {
        "borrow": "idle",
        "dim": 0.6,
        "dir": 1,
        "overlay": null,
        "rate": 0.5,
        "why": "Idle at half pace, dimmed. This one was always right."
      }
    },
    "tint_delay_s": {
      "approval": 0.1,
      "why": "The ring is seen to arrive before the colour follows - the knock comes before the door opens."
    },
    "why_ease": "The spin RATE is eased, not snapped. A face whose rate steps from 0.22 to 1.35 in one frame reads as a cut even when the angle is continuous."
  },
  "states": [
    {
      "default": {
        "color": "ice-3",
        "pattern": "breathe"
      },
      "id": "idle",
      "name": "Idle"
    },
    {
      "default": {
        "color": "ember-4",
        "pattern": "solid"
      },
      "default_note": "Ember stays: it is the product's established look. Listening is made unmistakable by MOTION instead - the microphone envelope scales the whole face (see `speech`) and drives each face's own listening table.",
      "id": "listening",
      "name": "Listening"
    },
    {
      "default": {
        "color": null,
        "params": {
          "light": 0.62,
          "offset_deg": 246,
          "period_s": 5.0,
          "sat": 0.72,
          "span_deg": 58
        },
        "pattern": "sweep"
      },
      "default_note": "A narrow cool sweep (hue 217-275: azure to violet) replacing the 360-degree rainbow. The audit found the rainbow had no identity: sixteen faces red, three green, one violet in one gallery, and its brightness pulsed with hue. The first replacement (188-260) bottomed out on cyan, which is idle's hue - a thinking face caught at that phase read as idle - so the band starts above ice. Rainbow stays selectable.",
      "id": "thinking",
      "name": "Thinking"
    },
    {
      "default": {
        "color": "ice-4",
        "params": {
          "gain": 1.4,
          "loud": "ice-5"
        },
        "pattern": "reactive"
      },
      "default_note": "Brightens with Jarvis's own voice through the speech envelope (see `speech`). Was gradient azure-4 to magenta-4, whose pattern colours beat the bound ice-5, so speaking rendered pink on nineteen of twenty faces.",
      "id": "speaking",
      "name": "Speaking"
    },
    {
      "default": {
        "color": "amber-4",
        "pattern": "pulse"
      },
      "id": "approval",
      "motion": "idle",
      "motion_note": "Borrows idle's movement (via the shell transform) and carries the WAITING CLOCK overlay: an arc from twelve o'clock closing over `state_transforms.approval_clock_s`, plus the knock ping. The colour audit measured ember-4 (listening) against amber-4 (approval) at a colour difference of 12.1 in normal vision and 4.5 under deuteranopia; two states may share a hue only if they never share a movement, so approval's identity is its motion. Its tint is delayed 100ms after the ring.",
      "name": "Waiting on you"
    },
    {
      "default": {
        "color": "neutral-3",
        "pattern": "breathe"
      },
      "id": "standby",
      "motion": "idle",
      "motion_note": "Faces implement four motion tables, not seven. This state borrows the named movement and keeps its own bound colour and pattern.",
      "name": "Standby"
    },
    {
      "default": {
        "color": "rose-4",
        "params": {
          "period_s": 1.1,
          "sharpness": 4.0
        },
        "pattern": "pulse"
      },
      "default_note": "A pulse on rose-4 that never leaves rose-4 (the hot slot rises from the base and returns to it). Was strobe rose-4 to neutral-1, which is near-black half of every 0.8s: any glance, still or thumbnail on the off phase saw nothing and read as crashed. Strobe stays selectable.",
      "id": "error",
      "motion": "thinking",
      "motion_note": "Faces implement four motion tables, not seven. This state borrows the named movement and keeps its own bound colour and pattern.",
      "name": "Error"
    },
    {
      "default": {
        "color": "neutral-4",
        "pattern": "solid"
      },
      "dim": 0.45,
      "id": "banked",
      "motion": "idle",
      "motion_note": "Faces implement four motion tables, not seven. This state borrows the named movement and keeps its own bound colour and pattern.",
      "name": "Banked",
      "note": "Things are waiting and Jarvis is not going to say them out loud - the interruption budget for today is spent, or you muted it. Dimmed, still, silent until tapped. The rim ring is drawn at full and carries one notch per waiting item. A job finishing while banked adds a notch and makes no sound; it must never move the face to speaking.",
      "rim_ring": true,
      "still": true
    }
  ],
  "version": "1"
});
