// GENERATED by tools/gen_menu_cases.py from backend/jarvis_menus.py - do not edit by hand.
// Run `python3 tools/gen_menu_cases.py` after changing the list; CI runs `--check`.

export const VERSION = 1;
export const GROUP_PREFIX = "group.";
export const WORDS = {
  "title": "Show or hide menus",
  "device_note": "This hides menus on this device only.",
  "help": "Hiding a menu only tidies it away. Nothing is turned off, and Jarvis can still do it when you ask. Asking Jarvis to hide or show a menu changes every device that hears it.",
  "never_note": "Some things always stay visible: approvals, security, What asks first, and the connection status.",
  "tray_note": "The system-tray menu is not affected.",
  "none_hidden": "Nothing is hidden.",
  "hidden_line_one": "1 hidden - Show",
  "hidden_line_many": "{n} hidden - Show",
  "hidden_speech_one": "1 menu hidden. Show or hide menus.",
  "hidden_speech_many": "{n} menus hidden. Show or hide menus.",
  "show_everything": "Show everything",
  "visit_banner": "Shown for now.",
  "visit_keep": "Keep it visible",
  "visit_again": "Hide again",
  "state_expanded": "Expanded",
  "state_collapsed": "Collapsed",
  "hide_switch": "Hide {title}",
  "group_hides": "Hides {members}",
  "collapse": "Fold",
  "expand": "Open",
  "folded_line": "Folded. Tap Open to see it."
};
export const REPLIES = {
  "hide": "Done. On the devices that are open, the {title} menu is hidden. Nothing is turned off. Say \"show the {title} menu\" to bring it back.",
  "show": "Done. On the devices that are open, the {title} menu is showing.",
  "collapse": "Done. On the devices that are open, the {title} menu is folded to one line.",
  "expand": "Done. On the devices that are open, the {title} menu is open.",
  "reset": "Done. On the devices that are open, every menu is showing again.",
  "unknown": "I don't know a menu called that.",
  "never": "That one stays visible so you can always reach it.",
  "empty": "There is no {title} menu yet.",
  "cannot_collapse": "That menu cannot be folded.",
  "always": "That one is always visible."
};
export const ACTIONS = ["hide", "show", "collapse", "expand", "reset"];
export const GROUPS = [
  {
    "id": "group.study",
    "title": "Study",
    "about": "Quiz and Review decks.",
    "names": [
      "study",
      "studying"
    ],
    "members": {
      "desktop": [
        "brain.work.quiz",
        "brain.work.quiz.youtube",
        "brain.work.decks"
      ],
      "phone": [
        "brain.work.quiz",
        "brain.work.quiz.youtube",
        "brain.work.decks"
      ]
    },
    "listed": {
      "desktop": true,
      "phone": true
    }
  },
  {
    "id": "group.goals-projects",
    "title": "Goals and projects",
    "about": "Goals, Projects and Progress.",
    "names": [
      "goals and projects",
      "goals & projects",
      "projects and goals"
    ],
    "members": {
      "desktop": [
        "brain.tab.projects",
        "brain.work.goals",
        "brain.projects.progress"
      ],
      "phone": [
        "brain.tab.projects",
        "brain.work.goals",
        "brain.projects.progress"
      ]
    },
    "listed": {
      "desktop": true,
      "phone": true
    }
  },
  {
    "id": "group.graphics-cards",
    "title": "Graphics cards",
    "about": "Hardware, the second card's switches and the big model.",
    "names": [
      "graphics cards",
      "graphics card",
      "gpu",
      "gpus"
    ],
    "members": {
      "desktop": [
        "settings.hardware",
        "settings.second-card",
        "settings.second-card.study-helper",
        "settings.second-card.referee",
        "settings.second-card.third-card",
        "settings.big-model"
      ],
      "phone": [
        "settings.hardware",
        "settings.second-card",
        "settings.second-card.study-helper",
        "settings.second-card.referee",
        "settings.second-card.third-card",
        "settings.big-model"
      ]
    },
    "listed": {
      "desktop": true,
      "phone": true
    }
  },
  {
    "id": "group.chatbots",
    "title": "Chatbots",
    "about": "Talk to a chatbot for me, and customer-support chats.",
    "names": [
      "chatbots",
      "chatbot"
    ],
    "members": {
      "desktop": [
        "brain.work.chatbot",
        "brain.work.support"
      ],
      "phone": [
        "brain.work.chatbot",
        "brain.work.support"
      ]
    },
    "listed": {
      "desktop": true,
      "phone": true
    }
  },
  {
    "id": "group.finance",
    "title": "Finance",
    "about": "Spending summaries and the retirement what-if.",
    "names": [
      "finance",
      "finances",
      "money and spending"
    ],
    "members": {
      "desktop": [
        "settings.spending",
        "brain.work.retirement"
      ],
      "phone": [
        "settings.spending",
        "brain.work.retirement"
      ]
    },
    "listed": {
      "desktop": true,
      "phone": true
    }
  },
  {
    "id": "group.home",
    "title": "Home",
    "about": "Home status and smart-home settings.",
    "names": [
      "home",
      "smart home"
    ],
    "members": {
      "desktop": [],
      "phone": []
    },
    "listed": {
      "desktop": false,
      "phone": false
    }
  }
];
export const MENUS = [
  {
    "id": "settings.connection",
    "title": "Connection",
    "about": "The pairing key, the server address and the link status.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Acting is blocked when the link is stale (rule 4), so its status is always visible.",
    "names": [
      "connection",
      "connection settings",
      "pairing",
      "the server address"
    ]
  },
  {
    "id": "settings.devices",
    "title": "Devices",
    "about": "Every paired device with its own key.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": true,
    "why": "Removing a lost phone must stay reachable.",
    "names": [
      "devices",
      "paired devices"
    ]
  },
  {
    "id": "settings.faq",
    "title": "Help and FAQ",
    "about": "Answers to common questions.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "faq",
      "the faq",
      "frequently asked questions"
    ]
  },
  {
    "id": "settings.appearance-card",
    "title": "Appearance",
    "about": "Theme, faces and how it all looks.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "appearance",
      "the theme",
      "themes",
      "faces"
    ]
  },
  {
    "id": "settings.animal-options",
    "title": "Animal options",
    "about": "Every animal-face option in one place.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "animal options",
      "animal settings"
    ]
  },
  {
    "id": "settings.voice",
    "title": "Voice",
    "about": "Talk, read aloud, hands-free and sounds.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "voice",
      "voice settings"
    ]
  },
  {
    "id": "settings.manner",
    "title": "How Jarvis talks",
    "about": "Warm and brief, or plain.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "how jarvis talks",
      "manner"
    ]
  },
  {
    "id": "settings.briefing-settings",
    "title": "Morning briefing settings",
    "about": "What the morning briefing includes.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "briefing settings",
      "morning briefing settings"
    ]
  },
  {
    "id": "settings.shortcuts",
    "title": "Shortcuts",
    "about": "Keyboard shortcuts.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "shortcuts",
      "keyboard shortcuts",
      "hotkeys"
    ]
  },
  {
    "id": "settings.security",
    "title": "Security",
    "about": "App lock and Windows Hello or the screen lock.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Safety: the lock and fingerprint settings must always be reachable.",
    "names": [
      "security",
      "security settings",
      "app lock",
      "windows hello"
    ]
  },
  {
    "id": "settings.voices",
    "title": "Jarvis's voice",
    "about": "Custom voices and the voice pack.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "jarvis's voice",
      "jarvis's voices",
      "custom voices"
    ]
  },
  {
    "id": "settings.web-search",
    "title": "Web search",
    "about": "Which search provider Jarvis uses.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "web search",
      "search settings",
      "the search provider"
    ]
  },
  {
    "id": "settings.account-secrets",
    "title": "Accounts",
    "about": "Keys and account details kept on this PC.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "accounts",
      "account secrets",
      "credentials"
    ]
  },
  {
    "id": "settings.hardware",
    "title": "Hardware and models",
    "about": "Your graphics cards and the three setups.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": "group.graphics-cards",
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "hardware",
      "hardware and models"
    ]
  },
  {
    "id": "settings.second-card",
    "title": "Second graphics card",
    "about": "The second card's switches and its own copy of Ollama.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": "group.graphics-cards",
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "second graphics card",
      "second card",
      "second gpu"
    ]
  },
  {
    "id": "settings.second-card.study-helper",
    "title": "Study helper (second card switch)",
    "about": "One row inside the second graphics card.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "row",
    "group": "group.graphics-cards",
    "parent": "settings.second-card",
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "study helper",
      "the study helper switch"
    ]
  },
  {
    "id": "settings.second-card.referee",
    "title": "Referee suggestions (second card switch)",
    "about": "One row inside the second graphics card.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "row",
    "group": "group.graphics-cards",
    "parent": "settings.second-card",
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "referee",
      "referee suggestions",
      "the referee switch"
    ]
  },
  {
    "id": "settings.second-card.third-card",
    "title": "Third graphics card",
    "about": "The section for a third card, when one is capable.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "row",
    "group": "group.graphics-cards",
    "parent": "settings.second-card",
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "third graphics card",
      "third card"
    ]
  },
  {
    "id": "settings.big-model",
    "title": "Big model (slow)",
    "about": "One bigger model split across both cards.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": "group.graphics-cards",
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "big model",
      "the big model"
    ]
  },
  {
    "id": "settings.folders",
    "title": "Folders Jarvis may look in",
    "about": "The folders and the Notion export.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "folders",
      "folders jarvis may look in"
    ]
  },
  {
    "id": "settings.spending",
    "title": "Spending",
    "about": "Spending summaries from a bank file you drop in.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": "group.finance",
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "spending",
      "spending summaries"
    ]
  },
  {
    "id": "settings.screen-look",
    "title": "Look at this and Watch with me",
    "about": "The screen feature's lists and picture mode.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "look at this",
      "watch with me",
      "screen settings"
    ]
  },
  {
    "id": "settings.browser-engine",
    "title": "Browser without a window",
    "about": "Which browser Jarvis uses for plain reading.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "browser without a window",
      "headless browser",
      "browser settings"
    ]
  },
  {
    "id": "settings.backup",
    "title": "Backups",
    "about": "One locked backup file into a folder you pick.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "backups",
      "backup settings"
    ]
  },
  {
    "id": "settings.updates",
    "title": "Updates",
    "about": "New versions of this app.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "updates",
      "app updates"
    ]
  },
  {
    "id": "settings.tool-updates",
    "title": "Check for tool updates",
    "about": "Outdated packages and tools.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "tool updates"
    ]
  },
  {
    "id": "settings.more-options",
    "title": "More options",
    "about": "Startup, logs and crash notes.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Already a fold of its own; it stays where it is.",
    "names": []
  },
  {
    "id": "settings.asks-first",
    "title": "What asks first",
    "about": "Every action and whether it asks.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Safety: what asks first must always be reachable.",
    "names": [
      "what asks first",
      "asks first",
      "what asks first settings"
    ]
  },
  {
    "id": "settings.reach",
    "title": "What Jarvis can reach",
    "about": "Which tools Jarvis may use.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "what jarvis can reach",
      "reach"
    ]
  },
  {
    "id": "settings.email-sending",
    "title": "Sending email",
    "about": "Sending email, one card per email.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "sending email",
      "email sending"
    ]
  },
  {
    "id": "settings.about",
    "title": "About Jarvis",
    "about": "Version, licences and credits.",
    "apps": [
      "desktop"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "about jarvis",
      "about"
    ]
  },
  {
    "id": "settings.backend-supports",
    "title": "What this backend supports",
    "about": "The capability list the app branches on.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "what this backend supports",
      "backend capabilities",
      "this backend"
    ]
  },
  {
    "id": "settings.watch-notify",
    "title": "Smartwatch notifications",
    "about": "Whether notifications show on a watch.",
    "apps": [
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "smartwatch notifications",
      "watch notifications"
    ]
  },
  {
    "id": "settings.phone-notify",
    "title": "Phone notifications",
    "about": "Reading phone notifications, and the apps allowed.",
    "apps": [
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "phone notifications"
    ]
  },
  {
    "id": "settings.floating-avatar",
    "title": "Floating Jarvis",
    "about": "The floating face or bubble.",
    "apps": [
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "floating jarvis",
      "floating face",
      "the bubble"
    ]
  },
  {
    "id": "settings.quick-tiles",
    "title": "Quick Settings tiles",
    "about": "The tiles in the phone's quick panel.",
    "apps": [
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "quick settings tiles",
      "quick tiles"
    ]
  },
  {
    "id": "settings.menu-visibility",
    "title": "Show or hide menus",
    "about": "The list you are looking at.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "settings",
    "view": "",
    "kind": "card",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Otherwise nothing hidden could be shown again.",
    "names": [
      "show or hide menus",
      "menus",
      "the menu list"
    ]
  },
  {
    "id": "brain.tab.memory",
    "title": "Memory",
    "about": "What Jarvis knows and how it learns.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "memory"
    ]
  },
  {
    "id": "brain.tab.history",
    "title": "History",
    "about": "Your past chats.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "history",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "history",
      "chat history"
    ]
  },
  {
    "id": "brain.tab.faculties",
    "title": "Model",
    "about": "The models, compute and skills.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "model"
    ]
  },
  {
    "id": "brain.tab.work",
    "title": "Work",
    "about": "Focus, chatbots, today, goals, quiz and the rest.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "work",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "work"
    ]
  },
  {
    "id": "brain.tab.projects",
    "title": "Projects",
    "about": "Projects, their notes and benchmarks.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "projects",
    "kind": "tab",
    "group": "group.goals-projects",
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "projects"
    ]
  },
  {
    "id": "brain.tab.galaxy",
    "title": "Galaxy",
    "about": "The map of what Jarvis knows.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "galaxy",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "galaxy"
    ]
  },
  {
    "id": "brain.tab.now",
    "title": "Now",
    "about": "What Jarvis is doing right now.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "now",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "now"
    ]
  },
  {
    "id": "brain.tab.trust",
    "title": "Trust",
    "about": "Content risk and the audit chain.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "trust",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "It holds pending attention, so it can never be hidden.",
    "names": []
  },
  {
    "id": "brain.tab.watch",
    "title": "Watch",
    "about": "The GitHub watchlist and what needs you.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "watch",
    "kind": "tab",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "It holds pending attention, so it can never be hidden.",
    "names": []
  },
  {
    "id": "brain.memory.learning",
    "title": "Learning",
    "about": "How much Jarvis remembers and whether it learns.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "learning",
      "memory counts"
    ]
  },
  {
    "id": "brain.memory.history-import",
    "title": "Bring in old chats",
    "about": "Import chats from another AI.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "bring in old chats",
      "history import"
    ]
  },
  {
    "id": "brain.memory.topics",
    "title": "Topics",
    "about": "A mode for each topic of what Jarvis learns.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "topics"
    ]
  },
  {
    "id": "brain.memory.auto",
    "title": "Saved automatically",
    "about": "Facts Jarvis saved without asking.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "saved automatically"
    ]
  },
  {
    "id": "brain.memory.profile",
    "title": "Always keep in mind",
    "about": "Facts pinned to every answer.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "always keep in mind",
      "pinned facts"
    ]
  },
  {
    "id": "brain.memory.between-us",
    "title": "Between us",
    "about": "Inside jokes and shared references.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "between us",
      "inside jokes"
    ]
  },
  {
    "id": "brain.memory.people-things",
    "title": "People and things",
    "about": "The people and things Jarvis has heard about.",
    "apps": [
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "people and things",
      "people"
    ]
  },
  {
    "id": "brain.memory.waiting",
    "title": "Waiting for you",
    "about": "Facts waiting for your yes.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": false,
    "collapse": true,
    "why": "Something is waiting on you; it must not be hidden away.",
    "names": []
  },
  {
    "id": "brain.memory.known",
    "title": "What Jarvis knows about you",
    "about": "The facts, by topic.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "what jarvis knows about you"
    ]
  },
  {
    "id": "brain.memory.wiki",
    "title": "Wiki",
    "about": "The wiki Jarvis builds from your notes.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "wiki",
      "the wiki"
    ]
  },
  {
    "id": "brain.memory.deep",
    "title": "Deep questions",
    "about": "Slow questions and their answers.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "deep questions"
    ]
  },
  {
    "id": "brain.memory.as-of",
    "title": "What did I believe on this date?",
    "about": "Ask what a fact said on a past day.",
    "apps": [
      "phone"
    ],
    "area": "brain",
    "view": "memory",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.memory",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "what did i believe",
      "as of a date"
    ]
  },
  {
    "id": "brain.history.conversations",
    "title": "Chat history and conversations",
    "about": "The list of your past chats and how long they are kept.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "history",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.history",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "conversations",
      "past chats"
    ]
  },
  {
    "id": "brain.history.tags",
    "title": "Chat tags",
    "about": "The tag chips and the tag editor.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "history",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.history",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "chat tags",
      "tags"
    ]
  },
  {
    "id": "brain.history.tag-suggestions",
    "title": "Suggest tags overnight",
    "about": "The overnight tag suggestions switch.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "history",
    "kind": "row",
    "group": null,
    "parent": "brain.history.tags",
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "tag suggestions",
      "suggest tags overnight"
    ]
  },
  {
    "id": "brain.history.forget-range",
    "title": "Forget a time frame",
    "about": "Pick days, tick what to forget, one card, 10 minutes to undo.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "history",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.history",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "forget a time frame"
    ]
  },
  {
    "id": "brain.model.models",
    "title": "Models",
    "about": "The models Jarvis can use.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.faculties",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "models list",
      "model list"
    ]
  },
  {
    "id": "brain.model.compute",
    "title": "Compute",
    "about": "The graphics card plan.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.faculties",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "compute"
    ]
  },
  {
    "id": "brain.model.skills",
    "title": "Skills",
    "about": "Installed skills with scan verdicts.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.faculties",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "skills"
    ]
  },
  {
    "id": "brain.model.memory",
    "title": "Memory (model view)",
    "about": "The memory summary on the Model page.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.faculties",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "model memory"
    ]
  },
  {
    "id": "brain.model.pc-help",
    "title": "PC help",
    "about": "Five plain answers about the PC.",
    "apps": [
      "phone"
    ],
    "area": "brain",
    "view": "faculties",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.faculties",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "pc help"
    ]
  },
  {
    "id": "brain.work.focus",
    "title": "Focus session",
    "about": "Start and stop a focus session.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "focus",
      "focus session"
    ]
  },
  {
    "id": "brain.work.chatbot",
    "title": "Talk to a chatbot for me",
    "about": "Jarvis holds a conversation with another AI for you.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.chatbots",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "chatbot driver",
      "talk to a chatbot"
    ]
  },
  {
    "id": "brain.work.support",
    "title": "Chat with customer support for me",
    "about": "Customer-support chats, one card per offer.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.chatbots",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "customer support",
      "support chats"
    ]
  },
  {
    "id": "brain.work.today",
    "title": "Today",
    "about": "Your own cards for the day.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "today"
    ]
  },
  {
    "id": "brain.work.widgets",
    "title": "Widgets",
    "about": "Widgets you described.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "widgets"
    ]
  },
  {
    "id": "brain.work.coming-up",
    "title": "Coming up",
    "about": "Reminders, alarms, timers and repeating jobs.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": false,
    "collapse": true,
    "why": "A reminder that is due shows here; it must stay reachable.",
    "names": [
      "coming up"
    ]
  },
  {
    "id": "brain.work.goals",
    "title": "Goals",
    "about": "Plans you edit, with a weekly check-in.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.goals-projects",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "goals"
    ]
  },
  {
    "id": "brain.work.quiz",
    "title": "Quiz me on a text",
    "about": "Questions on a text you paste or a YouTube link.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.study",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "quiz",
      "quizzes"
    ]
  },
  {
    "id": "brain.work.quiz.youtube",
    "title": "Quiz from a YouTube link",
    "about": "The YouTube link box inside the quiz.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "row",
    "group": "group.study",
    "parent": "brain.work.quiz",
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "youtube link",
      "quiz youtube link"
    ]
  },
  {
    "id": "brain.work.decks",
    "title": "My study decks",
    "about": "Questions kept to study again.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.study",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "decks",
      "review decks",
      "study decks"
    ]
  },
  {
    "id": "brain.work.retirement",
    "title": "Retirement what-if",
    "about": "A simple what-if from numbers you typed.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": "group.finance",
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "retirement",
      "retirement what-if"
    ]
  },
  {
    "id": "brain.work.briefing",
    "title": "Morning briefing",
    "about": "What the morning briefing said.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "morning briefing",
      "briefing"
    ]
  },
  {
    "id": "brain.work.jobs",
    "title": "Background jobs",
    "about": "Long jobs Jarvis is running.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "background jobs",
      "background work"
    ]
  },
  {
    "id": "brain.work.undo",
    "title": "Undo shelf",
    "about": "Changes you can still undo.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": false,
    "collapse": true,
    "why": "Undo is a safety net; hiding it could strand a 10-minute Undo.",
    "names": []
  },
  {
    "id": "brain.work.activity",
    "title": "Activity",
    "about": "What Jarvis did lately.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "work",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.work",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "activity"
    ]
  },
  {
    "id": "brain.projects.progress",
    "title": "Progress",
    "about": "The activity heatmap and balance chart.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "projects",
    "kind": "card",
    "group": "group.goals-projects",
    "parent": "brain.tab.projects",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "progress",
      "heatmap"
    ]
  },
  {
    "id": "brain.now.right-now",
    "title": "Right now",
    "about": "What Jarvis is doing and its power state.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "now",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.now",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "right now"
    ]
  },
  {
    "id": "brain.now.budget",
    "title": "Attention budget",
    "about": "How many interruptions are left.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "now",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.now",
    "hide": false,
    "collapse": true,
    "why": "Pending attention is counted here, so it stays visible.",
    "names": []
  },
  {
    "id": "brain.now.trace",
    "title": "What Jarvis is doing",
    "about": "The tool steps, newest last.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "now",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.now",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "trace",
      "what jarvis is doing"
    ]
  },
  {
    "id": "brain.now.findings",
    "title": "Findings",
    "about": "What Jarvis noticed on its own.",
    "apps": [
      "phone"
    ],
    "area": "brain",
    "view": "now",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.now",
    "hide": true,
    "collapse": true,
    "why": "",
    "names": [
      "findings"
    ]
  },
  {
    "id": "brain.trust.rush-latch",
    "title": "Rush latch banner",
    "about": "Outside text that tried to raise the tier.",
    "apps": [
      "phone"
    ],
    "area": "brain",
    "view": "trust",
    "kind": "answer",
    "group": null,
    "parent": "brain.tab.trust",
    "hide": false,
    "collapse": false,
    "why": "Safety: it must never vanish from the screen.",
    "names": []
  },
  {
    "id": "brain.trust.content-risk",
    "title": "Content risk",
    "about": "Read-only content risk.",
    "apps": [
      "desktop"
    ],
    "area": "brain",
    "view": "trust",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.trust",
    "hide": false,
    "collapse": true,
    "why": "Inside Trust, which can never be hidden.",
    "names": []
  },
  {
    "id": "brain.trust.ledger",
    "title": "Audit chain",
    "about": "The ledger's chain status.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "trust",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.trust",
    "hide": false,
    "collapse": true,
    "why": "Inside Trust, which can never be hidden.",
    "names": []
  },
  {
    "id": "brain.watch.watchlist",
    "title": "GitHub watchlist",
    "about": "The repos Jarvis watches.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "brain",
    "view": "watch",
    "kind": "card",
    "group": null,
    "parent": "brain.tab.watch",
    "hide": false,
    "collapse": true,
    "why": "Inside Watch, which can never be hidden.",
    "names": []
  },
  {
    "id": "entry.appearance",
    "title": "Appearance button on Home",
    "about": "The Appearance button in Home's row.",
    "apps": [
      "phone"
    ],
    "area": "entry",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "appearance button"
    ]
  },
  {
    "id": "entry.voices",
    "title": "Jarvis's voice row",
    "about": "The row that opens Jarvis's voice.",
    "apps": [
      "phone"
    ],
    "area": "entry",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "voices row"
    ]
  },
  {
    "id": "entry.voice-check",
    "title": "Voice check row",
    "about": "The row that opens the voice check.",
    "apps": [
      "phone"
    ],
    "area": "entry",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "voice check",
      "voice check row"
    ]
  },
  {
    "id": "entry.history",
    "title": "History entry in Brain",
    "about": "The row that opens your past chats.",
    "apps": [
      "phone"
    ],
    "area": "entry",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": true,
    "collapse": false,
    "why": "",
    "names": [
      "history entry"
    ]
  },
  {
    "id": "entry.checks",
    "title": "Connection status line",
    "about": "The status line that opens Platform checks.",
    "apps": [
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "It is the connection status (rule 4).",
    "names": []
  },
  {
    "id": "entry.help",
    "title": "Help",
    "about": "The Help entry.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Settings and Help themselves always stay reachable.",
    "names": [
      "help",
      "the help button"
    ]
  },
  {
    "id": "entry.settings",
    "title": "Settings",
    "about": "The Settings entry.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "entry",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Settings and Help themselves always stay reachable.",
    "names": [
      "settings",
      "the settings button"
    ]
  },
  {
    "id": "safety.approvals",
    "title": "Approvals",
    "about": "Approval cards, the widget, the notification.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "answer",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Approvals must always be reachable.",
    "names": [
      "approvals",
      "the inbox",
      "inbox"
    ]
  },
  {
    "id": "safety.stale-link",
    "title": "Stale-link banner",
    "about": "The warning that the link is old.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "answer",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Rule 4: acting is blocked when the event stream is stale.",
    "names": []
  },
  {
    "id": "safety.crisis-help",
    "title": "Crisis help",
    "about": "The help line shown in an answer.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "answer",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "It lives in the answer itself and is never a menu.",
    "names": [
      "crisis help"
    ]
  },
  {
    "id": "safety.stop-everything",
    "title": "Stop everything",
    "about": "The hotkey, tray entry and phone control.",
    "apps": [
      "desktop",
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "answer",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Stop must always work.",
    "names": [
      "stop everything"
    ]
  },
  {
    "id": "safety.live-stop",
    "title": "Stop button in Jarvis Live",
    "about": "End Live.",
    "apps": [
      "phone"
    ],
    "area": "safety",
    "view": "",
    "kind": "answer",
    "group": null,
    "parent": null,
    "hide": false,
    "collapse": false,
    "why": "Stop must always work.",
    "names": []
  }
];
export const NEVER_HIDE = [
  "settings.connection",
  "settings.devices",
  "settings.security",
  "settings.more-options",
  "settings.asks-first",
  "settings.menu-visibility",
  "brain.tab.trust",
  "brain.tab.watch",
  "brain.memory.waiting",
  "brain.work.coming-up",
  "brain.work.undo",
  "brain.now.budget",
  "brain.trust.rush-latch",
  "brain.trust.content-risk",
  "brain.trust.ledger",
  "brain.watch.watchlist",
  "entry.checks",
  "entry.help",
  "entry.settings",
  "safety.approvals",
  "safety.stale-link",
  "safety.crisis-help",
  "safety.stop-everything",
  "safety.live-stop"
];
export const ALIASES = {
  "about": "settings.about",
  "about jarvis": "settings.about",
  "account secrets": "settings.account-secrets",
  "accounts": "settings.account-secrets",
  "activity": "brain.work.activity",
  "always keep in mind": "brain.memory.profile",
  "animal options": "settings.animal-options",
  "animal settings": "settings.animal-options",
  "app lock": "settings.security",
  "app updates": "settings.updates",
  "appearance": "settings.appearance-card",
  "appearance button": "entry.appearance",
  "appearance button on home": "entry.appearance",
  "approvals": "safety.approvals",
  "as of a date": "brain.memory.as-of",
  "asks first": "settings.asks-first",
  "attention budget": "brain.now.budget",
  "audit chain": "brain.trust.ledger",
  "backend capabilities": "settings.backend-supports",
  "background jobs": "brain.work.jobs",
  "background work": "brain.work.jobs",
  "backup settings": "settings.backup",
  "backups": "settings.backup",
  "between us": "brain.memory.between-us",
  "big model": "settings.big-model",
  "big model (slow)": "settings.big-model",
  "briefing": "brain.work.briefing",
  "briefing settings": "settings.briefing-settings",
  "bring in old chats": "brain.memory.history-import",
  "browser settings": "settings.browser-engine",
  "browser without a window": "settings.browser-engine",
  "bubble": "settings.floating-avatar",
  "chat history": "brain.tab.history",
  "chat history and conversations": "brain.history.conversations",
  "chat tags": "brain.history.tags",
  "chat with customer support for me": "brain.work.support",
  "chatbot": "group.chatbots",
  "chatbot driver": "brain.work.chatbot",
  "chatbots": "group.chatbots",
  "check for tool updates": "settings.tool-updates",
  "coming up": "brain.work.coming-up",
  "compute": "brain.model.compute",
  "connection": "settings.connection",
  "connection settings": "settings.connection",
  "connection status line": "entry.checks",
  "content risk": "brain.trust.content-risk",
  "conversations": "brain.history.conversations",
  "credentials": "settings.account-secrets",
  "crisis help": "safety.crisis-help",
  "custom voices": "settings.voices",
  "customer support": "brain.work.support",
  "decks": "brain.work.decks",
  "deep questions": "brain.memory.deep",
  "devices": "settings.devices",
  "email sending": "settings.email-sending",
  "faces": "settings.appearance-card",
  "faq": "settings.faq",
  "finance": "group.finance",
  "finances": "group.finance",
  "findings": "brain.now.findings",
  "floating face": "settings.floating-avatar",
  "floating jarvis": "settings.floating-avatar",
  "focus": "brain.work.focus",
  "focus session": "brain.work.focus",
  "folders": "settings.folders",
  "folders jarvis may look in": "settings.folders",
  "forget a time frame": "brain.history.forget-range",
  "frequently asked questions": "settings.faq",
  "galaxy": "brain.tab.galaxy",
  "github watchlist": "brain.watch.watchlist",
  "goals": "brain.work.goals",
  "goals & projects": "group.goals-projects",
  "goals and projects": "group.goals-projects",
  "gpu": "group.graphics-cards",
  "gpus": "group.graphics-cards",
  "graphics card": "group.graphics-cards",
  "graphics cards": "group.graphics-cards",
  "hardware": "settings.hardware",
  "hardware and models": "settings.hardware",
  "headless browser": "settings.browser-engine",
  "heatmap": "brain.projects.progress",
  "help": "entry.help",
  "help and faq": "settings.faq",
  "help button": "entry.help",
  "history": "brain.tab.history",
  "history entry": "entry.history",
  "history entry in brain": "entry.history",
  "history import": "brain.memory.history-import",
  "home": "group.home",
  "hotkeys": "settings.shortcuts",
  "how jarvis talks": "settings.manner",
  "inbox": "safety.approvals",
  "inside jokes": "brain.memory.between-us",
  "jarvis's voice": "settings.voices",
  "jarvis's voice row": "entry.voices",
  "jarvis's voices": "settings.voices",
  "keyboard shortcuts": "settings.shortcuts",
  "learning": "brain.memory.learning",
  "look at this": "settings.screen-look",
  "look at this and watch with me": "settings.screen-look",
  "manner": "settings.manner",
  "memory": "brain.tab.memory",
  "memory (model view)": "brain.model.memory",
  "memory counts": "brain.memory.learning",
  "menu list": "settings.menu-visibility",
  "menus": "settings.menu-visibility",
  "model": "brain.tab.faculties",
  "model list": "brain.model.models",
  "model memory": "brain.model.memory",
  "models": "brain.model.models",
  "models list": "brain.model.models",
  "money and spending": "group.finance",
  "more options": "settings.more-options",
  "morning briefing": "brain.work.briefing",
  "morning briefing settings": "settings.briefing-settings",
  "now": "brain.tab.now",
  "paired devices": "settings.devices",
  "pairing": "settings.connection",
  "past chats": "brain.history.conversations",
  "pc help": "brain.model.pc-help",
  "people": "brain.memory.people-things",
  "people and things": "brain.memory.people-things",
  "phone notifications": "settings.phone-notify",
  "pinned facts": "brain.memory.profile",
  "progress": "brain.projects.progress",
  "projects": "brain.tab.projects",
  "projects and goals": "group.goals-projects",
  "quick settings tiles": "settings.quick-tiles",
  "quick tiles": "settings.quick-tiles",
  "quiz": "brain.work.quiz",
  "quiz from a youtube link": "brain.work.quiz.youtube",
  "quiz me on a text": "brain.work.quiz",
  "quiz youtube link": "brain.work.quiz.youtube",
  "quizzes": "brain.work.quiz",
  "reach": "settings.reach",
  "referee": "settings.second-card.referee",
  "referee suggestions": "settings.second-card.referee",
  "referee suggestions (second card switch)": "settings.second-card.referee",
  "referee switch": "settings.second-card.referee",
  "retirement": "brain.work.retirement",
  "retirement what-if": "brain.work.retirement",
  "review decks": "brain.work.decks",
  "right now": "brain.now.right-now",
  "rush latch banner": "brain.trust.rush-latch",
  "saved automatically": "brain.memory.auto",
  "screen settings": "settings.screen-look",
  "search provider": "settings.web-search",
  "search settings": "settings.web-search",
  "second card": "settings.second-card",
  "second gpu": "settings.second-card",
  "second graphics card": "settings.second-card",
  "security": "settings.security",
  "security settings": "settings.security",
  "sending email": "settings.email-sending",
  "server address": "settings.connection",
  "settings": "entry.settings",
  "settings button": "entry.settings",
  "shortcuts": "settings.shortcuts",
  "show or hide": "settings.menu-visibility",
  "skills": "brain.model.skills",
  "smart home": "group.home",
  "smartwatch notifications": "settings.watch-notify",
  "spending": "settings.spending",
  "spending summaries": "settings.spending",
  "stale-link banner": "safety.stale-link",
  "stop button in jarvis live": "safety.live-stop",
  "stop everything": "safety.stop-everything",
  "study": "group.study",
  "study decks": "brain.work.decks",
  "study helper": "settings.second-card.study-helper",
  "study helper (second card switch)": "settings.second-card.study-helper",
  "study helper switch": "settings.second-card.study-helper",
  "studying": "group.study",
  "suggest tags overnight": "brain.history.tag-suggestions",
  "support chats": "brain.work.support",
  "tag suggestions": "brain.history.tag-suggestions",
  "tags": "brain.history.tags",
  "talk to a chatbot": "brain.work.chatbot",
  "talk to a chatbot for me": "brain.work.chatbot",
  "theme": "settings.appearance-card",
  "themes": "settings.appearance-card",
  "third card": "settings.second-card.third-card",
  "third graphics card": "settings.second-card.third-card",
  "this backend": "settings.backend-supports",
  "today": "brain.work.today",
  "tool updates": "settings.tool-updates",
  "topics": "brain.memory.topics",
  "trace": "brain.now.trace",
  "trust": "brain.tab.trust",
  "undo shelf": "brain.work.undo",
  "updates": "settings.updates",
  "voice": "settings.voice",
  "voice check": "entry.voice-check",
  "voice check row": "entry.voice-check",
  "voice settings": "settings.voice",
  "voices row": "entry.voices",
  "waiting for you": "brain.memory.waiting",
  "watch": "brain.tab.watch",
  "watch notifications": "settings.watch-notify",
  "watch with me": "settings.screen-look",
  "web search": "settings.web-search",
  "what asks first": "settings.asks-first",
  "what asks first settings": "settings.asks-first",
  "what did i believe": "brain.memory.as-of",
  "what did i believe on this date": "brain.memory.as-of",
  "what jarvis can reach": "settings.reach",
  "what jarvis is doing": "brain.now.trace",
  "what jarvis knows about you": "brain.memory.known",
  "what this backend supports": "settings.backend-supports",
  "widgets": "brain.work.widgets",
  "wiki": "brain.memory.wiki",
  "windows hello": "settings.security",
  "work": "brain.tab.work",
  "youtube link": "brain.work.quiz.youtube"
};
export const DEFAULTS = {
  "hidden": [],
  "collapsed": [],
  "note": "Everything visible and unfolded. Advanced tabs on the desktop keep their own switch (a tab is shown only when BOTH allow it).",
  "storage": {
    "desktop": {
      "hidden_key": "jarvis.menus.hidden",
      "collapsed_key": "jarvis.menus.collapsed",
      "version_key": "jarvis.menus.v",
      "version": 1,
      "format": "JSON array of strings, in localStorage, in try/catch"
    },
    "phone": {
      "prefs_file": "jarvis_menus",
      "hidden_key": "hidden",
      "collapsed_key": "collapsed",
      "version_key": "v",
      "version": 1,
      "format": "string sets in SharedPreferences, guarded"
    }
  }
};
export const MIGRATION = [
  {
    "rule": "first_run",
    "text": "Nothing to migrate: no earlier choice exists. Start with everything visible."
  },
  {
    "rule": "stale_ids",
    "text": "A stored id that no longer exists, or belongs to the other app, is ignored silently and dropped the next time the list is saved."
  },
  {
    "rule": "never_ids",
    "text": "A never-hideable id found in the hidden set is ignored and dropped."
  },
  {
    "rule": "unknown_version",
    "text": "A stored version other than 1 is read as empty (everything visible) and is not overwritten until the owner changes something."
  },
  {
    "rule": "storage_failure",
    "text": "If storage cannot be read or written, everything shows and nothing crashes."
  },
  {
    "rule": "existing_folds",
    "text": "The Advanced switch, #more-options and 'Hide memory lists and chat history' keep their own storage; this store neither reads nor replaces them."
  }
];
