/**
 * palette.js - the words and the list behind the command palette, and
 * nothing that touches a page.
 *
 * WHAT THIS IS FOR. The desktop has 104 menu entries, 33 Settings cards, ten
 * Brain tabs and ten hotkeys, and no way to search any of it: finding one
 * card means opening the right window and knowing which tab it lives on
 * (docs/UI-AUDIT-2026-10-05.md section 2.4, and its "what I would change"
 * row 4 - "build the in-app command palette (already decided, never
 * built)"). This is that palette's list. It offers ONLY what the app can
 * already do: every row is a menu the owner can already reach by hand.
 *
 * WHERE EVERY NAME COMES FROM. THE REAL CATALOGUE, never a second copy.
 * menu-catalog.js is generated by tools/gen_menu_cases.py from
 * backend/jarvis_menus.py, which is the same list "Show or hide menus",
 * Jarvis's own voice and the phone all read. A hand-typed list here would
 * drift from it within a week and send the owner to a card that no longer
 * exists, so there is deliberately no place in this file to type a menu
 * name. Aliases (what Jarvis already answers to) and the `about` line come
 * from the catalogue too.
 *
 * A ROW OPENS WHAT IT SAYS. `placeFor` turns a catalogue id into the place
 * the app already knows how to open - the same two mechanisms the Jarvis bar
 * already uses for "open <a settings section>" and "earlier chats" - and a
 * test walks every row to be sure each one lands somewhere real.
 *
 * NO PAGE, NO TAURI: node can import it (the same rule sayable.js and
 * menu-visibility.js follow), so the list and the search are tested without
 * a browser.
 *
 * @module palette
 */

import {
  GROUPS,
  GROUP_PREFIX,
  MENUS,
  has,
  isGroupId,
  menu,
  members,
  titleOf,
} from "./menu-visibility.js";

const APP = "desktop";

/**
 * The words on the surface. Lower case in the code, sentence case on screen,
 * the same shape as the rest of the app's copy.
 */
export const WORDS = Object.freeze({
  title: "Find anything",
  /** The search field's own name, for a screen reader. */
  search_label: "Search what Jarvis can do",
  placeholder: "Type a few letters - a screen, a setting, an action…",
  /** Shown in the empty bar before the palette is opened, so it is findable. */
  hint: "Type / to find anything",
  /** The list with nothing typed: a plain count, not a bare number. */
  all_one: "1 thing Jarvis can do",
  all_many: "{n} things Jarvis can do",
  /** A search that matched nothing. */
  none_title: "Nothing matches that.",
  none_body: "Try the name you see in the window, or a word from its one-line description.",
  /** A screen with nothing at all in the catalogue - never expected, said plainly. */
  empty_title: "There is nothing to list yet.",
  empty_body: "The list is built from the app's own menus, and none of them reached this bar.",
  /** The keys, in the footer. */
  keys: "↑ ↓ to move · Enter to open · Esc to close",
  /** What a screen reader hears when the palette opens. */
  opened: "Find anything, {n} things. Type to search.",
  opened_one: "Find anything, 1 thing. Type to search.",
  opened_none: "Find anything. Nothing to list yet.",
  /** ...and when the list changes. */
  results_one: "1 match",
  results_many: "{n} matches",
  results_none: "Nothing matches that",
  /** The group headings the list draws itself under. */
  group_headings: Object.freeze({
    screens: "Screens",
    settings: "Settings",
    brain: "Brain",
    actions: "Actions",
  }),
});

/** Fill `{n}` (or any other single key) without a template engine. */
export function fill(text, vars = {}) {
  return String(text).replace(/\{(\w+)\}/g, (whole, key) =>
    Object.prototype.hasOwnProperty.call(vars, key) ? String(vars[key]) : whole);
}

/**
 * The label on the bar's own button, which is the only discoverable way in
 * besides typing "/". Kept beside the words so the two cannot disagree.
 */
export const HINT_LABEL = "Find";

/** The key that does the same thing, shown on that button. */
export const HINT_KEY = "/";

/**
 * One small monochrome glyph per heading, as SVG shape DATA - the same
 * numbers a `<path d="...">` takes. Deliberately not markup: palette-ui.js
 * builds the element, so there is no `innerHTML` sink anywhere near a list
 * built from the catalogue (tests/html-sinks.mjs walks every sink in src/,
 * and a sink fed "a constant" from here would be one more thing to justify).
 * The shapes carry no colour of their own (they inherit `currentColor`),
 * which is why `scripts/check-tokens.py` has nothing to say about them.
 *
 * `viewBox` is shared: every glyph is drawn on the bar's own 16x16 grid.
 */
export const ICON_VIEWBOX = "0 0 16 16";

export const ICONS = Object.freeze({
  screens: [
    { path: "M2.5 3.5h11a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1h-11a1 1 0 0 1-1-1v-6a1 1 0 0 1 1-1Zm.5 1.5v5h9v-5H3Z" },
    { path: "M6 13h4a.75.75 0 0 1 0 1.5H6A.75.75 0 0 1 6 13Z" },
  ],
  settings: [
    { path: "M2 4.25h5.1a2.25 2.25 0 0 0 4.3 0H14a.75.75 0 0 1 0 1.5H11.4a2.25 2.25 0 0 0-4.3 0H2A.75.75 0 0 1 2 4.25Z" },
    { circle: { cx: "8.75", cy: "5", r: "1.4" } },
    { path: "M2 11.75h2.6a2.25 2.25 0 0 0 4.3 0H14a.75.75 0 0 1 0 1.5H8.9a2.25 2.25 0 0 0-4.3 0H2a.75.75 0 0 1 0-1.5Z" },
    { circle: { cx: "5.75", cy: "12.5", r: "1.4" } },
  ],
  brain: [
    { path: "M8 1.5a3 3 0 0 0-2.9 2.2A2.6 2.6 0 0 0 3.2 6.4 2.5 2.5 0 0 0 2 8.6c0 .9.5 1.7 1.2 2.2A2.6 2.6 0 0 0 5 14.5c.9 0 1.7-.4 2.2-1.1V1.9A1 1 0 0 0 8 1.5Z" },
    { path: "M8 1.5a3 3 0 0 1 2.9 2.2 2.6 2.6 0 0 1 1.9 2.7 2.5 2.5 0 0 1 1.2 2.2c0 .9-.5 1.7-1.2 2.2a2.6 2.6 0 0 1-1.8 3.7c-.9 0-1.7-.4-2.2-1.1V1.9A1 1 0 0 1 8 1.5Z", opacity: "0.55" },
  ],
  actions: [
    { path: "M8.9 1.5 3.4 8.8a.6.6 0 0 0 .5 1h2.6l-.5 4.7 5.6-7.3a.6.6 0 0 0-.5-1H8.4l.5-4.7Z" },
  ],
});

/**
 * The heading a row is drawn under. Read off the catalogue's own `area` and
 * `kind`, so a new menu lands in the right heading without an edit here.
 * `area` is one of brain / settings / safety / entry (jarvis_menus.py).
 */
export function headingOf(item) {
  if (item.kind === "entry" || item.area === "safety" || item.area === "entry") {
    return WORDS.group_headings.actions;
  }
  if (item.area === "settings") return WORDS.group_headings.settings;
  if (item.kind === "tab") return WORDS.group_headings.screens;
  return WORDS.group_headings.brain;
}

/**
 * Where one catalogue entry is, in the app: which window it is in, which
 * Brain tab it sits on, and the thing to show once that window is open.
 *
 * `tab` is the Brain view a card sits under - taken from the catalogue's own
 * `view`, which is the same key brain.js's rail uses ("work", "memory", …).
 */
export function entryPlace(m) {
  if (!m) return null;
  // The catalogue's `area` names the window a menu lives in - except for the
  // two "entry" rows (Help, Settings), which are the tray and Brain rows that
  // open the Settings window rather than anything inside the Brain.
  const settings = m.area === "settings" || m.id === "entry.settings" || m.id === "entry.help";
  return {
    id: m.id,
    title: m.title,
    about: m.about || "",
    kind: m.kind,
    area: m.area,
    /** The Brain view key the rail uses ("work", "memory", …); a tab's own
     *  view is itself. A Settings card has none. */
    tab: settings ? "" : (m.view || ""),
    window: settings ? "settings" : "brain",
  };
}

/**
 * The whole list, in the order it should be read: the six named feature
 * groups first (they are what Jarvis itself answers to by voice), then every
 * menu this computer has, in catalogue order.
 *
 * A menu hidden with "Show or hide menus" is left in on purpose: hiding is
 * cosmetic (nothing is turned off), the palette is a way to REACH a menu the
 * owner has tidied away, and a link to a hidden card already shows it for
 * that visit. The row says it is hidden so nothing here is a surprise.
 *
 * @param {{hiddenFor?: (id: string) => boolean}} [deps]
 * @returns {Array<object>}
 */
export function buildPalette({ hiddenFor = () => false } = {}) {
  const items = [];

  for (const g of GROUPS) {
    const mems = members(g.id, APP);
    if (mems.length === 0) continue;
    items.push({
      kind: "group",
      id: g.id,
      title: g.title,
      about: g.about || "",
      /** The names Jarvis already answers to, so typing one finds it. */
      names: Array.isArray(g.names) ? g.names.slice() : [],
      place: { group: true, id: g.id, members: mems },
      hidden: false,
    });
  }

  for (const m of MENUS) {
    if (!has(m, APP)) continue;
    // `safety.*` is not a destination: it is the catalogue's own bookkeeping
    // for things that must never be hidden (approval cards, the stale-link
    // banner, the crisis-help line). None of them is a place a window can
    // open, and offering one would be a row that does nothing the moment it
    // is pressed - the defect this whole audit was about. The row that DOES
    // take the owner there already exists and is listed on its own.
    if (m.area === "safety" && m.kind !== "entry") continue;
    items.push({
      kind: m.kind,
      id: m.id,
      title: m.title,
      about: m.about || "",
      names: Array.isArray(m.names) ? m.names.slice() : [],
      place: entryPlace(m),
      hidden: Boolean(hiddenFor(m.id)),
    });
  }

  return items;
}

/**
 * Case- and punctuation-blind, so "What asks first?" and "what asks first"
 * are the same search. Kept here rather than in the search so the test and
 * the surface always fold the same way.
 */
export function fold(text) {
  return String(text == null ? "" : text)
    .toLowerCase()
    .replace(/[’']/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/** Where `needle` sits inside `hay`: 0 at the very start, then by word start,
 *  then anywhere. `-1` when it is not there at all. */
function rankAt(hay, needle) {
  if (!hay || !needle) return -1;
  const at = hay.indexOf(needle);
  if (at < 0) return -1;
  if (at === 0) return 0;
  return /[\s-]/.test(hay[at - 1]) ? 1 : 2;
}

/**
 * Ranks one item against an already-folded query. Lower is better; -1 is no
 * match. A title that starts with the words beats a title that contains
 * them, which beats an alias, which beats the one-line description - so
 * typing "work" finds the Work screen first and "network" in a paragraph
 * last.
 */
export function scoreItem(item, query) {
  const q = fold(query);
  if (!q) return 0;
  const title = fold(item.title);
  const titleAt = rankAt(title, q);
  if (titleAt === 0) return 0;
  if (titleAt === 1) return 1;
  if (titleAt === 2) return 2;
  for (const name of item.names || []) {
    const at = rankAt(fold(name), q);
    if (at >= 0) return 3 + at;
  }
  const aboutAt = rankAt(fold(item.about), q);
  if (aboutAt >= 0) return 6 + aboutAt;
  const idAt = rankAt(fold(String(item.id).replace(/\./g, " ")), q);
  if (idAt >= 0) return 9 + idAt;
  return -1;
}

/**
 * The rows the search shows, best first. Ties keep catalogue order, so the
 * list never shuffles between two keystrokes.
 *
 * @param {Array<object>} items  from {@link buildPalette}
 * @param {string} query
 */
export function search(items, query) {
  const q = fold(query);
  if (!q) return items.map((item, index) => ({ item, score: 0, index }));
  const out = [];
  items.forEach((item, index) => {
    const score = scoreItem(item, q);
    if (score >= 0) out.push({ item, score, index });
  });
  out.sort((a, b) =>
    a.score - b.score ||
    a.item.title.length - b.item.title.length ||
    a.index - b.index);
  return out;
}

/**
 * The line a row is announced with and read as its second half. Groups say
 * what they hide; a menu says what it is, and says so when it is hidden on
 * this computer (the same fact the Settings card would show).
 */
export function describe(item) {
  const about = item.about ? item.about : "";
  const hid = item.hidden ? ` Hidden on this computer.` : "";
  if (item.kind === "group") {
    const n = item.place && item.place.members ? item.place.members.length : 0;
    return `${about}${about ? " " : ""}${n === 1 ? "1 menu" : `${n} menus`}.${hid}`.trim();
  }
  return `${about}${hid}`.trim();
}

/**
 * What pressing Enter on a row asks the app to open. This is the shape the
 * two existing navigation mechanisms already take:
 *
 *  * `settings` - the id Settings already uses for that card (settings.js's
 *    own goToPlace, the same path "open <a settings section>" takes);
 *  * `brain` - the view's key and, when the row names a card, the card's own
 *    menu id, which brain.html already carries as `data-menu-id`;
 *  * `group` - the first member, so a group row goes somewhere real rather
 *    than nowhere: the group itself is a hiding unit, not a place.
 *
 * Returns null for anything the app cannot open, and the surface then says
 * so rather than doing nothing.
 */
export function placeFor(item) {
  if (!item) return null;
  if (item.kind === "group") {
    const first = item.place && item.place.members ? item.place.members[0] : null;
    const m = first ? menu(first) : null;
    return m ? placeFor({ id: m.id, kind: m.kind, area: m.area, place: entryPlace(m) }) : null;
  }
  const place = item.place;
  if (!place) return null;
  if (place.window !== "settings" && place.window !== "brain") return null;
  if (place.window === "settings") {
    // `settings.hardware` is Settings -> #hardware. A row that is itself a
    // row of a card (`settings.second-card.referee`) opens its parent card,
    // which is where it lives on the page. The two "entry" rows name their
    // own target instead (Help opens the FAQ card, Settings the window).
    const m = menu(item.id);
    const parent = m && m.parent && m.parent.startsWith("settings.") ? m.parent : null;
    const own = item.id === "entry.help" ? "faq"
      : item.id === "entry.settings" ? "connection" : null;
    const card = parent || own || item.id;
    const elementId = card.startsWith("settings.") ? card.slice("settings.".length) : card;
    return { window: "settings", place: elementId, card };
  }
  const tab = place.tab || "";
  // Which element to show once the window is open. A card is itself; a ROW
  // (kind "row", e.g. `brain.work.quiz.youtube`, `brain.history.tag-suggestions`)
  // has no element of its own, so it opens the nearest card it lives inside -
  // which is where the rail would take the owner by hand. A tab needs no
  // card: the tab is the destination.
  let card = "";
  if (item.kind !== "tab") {
    if (item.kind === "card") {
      card = item.id;
    } else {
      let m = menu(item.id);
      while (m && m.parent) {
        const up = menu(m.parent);
        if (up && up.kind === "card") {
          card = up.id;
          break;
        }
        m = up;
      }
    }
  }
  return card || tab ? { window: "brain", tab, card, place: card || tab } : null;
}

/** True when a row is a feature group rather than one menu. */
export function isGroup(item) {
  return Boolean(item && (item.kind === "group" || isGroupId(item.id)));
}

/** The group a menu belongs to, for a row's own subtitle; "" when it has none. */
export function groupTitleOf(id) {
  const m = menu(id);
  if (!m || !m.group) return "";
  const id2 = m.group.startsWith(GROUP_PREFIX) ? m.group.slice(GROUP_PREFIX.length) : m.group;
  const g = GROUPS.find((x) => x.id === id2 || x.id === GROUP_PREFIX + id2);
  return g ? g.title : "";
}

/** The title the catalogue gives an id - used by tests and by the surface's
 *  own "opened X" line, never a second list of names. */
export function title(id) {
  return titleOf(id);
}
