"""test_tool_updates.py - "Check for tool updates" (jarvis_tool_updates.py,
tool-updates.patch; the owner's own request, made directly).

    python3 backend/test_tool_updates.py

Runs anywhere; no model, and NO REAL NETWORK CALL - every PyPI, crates.io
and GitHub fetch is a fake function this file supplies. What it proves:

1. Parsing: requirements.lock's `name==version` lines (continuations joined,
   duplicate-marker lines deduped) and Cargo.lock's `[[package]]` entries
   (a local, sourceless package such as jarvis-desktop itself is skipped;
   only a crates.io registry source counts).
2. The report: an outdated package/crate is flagged with the exact command
   to run (never executed here or anywhere in the module - the module
   imports no subprocess, no os.system); an up-to-date one is not; a fetch
   that fails lands in "unreachable", never raises; the summary sentence
   counts correctly. crates.io is asked once per crate NAME, not once per
   pinned version.
3. A missing requirements.lock/rust-crates.lock says so plainly (available:
   false, why), rather than reporting zero tools.
4. GitHub tools: empty by default (and says why, in GITHUB_TOOLS_NOTE); a
   fake pinned tool with a fake 403 answer becomes one WARN line
   ("unreachable"), never a crash - the rate-limit case the brief asks for.
5. The one-time card: not yet approved needs a person's yes (denied/timed
   out add nothing; approved sets the flag AND runs the check in the same
   thread); already approved runs straight away, no gate call at all;
   a non-"ask" tier is refused (503).
6. Never says "vulnerable" (that is check_python_advisories.py's job, not
   this one) and never imports anything that could execute a shell command.
7. The route and the patch: install() answers /api/tool_updates and
   /api/tool_updates/check after the server's own checks and passes
   everything else on; tool-updates.patch applies after the rest of the
   stack and reverses; the module is shipped.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import traceback
import urllib.error
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _where import require_shipped  # noqa: E402
require_shipped("jarvis_tool_updates.py")
import _stack  # noqa: E402
import jarvis_tool_updates as TU  # noqa: E402

FAILED, PASSED = [], []
SKIPPED = []
TMP = Path(tempfile.mkdtemp(prefix="jarvis-tool-updates-"))
CONF = TMP / "config"
CONF.mkdir()
TU._config_dir = lambda: CONF


def check(name, cond, detail=""):
    (PASSED if cond else FAILED).append(name)
    print(f"{'ok   ' if cond else 'FAIL '} {name}" + (f"\n        {detail}" if detail and not cond
                                                        else ""))


def skip(why):
    """A check this machine cannot run: printed as `skip`, counted on its own,
    never as a pass. (It used to be check("SKIP - ...", True) - a condition of
    the constant True, so it printed as a pass and was counted as one.)"""
    SKIPPED.append(why)
    print(f"skip  {why}")


class Verdict:
    def __init__(self, allowed, outcome, tier="ask"):
        self.allowed, self.outcome, self.tier = allowed, outcome, tier
        self.reason = outcome


def run_now(fn):
    fn()


def fresh():
    TU._reset_for_tests()
    try:
        TU.settings_path().unlink()
    except FileNotFoundError:
        pass


def http_error(url, code):
    return urllib.error.HTTPError(url, code, "boom", {}, None)


# ---------------------------------------------------------------------------
#   1. Parsing
# ---------------------------------------------------------------------------

LOCK_TEXT = """\
# a comment line, and a blank one below

anyio==4.15.1 ; python_full_version >= '3.11' \\
    --hash=sha256:aaaa \\
    --hash=sha256:bbbb
    # via httpx
beautifulsoup4==4.15.0 \\
    --hash=sha256:cccc
numpy==1.26.0 ; python_full_version < '3.11' \\
    --hash=sha256:dddd
numpy==2.1.0 ; python_full_version >= '3.11' \\
    --hash=sha256:eeee
"""

CARGO_TEXT = """\
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "jarvis-desktop"
version = "0.2.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "libc"
version = "0.2.150"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def456"
"""


def t_python_lock_parsing():
    pins = TU.parse_python_lock(LOCK_TEXT)
    check("three distinct canonical names", set(pins) == {"anyio", "beautifulsoup4", "numpy"},
          sorted(pins))
    check("the original (unlowered) name is kept", pins["anyio"][0] == "anyio")
    check("a package pinned twice for two Python markers keeps one entry (the last seen)",
          pins["numpy"][1] == "2.1.0", pins["numpy"])
    check("no hash line is ever read as a package",
          all(not n.startswith("hash") for n in pins))


def t_cargo_lock_parsing():
    pins = TU.parse_cargo_lock(CARGO_TEXT)
    check("the local jarvis-desktop package (no source) is skipped",
          all(n != "jarvis-desktop" for n, _v in pins), pins)
    check("both crates.io-sourced crates are kept, with their real versions",
          set(pins) == {("serde", "1.0.200"), ("libc", "0.2.150")}, pins)


def t_cargo_lock_unreadable_without_toml():
    saved = TU._toml
    try:
        TU._toml = None
        check("no tomllib/tomli at all: None, never an empty list",
              TU.parse_cargo_lock(CARGO_TEXT) is None)
    finally:
        TU._toml = saved


# ---------------------------------------------------------------------------
#   2. The report
# ---------------------------------------------------------------------------


def t_python_group_outdated_uptodate_and_unreachable(tmp_path=None):
    d = TMP / "py1"
    d.mkdir()
    (d / "requirements.lock").write_text(
        "alpha==1.0.0\nbeta==2.0.0\ngamma==3.0.0\n", encoding="utf-8")

    asked = []

    def fetch(url):
        asked.append(url)
        if "alpha" in url:
            return {"info": {"version": "1.5.0"}}     # newer: outdated
        if "beta" in url:
            return {"info": {"version": "2.0.0"}}     # same: up to date
        raise http_error(url, 500)                    # gamma: unreachable

    def installed(name):
        return {"alpha": "1.0.0", "beta": "2.0.0"}.get(name)  # gamma not installed

    g = TU._python_group(d, fetch, installed)
    by_name = {it["name"]: it for it in g["items"]}
    check("alpha is outdated with the exact upgrade command",
          by_name["alpha"]["outdated"] is True
          and by_name["alpha"]["command"] == "py -3 -m pip install --upgrade alpha")
    check("beta is up to date, no command offered",
          by_name["beta"]["outdated"] is False and by_name["beta"]["command"] is None)
    check("gamma (network failure) is unreachable, not raised, not in items",
          "gamma" not in by_name
          and g["unreachable"] and g["unreachable"][0]["name"] == "gamma")
    check("a package not installed here falls back to the lock's version, and says so",
          "note" not in by_name["alpha"] and "note" not in by_name["beta"])

    # Was `check("nothing here ever calls the network for the local package name
    # itself", True)`: the condition was the constant True, so it printed ok
    # whatever the report did, and nothing in this test observed the network at
    # all (the comment above it describes a case the test never ran). What IS
    # observable is which names the report asks about, so that is what is
    # asserted now - once per name the lock pins, and never anything else.
    asked_names = sorted({n for n in ("alpha", "beta", "gamma") if any(n in u for u in asked)})
    check("only the lock's own package names are asked about over the network, once each",
          asked_names == ["alpha", "beta", "gamma"] and len(asked) == 3, asked)


def t_python_group_missing_lock_says_so():
    d = TMP / "py2"
    d.mkdir()
    g = TU._python_group(d, lambda u: {}, lambda n: None)
    check("no requirements.lock: available is false, with a plain why",
          g["available"] is False and "apply-patches.ps1" in g["why"] and g["items"] == [])


def t_rust_group_dedupes_by_name_and_flags_outdated():
    d = TMP / "rs1"
    d.mkdir()
    (d / "rust-crates.lock").write_text("""\
[[package]]
name = "jarvis-desktop"
version = "0.2.0"

[[package]]
name = "serde"
version = "1.0.100"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "libc"
version = "0.2.99"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "anyhow"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
""", encoding="utf-8")
    calls = []

    def fetch(url):
        calls.append(url)
        if "serde" in url:
            return {"crate": {"max_stable_version": "1.0.200"}}
        if "anyhow" in url:
            return {"crate": {"max_stable_version": "1.0.1"}}
        return {"crate": {"max_stable_version": "0.2.99"}}

    g = TU._rust_group(d, fetch)
    check("the local jarvis-desktop package is never checked",
          all("jarvis-desktop" not in c for c in calls))
    check("serde is asked ONCE even though it is pinned at two versions",
          sum("serde" in c for c in calls) == 1, calls)
    serde_items = [it for it in g["items"] if it["name"] == "serde"]
    check("both serde pins are reported, each against the SAME latest version",
          len(serde_items) == 2 and all(it["latest"] == "1.0.200" for it in serde_items))
    check("the older serde pin is outdated, with a cargo command; the newer is not",
          any(it["outdated"] and it["command"] == "cd jarvis-desktop\\src-tauri; "
              "cargo update -p serde@1.0.100" for it in serde_items)
          and any(not it["outdated"] for it in serde_items))
    check("the command names the version - a bare name is ambiguous for a "
          "crate pinned at two versions, and cargo refuses it (bug audit "
          "2026-09-27, finding #6)",
          all("@" in it["command"] for it in serde_items if it["command"]))
    libc_item = next(it for it in g["items"] if it["name"] == "libc")
    check("libc is exactly at the latest version - not outdated", libc_item["outdated"] is False)
    anyhow_item = next(it for it in g["items"] if it["name"] == "anyhow")
    check("anyhow is pinned once and outdated, so its command stays a bare "
          "name - only a name pinned twice needs the version to disambiguate",
          anyhow_item["outdated"] and
          anyhow_item["command"] == "cd jarvis-desktop\\src-tauri; cargo update -p anyhow")


def t_rust_group_missing_lock_says_so():
    d = TMP / "rs2"
    d.mkdir()
    g = TU._rust_group(d, lambda u: {})
    check("no rust-crates.lock: available is false, with a plain why",
          g["available"] is False and "apply-patches.ps1" in g["why"])


def t_github_group_empty_by_default_and_rate_limit_warns():
    g = TU._github_group(lambda u: {})
    check("empty by default, and says why in plain words",
          g["items"] == [] and g["why"] == TU.GITHUB_TOOLS_NOTE and g["available"] is True)

    fake = TU.GithubTool("Example Tool", "example/example", "v1.0.0", "docs/EXAMPLE.md")

    def rate_limited(url):
        raise http_error(url, 403)

    g2 = TU._github_group(rate_limited, (fake,))
    check("a 403 becomes one WARN line (unreachable), never a crash",
          g2["items"] == [] and len(g2["unreachable"]) == 1
          and "rate-limited" in g2["unreachable"][0]["why"])

    def newer(url):
        return {"tag_name": "v2.0.0"}

    g3 = TU._github_group(newer, (fake,))
    check("a real newer tag is flagged outdated, by exact string, never installed",
          g3["items"][0]["outdated"] is True and g3["items"][0]["command"] is None)

    def same(url):
        return {"tag_name": "v1.0.0"}

    g4 = TU._github_group(same, (fake,))
    check("the same tag is not outdated", g4["items"][0]["outdated"] is False)


def t_run_check_shape_and_summary():
    d = TMP / "full"
    d.mkdir()
    (d / "requirements.lock").write_text("alpha==1.0.0\n", encoding="utf-8")
    (d / "rust-crates.lock").write_text("""\
[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
""", encoding="utf-8")
    report = TU.run_check(
        backend_dir=d,
        pypi_fetch=lambda u: {"info": {"version": "1.5.0"}},
        crates_fetch=lambda u: {"crate": {"max_stable_version": "1.0.0"}},
        github_fetch=lambda u: {"tag_name": "v0"},
        installed_version=lambda n: None,
        clock=lambda: 12345.0,
    )
    check("checked_at is the injected clock", report["checked_at"] == 12345.0)
    check("three groups, in order: Python, Rust, GitHub",
          [g["ecosystem"] for g in report["groups"]]
          == ["Python packages", "Rust crates", "GitHub tools"])
    check("one outdated (alpha) counted across the whole report",
          report["total_outdated"] == 1 and report["total_checked"] == 2)
    check("the summary sentence names the count",
          "1 of your 2 tools have a newer version" in report["summary"])


def t_never_says_vulnerable_or_can_execute_anything():
    src = (HERE / "jarvis_tool_updates.py").read_text(encoding="utf-8")
    # The words the OWNER actually sees (the card, the settings page, a
    # report item) - not the module's own docstring, which legitimately
    # CONTRASTS this feature with check_python_advisories.py's (that word
    # is expected there, explaining why this is a different check).
    owner_facing = " ".join([TU.TITLE, TU.DETAIL, TU.CARD, TU.MISSING, TU.GITHUB_TOOLS_NOTE,
                             " ".join(TU.LAST_WORDS.values())])
    check("never claims a security finding in anything the owner reads - that is "
          "check_python_advisories.py's job, a different check",
          "vulnerab" not in owner_facing.lower() and "insecure" not in owner_facing.lower())
    check("no subprocess, os.system or os.popen anywhere in this module - it only ever "
          "SHOWS a command, never runs one",
          "subprocess" not in src and "os.system" not in src and "os.popen" not in src)
    check("the report language says plainly this never installs anything",
          "never install" in TU.DETAIL.lower() or "it never installs" in TU.CARD.lower())


# ---------------------------------------------------------------------------
#   5. The one-time card
# ---------------------------------------------------------------------------


def t_not_approved_needs_a_card_only_a_yes_runs_it():
    fresh()
    calls = []

    def gate_yes(action, detail, prompt):
        calls.append((action, detail))
        return Verdict(True, "approved", "ask")

    ran = []
    fake_report = {"summary": "ok", "groups": []}

    def fake_run():
        ran.append(1)
        return fake_report

    code, out = TU.request_check({}, gate=gate_yes, tier_of=lambda a: "ask", spawn=run_now,
                                 run=fake_run)
    check("202 and waiting on the very first call", code == 202 and out["waiting"] is True)
    check("the gate was asked check_tool_updates, and the card names PyPI/crates.io/GitHub",
          calls and calls[0][0] == TU.ACTION
          and "pypi.org" in calls[0][1]["text"] and "crates.io" in calls[0][1]["text"])
    check("the card's detail says approving it leads off this PC",
          calls and calls[0][1].get("leaves_this_pc") is True)
    # The card promises "never ... anything about you" (security/privacy
    # audit, 2026-09-27): the User-Agent used to carry the owner's GitHub name.
    uas = (TU._PYPI_UA, TU._CRATES_UA, TU._GITHUB_UA)
    check("no User-Agent names the owner or their GitHub address",
          all("darknight" not in u.lower() and "github.com" not in u.lower() and "@" not in u
              for u in uas), uas)
    check("approving it both sets the flag AND runs the check, once",
          TU.approved() is True and ran == [1])
    check("the report from that run is now the last report",
          TU.last_report() == fake_report)
    check("last outcome is 'approved'", TU._P_STATE["last"]["outcome"] == "approved")


def t_denied_or_timed_out_leaves_it_unapproved():
    fresh()
    for outcome in ("denied", "timed_out"):
        fresh()
        ran = []
        code, out = TU.request_check(
            {}, gate=lambda a, d, p: Verdict(False, outcome), tier_of=lambda a: "ask",
            spawn=run_now, run=lambda: ran.append(1))
        check(f"a {outcome} card: 202 (the card was raised), but nothing was approved or run",
              code == 202 and TU.approved() is False and ran == [])
        check(f"last outcome after {outcome} is {outcome!r}",
              TU._P_STATE["last"]["outcome"] == outcome)


def t_already_approved_never_calls_the_gate_again():
    fresh()
    TU._set_approved()
    calls = []

    def gate_should_not_run(action, detail, prompt):
        calls.append(1)
        return Verdict(True, "approved", "ask")

    fake_report = {"summary": "already approved run", "groups": []}
    code, out = TU.request_check({}, gate=gate_should_not_run, tier_of=lambda a: "ask",
                                 spawn=run_now, run=lambda: fake_report)
    check("202, checking - never a card, and never blocks on the check itself",
          code == 202 and out["checking"] is True)
    check("the gate is never asked a second time", calls == [])
    check("the report is cached for the next GET, and 'checking' has gone back to false "
          "(spawn=run_now finishes the background run before returning here)",
          TU.last_report() == fake_report and TU.checking() is False)


def t_already_checking_is_a_no_op_not_a_second_run():
    fresh()
    TU._set_approved()
    with TU._C_LOCK:
        TU._C_STATE["running"] = True
    ran = []
    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved", "ask"),
                                 tier_of=lambda a: "ask", spawn=run_now,
                                 run=lambda: ran.append(1))
    check("a check already running is not started a second time",
          code == 202 and out["checking"] is True and ran == [])
    TU._reset_for_tests()


def t_needs_ask_tier():
    fresh()
    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved"),
                                 tier_of=lambda a: "auto", spawn=run_now, run=lambda: {})
    check("a tier other than 'ask' is refused (503) rather than treated as a standing yes",
          code == 503 and "ask" in out["error"])


def t_a_later_never_stops_an_already_approved_check():
    # Bug audit 2026-09-27, finding #4: the tier was read only before the
    # FIRST ever yes - once approved() was True, request_check never asked
    # jarvis-framework.toml again, so a later "never" (the exact thing
    # "What asks first" tells the owner switches this off) did nothing.
    fresh()
    ran = []
    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved", "ask"),
                                 tier_of=lambda a: "ask", spawn=run_now,
                                 run=lambda: ran.append(1) or {})
    check("first check, tier ask: approved and run", TU.approved() is True and ran == [1])
    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved"),
                                 tier_of=lambda a: "never", spawn=run_now,
                                 run=lambda: ran.append(2) or {})
    check("already approved, but the tier is now 'never': refused, not started",
          code == 503 and "never" in out["error"] and ran == [1], out)
    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved"),
                                 tier_of=lambda a: "notify", spawn=run_now,
                                 run=lambda: ran.append(3) or {})
    check("already approved, tier 'notify' (not 'ask'): also refused",
          code == 503 and ran == [1], out)


def t_a_run_that_fails_after_approval_still_counts_as_the_one_card():
    fresh()

    def boom():
        raise RuntimeError("network is down")

    code, out = TU.request_check({}, gate=lambda a, d, p: Verdict(True, "approved", "ask"),
                                 tier_of=lambda a: "ask", spawn=run_now, run=boom)
    check("approved even though the check itself failed this once",
          TU.approved() is True)
    check("the card's own outcome is 'approved' (a bug in the check itself is not the "
          "card's problem, and does not mean asking again)",
          TU._P_STATE["last"]["outcome"] == "approved")
    check("the 'checking' flag is cleared even though run() raised - a bug here can never "
          "wedge the button off forever",
          TU.checking() is False)


def t_approved_flag_survives_a_damaged_file():
    fresh()
    TU.settings_path().write_text("not json", encoding="utf-8")
    check("a damaged settings file reads as not approved (fails closed)",
          TU.approved() is False)
    fresh()


# ---------------------------------------------------------------------------
#   7. install() and the patch
# ---------------------------------------------------------------------------


def t_install_wraps_the_routes():
    fresh()
    hits = []

    class H:
        def __init__(self):
            self.path = ""
            self._body = b"{}"

        def do_GET(self):
            hits.append("get0")

        def do_POST(self):
            hits.append("post0")

        def _send(self, code, out):
            self.sent = (code, out)
            return self.sent

    line = TU.install(H, origin_ok=lambda self: True, token_ok=lambda self: True,
                      read_body=lambda self: self._body)
    check("install returns a banner line naming the feature", "tool updates" in line.lower())

    h = H()
    h.path = TU.PATH
    h.do_GET()
    check("GET /api/tool_updates is answered here", h.sent[0] == 200 and h.sent[1]["available"])

    h2 = H()
    h2.path = "/api/something/else"
    h2.do_GET()
    check("any other GET passes through to the original", hits == ["get0"])

    h3 = H()
    h3.path = TU.CHECK_ROUTE
    h3._body = json.dumps({}).encode()
    h3.do_POST()
    check("POST /api/tool_updates/check is answered here (some code came back)",
          h3.sent[0] in (200, 202, 503))

    h4 = H()
    h4.path = "/api/something/else"
    h4.do_POST()
    check("any other POST passes through to the original", "post0" in hits)


def _rehearse():
    order = _stack.order()
    if "tool-updates.patch" not in order:
        return False, "tool-updates.patch is not in apply-patches.ps1's list", None, None
    before_list = order[:order.index("tool-updates.patch")]
    patch = (HERE / "tool-updates.patch").read_text(encoding="utf-8")
    text, log = _stack.stand_in("jarvis_hud.py", before_list)
    if text is None:
        return False, "; ".join(log), None, None
    git = shutil.which("git")
    if not git:
        return False, "git is not installed", None, None
    d = Path(tempfile.mkdtemp(prefix="jarvis-tool-updates-patch-"))
    try:
        (d / "jarvis_hud.py").write_text(text, encoding="utf-8", newline="\n")
        (d / "p.patch").write_text(patch, encoding="utf-8", newline="\n")
        r = subprocess.run([git, "apply", "--include", "jarvis_hud.py", "p.patch"], cwd=d,
                           capture_output=True, text=True)
        if r.returncode != 0:
            return False, r.stderr, None, None
        after = (d / "jarvis_hud.py").read_text(encoding="utf-8")
        r = subprocess.run([git, "apply", "-R", "--include", "jarvis_hud.py", "p.patch"],
                           cwd=d, capture_output=True, text=True)
        if r.returncode != 0 or (d / "jarvis_hud.py").read_text(encoding="utf-8") != text:
            return False, f"does not reverse cleanly: {r.stderr}", None, None
    finally:
        shutil.rmtree(d, ignore_errors=True)
    return True, "", text, after


def t_the_patch():
    if not shutil.which("git"):
        return skip("git is not installed")
    ok, why, before, after = _rehearse()
    check("tool-updates.patch applies to what the earlier patches wrote, and reverses", ok, why)
    if not ok:
        return
    i = after.index("# tool-updates.patch")
    j = after.index("# Before the main socket", i)
    blk = after[i:j]
    check("the added block passes origin_ok/token_ok/read_body into jarvis_tool_updates.install",
          "import jarvis_tool_updates" in blk and "origin_ok=_origin_ok" in blk
          and "token_ok=_token_ok" in blk and "read_body=_read_body" in blk)
    try:
        compile("def f(self, bind, Handler):\n" + blk, "<patched block>", "exec")
        check("the patched block compiles", True)
    except SyntaxError as exc:
        check("the patched block compiles", False, str(exc))


if __name__ == "__main__":
    for fn in (t_python_lock_parsing, t_cargo_lock_parsing, t_cargo_lock_unreadable_without_toml,
               t_python_group_outdated_uptodate_and_unreachable, t_python_group_missing_lock_says_so,
               t_rust_group_dedupes_by_name_and_flags_outdated, t_rust_group_missing_lock_says_so,
               t_github_group_empty_by_default_and_rate_limit_warns, t_run_check_shape_and_summary,
               t_never_says_vulnerable_or_can_execute_anything,
               t_not_approved_needs_a_card_only_a_yes_runs_it,
               t_denied_or_timed_out_leaves_it_unapproved,
               t_already_approved_never_calls_the_gate_again,
               t_already_checking_is_a_no_op_not_a_second_run, t_needs_ask_tier,
               t_a_later_never_stops_an_already_approved_check,
               t_a_run_that_fails_after_approval_still_counts_as_the_one_card,
               t_approved_flag_survives_a_damaged_file, t_install_wraps_the_routes, t_the_patch):
        print(f"\n--- {fn.__name__} ---")
        try:
            fn()
        except Exception:
            FAILED.append(fn.__name__)
            traceback.print_exc()
    shutil.rmtree(TMP, ignore_errors=True)
    print(f"\n{len(PASSED)} passed, {len(SKIPPED)} skipped, {len(FAILED)} failed")
    if FAILED:
        print("failed: " + ", ".join(FAILED))
    sys.exit(1 if FAILED else 0)
