"""test_decks.py - review decks (the owner's decision of 2026-09-30;
jarvis_decks.py, decks.patch, docs/JARVIS-API.md section 102).

    python3 backend/test_decks.py          (needs `cryptography` and `fsrs==6.3.2`)

What it proves:
  - the schedule maths: fixed rating sequences reproduce the numbers py-fsrs
    6.3.2 itself gave (decks_fsrs_golden.json, generated by
    tools/gen_decks_golden.py), fuzzing off; the pin is exact and the optimizer
    (torch) is not asked for; Easy >= Good >= Hard, Again the shortest, the due
    date is always later than the review;
  - the store is sealed: no deck name, question, answer or passage appears in
    the file's bytes; no key, no `cryptography` or the wrong key means nothing
    is kept and the reason is said in words; a deleted card or deck leaves no
    trace in the file (secure_delete + VACUUM);
  - the one scheduler kind `review`: plain_repeat, silent, single, no card, no
    notification; created with the first deck and removed with the last; its
    note is the "N cards ready" line;
  - new cards a day (0, 5, 20), the 20-card run and "Do 10 more", the day
    rolling over by this PC's clock (two time zones), a card that cannot be
    rated until its back was shown, rated twice, in a paused deck, or after its
    deck was deleted;
  - Keep (finish with a `keep` body): the server's own prompt and passage are
    used, only answered questions, all or nothing, a quiz that stays open on
    any failure, duplicates and limits, a crisis phrase keeps nothing;
  - hide-lists shapes: the owner's words sit in a few named fields only; the
    counts and the line carry no words;
  - no streak / guilt wording anywhere in the module's strings;
  - the routes through install(), the patch on the stack, the shipped lists.
"""
from __future__ import annotations

import ast
import json
import os
import re
import shutil
import sqlite3
import sys
import tempfile
import time
import traceback
from importlib import metadata
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _where import require_shipped  # noqa: E402

require_shipped("jarvis_decks.py", "jarvis_quiz.py", "jarvis_schedule.py")

os.environ["TZ"] = "UTC"
if hasattr(time, "tzset"):
    time.tzset()

_BEFORE = set(sys.modules)
import jarvis_decks as D  # noqa: E402
_AFTER_IMPORT = set(sys.modules) - _BEFORE
import jarvis_quiz as Q  # noqa: E402
import jarvis_schedule as S  # noqa: E402

PASSED, FAILED = [], []
SKIPPED = []
_TMP = Path(tempfile.mkdtemp(prefix="jarvis-decks-"))
KEY = b"k" * 32
DAY = 24 * 3600.0


def check(name, cond, detail=""):
    (PASSED if cond else FAILED).append(name)
    print(f"{'ok   ' if cond else 'FAIL '} {name}" + (f"\n        {detail}" if detail and not cond else ""))


def skip(why):
    """A check this machine cannot run: printed as `skip`, counted on its own,
    never as a pass. (It used to be check("SKIP - ...", True) - a condition of
    the constant True, so it printed as a pass and was counted as one.)"""
    SKIPPED.append(why)
    print(f"skip  {why}")


class Clock:
    def __init__(self, t):
        self.t = float(t)

    def __call__(self):
        return self.t


T0 = S.wall_to_epoch(2026, 10, 1, 9, 0)


class KeyUnavailable(Exception):
    """Same name as jarvis_chat_log's, whose message is plain words."""


class World:
    def __init__(self, t=T0, key=KEY, **kw):
        self.clock = Clock(t)
        self.events, self.cards = [], []
        n = len(os.listdir(_TMP))
        self.sched = S.Scheduler(_TMP / f"sched-{n}.db", clock=self.clock, spawn=lambda fn: fn(),
                                 publish=lambda k, d: self.events.append((k, dict(d))),
                                 gate=lambda *a, **k2: self.cards.append(a) or ("approved", ""))
        S._SCHED = self.sched
        self.path = _TMP / f"study-{n}.db"
        self.d = D.Decks(self.path, (lambda: key) if not callable(key) else key,
                         clock=self.clock, scheduler=self.sched, fuzz=False, **kw)
        D._ONE = self.d


def mkcards(k, prefix="Q", start=0):
    return [{"n": i + 1, "front": f"{prefix}{i} question?", "back": f"{prefix}{i} answer",
             "passage": f"{prefix}{i} passage words", "kind": "recall", "level": "",
             "key_source": ""} for i in range(start, start + k)]


def study(d, cid, rating="good"):
    d.reveal(cid)
    return d.rate(cid, rating)


def raises(fn, code):
    try:
        fn()
    except D.DeckError as e:
        return e.code == code and e.message.endswith((".", "?")) or e.code == code
    except Exception:
        return False
    return False


# ---------------------------------------------------------------- the maths

def t_pin_and_golden():
    check("py-fsrs is exactly 6.3.2", metadata.version("fsrs") == "6.3.2", metadata.version("fsrs"))
    reqs = (HERE / "requirements.txt").read_text(encoding="utf-8")
    lines = [l for l in reqs.split("\n") if l.strip() and not l.lstrip().startswith("#")]
    fs = [l for l in lines if l.startswith("fsrs")]
    check("requirements.txt pins fsrs==6.3.2 exactly", len(fs) == 1 and fs[0].split("#")[0].strip() == "fsrs==6.3.2", fs)
    check("... without the optimizer extra, and no torch requirement at all",
          "[" not in fs[0].split("#")[0] and not [l for l in lines if re.match(r"torch\b", l)])
    lock = (HERE / "requirements.lock").read_text(encoding="utf-8")
    check("the hash-locked list holds fsrs 6.3.2 and no torch",
          "fsrs==6.3.2 \\" in lock and not re.search(r"^torch==", lock, re.M))
    g = json.loads((HERE / "decks_fsrs_golden.json").read_text(encoding="utf-8"))
    check("the golden file was made from 6.3.2", g["fsrs"] == "6.3.2" and len(g["sequences"]) >= 6)
    for name, rows in g["sequences"].items():
        st = D.new_state(g["start"])
        good = True
        detail = ""
        for row in rows:
            st = D.review(st, row["rating"], row["at"], fuzz=False)
            for k, v in row["after"].items():
                a = st[k]
                same = (a is None and v is None) or (a is not None and v is not None
                                                     and abs(float(a) - float(v)) <= 1e-9 * max(1.0, abs(float(v))))
                if not same:
                    good = False
                    detail = f"{name} {row['rating']} {k}: {a!r} != {v!r}"
        check(f"the wrapper reproduces py-fsrs's numbers: {name}", good, detail)


def t_scheduler_properties():
    ivs = {}
    for r in D.RATINGS:
        st = D.review(D.new_state(T0), r, T0, fuzz=False)
        ivs[r] = st["due"] - T0
        check(f"a first {r}: the due date is after the review", st["due"] > T0)
    check("first ratings: Easy >= Good >= Hard >= Again",
          ivs["easy"] >= ivs["good"] >= ivs["hard"] >= ivs["again"], ivs)
    check("Again on a new card comes back in a day (no same-day learning steps)", ivs["again"] == DAY)
    mature = D.new_state(T0)
    at = T0
    for _ in range(3):
        mature = D.review(mature, "good", at, fuzz=False)
        at = mature["due"]
    after = {r: D.review(mature, r, at, fuzz=False)["due"] - at for r in D.RATINGS}
    check("a settled card: Easy >= Good >= Hard >= Again, and Again is the shortest",
          after["easy"] >= after["good"] >= after["hard"] >= after["again"]
          and after["again"] < after["good"], after)
    check("Again on a settled card never asks for less than a day, and stays a review card",
          after["again"] >= DAY and D.review(mature, "again", at, fuzz=False)["state"] == 2)
    check("a rating that is not one of the four is refused",
          raises(lambda: D.review(D.new_state(T0), "meh", T0), "bad_rating"))
    fz = [D.review(mature, "good", at, fuzz=True)["due"] - at for _ in range(30)]
    check("fuzzing (real use) spreads long intervals a little and never below a day",
          len(set(fz)) > 1 and min(fz) >= DAY)


# ---------------------------------------------------------------- the store

def t_sealed_bytes():
    w = World()
    v = w.d.create_deck("Diabetes notes")
    cards = [{"n": 1, "front": "What does insulin regulate?", "back": "Blood glucose levels",
              "passage": "Insulin lowers blood glucose after meals.", "kind": "recall",
              "level": "", "key_source": ""},
             {"n": 2, "front": "Cuesta ___ mucho", "back": "Nunca", "passage": "Ella se cuesta ahorrar dinero.",
              "kind": "blank", "level": "B1", "key_source": "text"}]
    w.d.keep({"deck": v["id"]}, cards)
    raw = w.path.read_bytes()
    words = ["Diabetes", "insulin", "Insulin", "glucose", "Blood", "Cuesta", "Nunca", "ahorrar",
             "dinero", "notes", "question"]
    check("no deck name, question, answer or passage is in the file's bytes",
          not [x for x in words if x.encode() in raw], [x for x in words if x.encode() in raw])
    check("the plain columns (kind, level tag) are there, as designed",
          b"recall" in raw and b"B1" in raw)
    con = sqlite3.connect(str(w.path))
    row = con.execute("select name from decks").fetchone()
    blobs = [r[0] for r in con.execute("select front from cards")]
    con.close()
    check("the sealed name is bytes, nonce first (12) then tag-carrying ciphertext",
          isinstance(row[0], bytes) and len(row[0]) >= 12 + 16 + len("Diabetes notes"))
    check("two cards' fronts are different bytes (fresh nonces)", blobs[0] != blobs[1])
    fresh = D.Decks(w.path, lambda: KEY, clock=w.clock, fuzz=False)
    got = fresh.deck_cards(v["id"])
    check("a fresh object with the same key reads everything back",
          [c["front"] for c in got["cards"]] == ["What does insulin regulate?", "Cuesta ___ mucho"]
          and got["deck"]["name"] == "Diabetes notes" and got["cards"][1]["level"] == "B1")
    wrong = D.Decks(w.path, lambda: b"z" * 32, clock=w.clock, fuzz=False)
    check("a different key does not open it",
          raises(lambda: wrong.deck_cards(v["id"]), "deck_unavailable"))
    swapped = sqlite3.connect(str(w.path))
    a = swapped.execute("select id, front from cards order by rowid").fetchall()
    swapped.execute("update cards set front=? where id=?", (a[1][1], a[0][0]))
    swapped.commit()
    swapped.close()
    check("a sealed piece moved to another card does not open (the row's address is authenticated)",
          raises(lambda: D.Decks(w.path, lambda: KEY, clock=w.clock).deck_cards(v["id"]), "deck_unavailable"))


def t_no_key_fails_closed():
    w = World(key=lambda: (_ for _ in ()).throw(KeyUnavailable("Credential Manager could not be opened (5)")))
    before = w.path.exists()
    try:
        w.d.create_deck("Spanish")
        ok = False
        msg = ""
    except D.DeckError as e:
        ok, msg = e.code == "deck_unavailable", e.message
    check("no key: a deck cannot be made, and the reason is in plain words",
          ok and "Credential Manager could not be opened" in msg, msg)
    check("... and no file with words was written", w.path.exists() == before or w.path.stat().st_size < 4096
          and b"Spanish" not in w.path.read_bytes())
    check("... keeping a card fails the same way",
          raises(lambda: w.d.keep({"new_deck": "X"}, mkcards(1)), "deck_unavailable"))
    check("no decks yet and no key needed: the list is empty and available (nothing to open)",
          w.d.list_decks()["available"] is True and w.d.list_decks()["decks"] == [])
    w2 = World()
    w2.d.create_deck("Kept")
    w2.d.keep({"new_deck": "B"}, mkcards(2))
    bare = D.Decks(w2.path, lambda: (_ for _ in ()).throw(KeyUnavailable("the key is gone")),
                   clock=w2.clock, fuzz=False)
    ls = bare.list_decks()
    check("decks exist but the key is gone: unavailable, why said, no names, the counts still work",
          ls["available"] is False and "key is gone" in ls["why"] and ls["decks"] == []
          and ls["ready"] == 2 and ls["line"] == "2 cards ready", json.dumps(ls))
    check("... and the scheduler's line needs no key", bare.line() == "2 cards ready")
    check("... but reviewing needs the key", raises(lambda: bare.review_state(), "deck_unavailable"))
    nocrypto = D.Decks(_TMP / "nocrypto.db", lambda: KEY, clock=w2.clock, crypto=False, fuzz=False)
    try:
        nocrypto.create_deck("X")
        ok = False
    except D.DeckError as e:
        ok = e.code == "deck_unavailable" and "cryptography" in e.message
    check("no `cryptography` package: nothing is kept, and it says which package", ok)
    check("... and no file was made", not (_TMP / "nocrypto.db").exists())
    bad = D.Decks(_TMP / "badkey.db", lambda: b"short", clock=w2.clock, fuzz=False)
    check("a key that is not 32 bytes is refused", raises(lambda: bad.create_deck("X"), "deck_unavailable"))


def t_delete_leaves_no_trace():
    w = World()
    v = w.d.create_deck("Gone soon")
    w.d.keep({"deck": v["id"]}, mkcards(3))
    con = sqlite3.connect(str(w.path))
    blobs = [r[0] for r in con.execute("select front from cards")] + \
            [r[0] for r in con.execute("select passage from cards")] + \
            [r[0] for r in con.execute("select name from decks")]
    con.close()
    raw = w.path.read_bytes()
    check("before: the sealed pieces are in the file", all(b in raw for b in blobs))
    cid = w.d.deck_cards(v["id"])["cards"][0]["id"]
    one = sqlite3.connect(str(w.path)).execute("select front, back, passage from cards where id=?", (cid,)).fetchone()
    w.d.card_act(v["id"], cid, "delete")
    raw = w.path.read_bytes()
    check("a deleted card's sealed front, back and passage are gone from the file",
          not [b for b in one if bytes(b) in raw])
    w.d.deck_act(v["id"], "delete")
    raw = w.path.read_bytes()
    check("a deleted deck leaves none of its sealed bytes", not [b for b in blobs if bytes(b) in raw])
    check("the deck list is empty again", w.d.list_decks()["decks"] == [])


# ---------------------------------------------------------------- the kind

def t_the_scheduler_kind():
    k = S.KINDS.get("review")
    check("`review` is a registered kind: plain_repeat, silent, single, not notify, listed",
          k is not None and k.plain_repeat and k.silent and k.single and not k.notify
          and k.owner_listed and not k.has_text)
    check("jarvis_schedule loads this module before its loop (KIND_MODULES)", "jarvis_decks" in S.KIND_MODULES)
    w = World()
    check("no deck, no job, no line", w.sched.jobs_of("review") == [] and w.d.line() == ""
          and w.sched.listed() == [])
    a = w.d.create_deck("First")
    jobs = w.sched.jobs_of("review")
    check("the first deck makes exactly one job", len(jobs) == 1, jobs)
    j = w.sched.job(jobs[0])
    check("... active at once, no approval card raised", j["state"] == "active" and w.cards == [])
    check("... going off rings nothing (notify false) and it has no words of its own",
          j.get("notify") is False and j["text"] == "" and j["kind"] == "review", json.dumps(j))
    check("... once a day at 04:00", j["repeat"].endswith("04:00"), j["repeat"])
    w.d.create_deck("Second")
    check("a second deck keeps the one job", w.sched.jobs_of("review") == jobs)
    w.d.keep({"deck": a["id"]}, mkcards(3))
    listed = [x for x in w.sched.listed() if x["kind"] == "review"]
    check("Coming up shows it once, with the 'N cards ready' note",
          len(listed) == 1 and listed[0].get("note") == "3 cards ready", json.dumps(listed))
    w.d.deck_act(a["id"], "pause")
    check("pausing every deck with cards reads 'All decks paused'... only when all are paused",
          w.d.line() == "Nothing ready today")
    b = [x for x in w.d.list_decks()["decks"] if x["name"] == "Second"][0]
    w.d.deck_act(b["id"], "pause")
    check("all decks paused says so", w.d.line() == "All decks paused")
    w.d.deck_act(a["id"], "resume")
    w.d.deck_act(b["id"], "resume")
    w.sched.act(jobs[0], "delete")
    check("the job removed by hand is put back by the next look", w.d.ensure_job() == "added"
          and len(w.sched.jobs_of("review")) == 1)
    w.d.deck_act(a["id"], "delete")
    check("deleting one of two decks keeps the job", len(w.sched.jobs_of("review")) == 1)
    w.d.deck_act(b["id"], "delete")
    check("deleting the last deck removes the job", w.sched.jobs_of("review") == [] and w.d.line() == "")
    check("no approval card was raised at any point", w.cards == [])
    ev = json.dumps(w.events)
    check("no event carried a deck's words", "First" not in ev and "Second" not in ev)
    after = w.sched.add_repeat("review", dict(D.JOB_RULE), source="decks")
    try:
        w.sched.add_repeat("review", dict(D.JOB_RULE), source="decks")
        second = True
    except Exception:
        second = False
    check("the scheduler itself refuses a second review job (single)", after and not second)


# ---------------------------------------------------------------- caps and runs

def t_new_cards_a_day():
    w = World()
    v = w.d.create_deck("Many")
    w.d.keep({"deck": v["id"]}, mkcards(8))
    ls = w.d.list_decks()
    check("default 5 new cards a day: 5 ready of 8", ls["new_per_day"] == 5 and ls["ready"] == 5
          and ls["new_left"] == 5 and ls["decks"][0]["cards"] == 8 and ls["line"] == "5 cards ready")
    for _ in range(5):
        c = w.d.review_state()["card"]
        study(w.d, c["id"])
    ls = w.d.list_decks()
    check("after five are learned today: nothing more today, and the next day is named",
          ls["ready"] == 0 and ls["line"] == "Nothing ready today" and ls["new_left"] == 0
          and ls["next_ready_day"] == "2026-10-02", json.dumps(ls))
    w.clock.t += DAY
    ls = w.d.list_decks()
    check("tomorrow: the 3 left plus whichever of yesterday's five came back (the 1-day ones)",
          ls["ready"] >= 3 and ls["new_left"] == 5, json.dumps(ls))
    w2 = World()
    v2 = w2.d.create_deck("Zero")
    w2.d.keep({"deck": v2["id"]}, mkcards(4))
    check("new cards a day 0: no new card is ready", w2.d.set_new_per_day(0)["new_per_day"] == 0
          and w2.d.list_decks()["ready"] == 0 and w2.d.review_state()["state"] == "empty")
    w2.d.set_new_per_day(20)
    check("20: all 4 are ready", w2.d.list_decks()["ready"] == 4)
    for bad in (-1, 21, True, "5", 5.5, None):
        check(f"new cards a day {bad!r} -> bad_setting", raises(lambda b=bad: w2.d.set_new_per_day(b), "bad_setting"))
    check("the setting survives a new object on the same file",
          D.Decks(w2.path, lambda: KEY, clock=w2.clock).list_decks()["new_per_day"] == 20)
    w3 = World()
    v3 = w3.d.create_deck("Cross")
    w3.d.keep({"deck": v3["id"]}, mkcards(3))
    v4 = w3.d.create_deck("Other")
    w3.d.keep({"deck": v4["id"]}, mkcards(3, "R"))
    w3.d.set_new_per_day(4)
    check("the day's cap is shared by every deck", w3.d.list_decks()["ready"] == 4)
    only = w3.d.review_state(v4["id"])
    check("a deck's own review shows only its cards, under the shared cap", only["card"]["deck"] == v4["id"]
          and only["ready"] == 3 and only["new_left"] == 4)


def t_runs_of_twenty():
    w = World()
    v = w.d.create_deck("Big")
    w.d.set_new_per_day(20)
    w.d.keep({"deck": v["id"]}, mkcards(25))
    check("25 cards, a cap of 20 new a day: 20 ready", w.d.list_decks()["ready"] == 20)
    w.d.set_new_per_day(20)
    for i in range(20):
        st = w.d.review_state()
        if st["card"] is None:
            break
        study(w.d, st["card"]["id"])
    st = w.d.review_state()
    check("after 20 the run says it is enough for now, with no card", st["state"] == "empty" or st["state"] == "enough")
    w2 = World()
    v2 = w2.d.create_deck("Big2")
    w2.d.keep({"deck": v2["id"]}, mkcards(30))
    w2.d.set_new_per_day(20)
    # make 30 due reviews: learn 20 today, come back in 3 days when all are ready plus 10 new
    for i in range(20):
        study(w2.d, w2.d.review_state()["card"]["id"], "good")
    w2.clock.t += 5 * DAY
    st = w2.d.review_state()
    check("5 days later: 30 ready (20 reviews + 10 new), a run shows the first", st["ready"] == 30
          and st["state"] == "card" and st["run"] == {"done": 0, "limit": 20}, json.dumps(st))
    for i in range(20):
        r = study(w2.d, w2.d.review_state()["card"]["id"], "good")
    check("after 20 rated the run is enough for now: no card, 10 still ready, words come from code",
          r["state"] == "enough" and r["next"] is None and r["ready"] == 10 and r["line"] == "10 cards ready"
          and r["run"] == {"done": 20, "limit": 20}, json.dumps(r))
    st = w2.d.review_state()
    check("asking again does not start a new run", st["state"] == "enough" and st["card"] is None)
    more = w2.d.more()
    check("'Do 10 more' raises the limit by 10 and shows the next card",
          more["state"] == "card" and more["run"]["limit"] == 30 and more["card"] is not None)
    for i in range(10):
        r = study(w2.d, w2.d.review_state()["card"]["id"], "easy")
    check("... and then nothing is left", r["ready"] == 0 and r["state"] == "empty" and r["next"] is None)
    w2.clock.t += RUN_IDLE_PLUS()
    check("a run that sat idle over 30 minutes starts fresh", w2.d.review_state()["run"]["done"] == 0)


def RUN_IDLE_PLUS():
    return D.RUN_IDLE + 60.0


def t_the_run_limit_is_the_settings_files_number():
    """How many cards one run shows is [decks] run_limit in
    jarvis-framework.toml - 20 is the default, not the only number - and a
    value that is missing, unreadable or nonsense falls back to 20 rather than
    crashing or asking for no cards at all."""
    real = D.fw

    class Settings:
        """A stand-in jarvis_framework holding just the [decks] table."""

        CONFIG_DIR = _TMP

        def __init__(self, decks):
            self.decks = decks

        def load_framework(self):
            return {"decks": self.decks}

    def run_with(decks, cards=25):
        D.fw = Settings(decks)
        w = World()
        v = w.d.create_deck("Run")["id"]
        w.d.set_new_per_day(20)
        w.d.keep({"deck": v}, mkcards(cards))
        return w

    try:
        w = run_with({})
        check("no [decks] run_limit at all: a run shows the default 20",
              w.d.review_state()["run"] == {"done": 0, "limit": 20},
              json.dumps(w.d.review_state()))
        w2 = run_with({"run_limit": 7}, cards=10)
        got = w2.d.review_state()
        check("[decks] run_limit = 7 is what the run shows", got["run"] == {"done": 0, "limit": 7}
              and got["ready"] == 10, json.dumps(got))
        for _ in range(7):
            study(w2.d, w2.d.review_state()["card"]["id"])
        got = w2.d.review_state()
        check("... seven rated: enough for now, the rest still ready, and 'Do 10 more' adds 10",
              got["state"] == "enough" and got["card"] is None and got["ready"] == 3
              and got["run"] == {"done": 7, "limit": 7} and w2.d.more()["run"]["limit"] == 17,
              json.dumps(got))
        for bad in ("lots", "", None, 0, -1, 10 ** 6):
            w3 = run_with({"run_limit": bad}, cards=1)
            check(f"[decks] run_limit = {bad!r} -> the default 20, never no cards at all",
                  w3.d.review_state()["run"] == {"done": 0, "limit": 20},
                  json.dumps(w3.d.review_state()))
    finally:
        D.fw = real


def t_ratings_and_rules():
    w = World()
    v = w.d.create_deck("Rules")
    w.d.keep({"deck": v["id"]}, mkcards(3))
    c1 = w.d.review_state()["card"]["id"]
    check("a rating before the answer was shown -> not_revealed",
          raises(lambda: w.d.rate(c1, "good"), "not_revealed"))
    check("a rating that is not one of the four -> bad_rating",
          raises(lambda: w.d.rate(c1, "great"), "bad_rating") and raises(lambda: w.d.rate(c1, None), "bad_rating"))
    check("an unknown card -> card_not_found on reveal and on rate",
          raises(lambda: w.d.reveal("nope"), "card_not_found") and raises(lambda: w.d.rate("nope", "good"), "card_not_found")
          and raises(lambda: w.d.reveal(None), "card_not_found"))
    r = w.d.reveal(c1)
    check("reveal gives the back and the passage, and no label for a key the owner wrote",
          r["back"] == {"answer": "Q0 answer", "passage": "Q0 passage words"} and r["key_label"] is None)
    out = w.d.rate(c1, "good")
    check("rating answers ok, ready, the next card and the day it comes back (computed by code)",
          out["ok"] and out["ready"] == 2 and out["next"]["id"] != c1 and out["comes_back"] == "2026-10-03"
          and out["line"] == "2 cards ready", json.dumps(out))
    check("the same card cannot be rated twice (the reveal is used up)",
          raises(lambda: w.d.rate(c1, "good"), "not_revealed"))
    check("a card just rated is not up for review again: reveal -> card_not_found",
          raises(lambda: w.d.reveal(c1), "card_not_found"))
    c2 = out["next"]["id"]
    w.d.reveal(c2)
    w.d.deck_act(v["id"], "pause")
    check("a paused deck's card cannot be rated (deck_paused)", raises(lambda: w.d.rate(c2, "good"), "deck_paused"))
    check("... or revealed", raises(lambda: w.d.reveal(c2), "deck_paused"))
    st = w.d.review_state()
    check("... and the review says paused", st["state"] == "paused" and st["card"] is None and st["line"] == "All decks paused")
    check("a deck's own review while paused says so", w.d.review_state(v["id"])["line"] == "This deck is paused")
    w.d.deck_act(v["id"], "resume")
    w.d.reveal(c2)
    w.d.deck_act(v["id"], "delete")
    check("a deck deleted mid-review: the card is gone (card_not_found), nothing crashes",
          raises(lambda: w.d.rate(c2, "good"), "card_not_found"))
    check("... and the review says there are no decks", w.d.review_state()["state"] == "no_decks")
    check("reviewing an unknown deck -> deck_not_found", raises(lambda: w.d.review_state("dnope"), "deck_not_found"))
    w2 = World()
    v2 = w2.d.create_deck("Lapse")
    w2.d.keep({"deck": v2["id"]}, mkcards(1))
    cid = w2.d.review_state()["card"]["id"]
    study(w2.d, cid, "good")
    w2.clock.t += 3 * DAY
    o = study(w2.d, cid, "again")
    con = sqlite3.connect(str(w2.path))
    reps, lapses, state = con.execute("select reps, lapses, state from cards").fetchone()
    con.close()
    check("Again on a settled card counts a lapse, stays a review card and comes back in a day or so",
          reps == 2 and lapses == 1 and state == 2 and o["comes_back"] in ("2026-10-05", "2026-10-06"), (reps, lapses, state, o))
    w2.clock.t += 20 * DAY
    check("ready cards wait as long as needed; a month later the card is simply ready",
          w2.d.review_state()["ready"] == 1 and w2.d.list_decks()["line"] == "1 card ready")


def t_day_rolls_over_by_this_pcs_clock():
    # Windows has no time.tzset(), so TZ cannot be changed and another timezone
    # cannot be simulated here at all. CI (Linux) proves this test; on the owner's
    # PC it is reported as not proven rather than as a failure (2026-10-03).
    if not hasattr(time, "tzset"):
        skip("the day rolling over by this PC's clock: this system has no time.tzset, so "
             "another timezone cannot be simulated; CI proves this one on Linux")
        return
    keep_tz = os.environ.get("TZ")
    try:
        os.environ["TZ"] = "Pacific/Auckland"
        time.tzset()
        # 2026-10-01 23:30 UTC is 2026-10-02 12:30 in Auckland (NZDT, +13)
        late = S.wall_to_epoch(2026, 10, 2, 12, 30)
        w = World(t=late)
        v = w.d.create_deck("Kiwi")
        w.d.set_new_per_day(1)
        w.d.keep({"deck": v["id"]}, mkcards(3))
        study(w.d, w.d.review_state()["card"]["id"])
        check("one new card a day: the day's new card is used up", w.d.list_decks()["ready"] == 0)
        w.clock.t = S.wall_to_epoch(2026, 10, 2, 23, 59)
        check("still the same local day at 23:59", w.d.list_decks()["ready"] == 0)
        w.clock.t = S.wall_to_epoch(2026, 10, 3, 0, 1)
        ls = w.d.list_decks()
        check("just after local midnight it is a new day: the new-card allowance is back", ls["new_left"] == 1
              and ls["ready"] >= 1, json.dumps(ls))
        os.environ["TZ"] = "America/Los_Angeles"
        time.tzset()
        t = S.wall_to_epoch(2026, 10, 2, 23, 0)
        w2 = World(t=t)
        v2 = w2.d.create_deck("West")
        w2.d.set_new_per_day(1)
        w2.d.keep({"deck": v2["id"]}, mkcards(2))
        study(w2.d, w2.d.review_state()["card"]["id"], "easy")
        w2.clock.t = S.wall_to_epoch(2026, 10, 3, 7, 0)
        check("a card learned at 23:00 local is not new again at 07:00 the next local day, "
              "but the allowance is", w2.d.list_decks()["new_left"] == 1)
        w2.clock.t = S.wall_to_epoch(2026, 10, 12, 9, 0)
        check("its easy interval (about a week) has passed by the 12th: it is ready again",
              w2.d.review_state()["ready"] >= 1)
    finally:
        if keep_tz is None:
            os.environ["TZ"] = "UTC"
        else:
            os.environ["TZ"] = keep_tz
        time.tzset()


# ---------------------------------------------------------------- managing

def t_manage_decks_and_cards():
    w = World()
    d = w.d
    check("a deck needs a name of 1 to 60 characters",
          raises(lambda: d.create_deck(""), "bad_deck_name") and raises(lambda: d.create_deck("   "), "bad_deck_name")
          and raises(lambda: d.create_deck("x" * 61), "bad_deck_name") and raises(lambda: d.create_deck(None), "bad_deck_name")
          and raises(lambda: d.create_deck(5), "bad_deck_name"))
    v = d.create_deck("  Spanish   verbs ")
    check("the name is tidied and kept", v["name"] == "Spanish verbs" and v["kind"] == "empty" and v["cards"] == 0
          and v["ready"] == 0 and v["paused"] is False)
    check("rename works and is checked", d.deck_act(v["id"], "rename", "Verbos")["deck"]["name"] == "Verbos"
          and raises(lambda: d.deck_act(v["id"], "rename", ""), "bad_deck_name"))
    check("pause and resume", d.deck_act(v["id"], "pause")["deck"]["paused"] is True
          and d.deck_act(v["id"], "resume")["deck"]["paused"] is False)
    check("an action that does not exist -> bad_action", raises(lambda: d.deck_act(v["id"], "explode"), "bad_action"))
    check("an unknown deck -> deck_not_found", raises(lambda: d.deck_act("dnope", "pause"), "deck_not_found")
          and raises(lambda: d.deck_cards("dnope"), "deck_not_found"))
    d.keep({"deck": v["id"]}, [dict(mkcards(1)[0], level="A2", kind="blank", key_source="model")] + mkcards(1, "P")[:1])
    cards = d.deck_cards(v["id"])["cards"]
    check("the card list has the owner's words in front, back and passage, and the model-key label",
          cards[0]["key_label"] == D.KEY_LABEL and cards[0]["key_source"] == "model" and cards[0]["level"] == "A2"
          and cards[1]["key_label"] is None and cards[0]["new"] is True and cards[0]["due_day"] is None)
    check("the deck is 'mixed' when it holds Spanish and other cards", d.list_decks()["decks"][0]["kind"] == "mixed")
    cid = cards[0]["id"]
    e = d.card_act(v["id"], cid, "edit", front="New front?", back="New back")
    check("editing a card's front and back", e["card"]["front"] == "New front?" and e["card"]["back"] == "New back"
          and e["card"]["passage"] == cards[0]["passage"])
    check("... an empty front, an over-long front or back, or nothing to change -> bad_card",
          raises(lambda: d.card_act(v["id"], cid, "edit", front=""), "bad_card")
          and raises(lambda: d.card_act(v["id"], cid, "edit", front="x" * 501), "bad_card")
          and raises(lambda: d.card_act(v["id"], cid, "edit", back="x" * 2001), "bad_card")
          and raises(lambda: d.card_act(v["id"], cid, "edit"), "bad_card")
          and d.card_act(v["id"], cid, "edit", back="")["card"]["back"] == "")
    check("a card is only reachable through its own deck",
          raises(lambda: d.card_act("dnope", cid, "delete"), "card_not_found"))
    check("a card action that does not exist -> bad_action", raises(lambda: d.card_act(v["id"], cid, "burn"), "bad_action"))
    d.card_act(v["id"], cid, "delete")
    check("delete card: gone, the deck stays", len(d.deck_cards(v["id"])["cards"]) == 1
          and raises(lambda: d.card_act(v["id"], cid, "delete"), "card_not_found"))
    for i in range(19):
        d.create_deck(f"D{i}")
    check("20 decks is the most: too_many_decks", raises(lambda: d.create_deck("21st"), "too_many_decks"))
    check("... and keeping into a new deck says the same", raises(lambda: d.keep({"new_deck": "22nd"}, mkcards(1)), "too_many_decks"))
    check("the list carries its limits for the apps", d.list_decks()["limits"] == {
        "decks": 20, "cards": 1000, "name": 60, "front": 500, "back": 2000, "new_per_day": 20})


def t_keep_edges_in_the_store():
    w = World()
    d = w.d
    v = d.create_deck("Edges")
    check("nothing to keep -> nothing_to_keep", raises(lambda: d.keep({"deck": v["id"]}, []), "nothing_to_keep"))
    check("no deck named and none new -> deck_not_found", raises(lambda: d.keep({}, mkcards(1)), "deck_not_found"))
    check("an unknown deck -> deck_not_found", raises(lambda: d.keep({"deck": "dnope"}, mkcards(1)), "deck_not_found"))
    check("a bad new-deck name -> bad_deck_name (and no deck was made)",
          raises(lambda: d.keep({"new_deck": " "}, mkcards(1)), "bad_deck_name") and len(d.list_decks()["decks"]) == 1)
    d.keep({"deck": v["id"]}, mkcards(2))
    try:
        d.keep({"deck": v["id"]}, mkcards(1, "N") + mkcards(1))
        dup = False
    except D.DeckError as e:
        dup = e.code == "duplicate_card"
    check("a card already in the deck -> duplicate_card, and the new one beside it was not kept either",
          dup and len(d.deck_cards(v["id"])["cards"]) == 2)
    try:
        d.keep({"deck": v["id"]}, mkcards(1, "M") + mkcards(1, "M"))
        dup = False
    except D.DeckError as e:
        dup = e.code == "duplicate_card"
    check("two identical cards in one request -> duplicate_card, none kept", dup and len(d.deck_cards(v["id"])["cards"]) == 2)
    old = D.MAX_CARDS
    D.MAX_CARDS = 4
    try:
        check("the 1,000-card cap is over every deck together (deck_full), all or nothing",
              raises(lambda: d.keep({"deck": v["id"]}, mkcards(3, "F")), "deck_full")
              and len(d.deck_cards(v["id"])["cards"]) == 2
              and d.keep({"new_deck": "Fits"}, mkcards(2, "G")) == 2)
    finally:
        D.MAX_CARDS = old
    check("a new deck made in a failed keep is not left behind",
          raises(lambda: d.keep({"new_deck": "Ghost"}, mkcards(1) + [{"front": ""}]), "bad_card")
          and "Ghost" not in [x["name"] for x in d.list_decks()["decks"]])
    d.keep({"deck": v["id"]}, [{"n": 9, "front": "f" * 900, "back": "b" * 3000, "passage": "p" * 2000, "kind": "recall"}])
    last = d.deck_cards(v["id"])["cards"][-1]
    check("lengths are cut to the limits (500, 2000, 800)", len(last["front"]) == 500 and len(last["back"]) == 2000
          and len(last["passage"]) == 800)


# ---------------------------------------------------------------- keep through the quiz

class Model:
    def __init__(self):
        self.calls = []
        self.mark = ("got_it", "Yes, that matches the passage.")

    def __call__(self, system, user, schema, num_predict):
        self.calls.append(user)
        if "questions" in schema["properties"]:
            return json.dumps({"questions": [
                {"kind": "recall", "prompt": "What absorbs sunlight?", "passage": P1},
                {"kind": "explain", "prompt": "Why does the plant release oxygen?", "passage": P2},
                {"kind": "apply", "prompt": "Would a plant in the dark make glucose?", "passage": P2}]})
        return json.dumps({"level": self.mark[0], "comment": self.mark[1]})


SENT = ("Photosynthesis happens mainly in the leaves of a plant. Chlorophyll, a green "
        "pigment in the chloroplasts, absorbs sunlight. ")
SENT2 = ("The plant turns carbon dioxide and water into glucose and releases oxygen. "
         "Roots take water from the soil and stems carry it up. ")
TEXT = (SENT + SENT2) * 2
P1 = "Chlorophyll, a green pigment in the chloroplasts, absorbs sunlight."
P2 = "The plant turns carbon dioxide and water into glucose and releases oxygen."


def quiz_world(**kw):
    Q._reset_for_tests()
    m = Model()
    w = World(**kw)
    Q.configure(call=m)
    Q.configure(keep=lambda spec, cards: D.get().keep(spec, cards))
    return m, w


def new_quiz(answers=(1, 2)):
    qid = Q.handle_post("/api/quiz", {"text": TEXT, "count": 3})[1]["quiz"]["id"]
    for n in answers:
        Q.handle_post(f"/api/quiz/{qid}/answer", {"n": n, "answer": f"my answer {n}"})
    return qid


def open_quiz(qid):
    return Q.handle_get(f"/api/quiz/{qid}")[0] == 200


def t_keep_through_the_quiz():
    m, w = quiz_world()
    m.mark = ("partly", "Half.")
    qid = new_quiz()
    body = {"keep": {"new_deck": "Plants", "cards": [
        {"n": 1, "answer": "chlorophyll", "passage": "HACKED PASSAGE", "front": "HACKED FRONT"},
        {"n": 2, "answer": ""}]}}
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", body)
    check("finish with keep: 200, the ordinary summary, and kept: 2", code == 200 and out["ok"] and out["kept"] == 2
          and set(out) == {"ok", "summary", "kept"} and set(out["summary"]) == {"counts", "again"}, json.dumps(out))
    check("the quiz is gone after a successful finish", not open_quiz(qid))
    deck = w.d.list_decks()["decks"]
    check("the new deck exists with the two cards", len(deck) == 1 and deck[0]["name"] == "Plants" and deck[0]["cards"] == 2)
    cards = w.d.deck_cards(deck[0]["id"])["cards"]
    check("the front and passage are the server's own, whatever the app sent",
          cards[0]["front"] == "What absorbs sunlight?" and cards[0]["passage"] == P1
          and "HACKED" not in json.dumps(cards))
    check("the back is the owner's own words; an empty one stays empty (the passage shows on its own)",
          cards[0]["back"] == "chlorophyll" and cards[1]["back"] == "" and cards[1]["passage"] == P2)
    check("kind is kept, and a text quiz's cards carry no level or key source",
          cards[0]["kind"] == "recall" and cards[1]["kind"] == "explain" and cards[0]["level"] is None
          and cards[0]["key_source"] is None)
    check("keeping made no model call beyond the quiz's own", len(m.calls) == 1 + 2)
    check("the review job now exists", len(w.sched.jobs_of("review")) == 1)

    # an empty body / keep null works exactly as before
    qid = new_quiz()
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {})
    check("finish with no body: no `kept` key, exactly as before", code == 200 and set(out) == {"ok", "summary"})
    qid = new_quiz()
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": None})
    check("keep: null is the same as no keep", code == 200 and "kept" not in out)

    # only answered questions
    before = w.d.list_decks()
    qid = new_quiz(answers=(1,))
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [
        {"n": 1, "answer": "a"}, {"n": 2, "answer": "b"}]}})
    check("an unanswered question cannot be kept (bad_question), and the quiz is still open",
          code == 400 and out["error"] == "bad_question" and open_quiz(qid))
    check("... nothing was kept", w.d.list_decks()["decks"][0]["cards"] == 2)
    for bad in ({"n": 0}, {"n": 4}, {"n": True}, {"n": "1"}, {}, "x", None):
        code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [bad]}})
        check(f"a bad card entry {bad!r} -> bad_question, quiz open", code == 400 and out["error"] == "bad_question" and open_quiz(qid))
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [
        {"n": 1, "answer": "a"}, {"n": 1, "answer": "b"}]}})
    check("the same question twice -> bad_question", code == 400 and out["error"] == "bad_question")
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [
        {"n": 1, "answer": "x" * 2001}]}})
    check("an over-long back -> answer_too_long", code == 400 and out["error"] == "answer_too_long" and open_quiz(qid))
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [
        {"n": 1, "answer": 5}]}})
    check("a back that is not text -> a plain error", code == 400 and open_quiz(qid))
    for bad in ({}, {"cards": []}, {"deck": "d"}, [], "yes", {"cards": "no"}):
        code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": bad})
        check(f"keep {bad!r} -> nothing_to_keep, quiz open", code == 400 and out["error"] == "nothing_to_keep" and open_quiz(qid))
    # all or nothing: second card fails after a new deck
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "Ghost", "cards": [
        {"n": 1, "answer": "ok"}, {"n": 3, "answer": "unanswered"}]}})
    check("all or nothing: a bad second card keeps nothing and makes no deck",
          code == 400 and open_quiz(qid) and "Ghost" not in [x["name"] for x in w.d.list_decks()["decks"]])
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": "dnope", "cards": [{"n": 1, "answer": "ok"}]}})
    check("an unknown deck -> deck_not_found, 404, quiz open", code == 404 and out["error"] == "deck_not_found" and open_quiz(qid))
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "", "cards": [{"n": 1, "answer": "ok"}]}})
    check("a bad deck name -> bad_deck_name, 400", code == 400 and out["error"] == "bad_deck_name" and open_quiz(qid))
    # duplicate: q1 was kept above with the same server prompt/passage
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": before["decks"][0]["id"], "cards": [
        {"n": 1, "answer": "again"}]}})
    check("the same question again -> duplicate_card, 409, plain words, quiz open",
          code == 409 and out["error"] == "duplicate_card" and "Question 1" in out["message"] and open_quiz(qid))
    check("every failure answer has ok false, an error code and a message",
          out["ok"] is False and isinstance(out["message"], str) and out["message"])


def t_keep_failures_leave_the_quiz_open():
    m, w = quiz_world()
    qid = new_quiz()
    Q.configure(keep=None)
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "X", "cards": [{"n": 1, "answer": "a"}]}})
    check("no deck store configured -> deck_unavailable 503, quiz open",
          code == 503 and out["error"] == "deck_unavailable" and open_quiz(qid))

    def boom(spec, cards):
        raise RuntimeError("disk on fire")
    Q.configure(keep=boom)
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "X", "cards": [{"n": 1, "answer": "a"}]}})
    check("an unexpected failure in the store -> deck_unavailable, quiz open, the error text is not leaked",
          code == 503 and out["error"] == "deck_unavailable" and "fire" not in json.dumps(out) and open_quiz(qid))
    m2, w2 = quiz_world(key=lambda: (_ for _ in ()).throw(KeyUnavailable("Credential Manager is locked")))
    qid = new_quiz()
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "X", "cards": [{"n": 1, "answer": "a"}]}})
    check("the real store with no key: 503 deck_unavailable, the reason in words, the quiz still open",
          code == 503 and out["error"] == "deck_unavailable" and "Credential Manager is locked" in out["message"]
          and open_quiz(qid))
    check("... and afterwards the quiz can still be finished without keeping",
          Q.handle_post(f"/api/quiz/{qid}/finish", {})[0] == 200)
    check("... and nothing was written for it", not w2.path.exists() or b"absorbs" not in w2.path.read_bytes())


def t_crisis_words_are_never_kept():
    m, w = quiz_world()
    qid = new_quiz()
    calls = len(m.calls)
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "Sad", "cards": [
        {"n": 1, "answer": "I want to kill myself"}]}})
    import jarvis_wellbeing as W
    check("a crisis phrase in a card's back: the chat's help wording, crisis true, quiz open, nothing kept",
          code == 200 and out.get("crisis") is True and out["message"] == W.reply() and open_quiz(qid)
          and w.d.list_decks()["decks"] == [] and "mark" not in out)
    check("... no model call was made and the words are nowhere in the reply", len(m.calls) == calls
          and "kill myself" not in json.dumps(out))
    check("... and the file has no such words either", not w.path.exists() or b"kill myself" not in w.path.read_bytes())


def t_spanish_cards_keep_their_tags():
    Q._reset_for_tests()
    w = World()
    seen = []

    def spanish_model(system, user, schema, num_predict):
        seen.append(user)
        if "items" in schema["properties"]:
            return json.dumps({"items": [
                {"kind": "blank", "passage": "Ella está en casa con su hermano.", "word": "está"},
                {"kind": "translate", "prompt": "She is at home.", "passage": "Ella está en casa."}]})
        return json.dumps({"level": "got_it", "comment": "Bien."})
    Q.configure(call=spanish_model)
    Q.configure(keep=lambda spec, cards: D.get().keep(spec, cards))
    qid = Q.handle_post("/api/quiz", {"mode": "spanish", "level": "B1", "exercise": "mixed", "count": 2})[1]["quiz"]["id"]
    Q.handle_post(f"/api/quiz/{qid}/answer", {"n": 1, "answer": "está"})
    Q.handle_post(f"/api/quiz/{qid}/answer", {"n": 2, "answer": "Ella está en casa"})
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": "Español", "cards": [
        {"n": 1, "answer": ""}, {"n": 2, "answer": "Ella está en casa"}]}})
    check("a Spanish quiz's questions can be kept", code == 200 and out["kept"] == 2, json.dumps(out))
    deck = w.d.list_decks()["decks"][0]
    cards = w.d.deck_cards(deck["id"])["cards"]
    check("the deck name may hold accents, and the deck is a Spanish deck", deck["name"] == "Español" and deck["kind"] == "spanish")
    check("both cards carry the level tag and 'model' as the key source, so the label shows on review",
          [c["level"] for c in cards] == ["B1", "B1"] and [c["key_source"] for c in cards] == ["model", "model"]
          and all(c["key_label"] == D.KEY_LABEL for c in cards))
    check("a blank's back is the owner's answer or empty when the key is the model's (never auto-filled)",
          cards[0]["back"] == "" and cards[1]["back"] == "Ella está en casa")
    check("the blank card's front is the sentence with the word hidden",
          cards[0]["front"] == "Ella _____ en casa con su hermano." and cards[0]["kind"] == "blank")
    r = w.d.reveal(cards[0]["id"])
    check("reveal on a model-key card carries the label", r["key_label"] == "Answer key written by the model")

    # the key from the owner's own text: the word may be on the back
    Q._reset_for_tests()
    text = ("Ella está en casa con su hermano todos los días de la semana. "
            "Por la mañana toman café y hablan de sus planes para el fin de semana. "
            "Después salen a caminar por el parque cercano a su casa y vuelven tarde.")

    def text_model(system, user, schema, num_predict):
        return json.dumps({"items": [{"kind": "blank", "passage": "Ella está en casa con su hermano todos los días de la semana.",
                                      "word": "está"}]})
    Q.configure(call=text_model)
    Q.configure(keep=lambda spec, cards: D.get().keep(spec, cards))
    qid = Q.handle_post("/api/quiz", {"mode": "spanish", "exercise": "blank", "text": text, "count": 1})[1]["quiz"]["id"]
    Q.handle_post(f"/api/quiz/{qid}/answer", {"n": 1, "answer": "esta"})
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": deck["id"], "cards": [{"n": 1, "answer": ""}]}})
    c = w.d.deck_cards(deck["id"])["cards"][-1]
    check("a blank whose key came from the owner's text: an empty back is filled with the word "
          "(the owner's own text), no label", code == 200 and c["back"] == "está" and c["key_source"] == "text"
          and c["key_label"] is None, json.dumps(c))


# ---------------------------------------------------------------- shapes, words, purity

def t_hide_lists_shapes():
    w = World()
    v = w.d.create_deck("Secret deck name")
    w.d.keep({"deck": v["id"]}, mkcards(2, "Hidden"))
    ls = w.d.list_decks()
    words_in = json.dumps({k: v2 for k, v2 in ls.items() if k != "decks"})
    check("the deck list's only owner-word field is each deck's `name`; every count is a number",
          set(ls["decks"][0]) == {"id", "name", "cards", "ready", "paused", "kind"}
          and isinstance(ls["decks"][0]["cards"], int) and isinstance(ls["decks"][0]["ready"], int)
          and "Secret" not in words_in and "Hidden" not in words_in)
    st = w.d.review_state()
    rest = json.dumps({k: v2 for k, v2 in st.items() if k != "card"})
    check("the review answer's only owner-word field is card.front; the line and counts carry no words",
          set(st["card"]) == {"id", "front", "kind", "level", "deck", "new"} and "Hidden" not in rest
          and st["line"] == "2 cards ready" and isinstance(st["ready"], int) and isinstance(st["run"]["done"], int))
    rv = w.d.reveal(st["card"]["id"])
    check("reveal: the words are back.answer and back.passage only", set(rv) == {"ok", "back", "key_label"}
          and set(rv["back"]) == {"answer", "passage"})
    cs = w.d.deck_cards(v["id"])
    check("the card list: front, back and passage are the owner-word fields",
          set(cs["cards"][0]) == {"id", "front", "back", "passage", "kind", "level", "key_source", "key_label", "new", "due_day"}
          and set(cs["deck"]) == {"id", "name"})
    check("the empty state has a line and counts but never a card",
          World().d.review_state()["card"] is None and World().d.review_state()["state"] == "no_decks")


BANNED = re.compile(r"\b(missed|overdue|behind|streaks?|xp|hearts?|lost|keep it up|in a row|days in a row|"
                    r"leaderboard|league|points)\b", re.I)


def _strings(path: Path, skip=()):
    tree = ast.parse(path.read_text(encoding="utf-8"))
    doc_ids = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            b = node.body
            if b and isinstance(b[0], ast.Expr) and isinstance(getattr(b[0], "value", None), ast.Constant) \
                    and isinstance(b[0].value.value, str):
                doc_ids.add(id(b[0].value))
    out = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str) and id(node) not in doc_ids:
            if node.value not in skip:
                out.append(node.value)
    return out


def t_no_streak_or_guilt_words():
    bad = [s for s in _strings(HERE / "jarvis_decks.py") if BANNED.search(s)]
    check("no streak, XP, hearts, 'missed', 'overdue', 'behind', 'lost' or 'in a row' in any string of jarvis_decks.py",
          not bad, bad)
    bad = [s for s in _strings(HERE / "jarvis_quiz.py") if BANNED.search(s)]
    check("... nor in the quiz module's strings (no exemption: the model-unavailable reassurance says "
          "'Nothing was changed')", not bad, bad)
    pool = D.CLASSES
    check("every deck error has a plain sentence with a status",
          all(isinstance(m, str) and len(m) > 10 and isinstance(c, int) for c, m in pool.values()))
    lines = [D.line_for(1, 0, False), D.line_for(1, 0, True), D.line_for(2, 1, False), D.line_for(2, 7, False), D.line_for(0, 0, False)]
    check("the lines are exactly: Nothing ready today / All decks paused / 1 card ready / 7 cards ready / (none)",
          lines == ["Nothing ready today", "All decks paused", "1 card ready", "7 cards ready", ""], lines)


def t_purity():
    src = (HERE / "jarvis_decks.py").read_text(encoding="utf-8")
    tree = ast.parse(src)
    mods = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            mods |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            mods.add((node.module or "").split(".")[0])
    jarvis_mods = sorted(m for m in mods if m.startswith("jarvis_"))
    check("it imports only jarvis_framework (settings folder), jarvis_chat_log (the key helper), jarvis_schedule, jarvis_quiz (to hand in `keep`)",
          set(jarvis_mods) <= {"jarvis_framework", "jarvis_chat_log", "jarvis_schedule", "jarvis_quiz"}, jarvis_mods)
    banned = ("jarvis_learner", "jarvis_memory", "jarvis_auto_learn", "jarvis_extract", "jarvis_gate",
              "jarvis_agent", "jarvis_facts", "jarvis_history", "urllib.request", "socket", "http.client",
              "jarvis_local_http", "requests", "subprocess", "ollama")
    code = "\n".join(l for l in src.split("\n") if not l.strip().startswith("#"))
    check("it never touches memory, the learner, the gate, an agent, a model or the network",
          not [b for b in banned if b in code], [b for b in banned if b in code])
    check("importing it pulled in no learner, memory, history, gate or agent module",
          not [n for n in _AFTER_IMPORT if any(x in n for x in ("learn", "memory", "history", "gate", "extract", "facts", "agent"))],
          sorted(_AFTER_IMPORT))
    hits = []
    for f in HERE.glob("jarvis_*.py"):
        if f.name in ("jarvis_decks.py", "jarvis_quiz.py"):
            continue
        if "jarvis_decks" in f.read_text(encoding="utf-8", errors="ignore"):
            hits.append(f.name)
    check("no other module (no model tool, no voice command, no learner) reaches the decks: only the scheduler's kind list and the locked backup (for its key's name) name it",
          set(hits) <= {"jarvis_schedule.py", "jarvis_backup.py"}, hits)
    tools = "".join(p.read_text(encoding="utf-8", errors="ignore") for p in
                    (HERE / "jarvis_agent.py", HERE / "jarvis_quick.py", HERE / "jarvis_reach.py") if p.exists())
    check("... and the model's tool list, the fast path and the 'what asks first' page know no deck action",
          "jarvis_decks" not in tools and "/api/decks" not in tools)
    # the sealed words never reach the audit log or a print
    check("nothing in the module logs or prints", "print(" not in code and "audit_log" not in code and "logging" not in code)


# ---------------------------------------------------------------- routes

class FakeHandler:
    def do_GET(self):
        self._send(404, {"error": "original handler"})

    def do_POST(self):
        self._send(404, {"error": "original handler"})


def make_handler(origin=True, token=True):
    class H(FakeHandler):
        def _send(self, code, out):
            self.sent = (code, out)
    D.install(H, origin_ok=lambda s: origin, token_ok=lambda s: token,
              read_body=lambda s: s._raw if s._raw is not None else json.dumps(s._body or {}).encode())
    return H


def call(H, method, path, body=None, raw=None):
    h = H.__new__(H)
    h.path, h._body, h._raw, h.sent = path, body, raw, None
    getattr(h, "do_" + method)()
    return h.sent


def t_routes_through_install():
    Q._reset_for_tests()
    w = World()
    H = make_handler()
    check("install hands the quiz its keep function", Q._STATE["keep"] is not None)
    check("installing twice does not wrap twice", "already on" in D.install(
        H, origin_ok=lambda s: True, token_ok=lambda s: True, read_body=lambda s: b"{}"))
    code, out = call(H, "GET", "/api/decks")
    check("GET /api/decks on an empty PC", code == 200 and out["ok"] and out["decks"] == [] and out["line"] == ""
          and out["available"] is True)
    code, out = call(H, "POST", "/api/decks", {"name": "Routes"})
    did = out["deck"]["id"]
    check("POST /api/decks makes a deck", code == 200 and out["ok"] and out["deck"]["name"] == "Routes")
    w.d.keep({"deck": did}, mkcards(3))
    check("POST /api/decks with a bad name -> 400 bad_deck_name",
          call(H, "POST", "/api/decks", {"name": ""})[1]["error"] == "bad_deck_name"
          and call(H, "POST", "/api/decks", raw=b"[1]")[1]["error"] == "bad_deck_name")
    code, out = call(H, "GET", f"/api/decks/{did}/cards/")
    check("GET /api/decks/<id>/cards (with a trailing slash)", code == 200 and len(out["cards"]) == 3)
    check("POST /api/decks/<id>/act rename", call(H, "POST", f"/api/decks/{did}/act", {"do": "rename", "name": "Renamed"})[1]["deck"]["name"] == "Renamed")
    cid = out["cards"][0]["id"]
    code, out2 = call(H, "POST", f"/api/decks/{did}/cards/{cid}/act", {"do": "edit", "front": "Edited?"})
    check("POST /api/decks/<id>/cards/<cid>/act edit", code == 200 and out2["card"]["front"] == "Edited?")
    check("POST /api/decks/settings", call(H, "POST", "/api/decks/settings", {"new_per_day": 3})[1] == {"ok": True, "new_per_day": 3}
          and call(H, "POST", "/api/decks/settings", {"new_per_day": 99})[0] == 400)
    code, out = call(H, "GET", "/api/review")
    check("GET /api/review", code == 200 and out["ok"] and out["state"] == "card" and out["ready"] == 3)
    code, out = call(H, "GET", f"/api/review?deck={did}&x=1")
    check("GET /api/review?deck=<id> reads the query string", code == 200 and out["card"]["deck"] == did)
    check("GET /api/review?deck=<unknown> -> 404 deck_not_found", call(H, "GET", "/api/review?deck=dnope")[0] == 404)
    cid = out["card"]["id"]
    check("POST /api/review/rate before reveal -> 409 not_revealed",
          call(H, "POST", "/api/review/rate", {"card": cid, "rating": "good"})[0] == 409)
    code, out = call(H, "POST", "/api/review/reveal", {"card": cid})
    check("POST /api/review/reveal", code == 200 and set(out["back"]) == {"answer", "passage"})
    code, out = call(H, "POST", "/api/review/rate", {"card": cid, "rating": "good"})
    check("POST /api/review/rate", code == 200 and out["ok"] and "next" in out and out["ready"] == 2, json.dumps(out))
    check("POST /api/review/rate with a bad rating -> 400 bad_rating",
          call(H, "POST", "/api/review/rate", {"card": cid, "rating": "meh"})[1]["error"] == "bad_rating")
    code, out = call(H, "POST", "/api/review/more", {})
    check("POST /api/review/more", code == 200 and out["run"]["limit"] == 30)
    check("unrelated routes and methods fall through to the original handler",
          call(H, "GET", "/api/other")[1] == {"error": "original handler"}
          and call(H, "POST", "/api/decksx", {})[1] == {"error": "original handler"}
          and call(H, "GET", f"/api/decks/{did}")[1] == {"error": "original handler"}
          and call(H, "GET", "/api/decks/settings")[1] == {"error": "original handler"}
          and call(H, "GET", "/api/review/rate")[1] == {"error": "original handler"}
          and call(H, "POST", "/api/review", {})[1] == {"error": "original handler"})
    check("a body that is not JSON is 400", call(H, "POST", "/api/decks", raw=b"{oops")[0] == 400)
    Hb = make_handler(origin=False)
    check("a refused origin never reaches the decks", call(Hb, "GET", "/api/decks") == (403, {"error": "cross-origin request refused"}))
    Ht = make_handler(token=False)
    check("a bad token is 401 and reaches nothing",
          call(Ht, "POST", "/api/decks", {"name": "X"})[0] == 401 and call(Ht, "GET", "/api/review")[0] == 401)
    check("no deck was made by the refused calls", len(w.d.list_decks()["decks"]) == 1)


def t_the_patch_and_the_shipped_lists():
    import _stack
    order = _stack.order()
    check("decks.patch is in apply-patches.ps1's list, after quiz.patch",
          "decks.patch" in order and order.index("decks.patch") > order.index("quiz.patch"), order[-3:])
    hud, log = _stack.stand_in("jarvis_hud.py")
    if hud is None:
        print("SKIP  the stack stand-in (git is missing)")
        return
    check("its hunk applies to what the patches before it wrote (nothing materialised)",
          not [l for l in log if l.startswith("decks.patch")], [l for l in log if l.startswith("decks.patch")])
    check("the server installs jarvis_decks right after the quiz block, before the sockets",
          hud.index("jarvis_quiz.install") < hud.index("jarvis_decks.install") < hud.rindex("_loopback_companion(bind"))
    check("the install block wraps its own failure and says so on the banner", 'print(f"  decks      NOT ON' in hud)
    patch = (HERE / "decks.patch").read_text(encoding="utf-8")
    check("the patch touches only jarvis_hud.py, in one hunk",
          [l[6:] for l in patch.split("\n") if l.startswith("+++ b/")] == ["jarvis_hud.py"]
          and patch.count("\n@@ ") + patch.startswith("@@") == 1)
    ps1 = (HERE.parent / "scripts" / "apply-patches.ps1").read_text(encoding="utf-8")
    check("jarvis_decks.py is copied in by apply-patches.ps1 and listed in _where.py",
          "'jarvis_decks.py'" in ps1 and "jarvis_decks.py" in (HERE / "_where.py").read_text())
    check("the golden file is a test fixture, not shipped", "decks_fsrs_golden" not in ps1)


# ---------------------------------------------------------------- the audit fixes (2026-09-30)

def t_without_fsrs_nothing_is_kept():
    w = World()
    saved = D.fsrs
    D.fsrs = None
    try:
        ok, why = w.d.available()
        check("no py-fsrs: available() says so in words", ok is False and "py-fsrs" in why, why)
        check("... the deck list carries the same banner text",
              w.d.list_decks()["available"] is False and "py-fsrs" in w.d.list_decks()["why"])
        check("... keeping fails plainly (deck_unavailable), nothing is written",
              raises(lambda: w.d.keep({"new_deck": "X"}, mkcards(1)), "deck_unavailable")
              and not w.path.exists())
        check("... and so does making a deck",
              raises(lambda: w.d.create_deck("X"), "deck_unavailable"))
    finally:
        D.fsrs = saved
    check("with py-fsrs back, keeping works", w.d.keep({"new_deck": "X"}, mkcards(1)) == 1)


def t_two_apps_never_cross_runs():
    w = World()
    a = w.d.create_deck("A")["id"]
    b = w.d.create_deck("B")["id"]
    w.d.set_new_per_day(20)
    w.d.keep({"deck": a}, mkcards(30, "A"))
    w.d.keep({"deck": b}, mkcards(30, "B"))
    for _ in range(3):                      # the phone reviews deck A
        cid = w.d.review_state(a)["card"]["id"]
        w.d.reveal(cid)
        w.d.rate(cid, "good", a)
    st_all = w.d.review_state()             # the desktop reviews everything, at the same time
    check("a rating in deck A did not count in the all-decks run", st_all["run"] == {"done": 0, "limit": 20},
          json.dumps(st_all["run"]))
    cid = st_all["card"]["id"]
    w.d.reveal(cid)
    out = w.d.rate(cid, "good", "")
    check("... the desktop's rating counts in its own run only",
          out["run"]["done"] == 1 and w.d.review_state(a)["run"]["done"] == 3, json.dumps(out["run"]))
    for _ in range(5):
        cid = w.d.review_state(a)["card"]["id"]
        w.d.reveal(cid)
        r = w.d.rate(cid, "good", a)
    check("five more in deck A leave the all-decks run at 1 and deck A's at 8",
          w.d.review_state()["run"]["done"] == 1 and w.d.review_state(a)["run"]["done"] == 8)
    cid = w.d.review_state(b)["card"]["id"]
    w.clock.t += 1
    w.d.review_state()                      # the all-decks view is the newest
    w.d.reveal(cid)
    r = w.d.rate(cid, "good")               # an old app that sends no scope
    check("no scope sent: the newest run the card belongs to counts it (all-decks was newest)",
          w.d.review_state()["run"]["done"] == 2 and r["ok"], json.dumps(w.d.review_state()["run"]))
    cid = w.d.review_state(b)["card"]["id"]
    w.d.reveal(cid)
    w.d.rate(cid, "good", a)
    check("a scope that is not the card's deck is ignored, not trusted (deck A's run stays at 8)",
          w.d.review_state(a)["run"]["done"] == 8)


def t_zero_new_cards_promises_nothing():
    w = World()
    v = w.d.create_deck("Z")["id"]
    w.d.keep({"deck": v}, mkcards(5))
    w.d.set_new_per_day(0)
    ls = w.d.list_decks()
    check("new cards a day = 0: nothing ready and no 'next ready day' promised",
          ls["ready"] == 0 and ls["next_ready_day"] is None, json.dumps(ls))
    w.d.set_new_per_day(2)
    study(w.d, w.d.review_state()["card"]["id"])
    study(w.d, w.d.review_state()["card"]["id"])
    check("an allowance of 2 used up with cards waiting: tomorrow is named",
          w.d.list_decks()["next_ready_day"] == D._tomorrow(w.clock.t), w.d.list_decks()["next_ready_day"])


def t_days_are_calendar_days_across_dst():
    # See t_day_rolls_over_by_this_pcs_clock above: no time.tzset() on Windows.
    if not hasattr(time, "tzset"):
        skip("calendar days across DST: this system has no time.tzset, so DST cannot be "
             "simulated; CI proves this one on Linux")
        return
    keep_tz = os.environ.get("TZ")
    try:
        for tz, y, mo, d, _tomorrow in (("America/New_York", 2026, 3, 7, "2026-03-08"),
                                       ("America/New_York", 2026, 11, 1, "2026-11-02"),
                                       ("Pacific/Auckland", 2026, 9, 26, "2026-09-27"),
                                       ("Pacific/Auckland", 2027, 4, 4, "2027-04-05")):
            os.environ["TZ"] = tz
            time.tzset()
            for hh, mm in ((23, 30), (0, 30)):
                now = S.wall_to_epoch(y, mo, d, hh, mm)
                want_day = time.strftime("%Y-%m-%d", time.localtime(time.mktime((y, mo, d + 1, hh, mm, 0, 0, 0, -1))))
                check(f"{tz} {y}-{mo:02d}-{d:02d} {hh}:{mm:02d}: tomorrow is the next calendar day",
                      D._tomorrow(now) == want_day, (D._tomorrow(now), want_day))
                st = D.new_state(now)
                for rating in ("good", "easy"):
                    out = D.review(st, rating, now, fuzz=False)
                    got, was = time.localtime(out["due"]), time.localtime(now)
                    days = round((out["due"] - now) / 86400)
                    want = time.localtime(time.mktime((was.tm_year, was.tm_mon, was.tm_mday + days, was.tm_hour,
                                                       was.tm_min, 0, 0, 0, -1)))
                    check(f"{tz} {y}-{mo:02d}-{d:02d} {hh}:{mm:02d} rated {rating}: due is the same clock time "
                          f"{days} calendar days on",
                          (got.tm_year, got.tm_mon, got.tm_mday, got.tm_hour, got.tm_min)
                          == (want.tm_year, want.tm_mon, want.tm_mday, want.tm_hour, want.tm_min), (got, want))
        os.environ["TZ"] = "America/New_York"
        time.tzset()
        now = S.wall_to_epoch(2026, 3, 7, 23, 30)
        out = D.review(D.new_state(now), "again", now, fuzz=False)
        check("'Didn't remember' in New York on 7 March evening comes back on 8 March, not the 9th",
              time.strftime("%Y-%m-%d", time.localtime(out["due"])) == "2026-03-08",
              time.strftime("%Y-%m-%d %H:%M", time.localtime(out["due"])))
    finally:
        os.environ["TZ"] = keep_tz or "UTC"
        time.tzset()


def t_a_card_front_edit_reruns_the_duplicate_check():
    w = World()
    v = w.d.create_deck("Dup")["id"]
    same_passage = mkcards(2)
    for c in same_passage:
        c["passage"] = "One shared passage."
    w.d.keep({"deck": v}, same_passage)
    cards = w.d.deck_cards(v)["cards"]
    dup_front = cards[0]["front"]
    check("editing a front to another card's question (same passage) -> duplicate_card",
          raises(lambda: w.d.card_act(v, cards[1]["id"], "edit", front=dup_front), "duplicate_card"))
    same = w.d.card_act(v, cards[0]["id"], "edit", front=dup_front + " ")["card"]
    check("... but saving a card's own front again is fine", same["front"] == dup_front)
    check("... and a new, different front is fine",
          w.d.card_act(v, cards[1]["id"], "edit", front="A different question?")["card"]["front"]
          == "A different question?")


def t_keep_with_a_non_text_deck_is_bad_request():
    m, w = quiz_world()
    qid = new_quiz()
    for bad in (5, ["x"], {"a": 1}, True):
        code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"deck": bad, "cards": [{"n": 1, "answer": "a"}]}})
        check(f"keep.deck = {bad!r} -> 400 bad_request, the quiz stays open",
              code == 400 and out["error"] == "bad_request" and open_quiz(qid), json.dumps(out))
    code, out = Q.handle_post(f"/api/quiz/{qid}/finish", {"keep": {"new_deck": 7, "cards": [{"n": 1, "answer": "a"}]}})
    check("keep.new_deck that is not text -> 400 bad_request", code == 400 and out["error"] == "bad_request")


def t_long_blank_sentences_and_decomposed_text():
    import unicodedata
    long_sentence = ("La casa " + "muy grande y bonita " * 40 + "tiene una cocina pequena donde mi madre prepara "
                     "la cena cada noche " + "y otra parte mas " * 20).strip()
    cut = Q._cut_blank(long_sentence, "cocina")
    prompt = Q._window(cut[0], Q.PROMPT_MAX)
    check("a sentence over 500 characters: the window is at most 500 and keeps the blank",
          len(long_sentence) > 500 and len(prompt) <= Q.PROMPT_MAX and Q.BLANK in prompt, (len(prompt), prompt[:80]))
    check("a short sentence is left exactly as it is", Q._window("Yo _____ hoy.", 500) == "Yo _____ hoy.")
    nfd = unicodedata.normalize("NFD", "El niño está en la habitación pequeña.")
    cut = Q._cut_blank(nfd, unicodedata.normalize("NFD", "habitación"))
    check("pasted text with separate accent marks (NFD) still gives a blank item",
          cut is not None and Q.BLANK in cut[0] and cut[1] == unicodedata.normalize("NFC", "habitación"), cut)
    check("... and the passage check matches NFD text against the model's NFC copy",
          Q._norm(nfd) == Q._norm(unicodedata.normalize("NFC", nfd)))
    # end to end through write_spanish: an NFD text, the model's NFC answer
    text = unicodedata.normalize("NFD", "El niño está en la habitación pequeña. " * 10)
    reply = json.dumps({"items": [{"kind": "blank", "prompt": "", "passage": "El niño está en la habitación pequeña.",
                                   "word": "habitación", "accepted": []}]})
    Q.configure(call=lambda system, user, schema, num_predict: reply)
    items = Q.write_spanish(text, "A2", "blank", "", 1)
    check("write_spanish keeps a blank item from NFD-decomposed pasted text",
          len(items) == 1 and Q.BLANK in items[0]["prompt"], items)
    Q._reset_for_tests()



def t_after_a_pc_restart_the_next_rating_is_refused_then_recovers():
    w = World()
    v = w.d.create_deck("R")["id"]
    w.d.keep({"deck": v}, mkcards(3))
    cid = w.d.review_state(v)["card"]["id"]
    w.d.reveal(cid)
    d2 = D.Decks(w.path, lambda: KEY, clock=w.clock, scheduler=w.sched, fuzz=False)   # the PC restarted
    check("the reveal list is memory only: after a restart the rating is refused with not_revealed",
          raises(lambda: d2.rate(cid, "good", v), "not_revealed"))
    st = d2.review_state(v)
    check("... the same card is asked for again", st["state"] == "card" and st["card"]["id"] == cid)
    d2.reveal(cid)
    check("... and after showing the answer again the rating works", d2.rate(cid, "good", v)["ok"])


def t_wording_and_the_shared_fixture():
    import subprocess
    r = subprocess.run([sys.executable, str(HERE.parent / "tools" / "gen_decks_cases.py"), "--check"],
                       capture_output=True, text=True)
    check("tools/gen_decks_cases.py --check: both apps' decks-cases.json are current "
          "(python3 tools/gen_decks_cases.py)", r.returncode == 0, r.stdout + r.stderr)
    msg = Q.CLASSES["model_unavailable"][1]
    check("the model-unavailable sentence says 'Nothing was changed' and not 'lost'",
          "Nothing was changed" in msg and "lost" not in msg.lower(), msg)
    check("no file of either app or a test still says 'Nothing was lost'",
          not [f for f in (list((HERE.parent / "jarvis-desktop" / "src").glob("quiz.js"))
                           + list((HERE.parent / "jarvis-desktop" / "tests").glob("quiz.mjs"))
                           + list((HERE.parent / "jarvis-client" / "app" / "src").rglob("Quiz*.kt")))
               if "Nothing was lost" in f.read_text(encoding="utf-8")])

    class Handler:
        def do_GET(self):
            pass

        def do_POST(self):
            pass
    banner = Q.install(Handler, origin_ok=lambda h: True, token_ok=lambda h: True, read_body=lambda h: b"{}")
    check("the quiz's startup banner no longer says 'nothing saved' (Keep saves into a deck)",
          "nothing saved" not in banner.lower() and "Keep" in banner, banner)
    Q._reset_for_tests()



def main() -> int:
    try:
        import fsrs  # noqa: F401
    except Exception:
        print("skip  test_decks.py: py-fsrs is not installed (py -3 -m pip install -r backend/requirements.txt)")
        return 0
    try:
        for name, fn in list(globals().items()):
            if name.startswith("t_") and callable(fn):
                print(f"--- {name} ---")
                try:
                    fn()
                except Exception as exc:  # pragma: no cover
                    traceback.print_exc()
                    check(f"{name} ran without crashing", False, repr(exc))
    finally:
        Q._reset_for_tests()
        S._SCHED = None
        D._reset_for_tests()
        shutil.rmtree(_TMP, ignore_errors=True)
    print(f"\n{len(PASSED)} passed, {len(SKIPPED)} skipped, {len(FAILED)} failed")
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
