"""Writes index.html (landscape, 32 s) and vertical.html (upright, 15 s).

Both cuts share the same phone, browser and scene markup, so it lives here
once. Edit this file, then run:  python3 tools/build_html.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PHONE = '''          <div id="phone">
            <div class="screen">
              <!-- An Android status bar and punch-hole camera: jarvis-client is an Android app. -->
              <div class="sbar"><span>12:30</span><i class="cam"></i><span class="icons"><i class="sig"></i><i class="wifi"></i><i class="bat"></i></span></div>
              <canvas id="phone-face" width="360" height="360"></canvas>
              <!-- Drawn from jarvis-client ApprovalCard.kt (countdown, title, summary, buttons); the title is
                   PendingRows.kt titleForAction("control_browser"). -->
              <div id="pcard">
                <div class="exp-bar"><i id="exp-fill"></i></div>
                <div class="exp"><span>EXPIRES IN</span><b id="exp-n">00:47</b></div>
                <div class="title">Jarvis wants to control browser</div>
                <div class="sum">Renew my library book, The Quiet Orchard.</div>
                <div class="cmd">library.example.org · 2 steps</div>
                <div class="btns"><span class="ok" id="p-ok">Approve</span><span class="no">Deny</span></div>
                <div class="foot">Nothing runs until you decide.</div>
              </div>
              <div id="p-done"><b>✓ Approved</b></div>
              <!-- Android's own fingerprint sheet: BiometricGate.kt gives it the card's title, then its
                   "why", falling back to "Check the card before you confirm." -->
              <div id="sheet">
                <div class="grab"></div>
                <div class="st">Jarvis wants to control browser</div>
                <div class="ss">Check the card before you confirm.</div>
                <svg id="fp" viewBox="0 0 120 120">
                  <circle cx="60" cy="60" r="54" class="track" />
                  <circle cx="60" cy="60" r="54" class="ring" id="fp-ring" />
                  <g class="print" id="fp-print">
                    <path d="M40 74c0-14 9-24 20-24s20 10 20 24" />
                    <path d="M47 82c-1-4-1-8-1-10 0-9 6-15 14-15s14 6 14 15c0 5-1 9-3 13" />
                    <path d="M54 88c-1-5-1-11-1-15 0-5 3-8 7-8s7 3 7 8c0 7-1 12-3 16" />
                    <path d="M60 72c0 7 0 13-2 19" />
                    <path d="M34 62c4-12 14-20 26-20s22 8 26 20" />
                  </g>
                </svg>
                <div class="sh">Touch the fingerprint sensor</div>
                <div class="pin">Use PIN</div>
              </div>
            </div>
          </div>
'''

BROWSER = '''            <!-- A visible browser window: browser_control launches Chromium NOT headless, so the owner
                 can watch. The library site is sample data; the steps are the two on the card. -->
            <div id="browser">
              <div class="bbar"><i></i><i></i><i></i><div class="url"><span class="lock">🔒</span><span id="b-url"></span></div></div>
              <div class="bpage">
                <div class="bh">City Library · <b>My loans</b></div>
                <div class="brow"><span class="bt">The Quiet Orchard</span><span class="bd" id="b-due1">Due Friday</span><span class="bb" id="b-renew1">Renew</span></div>
                <div class="brow"><span class="bt">Field Notes on Rain</span><span class="bd">Due 12 Oct</span><span class="bb">Renew</span></div>
                <div class="brow"><span class="bt">A Short History of Maps</span><span class="bd">Due 20 Oct</span><span class="bb">Renew</span></div>
              </div>
            </div>
            <div class="bstep" id="b-step">Jarvis · step 2 of 2 · click “Renew”</div>
'''

TASK_NOTE = '          <div class="task-note" id="task-note">Browser control is ready, but off until a second graphics card is in.</div>\n'

ASK = '''          <div id="ask-wrap">
            <!-- Real capture: Brain > Memory, "Waiting for you", in two slices: the words, then Keep / Discard. -->
            <img id="ask-text" src="assets/ui/ask-text.png" alt="" />
            <img id="ask-buttons" src="assets/ui/ask-buttons.png" alt="" />
            <div class="press" id="press-keep"></div>
          </div>
'''

FINISH = '''      <div id="cap-prev" class="cap prev"><b class="jarvis">Jarvis:</b><span id="cap-prev-text"></span></div>
      <div id="cap" class="cap"><b id="cap-who"></b><span id="cap-text"></span></div>

      <div id="grain" class="layer"></div>
      <div id="vignette" class="layer"></div>
      <div id="fade" class="layer"></div>
'''

HEAD = '''<!doctype html>
<html lang="en">
  <!-- Generated by tools/build_html.py: edit that, not this. -->
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={w}, height={h}" />
    <title>{title}</title>
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/{timing}.js"></script>
    <script src="assets/{audio}.js"></script>
    <script src="assets/reactor.js" charset="utf-8"></script>
    <link rel="stylesheet" href="assets/film.css" />
{extra_css}  </head>
'''

LAND = HEAD.format(w=1920, h=1080, title="Jarvis v3: It Asks First", timing="timing", audio="audio-data", extra_css="") + '''  <body class="land">
    <div id="root" data-composition-id="jarvis-brag-v3" data-start="0" data-width="1920" data-height="1080" data-duration="32">
      <div id="bg" class="layer"></div>
      <div id="stage" class="layer">
        <!-- The reactor: jarvis-desktop/src/faces.html, drawn every frame. -->
        <div id="hero-wrap"><canvas id="hero" width="1400" height="1400"></canvas></div>

        <!-- 1: it asks first, on the PC and the phone; then the visible browser -->
        <section id="s2" class="clip" data-start="1.4" data-duration="9" data-track-index="3">
          <div class="head" id="h-ask">
            <div id="h-ask1">An AI assistant that asks<br />before it acts.</div>
            <div id="h-ask2" class="warm">Every time.</div>
          </div>
          <div class="head" id="h-shout">
            <div id="h-shout1">Nobody can shout “yes” at it.</div>
            <div id="h-shout2" class="warm">Your phone checks it’s you.</div>
          </div>
''' + TASK_NOTE + '''          <div id="desk">
            <div class="where">On your PC</div>
            <!-- Real capture: the quick-ask window's approval card (jarvis-desktop/src/index.html) for a
                 browser_control plan; its text is jarvis_browser_control.describe(), run on the plan. -->
            <div id="desk-card"><img id="desk-img" src="assets/ui/browser-card.png" alt="" /></div>
''' + BROWSER + '''          </div>
''' + PHONE + '''          <div class="where" id="phone-where">On your phone</div>
        </section>

        <!-- 2: June: what it learns stays on your PC -->
        <section id="s5" class="clip" data-start="10.4" data-duration="3" data-track-index="3">
          <div class="month" id="m-june">June.</div>
          <div class="head" id="h-private">Your email, your files, and what it<br />learns about you stay on your PC.</div>
          <!-- Real capture: Brain > Memory, "What did you know on…" (6/30/2026). -->
          <img id="june-card" class="shot" src="assets/ui/june-fact.png" alt="" />
        </section>

        <!-- 3: September: it asks before it remembers -->
        <section id="s6" class="clip" data-start="13.4" data-duration="5.2" data-track-index="3">
          <div class="month" id="m-sept">September.</div>
          <div class="head" id="h-keep">It asks before it remembers, too.</div>
''' + ASK + '''          <div id="facts-wrap">
            <!-- Real capture: Brain > Memory, "What Jarvis knows about you", after Keep. -->
            <img id="sept-card" class="shot" src="assets/ui/sept-rows.png" alt="" />
            <div id="retired-box"></div>
            <div id="retired-note">No longer used.<br /><span>Still in its history, on your PC.</span></div>
          </div>
        </section>

        <!-- 5: your rules -->
        <section id="s8" class="clip" data-start="23.4" data-duration="8.6" data-track-index="3">
          <div id="scrim" class="layer"></div>
          <div class="outro">
            <span id="o1">Your assistant.</span>
            <span id="o2">Your PC.</span>
            <span id="o3" class="warm">Your rules.</span>
          </div>
          <div class="small" id="small1">Needs a PC with an 8 GB NVIDIA graphics card.<br />Phone app: Android. No subscription.</div>
          <div id="wordmark">Jarvis</div>
        </section>
      </div>

''' + FINISH + '''
      <audio id="score" src="assets/music/score.mp3" data-start="0" data-duration="32" data-track-index="20" data-volume="1"></audio>
    </div>

    <script src="assets/film.js"></script>
    <script>
      (function () {
        var H = window.TIMING.hits;
        FILM.run({
          id: "jarvis-brag-v3",
          dur: 32,
          H: H,
          // [start, state] for the big reactor (face: Arc, the app's default).
          hero: [[0, "listening"], [H.drink, "listening"], [19.2, "thinking"], [H.reply, "speaking"],
                 [H.stop, "idle", "cut"], [H.outro, "idle"]],
          // [start, end, x, y, scale from, scale to, opacity]; hidden outside these.
          frames: [[0, 1.4, 0, -40, 0.9, 0.95, 1], [18.6, 23.4, 0, -120, 0.74, 0.8, 1], [23.4, 32, 0, -20, 0.74, 0.84, 0.9]],
          // Slow drift per shot; the push onto the phone for the fingerprint, eased back for the browser.
          drift: [[1.4, 5.0], [10.4, 13.4], [13.4, 18.6], [18.6, 22.3], [23.4, 32]],
          push: { at: 5.0, len: 1.2, to: 1.06, origin: "1455px 520px", back: 6.7, until: 10.4 },
          deskZoom: { at: H.zoom, len: 0.8, to: 1.55, origin: "8% 52%", out: H.tap - 0.2 },
          caps: [
            [H.hey, 1.5, "you", "Hey Jarvis, renew my library book.", "words", 0.9],
            [H.note, 2.9, "", "“Hey Jarvis” only listens once you switch it on.", "static", 0],
            [H.plain, 5.1, "", "Jarvis wants to open your library’s website and press Renew.", "static", 0],
            [H.done, 10.3, "jarvis", "Done. I pressed Renew for The Quiet Orchard.", "words", 0.6],
            [H.septSay, 15.3, "you", "I’m off coffee this month.", "words", 0.8],
            [H.drink, 19.5, "you", "What should I drink instead?", "words", 0.7],
            [H.reply, H.stop, "jarvis", "Since you’re off coffee this month, how about mint tea? Or an oat-milk hot choc", "type", 2.6],
            [H.stop, 23.4, "you", "Stop.", "big", 0]
          ]
        });
      })();
    </script>
  </body>
</html>
'''

TALL = HEAD.format(w=1080, h=1920, title="Jarvis v3: It Asks First (upright)", timing="timing-vertical", audio="audio-data-vertical",
                   extra_css='    <link rel="stylesheet" href="assets/film-tall.css" />\n') + '''  <body class="tall">
    <!-- The 15 s upright cut: the same scenes as index.html, re-laid-out for a phone held upright
         (not cropped). Words stay out of the top 200 px and the bottom 300 px, where short-video
         apps draw their own buttons. -->
    <div id="root" data-composition-id="jarvis-brag-v3-vertical" data-start="0" data-width="1080" data-height="1920" data-duration="15">
      <div id="bg" class="layer"></div>
      <div id="stage" class="layer">
        <div id="hero-wrap"><canvas id="hero" width="1400" height="1400"></canvas></div>

        <!-- 1: it asks first; then the visible browser -->
        <section id="s2" class="clip" data-start="0" data-duration="6.3" data-track-index="3">
          <div class="head" id="h-ask"><div id="h-ask1">An AI assistant that asks before it acts.</div></div>
''' + TASK_NOTE + PHONE + '''          <div id="desk">
''' + BROWSER + '''          </div>
        </section>

        <!-- 2: it asks before it remembers -->
        <section id="s6" class="clip" data-start="6.3" data-duration="3" data-track-index="3">
          <div class="head" id="h-keep">It asks before it remembers, too.</div>
''' + ASK + '''        </section>

        <!-- 4: your rules -->
        <section id="s8" class="clip" data-start="12.9" data-duration="2.1" data-track-index="3">
          <div id="scrim" class="layer"></div>
          <div class="outro">
            <span id="o1">Your assistant.</span>
            <span id="o2">Your PC.</span>
            <span id="o3" class="warm">Your rules.</span>
          </div>
          <div class="small" id="small1">Jarvis · runs on your PC · no subscription</div>
        </section>
      </div>

''' + FINISH + '''
      <audio id="score" src="assets/music/score-vertical.mp3" data-start="0" data-duration="15" data-track-index="20" data-volume="1"></audio>
    </div>

    <script src="assets/film.js"></script>
    <script>
      (function () {
        var H = window.TIMING.hits;
        FILM.run({
          id: "jarvis-brag-v3-vertical",
          dur: 15,
          H: H,
          phoneOut: H.browser,   // upright: the phone steps aside so the browser can be read
          staticHead: true,      // the hook is on screen from the first frame
          cardsLead: 0.9,        // ...and so is the phone card
          hero: [[0, "idle"], [H.drink, "listening"], [9.9, "thinking"], [H.reply, "speaking"], [H.stop, "idle", "cut"], [H.outro, "idle"]],
          frames: [[9.3, 12.9, 0, -40, 0.86, 0.92, 1], [12.9, 15, 0, 160, 0.8, 0.86, 0.85]],
          drift: [[6.3, 9.3], [9.3, 12.0], [12.9, 15]],
          push: { at: 1.7, len: 1.0, to: 1.08, origin: "540px 1150px", back: 3.2, until: 6.3 },
          caps: [
            [H.hey, 1.8, "you", "Hey Jarvis, renew my library book.", "words", 0.9],
            [H.done, 6.25, "jarvis", "Done. I pressed Renew for The Quiet Orchard.", "words", 0.5],
            [H.septSay, 8.0, "you", "I’m off coffee this month.", "words", 0.6],
            [H.drink, 10.05, "you", "What should I drink instead?", "words", 0.5],
            [H.reply, H.stop, "jarvis", "Since you’re off coffee, how about mint tea? Or an oat-milk hot choc", "type", 1.8],
            [H.stop, 12.9, "you", "Stop.", "big", 0]
          ]
        });
      })();
    </script>
  </body>
</html>
'''

(ROOT / "index.html").write_text(LAND, encoding="utf-8")
(ROOT / "vertical.html").write_text(TALL, encoding="utf-8")
print("wrote index.html and vertical.html")
