fn main() {
    // Declaring an app manifest is what turns the ACL on for this app's OWN
    // commands. Without it `has_app_manifest()` is false and Tauri's permission
    // check short-circuits: every `#[tauri::command]` is callable from every
    // window regardless of what the capability files say. The capability file
    // used to describe itself as a "least-privilege IPC surface" while gating
    // nothing app-defined, which is worse than having no file at all.
    //
    // `commands` autogenerates an `allow-<kebab-name>` and `deny-<kebab-name>`
    // permission per entry into `permissions/autogenerated/`. The sets in
    // `permissions/` group those per surface, and `capabilities/*.json` hands
    // each window only its own set.
    //
    // Anything added to `generate_handler!` in lib.rs must be added here too,
    // or it is reachable from nowhere and the failure is a runtime "not allowed
    // on window" rather than a compile error.
    let attributes =
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            // Chat
            "stream_chat",
            "cancel_chat",
            "set_route_lane",
            // The fanned-out event stream
            "get_link_state",
            "get_pending_approvals",
            "refresh_link",
            "decide_approval",
            "notify_user",
            // Settings -> Notifications: the owner's per-kind switches and his
            // quiet-hours window, pushed in by notifications-prefs.js. Without
            // this line the command has no permission at all and every push is
            // refused at the ACL - which is exactly the silent failure the
            // switches themselves had. Settings window only.
            "set_notification_prefs",
            // The HUD page's requests, made in Rust so the page holds no
            // token (apps security audit M2; hud_proxy.rs).
            "hud_get",
            "hud_chat",
            "hud_chat_cancel",
            // App lock and the widget: is the lock on, and "Approve in the
            // Jarvis bar" (apps security audit M3).
            "get_app_lock",
            // App lock and "Hide memory lists", two yes/no answers: a face's
            // nod on a saved fact never plays while either is on.
            "get_lock_flags",
            "open_approval_in_quickbar",
            // A note on a proposal, and the controls for the turn already
            // running. `jarvis-link.js` invoked all five of these before any
            // of them existed, so every one of those buttons failed at the
            // Tauri boundary - see permissions/surfaces.toml's "approvals"
            // and "task-control" sets for which windows get them.
            "amend_approval",
            "pause_task",
            "resume_task",
            "stop_task",
            // The widget's "working on your screen" line and its Stop - the
            // same stop as the hotkey (screen_work.rs). task-control set.
            "screen_work",
            "stop_everything",
            "inject_task_note",
            // The interruption budget and the daily brief. Reads and two
            // writes; the tray calls the same functions in-process, so it
            // needs no grant.
            "get_digest",
            "mark_digest_seen",
            "set_attention_muted",
            // The Brain. One fan-out read over a fixed allowlist, then one
            // command per power it can exercise.
            "brain_read",
            "brain_revert_undo",
            "brain_cancel_job",
            "brain_cancel_hold",
            "brain_watch_add",
            "brain_watch_remove",
            "brain_watch_seen",
            "brain_remove_skill",
            "brain_model",
            // Memory: one decision per fact, and the switch that governs
            // whether facts are proposed at all.
            "brain_memory_decide",
            "brain_memory_forget",
            // "Erase the words": one fact's words wiped, its dates kept.
            "brain_memory_erase",
            "brain_memory_edit",
            "brain_memory_learning",
            "brain_memory_export",
            "brain_memory_as_of",
            // Same omission as `restart_app` below: in generate_handler! and
            // called by brain.js, absent here, so unreachable from every
            // window.
            "brain_memory_sleep_time",
            // "Both are true" on a correction card (memory-intake.patch).
            "brain_memory_keep_both",
            // Automatic learning (JARVIS-API.md section 19): the "Saved
            // automatically" list and its two switches. Brain only.
            "brain_memory_learning_status",
            "brain_memory_auto_list",
            "brain_memory_learning_auto",
            "brain_memory_learning_sensitive",
            // How many facts were saved automatically while the Brain was
            // closed - ids only, never the words. Brain only.
            "brain_memory_saved_unseen",
            // "Always keep in mind" (JARVIS-API.md section 6): the pinned
            // facts, and pin or unpin ONE fact. Brain only.
            "brain_memory_profile",
            "brain_memory_pin",
            // "Between us" (JARVIS-API.md section 44, the owner's decision,
            // 2026-09-27): the shared-joke facts, and tag or untag ONE fact.
            // Brain only.
            "brain_memory_shared",
            "brain_memory_share",
            // "Used in this answer" / "Jarvis remembered N things" (the
            // owner's decision, 2026-09-25): the words of a few facts, by id.
            // A read. The quickbar and the Brain.
            "memory_used",
            // Can this PC hold a temporary chat? A read. The quickbar.
            "temporary_chat_available",
            // Chat history on the PC (JARVIS-API.md section 18): list, open
            // one read-only, delete ONE, and the two settings. Brain only.
            "brain_history_list",
            "brain_history_open",
            // "Search what was said" (JARVIS-API.md section 71): a read,
            // refused while the private lists are hidden. Brain only.
            "brain_history_search",
            // Chat tags (docs/CHAT-TAGS-DESIGN.md section 10): read them,
            // change one, file one chat. No card; hidden under "Hide memory
            // lists"; edits held on a stale link. Brain only.
            "brain_history_tags",
            "brain_history_tags_edit",
            "brain_history_tag",
            // "New section here" (JARVIS-API section 106) and the "Suggest
            // tags overnight" switch (section 104). Brain only.
            "brain_history_mark",
            "brain_history_tag_suggest",
            "brain_history_fork",
            // "Continue this chat" (the chat audit, 2026-09-28): the Brain
            // tells the Jarvis bar which chat to carry on (the id only), and
            // the bar reads that one chat - never a support, chatbot or
            // comparison record.
            "brain_continue_chat",
            // "Erase the words" names the chat it would also delete: a read.
            "brain_fact_chat",
            "chat_continue_open",
            // Is the private lists' "Hide" on? Yes or no, nothing read. The
            // Jarvis bar hides its thread of earlier answers with it.
            "chat_thread_hidden",
            // "History of this fact" (section 71): every version of one
            // fact, hidden like every memory list. Brain only.
            "brain_fact_history",
            // "Facts this chat taught" (section 79): History's Delete offers
            // to forget them, one Forget per ticked fact. A read, hidden like
            // every memory list. Brain only.
            "brain_conversation_facts",
            "brain_history_delete",
            "brain_history_settings",
            // Backend supervision — settings window only
            "supervisor_status",
            "set_supervision",
            "start_backend",
            "stop_backend",
            // The theme. Readable everywhere, writable from the two windows
            // that offer a picker.
            "get_theme",
            "set_theme",
            // "Match Windows light or dark mode": the read is everywhere the
            // theme is, the switch is with the two pickers.
            "get_theme_prefs",
            "set_theme_follow_system",
            // Settings' "Open Faces" button.
            "open_faces",
            // Settings' "Everything Jarvis can do" button, and the same row in
            // the tray menu (2026-10-08, docs/FEATURES-LIST-DESIGN.md). The page
            // this opens holds no command of its own.
            "open_features",
            // The right/wrong mark on one answer (feedback.patch). Quickbar.
            "mark_answer",
            // The first-run walkthrough — one command, closes itself.
            "finish_onboarding",
            // Windows Hello (lock.rs). The Security settings are read and
            // changed from the settings window only; loosening one asks
            // Windows Hello first. Show, for the Brain's private lists, is
            // the Brain's only.
            "get_security_settings",
            "set_security_settings",
            "reveal_private_answers",
            // Connection settings — settings window only
            "get_api_settings",
            "set_api_settings",
            // Settings' "Show the token for my phone". Settings window only.
            "reveal_pairing_token",
            // Settings' "Second graphics card": read what was found and the
            // switches, and turn ONE switch on or off. ON only raises an
            // approval card. Settings window only.
            // Settings' "What this backend supports": the capability NAMES
            // GET /api/version reports, as the phone lists them. Read only.
            // Settings window only.
            "get_backend_capabilities",
            "get_second_card",
            "set_second_card",
            // Moving one of the second card's own switches onto a third,
            // capable graphics card, or moving it back off (2026-09-28).
            // Its own command (the wire shape differs: "assign", not
            // "enabled"); read is folded into get_second_card's own
            // answer (status()'s "third" key). Settings window only.
            "set_third_card",
            // "Everyday chat runs on" (2026-10-05): pin everyday chat to one
            // graphics card, or go back to leaving it to Ollama. Its own
            // command (the wire shape differs: "action" and "card", not
            // "enabled"), and pinning raises its own approval card
            // (chat_card_pin); read is folded into get_second_card's own
            // answer (status()'s "chat_card" key). Settings window only.
            "set_chat_card",
            // "When to suggest the bigger model" (2026-09-27): no approval
            // card either way, folded into the same Settings section. read
            // is folded into get_second_card's own answer.
            "set_second_card_suggest",
            // Settings' "Big model (slow)" (backend/big-model.patch): read
            // what was found and the three switches, and turn ONE switch on
            // or off. ON only raises an approval card. Settings window only.
            "get_big_model",
            "set_big_model",
            // Settings' "Hardware and models" (backend/hardware.patch): the
            // cards and the three setups; choose one (changes nothing by
            // itself); ask for ONE step of it, read from the backend's own
            // answer (each step is its own approval card); measure.
            // Settings window only.
            "get_hardware",
            "apply_hardware",
            "hardware_step",
            "measure_hardware",
            // "PC help" (JARVIS-API section 84): five plain answers about
            // this PC, read-only. Settings window only.
            "get_pc_help",
            "get_tutorials",
            "mark_tutorial",
            "get_faq",
            // Settings' "Web search" (backend/web-search.patch): the five
            // providers and their "why" lines, ONE change at a time (turning
            // "Ask before every web search" off raises a card on the PC), a
            // test search, and the Exa / Tavily / Brave key written straight into
            // Credential Manager on this PC - never sent over HTTP, never
            // shown again. Settings window only.
            "get_web_search",
            "set_web_search",
            "test_web_search",
            "save_search_key",
            "forget_search_key",
            // Settings' "Accounts" (ease-of-use audit row 15): the IMAP
            // username and password, the private calendar link, and the
            // Home Assistant token, written straight into Credential
            // Manager on this PC - never sent over HTTP, never shown again.
            // Settings window only.
            "get_account_secrets",
            "save_account_secret",
            "forget_account_secret",
            // Settings' "Chatbot API keys" (docs/ACCOUNT-KEYS-DESIGN.md
            // steps 1-2, 2026-10-06): the six API services the chatbot
            // driver can use (OpenAI, DeepSeek, Mistral, xAI, OpenRouter,
            // Groq), each key written straight into Credential Manager on
            // this PC under the name `jarvis_chatbot_api.KEY_TARGETS` builds
            // - never sent over HTTP, never to the phone, never shown again.
            // The names cannot drift from the Python side:
            // backend/test_chatbot_keys.py and token_store.rs's own
            // `the_six_chatbot_targets_are_the_python_sides_own` both fail
            // if they do. Settings window only - rule 3.
            "get_chatbot_api_keys",
            "save_chatbot_api_key",
            "forget_chatbot_api_key",
            // The monthly money limits and the price list of those same six
            // services (docs/ACCOUNT-KEYS-DESIGN.md steps 3-5, 2026-10-06):
            // a key with no limit leaves the service unusable, so the two
            // were built together. Raising a limit is a loosening - the
            // BACKEND raises ONE approval card (raise_api_limit) plus
            // Windows Hello and refuses it from another device; lowering
            // one, removing one and correcting a price need no card. Every
            // write is held on a stale link. Settings window only.
            "chatbot_money",
            "set_chatbot_money",
            // Settings' "Accounts", the ADDRESS half (backend/accounts.patch,
            // jarvis_accounts.py, 2026-10-06): the mail server, its port and
            // mailbox, the sending server, its port and how the email is
            // encrypted, the Home Assistant address and the calendar's CalDAV
            // address - read, and ONE address saved at a time over the PC's
            // own route, which keeps them in accounts.json beside
            // web-search.json. ADDRESSES ONLY: the four secrets above are
            // never carried by these two, and this side refuses any other
            // name before a request is even built. Settings window only.
            "get_account_addresses",
            "save_account_address",
            // Settings' "What Jarvis can reach" (backend/reach.patch): every
            // way Jarvis can reach something outside itself, written by the
            // PC from its settings. Read only. Settings window only.
            "get_reach",
            // The sun, the moon and the weather behind the animal faces
            // (backend/sky.patch, 2026-09-28): the settings and the weather
            // now (a read - Settings, the Widget and the floating face keep
            // what drawing needs in this computer's localStorage); ONE
            // change at a time (Settings only; Open-Meteo ON raises one
            // approval card on the PC; adding is held on a stale link).
            "get_sky",
            "set_sky",
            // "Animal options" (backend/animal.patch, 2026-09-28): "Keep the
            // animal still" and the behaviour switches, shared with the
            // phone - a read and ONE change at a time (Settings only; no card
            // either way; turning one on is held on a stale link); and, from
            // any window with jarvis-link, sending this computer's old Still
            // to the PC once, only if it was on.
            "get_animal",
            "set_animal",
            "migrate_animal_still",
            // Settings' "What asks first" (backend/asks-first.patch): every
            // action and whether it asks, in the PC's words; "Ask me first"
            // on ONE action of the short safe list (stricter at once, never
            // held; looser is one card plus Windows Hello on the PC, held on
            // a stale link); "Lights, plugs and fans without a card" (ON
            // is one card, held; OFF at once); and (2026-09-27) "Offer this
            // to the AI model" on the four reading tools (ON one card, held;
            // OFF at once). Settings window only.
            "get_asks_first",
            "set_asks_first",
            "set_lights_without_card",
            "set_tool_enabled",
            // Settings' "Prompt coach" (docs/PROMPT-COACH-DESIGN.md, the
            // owner's request of 2026-10-08; backend/prompt-coach.patch):
            // whether the coach is on, in the PC's own words (a read), and
            // the switch - at once in BOTH directions, no approval card
            // either way and never held on a stale link: it opens no way out
            // of the PC, takes no action and loosens no rule. Settings window
            // only.
            "get_prompt_coach",
            "set_prompt_coach",
            // Settings' "Sending email" (backend/email-send.patch): whether
            // sending is set up - from which address, through which server -
            // in the PC's own words. A read; never the password. Settings
            // window only. Each email is its own approval card, answered
            // through decide_approval like every other.
            "get_email_sending",
            // Settings' "Folders Jarvis may look in" (backend/documents.patch):
            // the list (a read); add ONE folder through the Windows folder
            // picker (one approval card on the PC, held on a stale link);
            // remove one (at once); bring in a Notion export through the
            // Windows file picker (held on a stale link). The pickers run in
            // Rust - the window gets only the chosen path. Settings window only.
            "get_folders",
            "add_folder",
            "remove_folder",
            "import_notion",
            // "Spending summaries" (backend/spending.patch; JARVIS-API section
            // 100; the owner's decision of 2026-09-30). The chat table: read
            // by id once the stream announced it (the Jarvis bar only; not
            // asked for at all while the private lists are hidden or App lock
            // has locked Jarvis). The Settings box: read the layouts and
            // categories, read the columns of a waiting file, and save or
            // forget a layout, save or reset the categories, ask for
            // suggestions. PC only on the backend; no card; writes held on a
            // stale link.
            "chat_table",
            "get_spending",
            "spending_profile_read",
            "spending_profile_save",
            "spending_profile_delete",
            "spending_categories_save",
            "spending_categories_reset",
            "spending_suggest",
            // Settings' "Backups" (backend/jarvis_backup.py, backup.patch;
            // the owner's decision of 2026-09-27): one locked backup file
            // with a recovery code shown once. Setting the folder reuses
            // the Windows folder picker above (one approval card, held on
            // a stale link); "Back up now" and listing need no card;
            // restoring is one card that always needs Windows Hello, held
            // on a stale link. Settings window only.
            "get_backup",
            "list_backups",
            "set_backup_folder",
            "backup_now",
            "preview_restore",
            "restore_backup",
            "delete_older_backups",
            // Settings' "Devices" (docs/PAIRING-DESIGN.md, phase 1): the
            // address for the QR code, start / watch / cancel a pairing
            // (the QR code drawn in Rust; the window hidden from screen
            // capture while a code shows), the device list, Remove ONE
            // device, and retire / bring back the old shared key. Settings
            // window only.
            "pair_phone_address",
            "pair_start",
            "pair_session",
            "pair_cancel",
            "devices_list",
            "devices_remove",
            "devices_shared",
            // Settings' "How Jarvis talks" (backend/manner.patch): warm and
            // brief, or plain. One change at a time, no approval card either
            // way (it changes wording only). Settings window only.
            "get_manner",
            "set_manner",
            // Humour, the same screen's second switch (the owner's decision,
            // 2026-09-27): off to start, no card either way.
            "set_humor",
            // Settings' "Thinking levels" (Section 5.5): per running model.
            // Settings window only.
            "get_thinking",
            "set_thinking",
            // The quickbar's error fix buttons ("Check the connection
            // settings", "Choose a model"): open Settings or the Brain,
            // nothing else (plain_errors.rs).
            "open_fix_place",
            // Settings' "Voice": what the PC's voice settings are (GET
            // /api/voice/status) - whether each microphone's voice print is
            // trained, the wake word, the stop word, Smart Turn. Read only.
            // Settings window only.
            "get_voice_status",
            // Settings' "Voice": the PC's "hey Jarvis" switch. OFF at once
            // (and this PC stops listening); ON only raises an approval card,
            // and is held while the event stream is stale. Settings only.
            "set_wake_word",
            // Settings' "Voice", the parts that record and change things
            // (voice_training.rs): record a sentence through this PC's
            // microphone and hold it in memory; train in rounds (finishing
            // raises ONE card); the strictness and private-answer settings
            // (loosening raises a card); the guided test; custom voices
            // (adding one and switching to one each raise a card; going back
            // to the built-in voice and deleting are immediate) and the
            // better voice (ON a card, OFF at once). Settings window only.
            "start_voice_sample",
            "voice_sample_level",
            "stop_voice_sample",
            "cancel_voice_sample",
            "discard_voice_samples",
            "send_voice_training",
            "cancel_voice_training",
            "measure_voice",
            "set_voice_setting",
            "check_voice_with_someone_else",
            "propose_voice_threshold",
            "get_custom_voices",
            "create_custom_voice",
            "set_active_voice",
            "delete_custom_voice",
            "set_better_voice",
            "set_voice_speed",
            "set_voice_speaker",
            "set_voice_face",
            "set_voice_animal",
            "reset_voice_animal",
            "try_voice_animal",
            "hear_voice_sample",
            "get_face_voice_offer",
            "answer_face_voice_offer",
            // Widget geometry and capture
            "get_appearance",
            "set_appearance",
            // The in-memory appearance, for windows that only draw it: no
            // network call and no broadcast, so safe inside a listener.
            "appearance_snapshot",
            "appearance_colours",
            "update_status",
            "check_for_update",
            "set_update_check_on_start",
            "install_update",
            // The other half of installing an update. It was in lib.rs's
            // generate_handler! and invoked by settings.js, but never here -
            // which is precisely the failure the comment at the top of this
            // file warns about: registered, reachable from nowhere. The
            // owner installed an update, pressed Restart, and got "not
            // allowed on window" while the new binary sat there unused.
            "restart_app",
            "get_hotkeys",
            "set_hotkeys",
            "reset_hotkeys",
            "hide_widget",
            "resize_desktop_widget",
            "set_widget_always_on_top",
            "save_widget_position",
            "get_widget_prefs",
            // The floating face (Settings -> Appearance): whether it is on,
            // and turning it on or off. Settings window only - the window
            // itself has no button to call either from.
            "get_floating",
            "set_floating",
            // Bug audit 2026-09-27, desktop-rust finding #2: crash_notes and
            // find_python were added to generate_handler! in lib.rs but
            // never added here, so no permission file ever existed for
            // either one - the crash-notes list (More options) and "Find it
            // for me" (the Python search) refused every call at the ACL,
            // not a bug in either command itself.
            "crash_notes",
            "find_python",
            // Same finding: get_tool_updates, check_tool_updates and
            // chat_sources are also in generate_handler! but not here. These
            // three were not a break like crash_notes/find_python - someone
            // had already hand-written matching permission files in
            // permissions/autogenerated/ to work around it - but a hand-kept
            // copy of a "DO NOT EDIT!" generated file is exactly the kind of
            // drift that goes stale silently. Adding them here makes the
            // build regenerate those files itself, like every other command.
            "get_tool_updates",
            "check_tool_updates",
            "chat_sources",
            "prefill_quickbar",
            "capture_note",
            // How a filed note ended: waiting for approval, filed, or not.
            "capture_note_status",
            // Which note apps this PC is set up for - names only.
            "note_targets",
            // The wiki builder (backend/wiki.patch): read the list, add one
            // document (raises one approval card), follow that job, and
            // open the Jarvis Wiki folder. Brain window only.
            "wiki_status",
            "wiki_ingest",
            "wiki_ingest_status",
            "wiki_open_folder",
            // Deep questions (backend/big-model.patch): read the recent ones
            // and their answers, and ask one. No card per question - the
            // switch was approved - and asking is held on a stale link.
            // Brain window only.
            "get_deep",
            "ask_deep",
            // "Coming up" (backend/schedule.patch): timers, alarms,
            // reminders and the to-do list - a read, ONE job per change
            // (pause, resume, delete, done, add time), and one new to-do
            // item. No card; every change held on a stale link. Brain only.
            // And the standby schedule: one card on the PC (it repeats).
            "brain_schedule",
            "brain_schedule_act",
            "brain_schedule_add_todo",
            "brain_schedule_add_standby",
            // One Today card (2026-09-28, jarvis_today.py): no card, held
            // on a stale link. Brain only.
            "brain_schedule_add_today",
            // "Widgets you describe" (brain/widgets.rs, JARVIS-API.md section
            // 87): the Brain manages them; the widget window draws one and
            // presses ONE of the five tile actions.
            "brain_widgets",
            "brain_widgets_draft",
            "brain_widgets_add",
            "brain_widgets_discard",
            "brain_widgets_delete",
            "widget_board",
            "widget_board_action",
            // A NAMED list ("shopping") cleared after the page's "are you
            // sure?", with the count it showed (2026-09-25).
            "brain_schedule_clear_list",
            // Goals (backend/goals.patch, JARVIS-API.md section 59): a
            // read, one new draft, accepting it (the backend's own one
            // approval card, through jarvis_schedule.py, never a card of
            // this app's own making), one step done or not, and Stop
            // tracking. No card raised here directly; every write held on
            // a stale link. Brain only.
            "brain_goals",
            "brain_goals_create",
            "brain_goals_accept",
            "brain_goals_step",
            "brain_goals_stop",
            // Activity heatmap and balance chart (docs/GOALS-PROGRESS-DESIGN.md
            // part C, JARVIS-API.md section 105): read the days, read the
            // balance areas, save the picked areas. No card; the save held on a
            // stale link; the picture taken out while the private lists are
            // hidden or App lock is on. Brain only.
            "brain_progress_activity",
            "brain_progress_balance",
            "brain_progress_balance_save",
            // Quiz me on a text (docs/STUDY-FROM-TEXT-DESIGN.md section 11,
            // JARVIS-API.md section 98): write questions for a pasted text,
            // read the quiz again, check one answer, finish, stop. No card,
            // nothing saved; every write held on a stale link. Brain only.
            "brain_quiz_start",
            "brain_quiz_get",
            "brain_quiz_answer",
            "brain_quiz_finish",
            "brain_quiz_stop",
            "brain_quiz_cloud_info",
            "brain_quiz_cloud_start",
            "brain_quiz_cloud_get",
            "brain_quiz_cloud_cancel",
            // Quiz me on a YouTube video (docs/STUDY-FROM-TEXT-DESIGN.md
            // section 14, JARVIS-API.md section 112): ask whether the PC has it,
            // send the pasted link (ONE approval card on the PC), poll the
            // request, cancel it while its card waits. The link is sent once
            // and kept nowhere; the start held on a stale link, cancel never.
            // Brain only.
            "brain_youtube_info",
            "brain_youtube_start",
            "brain_youtube_get",
            "brain_youtube_cancel",
            // Retirement what-if (docs/FINANCE-DESIGN.md part B, JARVIS-API.md
            // section 103): read the form, play out the typed numbers. No card,
            // nothing saved; the run held on a stale link; nothing asked or sent
            // while the private lists are hidden or App lock is on. Brain only.
            "brain_retirement_defaults",
            "brain_retirement_run",
            // Review decks (JARVIS-API section 102): the owner's kept questions,
            // asked again on a schedule the PC works out. No card; every write
            // held on a stale link; words hidden with the private lists. Brain only.
            "brain_decks",
            "brain_decks_create",
            "brain_decks_settings",
            "brain_decks_act",
            "brain_decks_cards",
            "brain_decks_card_act",
            "brain_review",
            "brain_review_reveal",
            "brain_review_rate",
            "brain_review_more",
            // Topic controls (docs/TOPIC-CONTROLS-DESIGN.md; JARVIS-API.md
            // section 107; the owner's request of 2026-09-30): the topics and
            // their four modes, one change to the list, one mode change, filing
            // facts, the "local model may help sort" switch, the preview of a
            // change, and the two fact lists (Check these, Show them). The PC
            // raises the only cards; every write is held on a stale link; names
            // and both fact lists are hidden with the private lists. Brain only.
            "brain_topics",
            "brain_topics_edit",
            "brain_topics_mode",
            "brain_topics_file",
            "brain_topics_settings",
            "brain_topics_preview",
            "brain_topics_review",
            "brain_topics_hidden",
            // "Photo to reminder" (photo-reminder.patch, 2026-09-28): the
            // dates in a picture, read on the PC and PROPOSED (a scan sets
            // nothing up), and the owner's tap adding ONE reminder - no
            // card, held on a stale link. The Jarvis bar and the Brain.
            "photo_scan",
            "photo_add_reminder",
            // "Bring in chats from ChatGPT, Claude, Gemini or DeepSeek"
            // (history-import.patch, 2026-09-28): where a run is (a read),
            // the Windows "Open" dialog then start (held on a stale link;
            // it only PROPOSES - every fact waits for its own yes), and
            // cancel (never held). Brain only.
            "history_import_status",
            "history_import_start",
            "history_import_cancel",
            // Projects (backend/projects.patch; JARVIS-API section 88; the
            // owner's decision of 2026-09-28): read the projects, ONE change
            // named by an action from a fixed list (the PC raises the only
            // cards: Shareable ON, and taking off a mark Jarvis made), and a
            // coding project's folder by the Windows picker. Every change
            // held on a stale link except Shareable OFF. Brain only.
            "projects_read",
            "projects_write",
            "projects_choose_folder",
            // "Forget a time frame" (backend/forget-range.patch; JARVIS-API
            // section 64; the owner's decision of 2026-09-28): read the
            // status or the list for some days (hidden in Rust with the
            // private lists), and ONE of two things - "Forget these" (the
            // PC raises ONE card; held on a stale link, refused while the
            // list is hidden) or Undo (no card, never held). Brain only.
            "forget_range_read",
            "forget_range_write",
            // "Inbox tidy by voice" (backend/inbox-tidy.patch; JARVIS-API
            // section 95; the owner's decision of 2026-09-28): the Undo
            // strip under the Jarvis bar's input. Read whether a tidy is
            // open to Undo (counts and the PC's words, taken out in Rust
            // while Jarvis is locked or the lists are hidden) and Undo it -
            // one tap, no card, held on a stale link and while the words
            // are hidden. The tidy itself is an ordinary approval card.
            "inbox_tidy_read",
            "inbox_tidy_undo",
            // The picture of a filled-in web form, shown on the "Jarvis wants
            // to submit this form" card in the Jarvis bar (docs/FORM-REVIEW-
            // DESIGN.md, 2026-09-30). A read; nothing when App lock is on.
            "form_review_picture",
            // Focus sessions (backend/focus.patch): read one, start one
            // (Brain only, held on a stale link), and ONE thing to it -
            // pause, resume, +10 minutes, stop, and the widget's Lock on
            // (resume, extend and lock held on a stale link). No card.
            "focus_status",
            "focus_start",
            "focus_act",
            // "Talk to a chatbot for me" (backend/chatbot-routes.patch): read the
            // conversation (a read; the words taken out in Rust while the
            // private lists are hidden), start one (ONE card on the PC; held
            // on a stale link), new limits (a NEW card; held), stop (never
            // held), and pause/resume through /api/task/* (resume held - it
            // raises its own card). "Ask several and compare": start one (ONE
            // card listing every chatbot; held) and stop it (never held).
            // Brain only.
            "chatbot_status",
            "chatbot_start",
            "chatbot_limits",
            "chatbot_stop",
            "chatbot_pause",
            "chatbot_resume",
            "chatbot_compare_start",
            "chatbot_compare_stop",
            // "Chat with customer support for me" (jarvis_support.py through
            // jarvis_chatbot_routes.py): read the chat (a read; the owner's
            // words taken out in Rust while the private lists are hidden),
            // start one (ONE details card on the PC; held on a stale link),
            // stop and take over (never held), answer a waiting offer with
            // Decline or "Say something else" (held) or Take over (not), and
            // export the transcript to a file the owner picks. Resume is
            // chatbot_resume. Brain only.
            "support_status",
            "support_start",
            "support_stop",
            "support_takeover",
            "support_answer",
            "support_export",
            // The morning briefing (backend/briefing.patch): read the latest
            // one and "Brief me now" (a read, not held on a stale link) -
            // Brain only; and its setup - read it, set one up that repeats
            // (the scheduler's ONE card; held on a stale link), stop ONE,
            // and "Show who new emails are from" (ON is ONE card on the PC,
            // held on a stale link; OFF at once) - Settings only.
            "brain_briefing",
            "brain_briefing_now",
            "get_briefing_setup",
            "set_briefing",
            "stop_briefing",
            "set_briefing_senders",
            // Quickbar
            "hide_quickbar",
            "resize_quickbar",
            "set_quickbar_pinned",
            "write_clipboard",
            "write_clipboard_private",
            "open_external_url",
            // Diagnostics and startup. Settings window only: the log path is
            // a filesystem path and the startup entry is a registry write,
            // and neither belongs to a page that renders chat.
            "get_log_info",
            "open_log_folder",
            "get_autostart",
            "set_autostart",
            // Shared
            "check_server_health",
            // Push-to-talk voice: real microphone capture, quickbar only —
            // see permissions/surfaces.toml's "voice" set and
            // src-tauri/src/voice.rs's own module docstring.
            "start_voice_capture",
            "stop_voice_capture",
            "cancel_voice_capture",
            "start_automatic_listening",
            "stop_automatic_listening",
            "speak_reply",
            // Jarvis Live (live.rs): read the session, start it (no card;
            // held on a stale link and under App lock), stop it (never
            // held), more time / carry on, mute, and hold the microphone
            // closed while the bar shows a card. The Jarvis bar's and the
            // Live badge's; neither records or reads any words.
            "live_status",
            "live_start",
            "live_stop",
            "live_act",
            "live_mute",
            "live_hold",
            // "Look at this" and "Watch with me" (look.rs): read the session
            // (fixed words and minutes, never a word from the screen), one
            // verb on it (start - no card, held on a stale link and under App
            // lock; stop and drop never held), and the Never look at list
            // (add at once, remove is ONE card). The Jarvis bar and the
            // Watch badge hold the first two; only Settings holds the list.
            "screen_status",
            "screen_watch",
            "screen_never",
            // Picture mode's switch (look.rs): read it, turn it on (ONE card
            // on the PC) or off. Settings only.
            "screen_picture",
            // The headless browser's switch and default browser (browser_engine.rs):
            // read it, turn it on (ONE card on the PC) or off, pick the default.
            // Settings only.
            "browser_engine",
            // Interrupting by talking and "One moment." (voice_flow.rs):
            // ask for one utterance to be checked, read the status's `flow`
            // block, fetch the clip. Quickbar only; none records anything.
            "judge_barge_in",
            "get_voice_flow",
            "get_voice_moment",
            // The HUD's mic button. Shows the quickbar with push-to-talk
            // ready; records nothing. The one command the HUD holds.
            "summon_push_to_talk",
            // The HUD's "Open the Jarvis bar" button, beside that window's
            // own chat box (reversed 2026-10-06). Sends nothing. The HUD only.
            "hud_open_bar",
            // Lip-sync: hands the Jarvis bar's mouth track and playback
            // clock to every window's face (voice.rs `face_voice`). Checked
            // shape only; no words, no audio. Quickbar only.
            "face_voice",
            // Before a screen capture is sent: can the local model see it?
            // Asks the Jarvis server and loopback Ollama; quickbar only.
            "local_model_vision",
        ]));

    // Generates `src-tauri/gen/schemas/*`, embeds the Windows resource and
    // manifest, and makes `tauri::generate_context!()` resolvable.
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
