fn main() {
    // Declaring an app manifest is what turns the ACL on for this app's OWN
    // commands. Without it `has_app_manifest()` is false and Tauri's permission
    // check short-circuits: every `#[tauri::command]` is callable from every
    // window regardless of what the capability files say. The capability file
    // used to describe itself as a "least-privilege IPC surface" while gating
    // nothing app-defined, which is worse than having no file at all.
    //
    // `commands` autogenerates an `allow-<kebab-name>` and `deny-<kebab-name>`
    // permission per entry into `permissions/autogenerated/`. The sets in
    // `permissions/` group those per surface, and `capabilities/*.json` hands
    // each window only its own set.
    //
    // Anything added to `generate_handler!` in lib.rs must be added here too,
    // or it is reachable from nowhere and the failure is a runtime "not allowed
    // on window" rather than a compile error.
    let attributes =
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            // Chat
            "stream_chat",
            "cancel_chat",
            "set_route_lane",
            // The fanned-out event stream
            "get_link_state",
            "get_pending_approvals",
            "refresh_link",
            "decide_approval",
            // The interruption budget and the daily brief. Reads and two
            // writes; the tray calls the same functions in-process, so it
            // needs no grant.
            "get_digest",
            "mark_digest_seen",
            "set_attention_muted",
            // The Brain. One fan-out read over a fixed allowlist, then one
            // command per power it can exercise.
            "brain_read",
            "brain_revert_undo",
            "brain_cancel_job",
            "brain_cancel_hold",
            "brain_watch_add",
            "brain_watch_remove",
            "brain_watch_seen",
            "brain_remove_skill",
            "brain_model",
            // Memory: one decision per fact, and the switch that governs
            // whether facts are proposed at all.
            "brain_memory_decide",
            "brain_memory_forget",
            "brain_memory_edit",
            "brain_memory_learning",
            "brain_memory_export",
            // Backend supervision — settings window only
            "supervisor_status",
            "set_supervision",
            "start_backend",
            "stop_backend",
            // The theme. Readable everywhere, writable from the two windows
            // that offer a picker.
            "get_theme",
            "set_theme",
            // Connection settings — settings window only
            "get_api_settings",
            "set_api_settings",
            // Widget geometry and capture
            "get_appearance",
            "set_appearance",
            "update_status",
            "check_for_update",
            "set_update_check_on_start",
            "install_update",
            "get_hotkeys",
            "set_hotkeys",
            "reset_hotkeys",
            "hide_widget",
            "resize_desktop_widget",
            "set_widget_always_on_top",
            "save_widget_position",
            "get_widget_prefs",
            "prefill_quickbar",
            "capture_note",
            // Quickbar
            "hide_quickbar",
            "resize_quickbar",
            "set_quickbar_pinned",
            "write_clipboard",
            "open_external_url",
            // Shared
            "check_server_health",
        ]));

    // Generates `src-tauri/gen/schemas/*`, embeds the Windows resource and
    // manifest, and makes `tauri::generate_context!()` resolvable.
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
