package com.jarvis.client.net

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * "Everything Jarvis can do" (docs/FEATURES-LIST-DESIGN.md, 2026-10-08; the
 * owner's request of the same day: *"is there a button where I can find the
 * entire feature set of Jarvis on my desktop or android phone?"*).
 *
 * The list is NOT here. It is one file - `features/features.json` in the
 * project - copied verbatim into this app's assets as `features.json` and read
 * by [FeaturesScreen]. `tools/check_feature_list.py` and
 * `backend/test_feature_list.py` prove the copies are byte-identical and that
 * every route section and menu id the two apps draw is either named by an
 * entry or in that checker's INTERNAL allow-list, so this list cannot quietly
 * fall behind the app.
 *
 * NOTHING HERE TOUCHES THE NETWORK OR THE PC. The text is static, written by
 * hand, and never generated by the model at run time; the page reads only, on
 * both apps (the design note's "Deliberately not in this"). That is also why
 * there is no card, no stale-link hold and no JarvisRuntime call anywhere in
 * this file - which is what makes [readOf] and [rows] pure enough to test on
 * the JVM, with no Android and no emulator.
 */
object Features {

    /** The asset the phone reads. The desktop page fetches its own copy. */
    const val ASSET = "features.json"

    /**
     * The nine groups, in the order the file is written in and both apps draw
     * them. [rows] keeps this order whatever order the file happens to be in,
     * and `check_feature_list.py` fails if the file's own order drifts from it.
     */
    val GROUPS = listOf(
        "Talking",
        "Memory",
        "Screen and pictures",
        "Notes and files",
        "Money and health",
        "Home",
        "Phone",
        "The PC itself",
        "Safety",
    )

    /** Which app a feature belongs to; `both` is most of them. */
    const val DESKTOP = "desktop"
    const val PHONE = "phone"
    const val BOTH = "both"

    /** Where this app's own features sit in a group: its own first, the other's marked. */
    const val THIS_APP = PHONE

    /** The words the page shows when the asset cannot be read, in plain language. */
    const val CANNOT_READ = "The feature list could not be read from this copy of the app."
    const val READING = "Reading the list…"

    /** The row on the Brain that opens the screen, and its screen's own words. */
    const val HEADING = "Everything Jarvis can do"
    const val INTRO =
        "Every feature Jarvis has, in plain words, in nine groups: what it does, how to " +
            "reach it, whether it asks first, and one real limit. Both apps show the same " +
            "list, so the phone and the PC cannot disagree about what a feature does. This " +
            "screen only reads - nothing here changes anything."
    const val OPEN = "See every feature"

    /** One feature, exactly the fields the design note fixes. */
    data class Entry(
        val id: String,
        val group: String,
        val title: String,
        val what: String,
        val where: String,
        val asks: String,
        /** A real limit, or empty - an empty one draws no limit line at all. */
        val limit: String,
        /** [DESKTOP], [PHONE] or [BOTH]. */
        val surface: String,
        /** The route section or menu ids this entry accounts for; never shown. */
        val covers: List<String>,
    ) {
        /**
         * The marker beside a feature that belongs to the OTHER app, and only
         * that one. A feature of this app's own - or one both apps have, which
         * is most of them - carries no marker at all: it is the normal case,
         * and labelling every row would say nothing.
         */
        val otherAppTag: String
            get() = when {
                surface == THIS_APP || surface == BOTH -> ""
                surface == DESKTOP -> "on your PC"
                surface == PHONE -> "on your phone"
                else -> ""
            }
    }

    /**
     * One row the screen draws, in order: a group's heading, then its features.
     * A flat list rather than a nested one so the screen's row count and this
     * list's are the same number, which is what `FeaturesListTest` holds to the
     * file's entry count.
     */
    sealed interface Row {
        data class Heading(val title: String, val count: Int) : Row
        data class Feature(val entry: Entry) : Row
    }

    /**
     * Reads the list. Strict on purpose: a missing `what`, `where` or `asks`
     * throws rather than drawing a row with a hole in it, because the whole
     * point of the page is that every feature answers those three questions.
     */
    fun readOf(text: String): List<Entry> {
        val array = JarvisJson.parseToJsonElement(text).jsonArray
        return array.map { element ->
            val o = element.jsonObject
            Entry(
                id = o.str("id"),
                group = o.str("group"),
                title = o.str("title"),
                what = o.str("what"),
                where = o.str("where"),
                asks = o.str("asks"),
                limit = o.opt("limit"),
                surface = o.opt("surface").ifEmpty { BOTH },
                covers = (o["covers"]?.jsonArray ?: emptyList()).mapNotNull { it.jsonPrimitive.contentOrNull },
            )
        }
    }

    /**
     * The rows the screen draws: the nine groups in their fixed order, this
     * app's own features first inside each group, the other app's marked by
     * [Entry.otherAppTag]. Nothing is ever dropped - an entry in a group this
     * object does not know lands in a last group called "Other" - so the row
     * count always equals the file's.
     */
    fun rows(entries: List<Entry>): List<Row> {
        val known = GROUPS.toSet()
        val order = GROUPS + entries.map { it.group }.filter { it !in known }.distinct()
        val out = mutableListOf<Row>()
        for (group in order) {
            // The file's own order, with this app's features moved to the front
            // (the design note's "each app shows its own surface's features
            // first"), which is a stable sort: equal rows keep their places.
            val mine = entries.filter { it.group == group }
            val sorted = mine.filter { it.surface != otherApp() } + mine.filter { it.surface == otherApp() }
            if (sorted.isEmpty()) continue
            out += Row.Heading(group, sorted.size)
            out += sorted.map { Row.Feature(it) }
        }
        return out
    }

    /** The surface that is not this app, for the "own features first" sort. */
    private fun otherApp(): String = if (THIS_APP == PHONE) DESKTOP else PHONE

    /** The number of feature rows [rows] draws - what the screen actually shows. */
    fun featureCount(rows: List<Row>): Int = rows.count { it is Row.Feature }

    private fun JsonObject.str(key: String): String {
        val got = opt(key)
        require(got.isNotEmpty()) { "features.json: `$key` is missing or empty" }
        return got
    }

    private fun JsonObject.opt(key: String): String =
        (this[key] as? JsonPrimitive)?.contentOrNull.orEmpty()
}
