package com.jarvis.client.net

// GENERATED by tools/gen_settings_cases.py from backend/jarvis_settings_registry.py
// - do not edit by hand. Run `python3 tools/gen_settings_cases.py` after changing
// SETTINGS_ROWS; CI runs `--check`.
// SettingsCatalogTest holds this file to src/test/resources/contract/settings-cases.json.

/**
 * The settings switches on the phone's Settings screen whose words the PHONE owns.
 *
 * ONLY TWO ROWS ARE HERE, and that is the design (handoff section 3.3, "words
 * only, and only where the phone owns them"). For a row the PC owns - the
 * prompt coach is the one to remember - the phone must keep READING THE PC at
 * read time; swapping it for a string from here would fail
 * tools/check_parity.py rule 2, because /api/prompt/coach is classified `ported`
 * and the phone has to still call it.
 *
 * This is deliberately NOT a description of the Settings screen: SettingsScreen.kt's
 * LazyColumn is hand-written and stays that way. Use [row] for a row's own words,
 * and [ROWS]/[byPhoneKey] in a test for its key, section, order and apps.
 */
object SettingsCatalog {
    data class Row(
        val id: String,
        val setting: String?,
        val owner: String,
        val section: String,
        val order: Int,
        val label: String,
        val detail: String,
        val labelSpan: String?,
        val detailSpan: String?,
        /** True when the PC sends this row's visible words: the words above are a fallback. */
        val fallback: Boolean,
        /** False for the one toggle that is not a setting at all (the spending accept-all row). */
        val settingRow: Boolean,
        /** SettingsScreen.kt's own `item(key = ...)`, for the rows the phone has. */
        val phoneKey: String?,
        /** For a phone row, the Kotlin its words were copied from - by eye, not by a check. */
        val source: String?,
    )

    /** Shown when a row is missing - never silently blank. */
    const val MISSING = "This switch is not in your phone's settings list."

    val ROWS: List<Row> = listOf(
        Row("follow-system", null, "desktop", "appearance-card", 1, "Match Windows light or dark mode", "Daylight when Windows is light, your dark theme when it is dark.\nA switch waits until Jarvis is idle, never mid-approval.\n", null, "follow-system-detail", false, true, null, null),
        Row("floating-enabled", null, "desktop", "appearance-card", 2, "Floating face", "A small window, always on top, that shows only Jarvis's face -\nno text box. Drag it anywhere. Say \"open a chat\", or press\nAlt+Space, to bring up the real Jarvis bar. Alt+Shift+F shows\nor hides this face (see Shortcuts below to change either key).\n", null, "floating-detail", false, true, null, null),
        Row("sky-show", null, "desktop", "animal-options", 3, "Show the sun and moon behind the face", "", "sky-show-label", "sky-show-detail", true, true, null, null),
        Row("face-auto", null, "desktop", "animal-options", 4, "Auto adjust", "Picks quality and frame rate for this computer, and steps down\nif the face runs slow. On a capable graphics chip an animal can\ngo up to Maximum.\n", null, "", false, true, null, null),
        Row("voice-one-moment", null, "desktop", "voice", 5, "Say \"One moment\" if I'm kept waiting", "", null, "voice-one-moment-detail", true, true, null, null),
        Row("voice-heard-sound", null, "desktop", "voice", 6, "Play a short sound when I finish speaking", "", null, "voice-heard-sound-detail", true, true, null, null),
        Row("mn-humor", null, "desktop", "manner", 7, "Occasional light humour in answers", "", null, "mn-humor-detail", true, true, null, null),
        Row("coach-enabled", "prompt_coach", "desktop", "prompt-coach", 8, "Prompt coach", "", "coach-enabled-label", "coach-enabled-detail", true, true, null, null),
        Row("br-senders", "briefing_senders", "desktop", "briefing-settings", 9, "Show who new emails are from", "The briefing lists who your newest unread emails are from (up to 5), next to how many there are. Off: the number only. Turning it on shows you an approval card first; turning it off happens at once.", null, "", false, true, null, null),
        Row("notif-alarms", null, "desktop", "notifications", 10, "Alarms and urgent alerts", "Alarms and urgent \"tell me when\" alerts ring until dismissed. They break through Windows Focus Assist so you do not miss them.", null, "", false, true, null, null),
        Row("notif-reminders", null, "desktop", "notifications", 11, "Reminders, timers and to-dos", "Timers, reminders and to-do items chime once when they are due and offer Snooze.", null, "", false, true, null, null),
        Row("notif-briefing", null, "desktop", "notifications", 12, "Morning briefing", "Tells you when your morning briefing is ready to read in the Brain.", null, "", false, true, null, null),
        Row("notif-handoff", null, "desktop", "notifications", 13, "Website needs you (Solve it here)", "Tells you when a website or support chat pauses at a captcha or sign-in page.", null, "", false, true, null, null),
        Row("notif-quiet-enabled", null, "desktop", "notifications", 14, "Turn on quiet hours", "", null, null, false, true, null, null),
        Row("hud-open-bar-show", null, "desktop", "hud-window", 15, "Show the \"Open the Jarvis bar\" button", "On: the button sits beside the big window's own chat box, and\nopens the Jarvis bar ready to type. Off: the button is not drawn\nthere. The chat box, its Send and the microphone button are\nunchanged, and Alt+Space still opens the Jarvis bar.\n", null, "hud-open-bar-detail", false, true, null, null),
        Row("sec-app-lock", null, "desktop", "security", 16, "App lock", "", null, "sec-app-lock-detail", true, true, null, null),
        Row("sec-private", null, "desktop", "security", 17, "Windows Hello for memory lists and chat history", "", null, "sec-private-detail", true, true, null, null),
        Row("cv-face-switch", null, "desktop", "voices", 18, "Voice follows the face", "", "cv-face-title", "cv-face-detail", true, true, null, null),
        Row("cv-better-switch", null, "desktop", "voices", 19, "Make custom voices on the second graphics card", "A more natural copy of the voice. Turning it on shows you an approval card first; turning it off happens at once.", null, "", false, true, null, null),
        Row("ws-enabled", "web_search", "desktop", "web-search", 20, "Web search", "", "ws-enabled-label", "ws-enabled-detail", true, true, null, null),
        Row("ws-ask", "ask_before_every_search", "desktop", "web-search", 21, "Ask before every web search", "", "ws-ask-label", "ws-ask-detail", true, true, null, null),
        Row("spd-accept", null, "desktop", "spending", 22, "", "", "spd-accept-text", null, false, false, null, null),
        Row("sp-switch", "screen_picture", "desktop", "screen-look", 23, "Turn on Picture mode (slow)", "", "sp-switch-label", null, false, true, null, null),
        Row("be-switch", "headless_browser", "desktop", "browser-engine", 24, "Let Jarvis use the windowless browser (Obscura)", "", "be-switch-label", null, false, true, null, null),
        Row("supervise", null, "desktop", "start-jarvis", 25, "Let Jarvis Desktop start and stop Jarvis", "", null, null, false, true, null, null),
        Row("autostart", null, "desktop", "more-options", 26, "Start Jarvis Desktop when Windows starts", "", null, null, false, true, null, null),
        Row("watch-notify", "smartwatch_notifications", "phone", "watch-notify", 1, "Show notifications on a compatible watch", "Off by default: every notification (approval cards, timers, reminders, \"tell me when\") stays on this phone only.", null, null, false, true, "watch-notify", "WatchNotifyPlate.kt:87-90"),
        Row("phone-notify", "phone_notifications", "phone", "phone-notify", 2, "Let your phone read notifications", "Off by default. Jarvis never sees a phone notification unless you turn this on AND add at least one app below.", null, null, false, true, "phone-notify", "PhoneNotificationsPlate.kt:107-110"),
    )

    private val BY_ID: Map<String, Row> = ROWS.associateBy { it.id }

    /** The rows that are really settings switches (not the spending accept-all row). */
    val SETTING_ROWS: List<Row> = ROWS.filter { it.settingRow }

    /** The rows whose visible words the PC sends: the words above are a fallback only. */
    val FALLBACK_ROWS: List<Row> = ROWS.filter { it.fallback }

    /** The row with this id, or null - callers keep their own fallback words. */
    fun row(id: String): Row? = BY_ID[id]

    /** The row the phone's own Settings screen shows under this key. */
    fun byPhoneKey(key: String): Row? = ROWS.firstOrNull { it.phoneKey == key }
}
