"""Writes index.html (landscape, 30 s) and vertical.html (upright, 15 s).

Both cuts share the station markup, so it lives here once. Edit this file,
then run:  python3 tools/build_html.py

Every word on screen is listed in ../brag-plan.md next to the file that
proves it. The screens in assets/ui/ are the real desktop app (see
../composition-brief.md for how they were made).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TIMING = {k: json.loads((ROOT / "assets" / f"{k}.json").read_text()) for k in ("timing", "timing-vertical")}

HEAD = '''<!doctype html>
<html lang="en">
  <!-- Generated by tools/build_html.py: edit that, not this. -->
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={w}, height={h}" />
    <title>{title}</title>
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/{timing}.js"></script>
    <script src="assets/{audio}.js"></script>
    <script src="assets/reactor.js" charset="utf-8"></script>
    <link rel="stylesheet" href="assets/day.css" />
{extra}  </head>
  <body class="{cls}">
    <div id="root" data-composition-id="{cid}" data-width="{w}" data-height="{h}" data-start="0" data-duration="{dur}">
      <div id="stage">
        <div id="sky" class="layer"></div>
        <div id="halo"></div>
        <div id="ribbon-line"></div>
        <div id="ribbon"></div>
        <div id="world">
'''

# ---------------------------------------------------------------- stations
# Each station is laid out in its own frame of the strip; `pos` is where it
# sits (left for landscape, top for upright), filled in per cut.

def col(part, hour, say=None, reply=None, sid="", later=False):
    s = f'''            <div class="col">
              <div class="part">{part}</div>
              <div class="hour">{hour}</div>
'''
    if say:
        s += f'''              <div class="who" id="{sid}-you">You</div>
              <div class="say" id="{sid}-say">{say}</div>
'''
    if later:
        s += f'''              <div class="who later" id="later">A minute later</div>
'''
    if reply:
        s += f'''              <div class="who" id="{sid}-jw">Jarvis</div>
              <div class="reply" id="{sid}-reply">{reply}</div>
'''
    return s + "            </div>\n"


def claim(sid, html):
    return f'            <div class="claim" id="{sid}-claim">{html}</div>\n'


def shot(sid, imgs, extra="", where=""):
    s = f'            <div class="shot" id="{sid}-shot">\n'
    if where:
        s += f'              <div class="where">{where}</div>\n'
    for i, src in imgs:
        s += f'              <img id="{i}" src="assets/ui/{src}" alt="" />\n'
    return s + extra + "            </div>\n"


def station(sid, pos, axis, body, night=False):
    side = "top" if axis == "y" else "left"
    return (f'          <section class="station{" night" if night else ""}" id="st-{sid}" style="{side}: {pos}px">\n'
            + body + "          </section>\n")


# Drawn Android phone, unlocked (a locked phone shows only "Jarvis: something
# you asked to be told about happened."). Every word is jarvis-client's own:
# Schedule.kt TELLME_TITLE "Tell me when", the backend's "An email from Alex
# arrived." and ScheduleNotifier.kt's "Stop" action on the "Alarms and urgent
# alerts" channel.
PHONE = '''              <div class="phone" id="phone">
                <div class="ringw" id="ring-a"></div><div class="ringw" id="ring-b"></div>
                <div class="scr"><div class="sb"><span>15:47</span><i class="cam"></i><span>▾ ▮</span></div>
                  <div class="notif" id="notif"><div class="app"><b>Jarvis</b> · Alarms and urgent alerts</div>
                    <div class="ti">Tell me when</div><div class="tx">An email from Alex arrived.</div><div class="act">Stop</div></div>
                </div>
              </div>
'''

# Drawn Android phone at night: jarvis-client's Mind screen (BrainScreen.kt
# TopBar "Mind", subtitle "State of mind"), its "Doing" plate with the Power
# field and the Active / Quiet / Standby buttons (BrainScreen.kt:322-335).
# The button for the current mode is disabled. The field changes when the
# desktop reports the new mode, so it flips a moment after the tap.
PHONE_NIGHT = '''              <div class="phone night" id="phone-n">
                <div class="scr"><div class="sb"><span>23:00</span><i class="cam"></i><span>▾ ▮</span></div>
                  <div class="topbar"><div class="tb">Mind</div><div class="tbs">State of mind</div></div>
                  <div class="sec">Doing</div>
                  <div class="plate">
                    <div class="field"><span>Activity</span><b>Idle</b></div>
                    <div class="field"><span>Power</span><b><i id="pw-a">Active</i><i id="pw-s">Standby</i></b></div>
                    <div class="btns"><span class="q" id="b-active">Active</span><span class="q">Quiet</span><span class="q" id="b-standby">Standby</span>
                      <div class="tap" id="tap"></div></div>
                  </div>
                </div>
              </div>
'''

TEXT = {
    "title": "A day with Jarvis.",
    "sub": "An AI assistant that lives on your own PC.",
    "brief_say": "Brief me now.",
    "brief_claim": "Made on your PC <b>without the AI model</b>. Email shows who wrote, not what they wrote.",
    "focus_say": "Focus for 30 minutes.",
    "focus_reply": "YouTube can wait.",
    "focus_claim": "It watches which app is in front, <b>on your PC only</b>, and keeps counts, never what it saw.",
    "tell_say": "Tell me when an email from Alex arrives. Urgently.",
    "tell_claim": "<b>One yes</b> sets it up. Your phone rings until you look. It never replies.",
    "learn_say": "I've started learning Spanish.",
    "learn_claim": "It learns from <b>your own words only</b>. Every fact has Forget and Erase the words.",
    "standby_claim": "<b>One tap</b> on your phone. Standby frees the graphics card; the next answer takes 5-15 seconds.",
    "end1": "Your day.", "end2": "Your PC.", "end3": "<i>Your rules.</i>",
    "small": "Made for a Windows PC with an 8 GB NVIDIA graphics card · Android phone app · No subscription",
}


def stations_landscape():
    ax, W = "x", 1920
    T = TEXT
    out = ""
    out += station("dawn", 0, ax, f'''            <div class="title" id="title">{T["title"]}</div>
            <div class="subtitle" id="sub">{T["sub"]}</div>
''')
    out += station("brief", W, ax, col("Morning", "7:30", T["brief_say"], None, "brief")
                   + shot("brief", [("brief-card", "brief-rows.png")], where="Brain › Work › Morning briefing")
                   + claim("brief", T["brief_claim"]))
    out += station("focus", 2 * W, ax, col("Morning", "9:00", T["focus_say"], T["focus_reply"], "focus")
                   + shot("focus", [("focus-run", "focus-running-box.png"), ("focus-drift", "focus-drifting-box.png")], where="Brain › Work › Focus session")
                   + claim("focus", T["focus_claim"]))
    out += station("tell", 3 * W, ax, col("Afternoon", "15:00", T["tell_say"], None, "tell")
                   + shot("tell", [("tell-card", "tellme-card.png")], '              <div class="pressring" id="tell-press"></div>\n' + PHONE, where="The approval card on the PC")
                   + claim("tell", T["tell_claim"]))
    out += station("learn", 4 * W, ax, col("Evening", "19:30", T["learn_say"], None, "learn", later=True)
                   + shot("learn", [("learn-card", "memory-saved.png")], '              <div class="pressring" id="learn-press"></div>\n', where="Brain › Memory")
                   + claim("learn", T["learn_claim"]), night=True)
    out += station("standby", 5 * W, ax, col("Night", "23:00", None, None, "standby")
                   + shot("standby", [], PHONE_NIGHT)
                   + claim("standby", T["standby_claim"]), night=True)
    out += station("end", 6 * W, ax, f'''            <div class="end">
              <div class="big"><span id="e1">{T["end1"]}</span> <span id="e2">{T["end2"]}</span> <span id="e3">{T["end3"]}</span></div>
              <div class="small" id="small">{T["small"]}</div>
              <div class="word" id="word">JARVIS</div>
            </div>
''', night=True)
    return out


def stations_vertical():
    ax, W = "y", 1920
    T = TEXT
    out = ""
    out += station("dawn", 0, ax, f'''            <div class="title" id="title">{T["title"]}</div>
            <div class="subtitle" id="sub">{T["sub"]}</div>
''')
    out += station("focus", W, ax, col("Morning", "9:00", T["focus_say"], T["focus_reply"], "focus")
                   + shot("focus", [("focus-run", "focus-running-box.png"), ("focus-drift", "focus-drifting-box.png")], where="Brain › Work › Focus session")
                   + claim("focus", T["focus_claim"]))
    out += station("tell", 2 * W, ax, col("Afternoon", "15:00", T["tell_say"], None, "tell")
                   + shot("tell", [("tell-card", "tellme-card.png")], '              <div class="pressring" id="tell-press"></div>\n' + PHONE, where="The approval card on the PC")
                   + claim("tell", T["tell_claim"]))
    out += station("end", 3 * W, ax, f'''            <div class="end">
              <div class="big"><span id="e1">{T["end1"]}</span><br /><span id="e2">{T["end2"]}</span><br /><span id="e3">{T["end3"]}</span></div>
              <div class="small" id="small">Made for a Windows PC<br />with an 8 GB NVIDIA graphics card<br />Android phone app · No subscription</div>
              <div class="word" id="word">JARVIS</div>
            </div>
''', night=True)
    return out


TAIL = '''        </div>
        <div id="sun-wrap"><canvas id="sun" width="340" height="340"></canvas></div>
        <div id="fade"></div>
      </div>
      <audio id="score" src="assets/music/{score}.mp3" data-start="0" data-duration="{dur}" data-track-index="20" data-volume="1"></audio>
    </div>
    <script src="assets/day.js"></script>
    <script>
{script}
    </script>
  </body>
</html>
'''

# The per-cut scene script: what appears when. Shared helpers come from day.js.
SCENES = r'''      (function () {
        var T = window.TIMING, H = T.hits;
        var SUN = __SUN__;
        DAY.run({
          id: "__CID__", dur: T.dur, H: H, axis: "__AXIS__", stride: 1920, stations: T.stations, drift: 22,
          nightFrom: [18.6, 19.8],
          // The reactor's state, from the app's own state names.
          hero: __HERO__,
          caps: [],
          sunPath: function (t) {
            var k = DAY.prog(t, H.end - 0.6, 1.6, DAY.E.io);
            return { x: SUN.dx * k, y: SUN.dy * k, s: 1 + (SUN.s - 1) * k, a: 1 };
          },
          scenes: function (t, h) {
            var A = h.appear, W = h.words, $ = h.$;
            // A press ring sits on a real button: its box is measured from the capture.
            function ring(rid, iid, b) {
              var r = $(rid), im = $(iid); if (!r || !im || !im.offsetWidth) return;
              var x = im.offsetLeft, y = im.offsetTop, pad = 8;
              r.style.left = (x + b.x * im.offsetWidth - pad) + "px"; r.style.top = (y + b.y * im.offsetHeight - pad) + "px";
              r.style.width = (b.w * im.offsetWidth + 2 * pad) + "px"; r.style.height = (b.h * im.offsetHeight + 2 * pad) + "px";
            }
            ring("tell-press", "tell-card", __APPROVE__);
            ring("learn-press", "learn-card", __ERASE__);
            A($("title"), t, H.title, { d: 0.9, dy: 18, blur: 8, out: T.stations[0].at[1] + 0.1, outD: 0.5 });
            if ($("sub")) A($("sub"), t, H.sub, { d: 0.7, dy: 12, out: T.stations[0].at[1] + 0.1, outD: 0.5 });
            [["brief", H.briefSay], ["focus", H.focusSay], ["tell", H.tellSay], ["learn", H.learnSay]].forEach(function (s) {
              if (!$(s[0] + "-say")) return;
              A($(s[0] + "-you"), t, s[1] - 0.05, { d: 0.3, dy: 8 });
              W($(s[0] + "-say"), t, s[1], 0.7);
            });
            // Focus: the real card on target, then off target the moment YouTube is in front.
            A($("focus-shot"), t, H.focusCard, { d: 0.6, dy: 40, e: DAY.E.back });
            h.swap(t, [[H.focusCard, "focus-run"], [H.drift - 0.05, "focus-drift"]], 0.15);
            A($("focus-jw"), t, H.drift - 0.05, { d: 0.3, dy: 8 });
            W($("focus-reply"), t, H.drift, 0.4);
            A($("focus-claim"), t, H.focusClaim, { d: 0.5, dy: 14 });
            // Brief me now.
            A($("brief-shot"), t, H.briefCard, { d: 0.6, dy: 40, e: DAY.E.back });
            A($("brief-claim"), t, H.briefClaim, { d: 0.5, dy: 14 });
            // Tell me when: the real card, Approve, then the phone rings.
            A($("tell-shot"), t, H.tellCard, { d: 0.6, dy: 40, e: DAY.E.back });
            h.press($("tell-press"), t, H.approve);
            A($("phone"), t, H.ring - 0.4, { d: 0.5, dy: 140 });
            A($("notif"), t, H.ring, { d: 0.35, dy: -24, e: DAY.E.back });
            ["ring-a", "ring-b"].forEach(function (id, i) {
              var el = $(id); if (!el) return;
              var d = t - (i ? H.ring2 : H.ring);
              el.style.opacity = d < 0 || d > 0.8 ? "0" : (0.9 * (1 - d / 0.8)).toFixed(3);
              el.style.transform = "scale(" + (0.6 + 0.8 * h.clamp(d / 0.8, 0, 1)).toFixed(3) + ")";
            });
            A($("tell-claim"), t, H.tellClaim, { d: 0.5, dy: 14 });
            // Evening: learned from your own words, with Forget and Erase the words.
            A($("learn-shot"), t, H.saved, { d: 0.6, dy: 40, e: DAY.E.back });
            h.press($("learn-press"), t, H.erase);
            A($("learn-claim"), t, H.learnClaim, { d: 0.5, dy: 14 });
            A($("later"), t, H.saved - 0.3, { d: 0.4, dy: 8 });
            // Night: one tap on the phone's Standby. The Power field flips when the
            // desktop reports the new mode, a moment after the tap.
            if ($("phone-n")) {
              A($("phone-n"), t, H.standby - 0.3, { d: 0.6, dy: 60 });
              var tap = $("tap"), bs = $("b-standby"), ba = $("b-active");
              if (tap) {
                var dd = t - H.press;
                tap.style.left = (bs.offsetLeft + bs.offsetWidth / 2) + "px"; tap.style.top = (bs.offsetTop + bs.offsetHeight / 2) + "px";
                tap.style.opacity = dd < 0 || dd > 0.5 ? "0" : (0.9 * (1 - dd / 0.5)).toFixed(3);
                tap.style.transform = "scale(" + (0.5 + h.clamp(dd / 0.5, 0, 1)).toFixed(3) + ")";
              }
              var sw = t >= H.asleep;
              ba.className = "q" + (sw ? "" : " off"); bs.className = "q" + (sw ? " off" : "");
              var k = h.prog(t, H.asleep, 0.25, DAY.E.out2);
              $("pw-a").style.opacity = (1 - k).toFixed(3); $("pw-s").style.opacity = k.toFixed(3);
            }
            A($("standby-claim"), t, H.standbyClaim, { d: 0.5, dy: 14 });
            // The end.
            A($("e1"), t, H.e1, { d: 0.7, dy: 16, blur: 6 });
            A($("e2"), t, H.e2, { d: 0.7, dy: 16, blur: 6 });
            A($("e3"), t, H.e3, { d: 0.7, dy: 16, blur: 6 });
            A($("small"), t, H.small, { d: 0.6, dy: 10 });
            A($("word"), t, H.word, { d: 0.8, dy: 0, blur: 10 });
          }
        });
      })();'''


def build(kind):
    t = TIMING["timing" if kind == "landscape" else "timing-vertical"]
    H = t["hits"]
    if kind == "landscape":
        w, h, cid, axis = 1920, 1080, "jarvis-v5", "x"
        body = stations_landscape()
        heroes = [[0, "idle"],
                  [H["briefSay"], "listening"], [H["briefCard"], "speaking"], [H["briefClaim"] + 1.0, "idle"],
                  [H["focusSay"], "listening"], [H["focusCard"], "idle"], [H["drift"], "speaking"], [H["drift"] + 1.0, "idle"],
                  [H["tellSay"], "listening"], [H["tellCard"], "approval"], [H["approve"] + 0.2, "idle"],
                  [H["learnSay"], "listening"], [H["saved"], "idle"],
                  [H["asleep"], "standby"]]
        sun = {"dx": 0, "dy": 280, "s": 1.9}
        extra = ""
    else:
        w, h, cid, axis = 1080, 1920, "jarvis-v5-vertical", "y"
        body = stations_vertical()
        heroes = [[0, "idle"],
                  [H["focusSay"], "listening"], [H["focusCard"], "idle"], [H["drift"], "speaking"], [H["drift"] + 1.0, "idle"],
                  [H["tellSay"], "listening"], [H["tellCard"], "approval"], [H["approve"] + 0.2, "idle"],
                  [H["end"] - 0.3, "idle"]]
        sun = {"dx": 400, "dy": -120, "s": 1.9}
        extra = '    <link rel="stylesheet" href="assets/vertical.css" />\n'
    boxes = {k: (ROOT / "assets" / "ui" / f).read_text().strip() for k, f in
             (("__APPROVE__", "tellme-card-approve.json"), ("__ERASE__", "memory-saved-erase.json"))}
    script = SCENES
    for k, v in boxes.items():
        script = script.replace(k, v)
    script = (script.replace("__CID__", cid).replace("__AXIS__", axis)
              .replace("__HERO__", json.dumps(heroes)).replace("__SUN__", json.dumps(sun)))
    html = HEAD.format(w=w, h=h, title="Jarvis: a day with Jarvis" + ("" if kind == "landscape" else " (upright)"),
                       timing="timing" if kind == "landscape" else "timing-vertical",
                       audio="audio-data" if kind == "landscape" else "audio-data-vertical",
                       extra=extra, cls=kind, cid=cid, dur=t["dur"])
    html += body + TAIL.format(script=script, dur=t["dur"], score="score" if kind == "landscape" else "score-vertical")
    (ROOT / ("index.html" if kind == "landscape" else "vertical.html")).write_text(html)


if __name__ == "__main__":
    build("landscape")
    build("vertical")
    print("wrote index.html and vertical.html")
