package com.jarvis.client.face

import androidx.compose.ui.graphics.Color

/**
 * The spec's 50 colours: ten families of five steps.
 *
 * GENERATED by tools/gen_palette.py from
 * app/src/test/resources/jarvis-visual-spec.json. Do not edit by hand —
 * SpecDriftTest re-reads that JSON and will fail if these drift from it.
 *
 * Step 1 is the deepest and step 5 the palest. Names are the spec's own, so
 * `Palette.ice(4)` and the desktop's `ice-4` are the same colour by
 * construction rather than by somebody checking.
 */
object Palette {

    /** `ice-1` — Ice Deep. */
    val ICE_1 = Color(0xFF0A3A4A)
    /** `ice-2` — Ice Shade. */
    val ICE_2 = Color(0xFF12657F)
    /** `ice-3` — Ice Core. */
    val ICE_3 = Color(0xFF2EA8CC)
    /** `ice-4` — Ice Bright. */
    val ICE_4 = Color(0xFF6FE3FF)
    /** `ice-5` — Ice Mist. */
    val ICE_5 = Color(0xFFB8F4FF)
    /** `azure-1` — Azure Deep. */
    val AZURE_1 = Color(0xFF0C2A55)
    /** `azure-2` — Azure Shade. */
    val AZURE_2 = Color(0xFF14479A)
    /** `azure-3` — Azure Core. */
    val AZURE_3 = Color(0xFF2F74E0)
    /** `azure-4` — Azure Bright. */
    val AZURE_4 = Color(0xFF62A3FF)
    /** `azure-5` — Azure Mist. */
    val AZURE_5 = Color(0xFFB0D2FF)
    /** `indigo-1` — Indigo Deep. */
    val INDIGO_1 = Color(0xFF1A1A52)
    /** `indigo-2` — Indigo Shade. */
    val INDIGO_2 = Color(0xFF2B2B8F)
    /** `indigo-3` — Indigo Core. */
    val INDIGO_3 = Color(0xFF4A4AD4)
    /** `indigo-4` — Indigo Bright. */
    val INDIGO_4 = Color(0xFF7B7BFF)
    /** `indigo-5` — Indigo Mist. */
    val INDIGO_5 = Color(0xFFC0C0FF)
    /** `violet-1` — Violet Deep. */
    val VIOLET_1 = Color(0xFF33115C)
    /** `violet-2` — Violet Shade. */
    val VIOLET_2 = Color(0xFF551F9C)
    /** `violet-3` — Violet Core. */
    val VIOLET_3 = Color(0xFF8340E0)
    /** `violet-4` — Violet Bright. */
    val VIOLET_4 = Color(0xFFAE7BFF)
    /** `violet-5` — Violet Mist. */
    val VIOLET_5 = Color(0xFFD9C0FF)
    /** `magenta-1` — Magenta Deep. */
    val MAGENTA_1 = Color(0xFF4D0C40)
    /** `magenta-2` — Magenta Shade. */
    val MAGENTA_2 = Color(0xFF8A1470)
    /** `magenta-3` — Magenta Core. */
    val MAGENTA_3 = Color(0xFFCC2FA8)
    /** `magenta-4` — Magenta Bright. */
    val MAGENTA_4 = Color(0xFFFF6FD0)
    /** `magenta-5` — Magenta Mist. */
    val MAGENTA_5 = Color(0xFFFFB8EA)
    /** `rose-1` — Rose Deep. */
    val ROSE_1 = Color(0xFF521018)
    /** `rose-2` — Rose Shade. */
    val ROSE_2 = Color(0xFF8F1B28)
    /** `rose-3` — Rose Core. */
    val ROSE_3 = Color(0xFFD4384A)
    /** `rose-4` — Rose Bright. */
    val ROSE_4 = Color(0xFFFF7B86)
    /** `rose-5` — Rose Mist. */
    val ROSE_5 = Color(0xFFFFC0C5)
    /** `ember-1` — Ember Deep. */
    val EMBER_1 = Color(0xFF4D1F08)
    /** `ember-2` — Ember Shade. */
    val EMBER_2 = Color(0xFF8A3A0E)
    /** `ember-3` — Ember Core. */
    val EMBER_3 = Color(0xFFD4661C)
    /** `ember-4` — Ember Bright. */
    val EMBER_4 = Color(0xFFFF9B52)
    /** `ember-5` — Ember Mist. */
    val EMBER_5 = Color(0xFFFFCFA8)
    /** `amber-1` — Amber Deep. */
    val AMBER_1 = Color(0xFF4A3708)
    /** `amber-2` — Amber Shade. */
    val AMBER_2 = Color(0xFF8A680E)
    /** `amber-3` — Amber Core. */
    val AMBER_3 = Color(0xFFD4A41C)
    /** `amber-4` — Amber Bright. */
    val AMBER_4 = Color(0xFFFFB648)
    /** `amber-5` — Amber Mist. */
    val AMBER_5 = Color(0xFFFFE0A0)
    /** `verdant-1` — Verdant Deep. */
    val VERDANT_1 = Color(0xFF0A3D2A)
    /** `verdant-2` — Verdant Shade. */
    val VERDANT_2 = Color(0xFF126B47)
    /** `verdant-3` — Verdant Core. */
    val VERDANT_3 = Color(0xFF22A874)
    /** `verdant-4` — Verdant Bright. */
    val VERDANT_4 = Color(0xFF5FE0A8)
    /** `verdant-5` — Verdant Mist. */
    val VERDANT_5 = Color(0xFFB0F4D8)
    /** `neutral-1` — Neutral Deep. */
    val NEUTRAL_1 = Color(0xFF0A0E14)
    /** `neutral-2` — Neutral Shade. */
    val NEUTRAL_2 = Color(0xFF1E2833)
    /** `neutral-3` — Neutral Core. */
    val NEUTRAL_3 = Color(0xFF46566A)
    /** `neutral-4` — Neutral Bright. */
    val NEUTRAL_4 = Color(0xFF8FA3B8)
    /** `neutral-5` — Neutral Mist. */
    val NEUTRAL_5 = Color(0xFFDDE7F2)

    /** Every colour by its spec id, e.g. `"ice-4"`. */
    val byId: Map<String, Color> = mapOf(
        "ice-1" to ICE_1,
        "ice-2" to ICE_2,
        "ice-3" to ICE_3,
        "ice-4" to ICE_4,
        "ice-5" to ICE_5,
        "azure-1" to AZURE_1,
        "azure-2" to AZURE_2,
        "azure-3" to AZURE_3,
        "azure-4" to AZURE_4,
        "azure-5" to AZURE_5,
        "indigo-1" to INDIGO_1,
        "indigo-2" to INDIGO_2,
        "indigo-3" to INDIGO_3,
        "indigo-4" to INDIGO_4,
        "indigo-5" to INDIGO_5,
        "violet-1" to VIOLET_1,
        "violet-2" to VIOLET_2,
        "violet-3" to VIOLET_3,
        "violet-4" to VIOLET_4,
        "violet-5" to VIOLET_5,
        "magenta-1" to MAGENTA_1,
        "magenta-2" to MAGENTA_2,
        "magenta-3" to MAGENTA_3,
        "magenta-4" to MAGENTA_4,
        "magenta-5" to MAGENTA_5,
        "rose-1" to ROSE_1,
        "rose-2" to ROSE_2,
        "rose-3" to ROSE_3,
        "rose-4" to ROSE_4,
        "rose-5" to ROSE_5,
        "ember-1" to EMBER_1,
        "ember-2" to EMBER_2,
        "ember-3" to EMBER_3,
        "ember-4" to EMBER_4,
        "ember-5" to EMBER_5,
        "amber-1" to AMBER_1,
        "amber-2" to AMBER_2,
        "amber-3" to AMBER_3,
        "amber-4" to AMBER_4,
        "amber-5" to AMBER_5,
        "verdant-1" to VERDANT_1,
        "verdant-2" to VERDANT_2,
        "verdant-3" to VERDANT_3,
        "verdant-4" to VERDANT_4,
        "verdant-5" to VERDANT_5,
        "neutral-1" to NEUTRAL_1,
        "neutral-2" to NEUTRAL_2,
        "neutral-3" to NEUTRAL_3,
        "neutral-4" to NEUTRAL_4,
        "neutral-5" to NEUTRAL_5,
    )

    /** The ten family names, in the spec's order. */
    val families: List<String> = listOf(
        "ice",
        "azure",
        "indigo",
        "violet",
        "magenta",
        "rose",
        "ember",
        "amber",
        "verdant",
        "neutral",
    )

    /**
     * One family's five steps, deepest first.
     *
     * Used to walk a bound colour up or down its OWN family until it clears
     * a contrast floor. Walking toward white instead would desaturate the
     * hue, and the hue is the thing the user bound.
     */
    fun steps(family: String): List<Color> = ramps[family] ?: emptyList()

    /**
     * The ten ramps, built once.
     *
     * `steps()` used to rebuild its list on every call: an ArrayList, an
     * iterator, five StringBuilders, five Strings and five map lookups — about
     * a dozen objects. `resolveRaw` calls it inside the FLICKER branch, which
     * is per frame, so a state bound to flicker allocated that twelve times a
     * frame for ten lists that can never change.
     */
    private val ramps: Map<String, List<Color>> =
        families.associateWith { f -> (1..5).mapNotNull { byId["$f-$it"] } }

    /** The family a colour belongs to, or null if it is not a palette colour. */
    fun familyOf(color: Color): String? =
        byId.entries.firstOrNull { it.value == color }?.key?.substringBeforeLast('-')

    /** The step (1..5) a colour sits at, or null if it is not a palette colour. */
    fun stepOf(color: Color): Int? =
        byId.entries.firstOrNull { it.value == color }
            ?.key?.substringAfterLast('-')?.toIntOrNull()
}
