package com.jarvis.client.ui.screens

import androidx.compose.animation.animateContentSize
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription
import androidx.compose.ui.unit.dp
import com.jarvis.client.net.Features
import com.jarvis.client.ui.Chevron
import com.jarvis.client.ui.parts.Kicker
import com.jarvis.client.ui.parts.Plate
import com.jarvis.client.ui.parts.Quiet
import com.jarvis.client.ui.parts.Section
import com.jarvis.client.ui.parts.pressable
import com.jarvis.client.ui.theme.LocalChrome
import com.jarvis.client.ui.theme.LocalMotion
import com.jarvis.client.ui.theme.LocalRadii
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * "Everything Jarvis can do" (docs/FEATURES-LIST-DESIGN.md, 2026-10-08; the
 * owner's request of the same day).
 *
 * One screen, the same words as the desktop's own page, read from this app's
 * copy of `features/features.json` ([Features.ASSET]) - so the two apps can
 * never disagree about what a feature does, and no text here is generated by
 * the model.
 *
 * READ-ONLY, AND NO CARD. There is nothing to press: no switch, no approval,
 * no request to the PC, and no stale-link hold. Deep config editing stays off
 * the phone (the standing rule), which is exactly why this screen is the
 * phone's honest answer to "what can Jarvis do" rather than a settings page.
 *
 * The rows use this app's own expander idiom, the same one [FaqScreen] uses:
 * a card that opens in place with the chevron turning over, a screen reader
 * told "Expanded" or "Collapsed" in words, and the answer in body text.
 */
@Composable
fun FeaturesScreen(
    onBack: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val chrome = LocalChrome.current
    val context = LocalContext.current
    val listState = rememberLazyListState()
    // Null until the asset has been read, so the screen says "Reading the
    // list…" rather than showing an empty page that looks broken.
    var rows by remember { mutableStateOf<List<Features.Row>?>(null) }
    var failed by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        val text = withContext(Dispatchers.IO) {
            runCatching {
                context.assets.open(Features.ASSET).bufferedReader().use { it.readText() }
            }.getOrNull()
        }
        if (text == null) {
            failed = true
        } else {
            // A file that does not parse is a broken copy of the app, not a
            // crash: the screen says so in one plain sentence, the same as the
            // desktop page does.
            runCatching { Features.rows(Features.readOf(text)) }
                .onSuccess { rows = it }
                .onFailure { failed = true }
        }
    }

    Column(modifier.fillMaxSize().background(chrome.surface0)) {
        TopBar(
            Features.HEADING,
            onBack,
            subtitle = "Every feature, in plain words. This screen only reads.",
        )

        LazyColumn(
            state = listState,
            verticalArrangement = Arrangement.spacedBy(8.dp),
            modifier = Modifier.weight(1f).fillMaxWidth().padding(horizontal = 18.dp),
        ) {
            item(key = "top-space") { Spacer(Modifier.height(6.dp)) }
            val drawn = rows
            if (failed) {
                item(key = "failed") {
                    Text(
                        Features.CANNOT_READ,
                        style = MaterialTheme.typography.bodyMedium,
                        color = chrome.warnInk,
                    )
                }
            } else if (drawn == null) {
                item(key = "reading") {
                    Text(
                        Features.READING,
                        style = MaterialTheme.typography.bodyMedium,
                        color = chrome.textMid,
                    )
                }
            } else {
                items(drawn, key = { rowKey(it) }) { row ->
                    when (row) {
                        is Features.Row.Heading -> FeatureHeading(row.title, row.count)
                        is Features.Row.Feature -> FeatureCard(row.entry)
                    }
                }
            }
            item(key = "bottom-space") { Spacer(Modifier.height(8.dp)) }
        }
    }
}

/** A stable key per drawn row, so a re-read does not re-order the screen. */
private fun rowKey(row: Features.Row): String = when (row) {
    is Features.Row.Heading -> "g:${row.title}"
    is Features.Row.Feature -> "f:${row.entry.id}"
}

/** A group's name and how many features are under it. */
@Composable
private fun FeatureHeading(title: String, count: Int) {
    val chrome = LocalChrome.current
    Column(Modifier.fillMaxWidth().padding(top = 10.dp)) {
        Kicker(title, Modifier.semantics { heading() })
        Text(
            if (count == 1) "1 feature" else "$count features",
            style = MaterialTheme.typography.labelSmall,
            color = chrome.textMid,
        )
    }
}

/**
 * One feature: closed, a title and the chevron; opened, the four things the
 * design note fixes and nothing else. A feature with no real limit draws no
 * limit line at all rather than an empty one.
 */
@Composable
private fun FeatureCard(entry: Features.Entry) {
    val chrome = LocalChrome.current
    var open by rememberSaveable(entry.id) { mutableStateOf(false) }
    val turn by animateFloatAsState(
        targetValue = if (open) 180f else 0f,
        animationSpec = LocalMotion.current.micro(),
        label = "feature-chevron",
    )
    Column(
        Modifier
            .fillMaxWidth()
            .animateContentSize()
            .clip(LocalRadii.current.cardShape)
            .background(chrome.surface1)
            .semantics { stateDescription = if (open) "Expanded" else "Collapsed" }
            .pressable(onClick = { open = !open })
            .padding(14.dp),
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                entry.title,
                style = MaterialTheme.typography.titleSmall,
                color = chrome.textHi,
                modifier = Modifier.weight(1f),
            )
            if (entry.otherAppTag.isNotEmpty()) {
                Spacer(Modifier.width(8.dp))
                Text(
                    entry.otherAppTag,
                    style = MaterialTheme.typography.labelSmall,
                    color = chrome.textMid,
                )
            }
            Spacer(Modifier.width(8.dp))
            // Turned in the draw phase, so the short turn redraws one small box
            // and recomposes nothing (the FAQ's own note, screens-14).
            Chevron(
                tint = chrome.textMid,
                modifier = Modifier.graphicsLayer { rotationZ = turn },
            )
        }
        if (open) {
            Spacer(Modifier.height(8.dp))
            FeatureField("What it does", entry.what)
            FeatureField("How to reach it", entry.where)
            FeatureField("Asks first", entry.asks)
            if (entry.limit.isNotEmpty()) FeatureField("One limit", entry.limit)
        }
    }
}

/** A labelled sentence inside an opened feature. */
@Composable
private fun FeatureField(label: String, value: String) {
    val chrome = LocalChrome.current
    Column(Modifier.fillMaxWidth().padding(bottom = 6.dp)) {
        Text(label, style = MaterialTheme.typography.labelSmall, color = chrome.textMid)
        Spacer(Modifier.height(2.dp))
        Text(value, style = MaterialTheme.typography.bodyMedium, color = chrome.textHi)
    }
}

/**
 * The Brain's way in: one plate that opens [FeaturesScreen], drawn next to the
 * Tutorials section (docs/FEATURES-LIST-DESIGN.md, 2026-10-08, asks for "a row
 * on Home next to Tutorials" - this phone's Tutorials are a section of the
 * Brain, not a row on Home, so this sits beside the Tutorials row itself).
 *
 * The same shape as [HistoryEntrySection]: nothing to decide, so no card, no
 * request to the PC, and no stale-link hold. It is deliberately NOT a menu id -
 * there is nothing here to hide or fold, and `MenuVisibilityTest` reads an
 * `item(key = ...)` as a menu that "Show or hide menus" must be able to hide.
 */
@Composable
internal fun FeaturesEntrySection(onOpen: () -> Unit) {
    val chrome = LocalChrome.current
    Section(Features.HEADING) {
        Plate {
            Text(
                Features.INTRO,
                style = MaterialTheme.typography.bodySmall,
                color = chrome.textMid,
            )
            Spacer(Modifier.height(4.dp))
            Quiet(Features.OPEN, onClick = onOpen)
        }
    }
}
