/**
 * The monthly money limits and the price list, on the desktop
 * (docs/ACCOUNT-KEYS-DESIGN.md steps 3-5, decisions 1, 3 and 4; the owner's
 * approval of 2026-10-06; src/chatbot-api-keys.js, src/chatbot-api-keys-settings.js,
 * src/settings.html, src-tauri/src/chatbot_money.rs, backend jarvis_chatbot_limits.py).
 *
 * What must hold, and this is the whole point of the feature:
 * - RAISING a limit is a loosening, so the page asks and the PC raises ONE
 *   approval card plus Windows Hello; LOWERING one, removing one, correcting a
 *   price and resetting one need no card. Which of the two it is decided by the
 *   PC from the amount against the limit it holds, never by this page;
 * - the page says which is coming BEFORE the tap, so a wait on a card is never
 *   a surprise, and it shows whichever the PC says actually happened;
 * - every number the page shows comes from the PC's own answer, including
 *   where each price came from ("yours" or "default, unverified") and when it
 *   was set - decision 4's whole point;
 * - CONTROL: the read and the write sit with the Settings window only, both
 *   commands are registered in build.rs and lib.rs, both have an autogenerated
 *   permission file, and the write is held on a stale link;
 * - CONTROL: Rust sends only the five known actions and a service name that
 *   cannot carry a path or a query into the route, and forwards only known
 *   keys - a key can never travel through this route;
 * - CONTROL: the PC's own `pc_only` refusal is passed on as the PC wrote it;
 * - CONTROL: /api/chatbot/money is classified in tools/check_parity.py as
 *   desktop-only, with the reason.
 *
 * The browser-free half runs anywhere, including CI, which has no Playwright.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  changeWords,
  estimatesLine,
  limitActionFor,
  limitButtonWords,
  moneyFor,
  raiseWords,
  willAskForApproval,
} from "../src/chatbot-api-keys.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const read = (p) => readFileSync(join(HERE, "..", p), "utf8");
const readRepo = (p) => readFileSync(join(REPO, p), "utf8");

let K = null;
try {
  await import("playwright");
  K = await import("./uikit.mjs");
} catch {
  console.log(
    "skip  the Settings page half: Playwright is not installed " +
      "(npm i -D playwright && npx playwright install chromium)"
  );
}

const fails = [];
const check = async (name, fn) => {
  try {
    await fn();
    console.log(`ok    ${name}`);
  } catch (e) {
    fails.push(name);
    console.log(`FAIL  ${name}\n      ${e.message}`);
  }
};

/** What the PC's own answer looks like, with one service. */
function answer(over = {}) {
  return {
    ok: true,
    available: true,
    can_change: true,
    raise_action: "raise_api_limit",
    lower_action: "lower_api_limit",
    until: "November 1",
    estimates: "Every price here is used to ESTIMATE what an answer cost.",
    raise_words: "Raising a limit asks you on an approval card, and Windows Hello on this PC "
      + "confirms it is you. Lowering one, removing one and correcting a price change at once, "
      + "with no card.",
    services: [{
      service: "openai",
      limit: 5,
      limit_words: "$5.00",
      spent_words: "$0.98",
      left_words: "$4.02",
      until: "November 1",
      reached: false,
      line: "About $4.02 of $5.00 left this month for OpenAI (prices are estimates you can "
        + "correct on the PC).",
      cap: "Answer length: capped with max_completion_tokens ...",
      can_change: true,
      price: {
        model: "gpt-5-mini",
        source: "default",
        verified: false,
        set: "",
        in: 0.25,
        out: 2,
        line: "$0.25 per million word-pieces in, $2 out - the default written 2026-09-28, "
          + "UNVERIFIED. Check it at https://openai.com/api/pricing and correct it here.",
        price_page: "https://openai.com/api/pricing",
      },
      ...over,
    }],
  };
}

/* ── The one rule, as the page works it out ───────────────────────────── */

await check("a bigger amount raises, a smaller one lowers, and a first one sets", () => {
  assert.equal(limitActionFor(5, 10), "raise_limit");
  assert.equal(limitActionFor(5, 3), "lower_limit");
  assert.equal(limitActionFor(5, 5), "lower_limit", "the same amount spends no more");
  assert.equal(limitActionFor(null, 5), "raise_limit", "a first limit lets it be used at all");
  assert.equal(limitActionFor(undefined, 0.5), "raise_limit");
  assert.equal(limitActionFor(5, ""), null, "nothing typed is nothing to send");
  assert.equal(limitActionFor(5, "abc"), null);
  assert.equal(limitActionFor(5, "-1"), null);
  assert.equal(limitActionFor(5, NaN), null);
});

await check("the button says what will happen, and only a raise warns of a card", () => {
  assert.equal(limitButtonWords(null, 5), "Set this limit");
  assert.equal(limitButtonWords(5, 10), "Raise it");
  assert.equal(limitButtonWords(5, 3), "Lower it");
  assert.equal(willAskForApproval(5, 10), true);
  assert.equal(willAskForApproval(5, 3), false);
  assert.equal(willAskForApproval(5, 5), false);
  assert.equal(willAskForApproval(null, 5), true, "the first limit loosens from nothing");
  assert.equal(willAskForApproval(null, NaN), false, "nothing to send is not a card");
});

await check("a raise is never asked for by a phone-shaped answer", () => {
  // can_change false is the PC saying "not from here": the page must not
  // pretend it could send anything.
  const m = moneyFor(answer({ can_change: false }), "openai");
  assert.equal(m.canChange, false);
  assert.equal(m.limit, 5);
});

/* ── Everything shown is the PC's own ─────────────────────────────────── */

await check("moneyFor reads the PC's own numbers, or nothing at all", () => {
  const m = moneyFor(answer(), "openai");
  assert.equal(m.limit, 5);
  assert.equal(m.leftWords, "$4.02");
  assert.equal(m.spentWords, "$0.98");
  assert.equal(m.until, "November 1");
  assert.match(m.line, /left this month for OpenAI/);
  assert.equal(moneyFor(answer(), "groq"), null, "a service the PC did not send");
  assert.equal(moneyFor(null, "openai"), null);
  assert.equal(moneyFor({}, "openai"), null);
  assert.equal(moneyFor({ services: "nope" }, "openai"), null);
});

await check("a price always says where the number came from and when it was set", () => {
  const dflt = moneyFor(answer(), "openai").price;
  assert.equal(dflt.source, "default");
  assert.equal(dflt.verified, false);
  assert.match(dflt.line, /UNVERIFIED/);
  assert.match(dflt.line, /2026-09-28/);
  assert.equal(dflt.pricePage, "https://openai.com/api/pricing");
  const mine = moneyFor(answer({
    price: { model: "gpt-5-mini", source: "yours", verified: true, set: "2026-10-06",
      in: 0.5, out: 4, line: "your own price", price_page: "" },
  }), "openai").price;
  assert.equal(mine.source, "yours");
  assert.equal(mine.set, "2026-10-06");
  assert.equal(mine.in, 0.5);
  assert.equal(mine.line, "your own price");
  // A service with no price at all must not be given one by this page.
  const none = moneyFor(answer({ price: null }), "openai").price;
  assert.equal(none, null);
});

await check("the page's own fallback words never invent a number or a card", () => {
  assert.doesNotMatch(estimatesLine(null), /UNVERIFIED/, "a fallback must not claim a price");
  assert.match(estimatesLine({ estimates: "the PC's sentence" }), /the PC's sentence/);
  assert.match(raiseWords({ raise_words: "the PC's sentence" }), /the PC's sentence/);
  assert.match(raiseWords(null), /Windows Hello/);
  assert.match(raiseWords(null), /no card/);
  assert.equal(changeWords({ said: "the PC's sentence" }), "the PC's sentence");
  assert.match(changeWords({ raised: true }), /approval card/);
  assert.match(changeWords({}), /Saved/);
});

/* ── CONTROL: the wiring ──────────────────────────────────────────────── */

await check("CONTROL: the read and the write sit with the Settings window only", () => {
  const toml = read("src-tauri/permissions/surfaces.toml");
  const sets = toml.split("[[set]]");
  const settingsSet = sets.find((s) => s.includes('identifier = "settings-surface"'));
  for (const c of ["chatbot-money", "set-chatbot-money"]) {
    assert.ok(settingsSet.includes(`"allow-${c}"`), c);
    assert.equal(sets.filter((s) => s.includes(`"allow-${c}"`)).length, 1, `${c} is elsewhere`);
  }
  const build = read("src-tauri/build.rs");
  const lib = read("src-tauri/src/lib.rs");
  for (const c of ["chatbot_money", "set_chatbot_money"]) {
    assert.ok(build.includes(`"${c}"`), `build.rs is missing ${c}`);
    assert.ok(lib.includes(`chatbot_money::${c}`), `lib.rs is missing ${c}`);
    assert.match(read(`src-tauri/permissions/autogenerated/${c}.toml`), /allow-/);
  }
  // The conversation's own limits command is a different thing and still there.
  assert.ok(lib.includes("chatbot_limits"), "brain/chatbot.rs's own command was renamed");
});

await check("CONTROL: every write is held on a stale link, and a raise waits", () => {
  const rs = read("src-tauri/src/chatbot_money.rs");
  const fn = rustFn(rs, "set_chatbot_money");
  assert.match(fn, /stale\(&app\)/, "the write is not held on a stale link");
  assert.match(fn, /RAISE_TIMEOUT/, "a raise does not get the long timeout");
  assert.match(fn, /READ_TIMEOUT/, "a tightening gets the short timeout");
  assert.match(fn, /body\.get\("action"\)/, "the timeout is not read from the built body");
  assert.doesNotMatch(rustFn(rs, "chatbot_money"), /stale\(/, "a read is held on a stale link");
});

await check("CONTROL: no key can travel through this route at all", () => {
  const rs = read("src-tauri/src/chatbot_money.rs");
  // Code only: the module's own notes say why a key has nothing to do with it,
  // and a comment must not be read as an instruction to carry one.
  const flat = codeOnly(rs).replace(/\s+/g, " ");
  assert.doesNotMatch(flat, /api.?key/i, "the money module's code names a key");
  assert.doesNotMatch(flat, /KEY_TARGETS|Credential Manager|read_key|search_key/);
  // The body is built from named fields only, never forwarded.
  const body = rustFn(rs, "limit_body");
  assert.match(body, /serde_json::Map::new\(\)/);
  assert.doesNotMatch(body, /json!\(body\)|raw_body/);
});

await check("CONTROL: the PC's own pc_only words are passed on, not replaced", () => {
  const rs = read("src-tauri/src/chatbot_money.rs");
  const refusal = rustFn(rs, "refusal");
  assert.match(refusal, /"message"/, "the PC's own message is not read");
  assert.match(refusal, /backend_refusal/, "there is no fallback for a body without one");
  const js = read("src/chatbot-api-keys-settings.js");
  assert.match(js, /problemWords\(error\)/, "a refusal is not shown as the PC's words");
});

await check("CONTROL: /api/chatbot/money is classified desktop-only, with its reason", () => {
  const parity = readRepo("tools/check_parity.py");
  const m = /"\/api\/chatbot\/money": \("([a-z-]+)", "([^"]{80,})"\)/.exec(parity);
  assert.ok(m, "check_parity.py does not classify /api/chatbot/money");
  assert.equal(m[1], "deliberate", "the phone would raise a money limit");
  assert.match(m[2], /Windows Hello/);
  assert.match(m[2], /pc_only/);
  assert.match(m[2], /raise_api_limit/);
});

await check("CONTROL: the page never writes innerHTML, and never shows a key", () => {
  for (const f of ["src/chatbot-api-keys.js", "src/chatbot-api-keys-settings.js"]) {
    const src = read(f);
    assert.doesNotMatch(src, /innerHTML/, f);
    assert.doesNotMatch(src, /localStorage|sessionStorage|indexedDB/, `${f} stores something`);
  }
  const js = read("src/chatbot-api-keys-settings.js");
  // The money half must not touch the key box's own value.
  const money = jsFn(js, "moneyRow");
  assert.ok(money, "moneyRow is gone");
  assert.doesNotMatch(money, /save_chatbot_api_key|password/, "the money row touches the key");
});

await check("CONTROL: the card's own ids and jump link are the ones the page looks for", () => {
  const html = read("src/settings.html");
  for (const id of ["cak-body", "cak-status", "cak-estimates", "cak-raise-words"]) {
    assert.ok(html.includes(`id="${id}"`), id);
  }
  assert.match(html, /<section class="card" id="chatbot-api-keys">/);
});

/** Code only: `//` and `///` comment lines dropped. A comment that says "this
 *  never carries a key" must not be read as a check that fails. */
function codeOnly(src) {
  return src.split("\n").filter((l) => !/^\s*\/\//.test(l)).join("\n");
}

/** A Rust function's own body, braces counted. */
function rustFn(src, name) {
  const m = new RegExp(
    `\\b(?:pub(?:\\([^)]*\\))?\\s+)?(?:async\\s+)?fn\\s+${name}\\s*[(<]`
  ).exec(src);
  assert.ok(m, `${name} is not in the file`);
  const start = m.index;
  let i = src.indexOf("{", m.index + m[0].length);
  let depth = 0;
  for (let j = i; j < src.length; j += 1) {
    if (src[j] === "{") depth += 1;
    else if (src[j] === "}") {
      depth -= 1;
      if (depth === 0) return src.slice(start, j + 1);
    }
  }
  throw new Error(`${name} has no closing brace`);
}

/** A JavaScript function's own body, braces counted. */
function jsFn(src, name) {
  const m = new RegExp(`(?:async\\s+)?function\\s+${name}\\s*\\(`).exec(src);
  if (!m) return "";
  const start = m.index;
  let i = src.indexOf("{", m.index);
  let depth = 0;
  for (let j = i; j < src.length; j += 1) {
    if (src[j] === "{") depth += 1;
    else if (src[j] === "}") {
      depth -= 1;
      if (depth === 0) return src.slice(start, j + 1);
    }
  }
  throw new Error(`${name} has no closing brace`);
}

if (fails.length) {
  console.log(`\n${fails.length} failed: ${fails.join(", ")}`);
  process.exit(1);
}
console.log(
  "\nChatbot money limits: a raise is one card plus Windows Hello, a lowering is not, " +
    "and every price says where it came from"
);
