/**
 * The job list on the desktop (JARVIS-API section 116).
 *
 * `backend/jarvis_tasks.py` is the durable queue; this is how the Brain's Work
 * tab reaches it. Four files have to agree, and none of them can see the
 * others at runtime:
 *
 *   backend/jarvis_tasks.py     what the payload contains (counted only)
 *   src-tauri/src/brain/routes.rs   the read allowlist ("tasks" -> /api/tasks)
 *   src-tauri/src/brain.rs          brain_task_act, the only steering command
 *   src/brain.js                    renderTaskList, drawn under the jobs
 *
 * TWO PARTS, ON PURPOSE. The CONTROL checks need no browser: they read those
 * files as text and hold each other honest, including a cross-check that what
 * `status()` sends is exactly what `renderTaskList` reads. They run anywhere.
 * The DOM checks need Chromium, so they are attempted only when Playwright is
 * actually importable and otherwise say so and pass - the shape the repo's own
 * bug audit (F2, 2026-10-05) asked every suite to use, after `uikit.mjs`
 * killed `test:ui` at suite 10 and silently dropped the 46 after it.
 *
 * WHAT THIS SUITE IS REALLY FOR. Two claims, both easy to lose in a later
 * edit: the Brain can STEER a job but can never APPROVE anything through this
 * feature, and the reply carries NO task title and no step text, so this pane
 * cannot become a new way for private words to reach a screen.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(HERE, "..", p), "utf8");

const fails = [];
const check = async (name, fn) => {
  try {
    await fn();
    console.log(`ok    ${name}`);
  } catch (e) {
    fails.push(name);
    console.log(`FAIL  ${name}\n      ${e.message}`);
  }
};

const ROUTES = read("src-tauri/src/brain/routes.rs");
const BRAIN_RS = read("src-tauri/src/brain.rs");
const LIB_RS = read("src-tauri/src/lib.rs");
const SURFACES = read("src-tauri/permissions/surfaces.toml");
const GENERATED = read("src-tauri/permissions/autogenerated/brain_task_act.toml");
const BRAIN_JS = read("src/brain.js");
const PY = read("../backend/jarvis_tasks.py");
const CHAIN = read("package.json");

/* ── 1. The read allowlist ───────────────────────────────────────────────── */

await check("the Brain may read the job list, by the name it asks for", () => {
  assert.match(ROUTES, /\("tasks",\s*"\/api\/tasks"\)/);
});

await check("the read grant can never reach a steering action", () => {
  // Both are POSTs the UI must go through brain_task_act to reach. The
  // allowlist test in routes.rs asserts the same thing from the Rust side;
  // this asserts the test still knows about them.
  assert.match(ROUTES, /"\/api\/tasks\/act",/);
  assert.match(ROUTES, /"\/api\/tasks\/input",/);
  const writes = ROUTES.slice(ROUTES.indexOf("const WRITES"));
  assert.ok(writes.includes("/api/tasks/act"), "act is not in the WRITES guard");
  assert.ok(writes.includes("/api/tasks/input"), "input is not in the WRITES guard");
});

/* ── 2. The one steering command ─────────────────────────────────────────── */

await check("the steering command is gated on a live link", () => {
  const fn = BRAIN_RS.slice(BRAIN_RS.indexOf("pub async fn brain_task_act"));
  const body = fn.slice(0, fn.indexOf("\n}\n"));
  assert.match(body, /require_link_live\(&app\)\?/,
    "steering a job list that cannot be confirmed live risks acting on work that has finished");
});

await check("only pause, resume, cancel, retry and an answer are accepted", () => {
  const fn = BRAIN_RS.slice(BRAIN_RS.indexOf("pub async fn brain_task_act"));
  assert.match(fn, /"pause" \| "resume" \| "cancel" \| "retry"/);
  assert.match(fn, /"input" =>/);
  assert.match(fn, /is not something that can be done to a job/,
    "an unknown act must be refused in words, not guessed at");
});

await check("the steering command can never approve anything", () => {
  const fn = BRAIN_RS.slice(BRAIN_RS.indexOf("pub async fn brain_task_act"));
  const body = fn.slice(0, fn.indexOf("\n}\n"));
  for (const banned of ["/api/approve", "/api/deny", "answer_approval", "brain_approve"]) {
    assert.ok(!body.includes(banned), `brain_task_act reaches ${banned}`);
  }
  // And the only paths it may post to are the two job-list routes.
  const paths = [...body.matchAll(/"(\/api\/[a-z/]+)"/g)].map((m) => m[1]);
  assert.deepEqual(paths.sort(), ["/api/tasks/act", "/api/tasks/input"]);
});

await check("the command is registered, so the page can call it at all", () => {
  assert.match(LIB_RS, /brain::brain_task_act,/);
});

/* ── 3. The grant ────────────────────────────────────────────────────────── */

await check("the generated permission names the command and nothing else", () => {
  assert.match(GENERATED, /identifier = "allow-brain-task-act"/);
  assert.match(GENERATED, /commands\.allow = \["brain_task_act"\]/);
  assert.match(GENERATED, /identifier = "deny-brain-task-act"/);
  // The identifier Tauri expects is derived from the command name; a mismatch
  // is a build error, but this catches it before a 20-second compile does.
  assert.equal("allow-" + "brain_task_act".replace(/_/g, "-"), "allow-brain-task-act");
});

await check("the grant lives in brain-act, beside cancel and revert", () => {
  const set = SURFACES.slice(SURFACES.indexOf('identifier = "brain-act"'));
  const block = set.slice(0, set.indexOf("]]") === -1 ? set.length : set.indexOf("\n]"));
  assert.match(block, /"allow-brain-task-act",/);
  // And it grants nothing beyond that one command.
  assert.equal((block.match(/allow-brain-task-act/g) || []).length, 1);
});

/* ── 4. What the page draws ──────────────────────────────────────────────── */

await check("the Work tab reads the job list", () => {
  assert.match(BRAIN_JS, /work:\s*\["jobs",\s*"tasks",\s*"undo",\s*"gate_history"\]/);
});

await check("the job list is drawn into the jobs card, after its own rows", () => {
  assert.match(BRAIN_JS, /function renderTaskList\(\)/);
  const fn = BRAIN_JS.slice(BRAIN_JS.indexOf("function renderJobs()"));
  const body = fn.slice(0, fn.indexOf("\nfunction renderUndo()"));
  assert.match(body, /dom\.jobs\.append\(renderTaskList\(\)\);/,
    "rows() clears the container, so the block must be rebuilt on every renderJobs");
  // Both ways out of renderJobs have to append it, or a backend without
  // /api/jobs would hide the job list that it does have.
  assert.equal((body.match(/dom\.jobs\.append\(renderTaskList\(\)\);/g) || []).length, 2);
});

await check("the four steers and the answer are offered, and nothing else", () => {
  const fn = BRAIN_JS.slice(BRAIN_JS.indexOf("function renderTaskList()"));
  const body = fn.slice(0, fn.indexOf("\nfunction renderJobs()"));
  for (const act of ['"pause"', '"cancel"', '"resume"', '"retry"']) {
    assert.ok(body.includes(`act(t.id, ${act}`), `${act} is not offered`);
  }
  assert.match(body, /invoke\("brain_task_act"/);
  for (const banned of ["approve", "deny", "brain_approve", "answer_approval"]) {
    assert.ok(!body.toLowerCase().includes(banned),
      `renderTaskList mentions ${banned}, which this feature must never do`);
  }
});

/* ── 5. The two files' contract, without a backend ───────────────────────── */

await check("what status() sends is what renderTaskList reads", () => {
  const status = PY.slice(PY.indexOf("def status(self)"));
  const body = status.slice(0, status.indexOf("\n    def feed("));
  for (const key of ["counts", "waiting", "running", "blocked", "stop", "tasks"]) {
    assert.ok(body.includes(`"${key}"`), `status() does not send ${key}`);
  }
  for (const key of ["id", "state", "kind", "step", "steps", "attempts",
    "tools", "needs_attention", "question"]) {
    assert.ok(body.includes(`"${key}"`), `a task row does not carry ${key}`);
  }
  // Every one of those keys is read on the JS side, so a rename cannot pass.
  const js = BRAIN_JS.slice(BRAIN_JS.indexOf("function renderTaskList()"));
  for (const key of ["state", "steps", "tools", "kind", "attempts",
    "needs_attention", "question", "waiting", "running", "blocked", "stop"]) {
    assert.ok(js.includes(`t.${key}`) || js.includes(`body.${key}`),
      `renderTaskList never reads ${key}`);
  }
});

await check("the reply carries no task title and no step text", () => {
  const status = PY.slice(PY.indexOf("def status(self)"));
  const body = status.slice(0, status.indexOf("\n    def feed("));
  // The comment above status() says why; this makes it enforced. A title
  // added to the payload would be the owner's own words reaching a screen
  // through a pane whose whole rule is that it shows counts.
  assert.ok(!/"title"/.test(body), "status() sends a title");
  assert.ok(!/t\.goal/.test(body) && !/"goal"/.test(body), "status() sends the goal");
  assert.ok(!/"result"/.test(body), "status() sends step results");
  assert.ok(!/t\.done/.test(body), "status() sends completed steps");
});

/* ── 6. The shared contract, against the same file the phone reads ───────── */

await check("the desktop and the phone read the same generated cases", () => {
  // Written from the real module by tools/gen_tasks_cases.py, read by
  // TasksTest.kt on the phone. Reading it here too is what stops this being
  // one of those fixture pairs (the 2026-10-04 review counted 45) that no test
  // ever checks still agree.
  const cases = JSON.parse(read("tests/fixtures/tasks-cases.json")).cases;
  assert.deepEqual(Object.keys(cases).sort(),
    ["empty", "mixed", "older_backend", "title_is_ignored"]);
  const mixed = cases.mixed;
  assert.equal(mixed.expect.rows, mixed.answer.tasks.length);
  // Every field of a row is one renderTaskList reads, and no row carries a
  // title: the payload is counted only.
  for (const row of mixed.answer.tasks) {
    assert.ok(!("title" in row), "the payload carries a task title");
    assert.ok(!("result" in row) && !("done" in row), "the payload carries step text");
    for (const key of ["state", "steps", "tools"]) {
      assert.ok(key in row, `a row is missing ${key}`);
    }
  }
  assert.ok(mixed.answer.tasks.some((t) => t.needs_attention),
    "no case exercises the blocked path");
  // And the one that stopped to ask: the wire HAS to carry its question, or a
  // screen would say "needs an answer" with nothing to show.
  const asking = mixed.answer.tasks.find((t) => t.state === "waiting_input");
  assert.ok(asking, "no case exercises a job that stopped to ask");
  assert.equal(asking.needs_attention, true);
  assert.ok(asking.question.includes("order number"), asking.question);
});

await check("a job that stopped to ask gets a box, and only that job", () => {
  const fn = BRAIN_JS.slice(BRAIN_JS.indexOf("function renderTaskList()"));
  const body = fn.slice(0, fn.indexOf("\nfunction renderJobs()"));
  assert.match(body, /jobState === "waiting_input"/);
  assert.match(body, /el\("input", "task-answer"\)/);
  assert.match(body, /act\(t\.id, "input", value\)/);
  // The box is added to the ROW that asked, never to the block, so a job in
  // any other state cannot offer it.
  assert.ok(body.includes("entry.append(box)"), "the box is not added to its own row");
  assert.ok(!body.includes("block.append(box)"), "the box is added to the whole list");
  assert.ok(body.indexOf("entry.append(box)") > body.indexOf("const entry = row({"),
    "the box is added before the row exists");
});

/* ── 7. The DOM, when a browser is available ─────────────────────────────── */

let playwright = null;
try {
  playwright = await import("playwright");
} catch {
  console.log("\n      (the DOM checks need Playwright; skipping them here - they run in CI)");
}

if (playwright) {
  const K = await import("./uikit.mjs");
  const { base, close } = await K.serve();
  const browser = await K.launch();
  const PAYLOAD = {
    counts: { queued: 1, running: 1, blocked: 1 },
    waiting: 1,
    running: 1,
    blocked: 1,
    stop: false,
    tasks: [
      { id: "a".repeat(32), state: "running", kind: "plan", step: 2, steps: 3,
        attempts: 1, tools: ["web_search", "send_email", "notes_write"],
        needs_attention: false, question: "" },
      { id: "b".repeat(32), state: "blocked", kind: "plan", step: 1, steps: 2,
        attempts: 2, tools: ["send_email", "home_control"],
        needs_attention: true, question: "Step 1 (send_email) was part-way through." },
    ],
  };
  const page = await K.open(browser, base, "brain.html", {}, { width: 900, height: 1200 });
  await page.evaluate((payload) => {
    const core = window.__TAURI__.core;
    const invoke = core.invoke;
    window.__taskActs = [];
    core.invoke = async (cmd, args) => {
      if (cmd === "brain_read") {
        return args && args.section === "tasks" ? JSON.parse(JSON.stringify(payload)) : invoke(cmd, args);
      }
      if (cmd === "brain_task_act") {
        window.__taskActs.push(args);
        return { id: args.id, state: "paused" };
      }
      return invoke(cmd, args);
    };
  }, PAYLOAD);
  await page.evaluate(() => window.dispatchEvent(new Event("jarvis-link")));

  await check("the brain window draws the job list", async () => {
    const text = await page.evaluate(() => document.body.innerText);
    assert.match(text, /Job list:/);
    assert.match(text, /step 2 of 3/);
    assert.match(text, /web_search/);
  });

  await check("a blocked job shows its question and a Retry", async () => {
    const text = await page.evaluate(() => document.body.innerText);
    assert.match(text, /needs you/);
    assert.match(text, /was part-way through/);
    const buttons = await page.evaluate(() =>
      [...document.querySelectorAll(".tasks-block button")].map((b) => b.textContent));
    assert.ok(buttons.includes("Retry"), buttons.join(","));
    assert.ok(buttons.includes("Pause"), buttons.join(","));
    // Nothing in this pane may offer an approval.
    assert.ok(!buttons.some((b) => /approve|deny/i.test(b)), buttons.join(","));
  });

  await check("pressing Pause steers the job and sends nothing else", async () => {
    await page.evaluate(() => {
      [...document.querySelectorAll(".tasks-block button")]
        .find((b) => b.textContent === "Pause").click();
    });
    await page.waitForTimeout(50);
    const calls = await page.evaluate(() => window.__taskActs);
    assert.equal(calls.length, 1, JSON.stringify(calls));
    assert.equal(calls[0].act, "pause");
    assert.ok(calls[0].id);
  });

  await browser.close();
  await close();
}

console.log(`\n${fails.length ? "FAILED" : "ok"} - ${fails.length} failed`);
if (fails.length) {
  console.log(fails.map((f) => `  - ${f}`).join("\n"));
  process.exit(1);
}
