/**
 * The Watch tab's "What is new" block, fed what `jarvis_watch.py` really sends.
 *
 * THE BUG THIS SUITE EXISTS FOR (2026-10-09). `GET /api/watch/report` serves
 * `{available, new, updated, count, topics, note}` - the module splits its rows
 * by `kind`, and its own consumer reads `peek["new"] + peek["updated"]`
 * (`jarvis_watch.py:524`). Both apps read `findings`/`items` instead, which the
 * route has never served, and titled every row with `full_name`/`name`, which a
 * row does not have either. So:
 *
 *   - every SUCCESSFUL read came back as the empty list, and the block drew
 *     "Nothing new since you last marked the list read." over a list it had
 *     never read - a permanent false all-clear on the success path, while the
 *     badge above it was free to say "Watches · 3 new" at the same moment. The
 *     same class of lie as the notification all-clear fixed in #128;
 *   - every row was titled "(repository)";
 *   - `Mark these read` was greyed out with rows waiting.
 *
 * WHY IT WAS NEVER CAUGHT. The desktop's own fixture was the literal
 * `{"available": true, "findings": [...]}`, so the harness agreed with the
 * client and disagreed with the backend. A fixture written to match the bug
 * cannot catch the bug. The fixture this suite uses is generated by running the
 * REAL module (`tools/gen_watch_report_cases.py`), so it cannot be edited to
 * agree with a broken client: rename a key on either side and the client's read
 * comes back empty, and the checks below fail.
 *
 * The `top_level_keys` / `row_keys` lists in that file are the other half of the
 * guard: they are what the route actually serves, and the last check here fails
 * if this window reads a key outside them.
 */
import assert from "node:assert/strict";
import * as K from "./uikit.mjs";

const { base, close } = await K.serve();
const browser = await K.launch();
const fails = [];
const check = async (name, fn) => {
  try { await fn(); console.log(`ok    ${name}`); }
  catch (e) { fails.push(name); console.log(`FAIL  ${name}\n      ${e.message}`); }
};
const SIZE = { width: 1180, height: 900 };

async function watchTab(report) {
  const page = await K.open(browser, base, "brain.html",
    { brain: { ...K.BRAIN, watch_report: report } }, SIZE);
  // Watch is an advanced tab (`brain.html:132`), so the rail's Advanced
  // toggle has to be opened before its tab exists to click.
  await page.locator("#rail-advanced-toggle").click();
  await page.locator("#tab-watch").click();
  await page.waitForTimeout(300);
  return page;
}

/** The repos the module put in one generated case, in the order it sends them:
 *  `new` first, then `updated` - the order the module's own consumer uses. */
const served = (c) => [...c.new, ...c.updated].map((r) => r.repo);

/* ── The false all-clear ─────────────────────────────────────────────────── */

await check("rows the backend really sends are drawn, not 'nothing new'", async () => {
  const c = K.WATCH.cases.new_and_updated;
  assert.ok(c.new.length && c.updated.length,
    "this case must carry both kinds, or it does not exercise the split");
  const page = await watchTab({ available: true, ...c });
  const text = await page.locator("#watch-report").innerText();
  await page.close();

  for (const repo of served(c)) {
    assert.match(text, new RegExp(repo.replace(/[/.]/g, "\\$&")),
      `${repo} was served in new/updated and must be drawn`);
  }
  assert.doesNotMatch(text, /Nothing new since you last marked the list read/,
    "a report with rows in it must never draw the all-clear");
  assert.doesNotMatch(text, /\(repository\)/,
    "every row has a `repo`; a placeholder title means the served key was missed");
});

await check("an EMPTY report is the one answer that may draw the all-clear", async () => {
  const page = await watchTab({ available: true, ...K.WATCH.cases.empty });
  const text = await page.locator("#watch-report").innerText();
  await page.close();
  assert.match(text, /Nothing new since you last marked the list read/,
    "a read that answered with nothing in it is a real all-clear");
});

/* ── Mark these read ─────────────────────────────────────────────────────── */

await check("'Mark these read' is offered exactly when there is something to mark", async () => {
  const withRows = await watchTab({ available: true, ...K.WATCH.cases.new_and_updated });
  const on = await withRows.locator("#watch-seen").isDisabled();
  await withRows.close();
  assert.equal(on, false, "rows are waiting, so Mark these read must be offered");

  const marked = await watchTab({ available: true, ...K.WATCH.cases.after_mark_read });
  const off = await marked.locator("#watch-seen").isDisabled();
  await marked.close();
  assert.equal(off, true, "nothing is waiting, so it must be greyed");
});

/* ── The licence that means "no permission" ──────────────────────────────── */

await check("'none stated' is drawn as no licence, with the warning, not as a licence", async () => {
  const row = K.WATCH.cases.new_only.new.find((r) => r.licence === "none stated");
  assert.ok(row, "the generated fixture must carry a repository with no licence file");

  const page = await watchTab({ available: true, ...K.WATCH.cases.new_only });
  const text = await page.locator("#watch-report").innerText();
  await page.close();

  assert.match(text, /no licence stated - no permission to use it/,
    "'none stated' is the module's words for a repository with no licence: " +
    "it must draw the warning, not a settled licence");
  assert.match(text, /no licence/, "and its tag must not read as a licence it has not got");
  // The whole point: the two words must not be shown back as though they were a
  // licence. (The tag is upper-cased in CSS, hence the `i`.)
  assert.doesNotMatch(text, /licence: none stated/i,
    "'none stated' must never be drawn as a licence name");

  const stated = K.WATCH.cases.new_only.new.filter((r) => r.licence && r.licence !== "none stated");
  assert.ok(stated.length, "the fixture must also carry real licences, or this proves nothing");
  for (const r of stated) {
    assert.match(text, new RegExp(r.licence.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"),
      `${r.repo}'s real licence (${r.licence}) must still be shown, not warned about`);
    assert.doesNotMatch(text, new RegExp(`no licence stated[^\\n]*${r.repo}`, "i"),
      `${r.repo} has a licence - it must not carry the no-permission warning`);
  }
});

/* ── Read nothing into a body nobody can read ────────────────────────────── */

await check("a 200 in a shape this window does not know says so, and never says nothing is new", async () => {
  // A 200 with none of the four keys the two shapes use: the route answering
  // successfully is not the same as the route answering with a list.
  const page = await watchTab({ available: true, ok: true, items_count: 4, list: [] });
  const text = await page.locator("#watch-report").innerText();
  const disabled = await page.locator("#watch-seen").isDisabled();
  await page.close();

  assert.match(text, /Could not read what is new/,
    "an unreadable body is not a report of nothing new - the block must say it could not read");
  assert.doesNotMatch(text, /Nothing new since you last marked the list read/,
    "and it must NOT borrow the reassuring sentence for a read that did not happen");
  assert.equal(disabled, true, "there is nothing on screen to mark read");
});

await check("the tolerant fallback still reads a body shaped as findings/items", async () => {
  // Kept deliberately, so a future backend renaming `new`/`updated` does not
  // silently empty the list. This is the OLD fiction's shape - it is read as a
  // fallback, never as the primary, and the generated-fixture checks above are
  // what fail if the primary read ever goes back to it (2026-10-09).
  const page = await watchTab({
    available: true,
    findings: [{ full_name: "example/reactor-faces", licence: "MIT", descr: "older shape" }],
  });
  const text = await page.locator("#watch-report").innerText();
  await page.close();
  assert.match(text, /example\/reactor-faces/, "the fallback shape must still be read");
  assert.match(text, /older shape/, "including its own description key");
  assert.doesNotMatch(text, /Nothing new since you last marked the list read/,
    "a body with rows in it is never the all-clear, whichever shape it arrived in");
});

/* ── The drift guard itself ──────────────────────────────────────────────── */

await check("the generated fixture is the route's own shape, and this window reads no other key", async () => {
  // What the module's `report()` and the route wrapper really answer.
  assert.deepEqual(K.WATCH.top_level_keys,
    ["available", "count", "new", "note", "topics", "updated"],
    "the route's top-level keys changed: the fixture is generated from the module, " +
    "so this failing means the backend moved, not this test");
  assert.deepEqual(K.WATCH.row_keys,
    ["archived", "at", "description", "kind", "licence", "repo", "stars", "topic",
      "url", "what_changed"],
    "a row's keys changed: both apps read this shape, so they must be updated with it");

  // Every key this window names for a report or a row, taken from the source
  // itself - so a NEW read of a key the backend does not serve fails here even
  // if the key happens to be absent from today's fixture.
  const src = await (await import("node:fs/promises"))
    .readFile(new URL("../src/brain.js", import.meta.url), "utf8");
  const body = src.slice(src.indexOf("function renderWatchReport()"));
  const fn = body.slice(0, body.indexOf("\nfunction ", 10));
  const named = [...new Set([...fn.matchAll(/\b(?:body|f)\.([a-z_]+)/g)].map((m) => m[1]))];
  const servedKeys = new Set([...K.WATCH.top_level_keys, ...K.WATCH.row_keys]);

  // The keys that are neither served nor read by accident. Each one is a
  // DELIBERATE tolerant fallback, kept so a future backend renaming these keys
  // keeps working - so this list is a decision, and growing it silently is what
  // this check refuses. None of them is served today (2026-10-09): they are
  // exactly what both apps used to read INSTEAD of the real shape.
  const fallbacks = ["findings", "items", "full_name", "name", "license", "descr", "note"];
  assert.deepEqual(named.filter((k) => !servedKeys.has(k) && !fallbacks.includes(k)), [],
    "renderWatchReport reads a key neither the route nor a row serves, and it is not " +
    "one of the documented fallbacks - that is exactly how both apps came to read " +
    "`findings`/`items` (2026-10-09)");

  // The other half, and the one that matters most: the window must actually
  // read what IS served. Deleting these reads is the original bug, and the
  // fixture above cannot notice on its own.
  for (const key of ["new", "updated"]) {
    assert.ok(named.includes(key),
      `renderWatchReport no longer reads \`${key}\`, which is half of what the ` +
      "route serves - the list would quietly empty and the block would say " +
      "'nothing new' over rows that are waiting (2026-10-09)");
  }
  assert.ok(/\bf\.repo\b/.test(fn),
    "the window no longer reads a row's `repo`, which is what the route names a " +
    "repository - every row would be titled '(repository)' again (2026-10-09)");
});

await browser.close();
close();
console.log(fails.length ? `\n${fails.length} failed: ${fails.join(", ")}`
  : "\nWatch reads what the backend sends");
process.exit(fails.length ? 1 : 0);
