#!/usr/bin/env python3
"""Compare the desktop's registered commands against build.rs's own ACL
export list, and fail when the two disagree.

    python3 tools/check_command_acl.py

build.rs's own doc comment states the rule: "Anything added to
generate_handler! in lib.rs must be added here too, or it is reachable
from nowhere and the failure is a runtime 'not allowed on window' rather
than a compile error." Nothing before this script checked that rule at
build time - it was found by hand, once, by a bug audit (2026-09-27,
desktop-rust finding #2), for two commands (crash_notes, find_python) that
had NO permission file at all, and three more (chat_sources,
get_tool_updates, check_tool_updates) that worked only because someone had
separately hand-committed matching files under permissions/autogenerated/
to paper over the same gap. Nothing caught either drift as it happened;
this does, the same way tools/check_parity.py catches the desktop and
phone drifting apart.

What it reads - all from THIS checkout:

  jarvis-desktop/src-tauri/src/lib.rs      the tauri::generate_handler!
                                            list - every command Tauri can
                                            actually dispatch to
  jarvis-desktop/src-tauri/build.rs        the .commands(&[...]) list -
                                            every command build.rs turns
                                            into an allow-*/deny-* pair

A command registered in lib.rs but missing from build.rs has no
permission at all, and every window's call to it is refused by the ACL -
this is finding #2's exact class of bug. The reverse (a name in build.rs
that lib.rs no longer registers) is dead ACL surface, not a functional
break, but is still reported: it is either a stale entry or a sign
build.rs and lib.rs were edited by two different pieces of work that never
saw each other.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_TAURI = REPO / "jarvis-desktop" / "src-tauri"


def commands_from_lib_rs(text: str) -> set[str]:
    marker = ".invoke_handler(tauri::generate_handler!["
    start = text.index(marker) + len(marker)
    end = text.index("\n        ]);", start)
    block = text[start:end]
    names = set()
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        # Each entry is `module::path::function_name,` - Tauri registers a
        # command under its function's own name, not the module path it was
        # written at, so only the last `::` segment is the real command id.
        path = line.rstrip(",").strip()
        if not re.fullmatch(r"[\w:]+", path):
            raise ValueError(f"unexpected line inside generate_handler!: {line!r}")
        names.add(path.rsplit("::", 1)[-1])
    return names


def commands_from_build_rs(text: str) -> set[str]:
    marker = ".commands(&["
    start = text.index(marker) + len(marker)
    end = text.index("\n        ]));", start)
    block = text[start:end]
    names = set()
    for line in block.splitlines():
        line = line.strip()
        # Comments here often quote a permission-set or setting name
        # ("approvals", "shopping", ...) that is not a command at all.
        if not line or line.startswith("//"):
            continue
        names.update(re.findall(r'"([a-z][a-z0-9_]*)"', line))
    return names


def main() -> int:
    lib_rs = (SRC_TAURI / "src" / "lib.rs").read_text()
    build_rs = (SRC_TAURI / "build.rs").read_text()

    registered = commands_from_lib_rs(lib_rs)
    exported = commands_from_build_rs(build_rs)

    missing_from_build_rs = sorted(registered - exported)
    stale_in_build_rs = sorted(exported - registered)

    if missing_from_build_rs:
        print("::error::Registered in lib.rs's generate_handler! but missing "
              "from build.rs's own commands list - refused by the ACL from "
              "every window:")
        for name in missing_from_build_rs:
            print(f"  {name}")
    if stale_in_build_rs:
        print("::error::Listed in build.rs but no longer registered in "
              "lib.rs's generate_handler! - dead ACL surface, or the two "
              "were edited by work that never saw each other:")
        for name in stale_in_build_rs:
            print(f"  {name}")

    if missing_from_build_rs or stale_in_build_rs:
        return 1
    print(f"{len(registered)} commands, generate_handler! and build.rs agree.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
