#!/usr/bin/env python3
"""Every command a page calls must be granted to the window that shows it.

    python3 tools/check_invoke_grants.py [-v]

This is the check for a whole class of bug this tree has already shipped:
a feature whose button calls a Tauri command the ACL does not grant, so the
call is refused at runtime and the button silently does nothing - no compile
error, no test failure, just a control that never works. Two of them are in
this tree today and are exactly what this script exists to print:

  * `brain.js`'s "Hidden menus" button calls `open_fix_place`, which lives in
    `surfaces.toml` under the quickbar's own set. The Brain's capability never
    grants it, so the button was dead in the window that draws it.
  * `brain.js` calls the four `brain_quiz_cloud_*` commands, each of which has
    a generated permission file under permissions/autogenerated/ and no grant
    in any set at all: every window's call is refused.

Nothing before this script compared the two halves. `tools/check_command_acl.py`
checks that a command registered in lib.rs has a permission FILE, which is
necessary and not sufficient: the file also has to be in a set, and the set has
to be granted to the capability of the window whose page makes the call.

What it reads - all from THIS checkout:

  jarvis-desktop/src/**/*.js, *.html   the pages and the modules they load
  src-tauri/permissions/surfaces.toml  the sets, and the allow-* in each
  src-tauri/capabilities/*.json        which window is granted which set
  src-tauri/tauri.conf.json            the two windows declared there
  src-tauri/src/**/*.rs                every other window, and the page it
                                        loads (WebviewWindowBuilder)

Two things it cannot decide, both of which it says out loud rather than
guessing:

  * a command NAME built at runtime (`invoke(command)`). The call site is
    listed in DYNAMIC_BELOW with a one-line reason, so a new one has to be
    added deliberately rather than arriving unnoticed.
  * a module loaded by more than one window (`jarvis-link.js` is loaded by
    seven of them). One window's capability cannot judge the whole file, so
    only the parts the window's OWN code calls are judged against it. The
    count is printed so the gap stays visible.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "jarvis-desktop" / "src"
SRC_TAURI = REPO / "jarvis-desktop" / "src-tauri"

# Every spelling of the IPC entry point this tree uses. `tauriCore` is the
# HUD's own copy of `window.__TAURI__.core`; `core` is the three panels that
# take `globalThis.__TAURI__.core` into a local of that name first
# (forget-range-panel.js, progress-panel.js, projects-panel.js). Leaving
# either out would have made the one page whose events are already known to be
# broken - and three panels' worth of calls - invisible to this check too.
INVOKE = re.compile(r"(?:\bTAURI\.core|\btauriCore|__TAURI__\.core|\bcore|\bTAURI)\.invoke\s*\(")

# A call site whose first argument is not a literal is put against this list.
# Key: (file, first argument as written). Value: the one-line reason.
#
# Each entry is a page's OWN wrapper around `TAURI.core.invoke`, and the
# wrapper exists so that every real call site in that page can be a plain
# `invoke("name")` - which this script reads as a literal and checks. So the
# reason is always the same shape: the name is a parameter here, and the
# literal names passed to it are checked above.
DYNAMIC_BELOW = {
    ("brain.js", "command"): "brain.js's own invoke(command, args) wrapper; every caller passes a literal.",
    ("brain.js", "cmd"): "the second layer above it - topicsCall, chatbotAct, supportAct, quizCall, decksCall, memoryWrite, widgetAct - each forwards a name its callers pass as a literal.",
    ("brain.js", "sw.command"): "AUTO_SWITCHES[which].command, from auto-learn.js's own two-entry table (brain_memory_learning_auto and brain_memory_learning_sensitive, both in the brain-memory set granted to this window).",
    ("main.js", "command"): "the Jarvis bar's invoke(command, args) and invokeStrict(command, args); every caller passes a literal.",
    ("widget.js", "command"): "the widget's invoke(command, args) and invokeStrict(command, args); every caller passes a literal.",
    ("settings.js", "command"): "the settings window's invoke(command, args); every caller passes a literal.",
    ("tutorials.js", "name"): "tutorials.js's own invoke(name, args); every caller passes a literal.",
    ("live-badge.js", "command"): "the Live badge's invoke(command, args); every caller passes a literal.",
    ("watch-badge.js", "command"): "the watch badge's invoke(command, args); every caller passes a literal.",
    ("floating.js", "command"): "the floating face's invoke(command, args); every caller passes a literal.",
    ("forget-range-panel.js", "command"): "the panel's invoke(command, args); every caller passes a literal.",
    ("progress-panel.js", "command"): "the panel's invoke(command, args); every caller passes a literal.",
    ("projects-panel.js", "command"): "the panel's invoke(command, args); every caller passes a literal.",
    ("account-secrets-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("briefing-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("folders-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("hardware-panel.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("manner-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("notifications-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("sky-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("spending-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("thinking-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("voice-panel.js", "command"): "the voice panel's invoke(command, args); every caller passes a literal.",
    ("web-search-settings.js", "command"): "a settings panel's invoke(command, args); every caller passes a literal.",
    ("sky-feed.js", "c"): "the feed's own (c, a) => TAURI.core.invoke(c, a); the caller passes a literal.",
    ("jarvis_hud.html", "c"): "the HUD relays the face modules' calls through this arrow; the page holds hud-link.",
}


# ---------------------------------------------------------------------------
#   Reading the pages: what is code, and what is only text that looks like it
# ---------------------------------------------------------------------------

def code_mask(src: str) -> list[bool]:
    """True at each offset that is real JavaScript, False inside a comment, a
    string, a template's text or a regex literal.

    Without this, a page's own log line - `console.error(`[jarvis] invoke(
    "${command}") failed:`)` - reads as a call to a command called
    `${command}`, and the console message would have to be listed as a
    dynamically built name. Offsets are untouched, so reported line numbers
    still point at the real line (the same trick as check-tokens.py).
    """
    mask = [True] * len(src)
    i, n = 0, len(src)
    prev = ""            # last real code character, for the regex-literal guess
    while i < n:
        c = src[i]
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                mask[i] = False
                i += 1
        elif c == "/" and i + 1 < n and src[i + 1] == "*":
            end = src.find("*/", i + 2)
            end = n if end < 0 else end + 2
            for j in range(i, end):
                if src[j] != "\n":
                    mask[j] = False
            i = end
        elif c in "\"'`":
            quote = c
            i += 1
            while i < n:
                if src[i] == "\\":
                    mask[i] = False
                    i += 2
                    continue
                if src[i] == quote:
                    i += 1
                    break
                if quote == "`" and src[i] == "$" and i + 1 < n and src[i + 1] == "{":
                    # ${ ... } is code again: skip the balanced braces, leaving
                    # the mask alone inside them.
                    depth = 1
                    i += 2
                    while i < n and depth:
                        if src[i] == "{":
                            depth += 1
                        elif src[i] == "}":
                            depth -= 1
                        i += 1
                    continue
                if src[i] != "\n":
                    mask[i] = False
                i += 1
        elif c == "/" and prev in "(,=:[!&|?{};+-*%~^<>" and not src.startswith("/=", i):
            i += 1
            while i < n and src[i] != "\n":
                if src[i] == "\\":
                    i += 1
                elif src[i] == "/":
                    i += 1
                    break
                i += 1
        else:
            if not c.isspace():
                prev = c
            i += 1
    return mask


def arguments(src: str, start: int) -> list[str]:
    """The top-level arguments of the call whose `(` is at `start`.

    Scanning begins just past that `(`, or every comma inside the call reads as
    nested one level too deep and the first "argument" comes back as the whole
    call: that is how `invoke("browser_engine", { action: "read" })` was read
    as a command called `read`.
    """
    out, depth, i, begin = [], 1, start + 1, start + 1
    while i < len(src) and depth:
        c = src[i]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                break
        elif c == "," and depth == 1:
            out.append(src[begin:i])
            begin = i + 1
        i += 1
    out.append(src[begin:i])
    return out


def blocks(src: str) -> list[tuple[str, int, int]]:
    """(name, start, end) for each top-level function or arrow const, so a call
    inside a shared module can be attributed to the name a page would call."""
    out = []
    for m in re.finditer(r"^(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)",
                         src, re.M):
        brace = src.find("{", m.end())
        if brace > 0:
            out.append((m.group(1), m.start(), _close(src, brace)))
    for m in re.finditer(r"^(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=", src, re.M):
        end = src.find("\n", m.end())
        # An arrow or a function expression keeps going to its closing brace.
        arrow = re.search(r"=>\s*\{", src[m.end():m.end() + 200])
        if arrow:
            end = _close(src, m.end() + arrow.end() - 1)
        out.append((m.group(1), m.start(), end))
    return sorted(out, key=lambda b: b[1])


def _close(src: str, brace: int) -> int:
    depth, i = 0, brace
    while i < len(src):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return len(src) - 1


def functions(src: str) -> list[tuple[str, list[str], int, int]]:
    """(name, parameters, definition start, definition end) for each function
    this file defines, whichever of the two shapes it is written in.

    The span starts at the definition rather than at its `{`, so that a call
    scan can tell `function invoke(command)` - the definition - from
    `invoke("get_theme")`, a call.
    """
    out = []
    for m in re.finditer(r"(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)", src):
        brace = src.find("{", m.end())
        if brace < 0:
            continue
        out.append((m.group(1), _params(m.group(2)), m.start(), _close(src, brace)))
    for m in re.finditer(r"(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=", src):
        # The arrow is not always the first thing after the `=`: sky-feed.js
        # writes `const call = invoke || (IS_TAURI ? (c, a) => ...invoke(c, a)
        # : null)`, and the name a page calls is still `call`. A head carrying
        # a `{` is an object literal whose member is the arrow - not this
        # name - so it is refused rather than guessed at.
        head = src[m.end():m.end() + 200]
        arrow = re.search(r"\(([^)]*)\)\s*=>", head)
        if not arrow or re.search(r"[{};]", head[:arrow.start()]):
            continue
        brace = src.find("{", m.end() + arrow.end())
        if brace < 0 or brace > m.end() + 400:
            continue
        out.append((m.group(1), _params(arrow.group(1)), m.start(), _close(src, brace)))
    return out


def _params(text: str) -> list[str]:
    return [p.strip().split("=")[0].strip() for p in text.split(",") if p.strip()]


def helpers(src: str, mask: list[bool]) -> dict[str, tuple[int, int]]:
    """{function name: (definition start, definition end)} for every function
    that hands a command name of its own on to the IPC - directly, or through
    another such function.

    This is what makes the check reach the commands behind the wrappers.
    Every page keeps one `invoke(command, args)`, so its real call sites read
    `invoke("get_theme")`; reading only `TAURI.core.invoke(...)` would have
    missed all four `brain_quiz_cloud_*` calls and a hundred others. brain.js
    then adds a SECOND layer - `topicsCall(cmd, args)`, `chatbotAct(cmd,
    args)`, `decksCall(cmd, args)` and friends - and following only the bottom
    layer would leave every `topicsCall("brain_topics_mode")` unchecked, which
    is the same class of bug one level down.
    """
    defs = functions(src)
    found: dict[str, tuple[int, int]] = {}
    for _ in range(3):                       # a chain this deep is a rewrite
        added = False
        for name, params, begin, end in defs:
            if name in found or not params:
                continue
            body = src[begin:end + 1]
            by = None
            call = INVOKE.search(body)
            if call:
                by = arguments(body, call.end() - 1)
            for other in found:
                call = re.search(r"(?<![\w$.])" + re.escape(other) + r"\s*\(", body)
                if by is None and call:
                    by = arguments(body, call.end() - 1)
            if by and by[0].strip() == params[0]:
                found[name] = (begin, end)
                added = True
        if not added:
            break
    return found


def calls(src: str) -> list[tuple[int, int, str]]:
    """(line, offset, first argument as written) for every IPC call site.

    Both spellings count: `TAURI.core.invoke("name", ...)`, and a call to one
    of the file's own forwarding helpers with a literal first argument.
    """
    mask = code_mask(src)
    found = [(m.start(), arguments(src, m.end() - 1))
             for m in INVOKE.finditer(src) if mask[m.start()]]
    for name, (begin, end) in helpers(src, mask).items():
        for c in re.finditer(r"(?<![\w$.])" + re.escape(name) + r"\s*\(", src):
            if not mask[c.start()] or begin <= c.start() <= end:
                continue                     # the definition, not a call
            found.append((c.start(), arguments(src, c.end() - 1)))
    out = []
    for at, args in sorted(found):
        if args:
            out.append((src[:at].count("\n") + 1, at, args[0].strip()))
    return out


def command_names(arg: str) -> tuple[list[str], bool]:
    """The command names a call site can reach, and whether it is opaque.

    `"get_theme"` is one name. `fromServer ? "get_appearance" :
    "appearance_snapshot"` is two - that is a choice between two commands, not
    a name built at runtime, and both need a grant. `command` is neither: it
    is the dynamic case, and the allow-list above is what makes it deliberate.
    """
    one = re.fullmatch(r'"([a-z0-9_]+)"', arg)
    if one:
        return [one.group(1)], False
    names = [s for s in re.findall(r'"([a-z0-9_]+)"', arg) if re.fullmatch(r"[a-z][a-z0-9_]*", s)]
    if names:
        return names, False
    return [], True


# ---------------------------------------------------------------------------
#   Reading the ACL: which window is granted which allow-*
# ---------------------------------------------------------------------------

def sets_from_surfaces() -> dict[str, set[str]]:
    text = (SRC_TAURI / "permissions" / "surfaces.toml").read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r'\[\[set\]\]\s*identifier\s*=\s*"([^"]+)"(.*?)(?=\n\[\[set\]\]|\Z)',
                         text, re.S):
        out[m.group(1)] = set(re.findall(r'"(allow-[a-z0-9-]+)"', m.group(2)))
    return out


def capabilities() -> dict[str, tuple[tuple[str, ...], set[str]]]:
    out = {}
    for path in sorted((SRC_TAURI / "capabilities").glob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        out[path.stem] = (tuple(doc.get("windows") or ()), set(doc.get("permissions") or ()))
    return out


def windows_to_pages() -> dict[str, str]:
    """label -> the page that window loads.

    The two windows in tauri.conf.json are declared there; every other one is
    built in Rust by `WebviewWindowBuilder::new(app, LABEL, WebviewUrl::App(
    "page.html"))`. The label is usually a constant, and two modules each
    define their own `BADGE_LABEL` meaning different windows - so constants are
    resolved per file, never in one pool.
    """
    out: dict[str, str] = {}
    for path in sorted((SRC_TAURI / "src").rglob("*.rs")):
        text = path.read_text(encoding="utf-8", errors="replace")
        consts = dict(re.findall(r'const\s+([A-Z_][A-Z0-9_]*)\s*:\s*&str\s*=\s*"([^"]+)"', text))
        for m in re.finditer(r"WebviewWindowBuilder::new\s*\(", text):
            call = text[m.end() - 1:text.find(".build()", m.end()) if ".build()" in text else m.end() + 4000]
            args = arguments(call, 0)
            if len(args) < 3:
                continue
            label = args[1].strip()
            label = consts.get(label, label.strip('"'))
            direct = re.search(r'WebviewUrl::App\(\s*"([^"]+)"', call)
            if direct:
                page = direct.group(1)
            else:
                # The Brain does not write its page inside the builder: it
                # builds `let page = match place { Some(p) =>
                # format!("brain.html#{p}"), None => "brain.html" }` a few
                # lines above and passes the variable. Take the last page name
                # written before the builder - and where there is none, main()
                # says so rather than quietly judging no calls for that window.
                before = text[max(0, m.start() - 600):m.start()]
                found = re.findall(r'"([\w.-]+\.html)', before)
                page = found[-1] if found else None
            if page:
                out[label] = page.split("#")[0]
    conf = json.loads((SRC_TAURI / "tauri.conf.json").read_text(encoding="utf-8"))
    for window in conf.get("app", {}).get("windows", []):
        out.setdefault(window["label"], window["url"])
    return out


# ---------------------------------------------------------------------------
#   Reading the pages: which module each one loads
# ---------------------------------------------------------------------------

def imports_of(text: str) -> set[str]:
    return set(re.findall(r'from\s+"\./([\w.-]+\.js)"', text)) | \
        set(re.findall(r'import\(\s*"\./([\w.-]+\.js)"\s*\)', text))


def read(name: str) -> str:
    path = SRC / name
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def modules_of(page: str) -> set[str]:
    """Every module a page loads, following imports from the page itself."""
    seen: set[str] = set()
    stack = list(set(re.findall(r'<script[^>]*\bsrc="([^"]+)"', read(page))) | imports_of(read(page)))
    while stack:
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        stack.extend(imports_of(read(name)))
    return seen


def called_from(module: str, owner: str, texts: list[str]) -> bool:
    """Does any ONE of these files CALL `owner`, one of `module`'s exports?

    Under its imported name, never by bare word, and within the file that
    does the importing. Both halves matter:
      * `decide` is jarvis-link.js's approval decision AND the name of an
        unrelated pacing function in face-pace.js, and faces.html writes
        `FacePace.decide(...)` - matching the word alone reported the Faces
        window as answering approvals it has no UI to answer;
      * the widget defines its OWN `decide(approved)` while importing
        `amend as amendOnBackend` from jarvis-link.js - pooling every file of
        a page into one blob paired that import with the wrong call, and
        reported the widget as deciding approvals it decides locally.
    So the name has to be imported FROM THIS MODULE, in this file, as a
    destructured binding (`import { decide } from "./jarvis-link.js"`) or
    through a namespace (`import * as link from ...`), and then called here.
    """
    for text in texts:
        for m in re.finditer(r'import\s*\{([^}]*)\}\s*from\s*"\./' + re.escape(module) + r'"', text):
            for part in m.group(1).split(","):
                bits = [b.strip() for b in part.split(" as ")]
                if len(bits) < 1 or not bits[0]:
                    continue
                # The EXPORT is what has to match: brain.js imports `announce`
                # and calls it, and pairing that with `setMuted`'s own name
                # alone flagged every function in the module for every page
                # that imported anything from it at all.
                if bits[0] == owner and re.search(r"(?<![\w$.])" + re.escape(bits[-1]) + r"\s*\(", text):
                    return True
        for m in re.finditer(r'import\s*\*\s*as\s+([\w$]+)\s*from\s*"\./' + re.escape(module) + r'"', text):
            if re.search(re.escape(m.group(1)) + r"\s*\.\s*" + re.escape(owner) + r"\s*\(", text):
                return True
    return False


def granted_anywhere() -> set[str]:
    text = (SRC_TAURI / "permissions" / "surfaces.toml").read_text(encoding="utf-8")
    names = set(re.findall(r'"(allow-[a-z0-9-]+)"', text))
    for path in (SRC_TAURI / "capabilities").glob("*.json"):
        names |= set(re.findall(r'"(allow-[a-z0-9-]+)"', path.read_text(encoding="utf-8")))
    return names


def main() -> int:
    verbose = "-v" in sys.argv
    sets = sets_from_surfaces()
    caps = capabilities()
    label_page = windows_to_pages()
    any_grant = granted_anywhere()

    granted: dict[str, set[str]] = {}
    page_cap: dict[str, str] = {}
    problems: list[str] = []
    for cap, (labels, permissions) in caps.items():
        allowed: set[str] = set()
        for name in permissions:
            if name.startswith("core:"):
                continue
            allowed |= sets.get(name, set())
            if name.startswith("allow-"):
                allowed.add(name)
        for label in labels:
            granted[label] = allowed
            page = label_page.get(label)
            if page is None:
                problems.append(f"::error::capabilities/{cap}.json grants window "
                                f"{label!r}, but nothing here says which page it "
                                f"loads - this check cannot judge its calls")
            else:
                page_cap.setdefault(page, cap)

    pages = sorted(p.name for p in SRC.glob("*.html"))
    files = sorted(str(p.relative_to(SRC)).replace("\\", "/")
                   for p in SRC.rglob("*") if p.suffix in (".js", ".html"))
    loads: dict[str, int] = {}
    for page in pages:
        for name in modules_of(page):
            loads[name] = loads.get(name, 0) + 1
    shared = {name for name, n in loads.items() if n > 1}
    pages_of: dict[str, list[str]] = {}
    for label, page in label_page.items():
        pages_of.setdefault(page, []).append(label)

    checked: set[str] = set()
    violations: list[tuple[str, str, int, str, str | None]] = []
    dynamic: list[tuple[str, int, str, str]] = []

    for page in pages:
        cap = page_cap.get(page)
        # What THIS window is allowed to call - the whole point of the check.
        # `any_grant` below is the weaker "some set, somewhere" question, and
        # using it here is exactly how `open_fix_place` (granted to the
        # quickbar alone) looked fine from the Brain.
        allowed: set[str] = set()
        for label in pages_of.get(page, []):
            allowed |= granted.get(label, set())
        local = [name for name in modules_of(page) if name not in shared] + [page]
        local_text = [read(name) for name in local]
        for name in sorted(modules_of(page) | {page}):
            text = read(name)
            if not text:
                continue
            owners = blocks(text)
            for line, at, arg in calls(text):
                names, opaque = command_names(arg)
                if opaque:
                    dynamic.append((name, line, arg, page))
                    continue
                if name in shared:
                    # One window's capability cannot judge a module seven of
                    # them load: only what THIS page's own code reaches counts.
                    owner = next((b[0] for b in owners if b[1] <= at <= b[2]), None)
                    if owner is not None and not called_from(name, owner, local_text):
                        continue
                for command in names:
                    checked.add(command)
                    if not any_grant:
                        continue
                    permission = "allow-" + command.replace("_", "-")
                    if permission in allowed:
                        continue
                    violations.append((name, page, line, command, cap))

    # Every name the pages call anywhere, so a command with a permission file
    # and no grant is named even where the window itself looks fine.
    everywhere: dict[str, list[str]] = {}
    for name in files:
        text = read(name)
        if not text:
            continue
        for line, _at, arg in calls(text):
            names, opaque = command_names(arg)
            for command in names:
                everywhere.setdefault(command, []).append(f"{name}:{line}")

    ungranted = sorted(n for n in everywhere if "allow-" + n.replace("_", "-") not in any_grant)

    unknown_dynamic = sorted({(f, a) for f, _l, a, _p in dynamic if (f, a) not in DYNAMIC_BELOW})

    for line in problems:
        print(line)
    if ungranted:
        print("::error::Called by a page but granted by no set in surfaces.toml "
              "or capabilities/*.json - every window's call to it is refused:")
        for command in ungranted:
            where = ", ".join(everywhere[command][:3])
            print(f"  {command}  ({where})")
    if violations:
        print("::error::Called from a window whose capability does not grant it - "
              "the control that calls it does nothing, silently:")
        for name, page, line, command, cap in violations:
            where = f"capability {cap}" if cap else "no capability"
            print(f"  {command}  ({name}:{line}, reached from {page}; "
                  f"{where} has no allow-{command.replace('_', '-')})")
    if unknown_dynamic:
        print("::error::Called with a name built at runtime, and not on this "
              "script's own DYNAMIC_BELOW list - add it there with a one-line "
              "reason, or make the name a literal:")
        for name, arg in unknown_dynamic:
            print(f"  {name}  invoke({arg})")

    if problems or ungranted or violations or unknown_dynamic:
        return 1

    print(f"{len(everywhere)} command(s) invoked from {len(pages)} page(s); every one is "
          f"granted by the window whose page calls it.")
    print(f"{len(DYNAMIC_BELOW)} call site(s) pass a name built at runtime, each listed "
          f"in this script with its reason.")
    if shared:
        print(f"{len(shared)} module(s) are loaded by more than one window, so their calls "
              f"are judged only where the window's own code reaches them "
              f"({', '.join(sorted(shared)[:4])}, ...).")
    if verbose:
        for page in pages:
            print(f"  {page:<20} {len(modules_of(page)):>3} module(s), "
                  f"capability {page_cap.get(page, '(none)')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
