#!/usr/bin/env python3
"""Every place a tutorial's `where` line sends the owner must be a name the two
apps really have.

    python3 tools/check_tutorial_places.py [-v] [--catalogue PATH]

WHY THIS EXISTS

The 23 tutorials are written as steps, and each step carries a `where` line
naming the button, card or screen the owner should use. Those lines are read on
the phone and on the PC, by someone who is new to the app, and they are the
most confident sentences in the whole project: "Settings -> Stop everything",
"Brain -> Voice -> Your voice print". A line that names a control the app does
not have is worse than a broken test, because it is user-facing, it is wrong,
and it survives every check the project already has - the tutorials are data,
not code, so nothing compiles them and nothing reads them.

That is not hypothetical. While the last sixteen tutorials were being written,
an agent invented three button labels in its first draft and caught them itself
("Choose the folder...", "Picture mode", "Choose the .zip..." are the real
ones), and two more tutorials described screens that do not exist at all (the
phone's "Timeline", and "tap to talk" on the phone). Nothing in this repository
could have seen either. This is the check that sees them.

WHAT IT READS

  * `backend/jarvis_tutorials.py` - the real file, not a fixture. Every `where`
    string in the `CATALOGUE` tuple and in the `FAQ` tuple, read from the
    module's own syntax tree so the line number reported is the line the owner
    would edit. The FAQ is read as well as the tutorials because it is the same
    `where` convention on the same screen ("Tutorials and the FAQ"), served by
    the same routes, and a wrong line there is the same confident mistake.
  * the names the DESKTOP really draws:
      - `jarvis-desktop/src/menu-catalog.js` - the generated catalogue both
        apps share. It is generated by `tools/gen_menu_cases.py` from
        `backend/jarvis_menus.py` and CI runs `--check`, so it cannot drift from
        the menu list the apps actually use. Every menu title, every id, every
        group title and every alias is a name this app knows a thing by.
      - every `*.html` under `jarvis-desktop/src/` - the visible words: the
        `<title>`, every `<h2>`, `<h3>` and `<summary>`, and the text of every
        `<button>`. This is where the real button labels live
        (`Choose a folder...`, `Choose the .zip...`) and where the real section
        headings live (`Picture mode`, `Hands-free ("Hey Jarvis")`).
      - every `*.js` under `jarvis-desktop/src/`, for four label shapes only: a
        `title:` field, a constant whose own name ends `_LABEL` or `_TITLE`
        (`SENSITIVE_LABEL`), the text `node(...)`/`el(...)` puts on a control it
        builds (`Restore...`), and the values in the app's own word tables
        (`WORDS`, `LABELS`, `TEXT` - `projects.js`'s `WORDS.shareable`). NOT
        every string in them: those alone are 14,287, and that set swallows
        real drift - see gap 4 below.
  * the names the PHONE really draws:
      - `jarvis-client/.../net/MenuCatalog.kt` - the phone's copy of the same
        generated catalogue.
      - `jarvis-client/.../ui/MenuPlaces.kt` - the `item(key = ...)` names the
        phone's screens really draw a menu under.
      - `jarvis-client/.../ui/Nav.kt` - the `Screen` enum: the phone's own
        names for its screens.
      - the `GroupHeading("...")` labels under `ui/screens/`, every
        `title = "..."` under `ui/`, and every constant in the phone's own code
        whose name ends `_TITLE`, `_LABEL` or `_NAME`
        (`SWIPE_TITLE = "Swipe to approve or deny"`).

A name found in EITHER app counts. Deciding which app a step is for is a
different question from whether the name exists, and it is the question this
check deliberately does not try to answer (see below).

`--catalogue PATH` reads a different file, on purpose, so the "can this check
fail?" question can be answered by pointing it at a copy. It prints a warning
saying so, and it is never used by CI: a run that read some other file must
never look like a run that read the real one.

WHAT IT CHECKS, AND WHAT IT DELIBERATELY DOES NOT

The shape it checks is the **breadcrumb**: a `where` line that contains `->`
and so presents a path to walk ("Brain -> Voice -> Hands-free"). Every piece of
that path that is name-shaped must be a name the apps have. A piece is NOT
name-shaped - and is skipped, not guessed at - when it is a sentence fragment:
it starts with an article or a filler word ("the switches", "a fact", "the
fact's own menu"), or it is a documentation reference (it holds a `/` or ends
`.md`), or it is longer than a name. A trailing qualifier is trimmed first, so
"Phone on the PC" is judged as `Phone` rather than as that whole phrase.

Two rules keep the matching honest rather than clever:

  * matching is EXACT, after case, whitespace, curly-quote and ellipsis
    normalising, plus one trailing `s` - no substring search, no fuzzy match,
    no "close enough". A substring search was tried and thrown away: it passed
    `a fact`, `the switches` and `Your voice print` against bodies of prose,
    which is exactly the crying-wolf failure this check must not have.
  * nothing is synthesised. Every accepted name is a string the app's own
    source really contains, so "this name exists" is a claim about the app and
    not about this script.

Five shapes are LEFT OUT on purpose, because they cannot be decided reliably
and a guard that cries wolf is worse than no guard:

  1. a `where` line with no `->`. It is a sentence ("The HUD window", "Any
     approval card", "The tray icon, or the Jarvis bar on the PC"), and pulling
     button names out of a sentence needs the kind of guessing that would fail
     an honest line. The proof this is a real gap: a wrong name written that
     way - "tap to talk, on the phone" - is not caught by this check.
  2. a name written in prose with no breadcrumb at all, quoted or not.
  3. whether a real name is in the RIGHT app, or on the RIGHT screen. "Brain ->
     Memory -> Forget a time frame" names two real things and one real card,
     and whether that card is under Memory or under History is a structural
     question the two apps answer differently (the phone's Brain is one long
     screen with group headings; the desktop's is a row of tabs).
  4. free-form string literals in the JS and Kotlin. Most of them are messages,
     not names, and accepting them all would pass almost anything - worse, it
     would SWALLOW real drift: measured, every quoted string in the two apps is
     14,287 names, and `Phone`, `Privacy` and `Sensitive topics` are all in it
     as somebody's message text. Only label-shaped strings are read (the four
     shapes above), which is a real gap: a name the app draws from a plain
     message string is invisible here.
  5. a label the app builds from its own word table under a NON-label name, or
     a `const val` in the phone's code that is not named `*_TITLE`, `*_LABEL` or
     `*_NAME`. Same reason as 4: widening to those was measured and swallowed
     `Phone` and `Privacy`.

The last two were found by pointing this check at the sixteen tutorials another
pull request is adding, which is also how the check was proved not to cry wolf:
with those shapes in, all 23 tutorials pass and every recorded entry still
matches, while an invented name anywhere in a breadcrumb still exits 1.

A recorded name still fails when it MOVES: the key is the kind of entry, its id,
its step number and the breadcrumb piece EXACTLY as the tutorial writes it, so a
name added to a different step, a step renumbered by an edit above it, the same
name in a second tutorial, or the same mistake reworded is a finding with no
entry and the check goes red again. An entry that stops being reported is itself
printed as stale - a recorded name is not a licence, and a list that can quietly
absorb a real finding is not a guard.

This check reads NO file from the owner's PC, makes no network call and writes
nothing. Every path in it is inside this checkout.
"""
from __future__ import annotations

import ast
import html as html_module
import json
import re
import sys
from collections import namedtuple
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOGUE_PY = REPO / "backend" / "jarvis_tutorials.py"
DESKTOP_SRC = REPO / "jarvis-desktop" / "src"
MENU_JS = DESKTOP_SRC / "menu-catalog.js"
PHONE = (REPO / "jarvis-client" / "app" / "src" / "main" / "java" / "com"
         / "jarvis" / "client")
MENU_KT = PHONE / "net" / "MenuCatalog.kt"
PLACES_KT = PHONE / "ui" / "MenuPlaces.kt"
NAV_KT = PHONE / "ui" / "Nav.kt"
PHONE_UI = PHONE / "ui"
PHONE_SCREENS = PHONE / "ui" / "screens"

#: The arrow the apps' prose uses for a breadcrumb. Both a real arrow and the
#: "->" an author may type instead are read, because either one presents the
#: line as a path to walk.
ARROWS = "\u2192->"

#: A breadcrumb piece that starts with one of these is a sentence fragment, not
#: a name: "the switches", "a fact", "the fact's own menu". They are skipped
#: rather than judged, because judging them would fail an honest line.
FILLER = {
    "the", "a", "an", "any", "this", "that", "these", "those", "just",
    "nothing", "type", "press", "all", "every", "both", "each", "one",
    "two", "some", "here", "there", "its", "his", "her", "their",
}

#: A qualifier hung off the end of a breadcrumb piece ("Phone on the PC",
#: "Memory in the Brain"). Trimmed once, so the piece is judged as the name the
#: owner would look for rather than as the whole phrase.
TRAILING_QUALIFIER = re.compile(
    r"\s+(?:on|in|at|from|for|of|with)\s+(?:the|this|your|my|a|an)\s+\S+$",
    re.IGNORECASE)

#: Longer than any name the apps draw. A fragment this long is a sentence.
LONGEST_NAME = 60

# ---------------------------------------------------------------------------
#   The names recorded as known drift
# ---------------------------------------------------------------------------
# A guard with a list of known drift is still a guard, because the list is
# keyed rather than wildcarded: a name NOT in it takes the exit code to 1
# exactly as before, and a name that IS in it is printed in full on every run.
# That is the difference between a recorded line and a silenced one - the
# recorded one cannot be forgotten, and it cannot spread.
#
# WHAT IS RECORDED HERE, AND WHY IT IS NOT FIXED. `backend/jarvis_tutorials.py`
# is the file these lines live in, and an open pull request (#53) owns it. This
# check may not edit it, so the lines that are wrong today are recorded instead:
# each entry names what the tutorial says, what the app really has, and where
# the fix belongs. The entries go stale the moment the wording changes - which
# is deliberate, because the person rewriting these lines is the person who
# should delete the entry.
#
# The key is (kind, id, step, piece): `kind` is "tutorial" or "faq", `id` is the
# tutorial's own id (or "faq"), `step` is the 1-based step inside it (or the
# 1-based question for the FAQ), and `piece` is the breadcrumb piece EXACTLY as
# the tutorial writes it, before any normalising - so the entry is greppable in
# the file, and a piece reworded into the same mistake still has to be recorded
# again.
_KnownDrift = namedtuple("_KnownDrift", "reason fix")

KNOWN_DRIFT = {
    # --- "Your voice print" is not a heading; the heading is "Your voice" ----
    ("tutorial", "talking", 3, "Your voice print"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `talking` tutorial, step 3 - the "
            "desktop's Settings, Voice section is headed \"Your voice\" "
            "(settings.html), and the trained print is the row under it; say "
            "\"Your voice\" or name that row"),
    # --- there is no "Sensitive topics" section in Memory --------------------
    ("tutorial", "memory", 2, "Sensitive topics"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `memory` tutorial, step 2 - the "
            "switch is really called \"Also remember sensitive topics "
            "automatically\" (settings.html, AutoLearnPlate.kt); name that "
            "switch, or drop the third step of the breadcrumb"),
    # --- "Brain -> Privacy" is not a place; there is no Privacy section ------
    ("tutorial", "records", 1, "Privacy"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `records` tutorial, step 1 - "
            "chat history is kept by a switch on the History screen "
            "(brain.tab.history, HistoryScreen.kt); no page in either app is "
            "called Privacy"),
    # --- "Brain -> Phone": there is no Phone card ----------------------------
    ("tutorial", "phone-pairing", 1, "Phone on the PC"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `phone-pairing` tutorial, step 1 "
            "- pairing lives in the Settings cards \"Connection\" and "
            "\"Devices\" (settings.connection, settings.devices); no card "
            "called Phone exists in either app, so \"Phone on the PC\" sends "
            "the owner looking for one"),
    ("tutorial", "phone-pairing", 2, "Phone"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `phone-pairing` tutorial, step 2 "
            "- the same missing card; the QR code and the short code are on "
            "the Settings \"Devices\" card"),
    ("tutorial", "phone-pairing", 3, "Phone"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `phone-pairing` tutorial, step 3 "
            "- one key per device is the Settings \"Devices\" card "
            "(\"Paired devices\" in settings.html)"),
    # --- "Pair a device" is not a control anywhere --------------------------
    ("tutorial", "phone-pairing", 2, "Pair a device"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: the `phone-pairing` tutorial, step 2 "
            "- no button, card or heading in either app carries this name; the "
            "short typed code is entered on the phone's pairing screen "
            "(ui/screens/PairByCode.kt) and approved on the PC"),
    # --- FAQ lines, same convention, same screen ----------------------------
    ("faq", "faq", 2, "Phone"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: FAQ question 2 - the same missing "
            "card; the server address is the Settings \"Connection\" card"),
    ("faq", "faq", 3, "API keys and services"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: FAQ question 3 - keys are kept in the "
            "Settings card \"Accounts\" (settings.account-secrets); there is no "
            "\"API keys and services\" page"),
    ("faq", "faq", 17, "Your second graphics card"):
        _KnownDrift(
            "the wording is owned by open pull request #53, so it cannot be "
            "corrected here",
            "backend/jarvis_tutorials.py: FAQ question 17 - the card is called "
            "\"Second graphics card\" (settings.second-card, settings.html); "
            "the extra \"Your\" makes it a name the owner cannot find"),
}


def known_drift(kind: str, entry_id: str, step: int, piece: str):
    """The recorded entry for one finding, or None - which means NEW.

    Keyed on the piece as the tutorial WRITES it, and not on the name this check
    judged it to be: the file's own words are what a person can grep for, and a
    piece reworded - even into the same mistake - is a new line that has to be
    looked at again.
    """
    return KNOWN_DRIFT.get((kind, entry_id, step, piece))


# ---------------------------------------------------------------------------
#   Reading the tutorials - the real file
# ---------------------------------------------------------------------------

def _as_dict(node):
    """A `{...}` literal in the tutorials file as {key: value node}, or None.

    Read from the syntax tree rather than `ast.literal_eval` so the line each
    `where` string is written on comes back with it: a finding the owner cannot
    jump to is half a finding.
    """
    if not isinstance(node, ast.Dict):
        return None
    out = {}
    for key, value in zip(node.keys, node.values):
        if isinstance(key, ast.Constant) and isinstance(key.value, str):
            out.setdefault(key.value, value)
    return out


def _string(node):
    """The string a node is, or None when it is anything else."""
    return node.value if isinstance(node, ast.Constant) and \
        isinstance(node.value, str) else None


def tutorial_wheres(path: Path):
    """([(kind, id, step, where, line)], why it could not be read).

    The two tuples the module really defines, `CATALOGUE` and `FAQ`, taken from
    its own `ast` - so this reads the file the apps are served from, and a file
    that has been renamed, emptied or broken is a failure here rather than a
    quiet pass over nothing.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as err:
        return [], f"{path} could not be read ({err})"
    try:
        tree = ast.parse(text)
    except SyntaxError as err:
        return [], f"{path} is not Python (line {err.lineno}: {err.msg})"

    literals: dict[str, ast.AST] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in ("CATALOGUE", "FAQ"):
                literals[target.id] = node.value

    out: list[tuple[str, str, int, str, int]] = []

    catalogue = literals.get("CATALOGUE")
    if catalogue is None:
        return [], (f"{path} defines no CATALOGUE - this check reads the real "
                    f"file, and a file without it is not the file to read")
    if not isinstance(catalogue, ast.Tuple):
        return [], f"{path}: CATALOGUE is not a tuple of tutorials"
    for index, tutorial in enumerate(catalogue.elts, 1):
        entry = _as_dict(tutorial)
        if entry is None:
            return [], f"{path}: tutorial #{index} in CATALOGUE is not a dict"
        entry_id = _string(entry.get("id")) or f"#{index}"
        steps = entry.get("steps")
        if not isinstance(steps, ast.Tuple):
            return [], f"{path}: tutorial `{entry_id}` has no `steps` tuple"
        for number, step in enumerate(steps.elts, 1):
            fields = _as_dict(step)
            if fields is None:
                return [], (f"{path}: step {number} of `{entry_id}` is not a "
                            f"dict")
            where = fields.get("where")
            if where is None:
                continue
            value = _string(where)
            if value is None:
                return [], (f"{path}: step {number} of `{entry_id}` has a "
                            f"`where` that is not a string")
            out.append(("tutorial", entry_id, number, value, where.lineno))

    faq = literals.get("FAQ")
    if isinstance(faq, ast.Tuple):
        for number, question in enumerate(faq.elts, 1):
            fields = _as_dict(question)
            if fields is None:
                return [], f"{path}: FAQ item {number} is not a dict"
            where = fields.get("where")
            if where is None:
                continue
            value = _string(where)
            if value is None:
                return [], (f"{path}: FAQ item {number} has a `where` that is "
                            f"not a string")
            out.append(("faq", "faq", number, value, where.lineno))
    return out, ""


# ---------------------------------------------------------------------------
#   The names the two apps really have
# ---------------------------------------------------------------------------

def _json_export(text: str, name: str):
    """The JSON literal written after `export const NAME =`, or None.

    The generated catalogue is JSON inside a JS file - quoted keys, arrays,
    nulls - so it is read by the JSON parser rather than by a regex. The span is
    found by walking brackets, which is the only thing that survives the
    strings in it holding braces of their own.
    """
    at = text.find(f"export const {name} =")
    if at < 0:
        return None
    start = min((i for i in (text.find("[", at), text.find("{", at)) if i >= 0),
                default=-1)
    if start < 0:
        return None
    depth, i, n = 0, start, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i += 1
            while i < n:
                if text[i] == "\\":
                    i += 2
                    continue
                if text[i] == '"':
                    break
                i += 1
        elif c in "[{":
            depth += 1
        elif c in "]}":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i + 1])
                except ValueError:
                    return None
        i += 1
    return None


def _balanced_text(text: str, open_at: int) -> str:
    """The text of the bracket pair opened at `open_at`, itself included.

    Strings are stepped over rather than counted, because a label in one of
    these tables may hold a brace of its own.
    """
    depth, i, n = 0, open_at, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i += 1
            while i < n:
                if text[i] == "\\":
                    i += 2
                    continue
                if text[i] == '"':
                    break
                i += 1
        elif c in "[{":
            depth += 1
        elif c in "]}":
            depth -= 1
            if depth == 0:
                return text[open_at:i + 1]
        i += 1
    return text[open_at:]


def names_from_menu_catalogue(path: Path):
    """Every name the shared menu catalogue carries, plus why it failed.

    Four things are names here, and all four are the app's own words for a
    thing: the menu's `title` (what is drawn), its `id` (what the code calls
    it), the `names` it answers to, and the group `title`. The aliases are the
    same list from the other side, so they are folded in with them.
    """
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as err:
        return [], f"{path} could not be read ({err})"
    if not text:
        return [], f"{path} is empty"

    found: list[str] = []
    menus = _json_export(text, "MENUS")
    groups = _json_export(text, "GROUPS")
    aliases = _json_export(text, "ALIASES")
    if not isinstance(menus, list) or not menus:
        return [], (f"{path}: no read `MENUS` list - the generated catalogue is "
                    f"not where this check reads it, so nothing could be "
                    f"matched")
    for menu in menus:
        if not isinstance(menu, dict):
            continue
        for key in ("title", "id"):
            value = menu.get(key)
            if isinstance(value, str):
                found.append(value)
        for value in menu.get("names") or ():
            if isinstance(value, str):
                found.append(value)
    if isinstance(groups, list):
        for group in groups:
            if isinstance(group, dict):
                for key in ("title", "id"):
                    value = group.get(key)
                    if isinstance(value, str):
                        found.append(value)
    if isinstance(aliases, dict):
        found.extend(k for k in aliases if isinstance(k, str))
    return found, ""


def names_from_desktop_js(directory: Path):
    """The labels the desktop's modules put on the things they build, and why
    nothing was read.

    Four label shapes, and nothing else. The alternative was measured and thrown
    away: every `export const SOME_NAME = "..."` in these files is 441 strings
    and most of them are sentences ("A Today card needs some words: what should
    it say?"), and every quoted string in every file is 14,287 - a set that
    begins to SWALLOW real drift ("Phone", "Privacy" and "Sensitive topics" all
    exist as somebody's message text), which is the one failure this check must
    not have. So what is kept is:

      * a `title:` field - a label or a tooltip the page shows;
      * a constant whose own name ends `_LABEL` or `_TITLE`;
      * the text of a button or heading the module builds itself, which is the
        third argument of `node(...)`/`el(...)` - this is where `Restore...`
        lives, and it is invisible to every other extractor here;
      * the app's own word tables, the objects bound to `WORDS`, `LABELS` or
        `TEXT` (`projects.js`'s `WORDS.shareable`, which draws the Shareable
        switch's heading).

    The last two were added after this check was pointed at the sixteen
    tutorials another pull request is adding: without them it reported three
    real labels (`Restore...`, `Shareable`, `Swipe to approve or deny`) as
    missing, which is exactly the false alarm a guard must not raise.
    """
    found: list[str] = []
    modules = sorted(p for p in directory.glob("*.js") if p.is_file())
    if not modules:
        return [], f"no .js module under {directory} - the desktop has no labels to read"
    for module in modules:
        try:
            text = module.read_text(encoding="utf-8", errors="replace")
        except OSError as err:
            return [], f"{module} could not be read ({err})"
        for match in re.finditer(r"(?<![\w])title:\s*\"([^\"]{1,60})\"", text):
            found.append(match.group(1))
        for match in re.finditer(
                r"^export const [A-Z][A-Z0-9_]*_(?:LABEL|TITLE) = \"([^\"]{1,60})\"",
                text, re.MULTILINE):
            found.append(match.group(1))
        for match in re.finditer(
                r"(?<![\w])(?:node|el)\(\s*\"[a-z0-9]+\"\s*,\s*\"[^\"]*\"\s*,"
                r"\s*\"([^\"]{1,60})\"", text):
            found.append(match.group(1))
        for table in re.finditer(
                r"^(?:export )?const (?:WORDS|LABELS|TEXT)\s*=\s*"
                r"(?:Object\.freeze\()?\{", text, re.MULTILINE):
            body = _balanced_text(text, text.index("{", table.start()))
            found.extend(re.findall(r":\s*\"([^\"]{1,60})\"", body))
    return found, ""


HTML_PIECES = re.compile(
    r"<(?P<tag>title)\b[^>]*>(?P<page>.*?)</(?P=tag)>"
    r"|<(?P<head>h2|h3|summary)\b[^>]*>(?P<heading>.*?)</(?P=head)>"
    r"|<button\b[^>]*>(?P<button>.*?)</button>",
    re.IGNORECASE | re.DOTALL)


def names_from_desktop_html(directory: Path):
    """Every visible word the desktop's pages draw, plus why nothing was read.

    The visible words are the only ones a `where` line can send the owner to, so
    these are the four places they come from: the page's `<title>`, a section
    heading, a fold's own label, and a button's text. Tags are stripped and
    entities decoded, because a name with `&amp;` or a nested `<span>` in it is
    not the name the owner reads.
    """
    found: list[str] = []
    pages = sorted(p for p in directory.rglob("*.html") if p.is_file())
    if not pages:
        return [], f"no .html page under {directory} - the desktop has no words to read"
    for page in pages:
        try:
            text = page.read_text(encoding="utf-8", errors="replace")
        except OSError as err:
            return [], f"{page} could not be read ({err})"
        for match in HTML_PIECES.finditer(text):
            if match.group("page") is not None:
                # "Jarvis — Brain" names the page twice: the app, and the window
                for piece in re.split(r"[\u2014\u2013-]", match.group("page")):
                    if piece.strip():
                        found.append(piece)
                continue
            found.append(match.group("heading") or match.group("button") or "")
    out = []
    for raw in found:
        text = html_module.unescape(re.sub(r"<[^>]+>", " ", raw))
        text = re.sub(r"\s+", " ", text).strip()
        if text and len(text) <= LONGEST_NAME and "<" not in text:
            out.append(text)
    return out, ""


def names_from_phone():
    """The phone's own names for its menus, items, screens and labels.

    Each source here is a place the phone really draws a word: the generated
    menu catalogue (its titles and ids), the `item(key=...)` keys its screens
    hang a menu under, the `Screen` enum, the `GroupHeading("...")` section
    labels, the `title = "..."` on a screen's plates, and a constant whose own
    name ends `_TITLE`, `_LABEL` or `_NAME`. Free-form strings are NOT read, and
    neither is any other `const val`: both were measured and both swallow real
    drift (see names_from_desktop_js).
    """
    found: list[str] = []
    why: list[str] = []

    try:
        menu_text = MENU_KT.read_text(encoding="utf-8", errors="replace")
    except OSError as err:
        return [], f"{MENU_KT} could not be read ({err})"
    pairs = re.findall(r'\b(?:Menu|Group)\(\s*"([^"]+)"\s*,\s*"([^"]+)"',
                       menu_text)
    if not pairs:
        return [], (f"{MENU_KT}: no `Menu(\"id\", \"title\"` entries - the "
                    f"phone's catalogue is not where this check reads it")
    for entry_id, title in pairs:
        found.extend((entry_id, title))

    try:
        places_text = PLACES_KT.read_text(encoding="utf-8", errors="replace")
    except OSError as err:
        why.append(f"{PLACES_KT} could not be read ({err})")
    else:
        # `"memory-counts" to "brain.memory.learning"` - the item key is the
        # name the screen draws the menu under, so its dashes become spaces.
        for key in re.findall(r'^\s*"([a-z0-9][a-z0-9-]*)"\s+to\s+"', places_text,
                              re.MULTILINE):
            found.append(key.replace("-", " "))

    try:
        nav_text = NAV_KT.read_text(encoding="utf-8", errors="replace")
    except OSError as err:
        why.append(f"{NAV_KT} could not be read ({err})")
    else:
        # The comments in Nav.kt name screens too, so they are stripped first:
        # a word that only ever appears in prose is not a screen.
        bare = re.sub(r"/\*.*?\*/", " ", nav_text, flags=re.DOTALL)
        bare = re.sub(r"//[^\n]*", " ", bare)
        enum = re.search(r"enum class Screen\s*\{(.*?)\}", bare, re.DOTALL)
        if enum:
            for name in re.split(r"[,\s]+", enum.group(1)):
                if re.fullmatch(r"[A-Z][A-Z0-9_]*", name):
                    found.append(name.lower().replace("_", " "))

    screens = sorted(p for p in PHONE_SCREENS.rglob("*.kt") if p.is_file())
    if not screens:
        why.append(f"no screen source under {PHONE_SCREENS}")
    for screen in screens:
        try:
            text = screen.read_text(encoding="utf-8", errors="replace")
        except OSError as err:
            why.append(f"{screen} could not be read ({err})")
            continue
        found.extend(re.findall(r'GroupHeading\(\s*"([^"]+)"', text))

    # The labels the phone's own screens put on their plates. `title = "..."`
    # rather than every string literal, for the reason names_from_desktop_js
    # gives: a screen's other strings are messages ("Choose a folder before
    # backing up"), and accepting those would pass almost anything - measured:
    # every Kotlin `const val` in this app is 1,211 strings and swallowing
    # "Phone" and "Privacy" with them. A constant whose own name ends `_TITLE`,
    # `_LABEL` or `_NAME` is a label by its author's own naming
    # (`SWIPE_TITLE = "Swipe to approve or deny"`), and 157 of those swallow
    # nothing.
    drawn = sorted(p for p in PHONE_UI.rglob("*.kt") if p.is_file())
    if not drawn:
        why.append(f"no UI source under {PHONE_UI}")
    for screen in drawn:
        try:
            text = screen.read_text(encoding="utf-8", errors="replace")
        except OSError as err:
            why.append(f"{screen} could not be read ({err})")
            continue
        found.extend(re.findall(r'(?<![\w])title\s*=\s*"([^"]{1,60})"', text))
    for source in sorted(p for p in PHONE.rglob("*.kt") if p.is_file()):
        try:
            text = source.read_text(encoding="utf-8", errors="replace")
        except OSError as err:
            why.append(f"{source} could not be read ({err})")
            continue
        found.extend(re.findall(
            r'^\s*(?:private )?const val [A-Z][A-Z0-9_]*_'
            r'(?:TITLE|LABEL|NAME)\s*=\s*"([^"]{1,60})"', text, re.MULTILINE))
    return found, "; ".join(why)


def normalise(name: str) -> str:
    """The one form both sides are compared in.

    Case, runs of whitespace, curly quotes and the ellipsis are folded, and one
    trailing `s` is dropped - nothing else. That is a normalising rule, not a
    fuzzy match: "Backup" is the same name as "Backups" and should not be a
    finding, while "Your voice print" is not the same name as "Your voice".
    """
    text = (name.replace("\u2019", "'").replace("\u2018", "'")
                .replace("\u201c", '"').replace("\u201d", '"')
                .replace("\u2014", "-").replace("\u2013", "-")
                .replace("\u2026", "..."))
    text = re.sub(r"\s+", " ", text).strip().lower()
    text = text.strip(" .,:;!?\u2026")
    return re.sub(r"s$", "", text)


def load_known_names():
    """(every name either app really has, why some of it could not be read)."""
    found: list[str] = []
    why: list[str] = []

    names, trouble = names_from_menu_catalogue(MENU_JS)
    found.extend(names)
    if trouble:
        why.append(trouble)

    names, trouble = names_from_desktop_html(DESKTOP_SRC)
    found.extend(names)
    if trouble:
        why.append(trouble)

    names, trouble = names_from_desktop_js(DESKTOP_SRC)
    found.extend(names)
    if trouble:
        why.append(trouble)

    names, trouble = names_from_phone()
    found.extend(names)
    if trouble:
        why.append(trouble)

    known = {normalise(n) for n in found if n and n.strip()}
    known.discard("")
    return known, "; ".join(why)


# ---------------------------------------------------------------------------
#   What a `where` line is telling the owner to use
# ---------------------------------------------------------------------------

def has_arrow(where: str) -> bool:
    return "\u2192" in where or "->" in where


def chains(where: str):
    """The breadcrumbs in one `where` line, each already split into pieces.

    A line may hold two of them ("Brain -> Memory, and Brain -> Backup"), so it
    is cut at a comma or a semicolon - and the "and"/"or" left joining the two
    is dropped with it - and then only the pieces that still contain an arrow
    are kept: a phrase with no arrow in it is prose, and prose is not checked.

    The word "and" is NOT a cut on its own, deliberately: "Hardware and models",
    "Goals and projects" and "Chat history and conversations" are real names,
    and cutting inside one would fail an honest line.
    """
    out = []
    for piece in re.split(r"[,;]", where):
        piece = re.sub(r"^\s*(?:and|or)\s+", "", piece, flags=re.IGNORECASE)
        if not has_arrow(piece):
            continue
        cleaned = piece.replace("\u2192", "->")
        out.append([part.strip() for part in cleaned.split("->")])
    return out


def name_like(piece: str) -> bool:
    """True when a breadcrumb piece is presented as a NAME and not as a
    sentence fragment. See the docstring's FILLER note."""
    if not piece or len(piece) > LONGEST_NAME:
        return False
    if "/" in piece or piece.lower().endswith(".md"):
        return False
    first = re.split(r"[\s'\u2019\"]", piece, 1)[0].lower()
    return first not in FILLER


def named_places(where: str):
    """[(the piece as written, the name judged)] for one `where` line.

    The trailing qualifier comes off here rather than in the report, so the
    finding names the thing the owner would look for ("Phone") and not the
    phrase the author wrapped around it ("Phone on the PC").
    """
    out = []
    for chain in chains(where):
        for piece in chain:
            trimmed = TRAILING_QUALIFIER.sub("", piece).strip()
            if name_like(piece):
                out.append((piece, trimmed or piece))
    # One line naming the same thing twice is one finding: "Brain" at the head
    # of both breadcrumbs is not two mistakes.
    seen, unique = set(), []
    for piece, name in out:
        if name.lower() in seen:
            continue
        seen.add(name.lower())
        unique.append((piece, name))
    return unique


# ---------------------------------------------------------------------------
#   The run
# ---------------------------------------------------------------------------

def main() -> int:
    verbose = "-v" in sys.argv
    catalogue = CATALOGUE_PY
    if "--catalogue" in sys.argv:
        # A way to exercise this check against a copy, on purpose - the same
        # door check_literal_keys.py leaves open with --no-git. It is said out
        # loud, so a run that read some other file can never look like a run
        # that read the real one.
        at = sys.argv.index("--catalogue")
        if at + 1 >= len(sys.argv):
            print("::error::--catalogue needs a path after it")
            return 1
        catalogue = Path(sys.argv[at + 1]).resolve()
        print(f"::warning::reading `{catalogue}` instead of "
              f"`{CATALOGUE_PY}` (--catalogue) - this run does NOT say anything "
              f"about the file CI reads.")

    wheres, problem = tutorial_wheres(catalogue)
    if problem:
        print(f"::error::{problem}")
        return 1
    if not wheres:
        print(f"::error::{catalogue} holds no `where` line at all - a check that "
              f"reads nothing must not pass")
        return 1
    # The file the findings are reported against. Normally the real one, so a
    # finding reads `backend/jarvis_tutorials.py:140`; under --catalogue it is
    # the copy, so the output never claims to be about a file it did not read.
    shown = (catalogue.relative_to(REPO).as_posix()
             if catalogue.is_relative_to(REPO) else str(catalogue))

    known, trouble = load_known_names()
    if trouble:
        print(f"::error::the names the apps have could not all be read, so a "
              f"finding below may only mean this check could not see the app: "
              f"{trouble}")
        return 1
    if not known:
        print("::error::read no UI name from either app - this check would pass "
              "having checked nothing")
        return 1

    chains_seen = sum(1 for _kind, _id, _step, where, _line in wheres
                      if has_arrow(where))
    checked = 0
    missing: list[tuple[str, str, int, int, str, str, str]] = []
    for kind, entry_id, step, where, line in wheres:
        for piece, name in named_places(where):
            checked += 1
            if normalise(name) in known:
                continue
            missing.append((kind, entry_id, step, line, where, piece, name))

    # Every recorded entry this run actually reports, and every unrecorded
    # finding. The first list is printed whether or not the run is otherwise
    # green; the second one is what sets the exit code.
    recorded: dict[tuple, tuple[str, str, int, int, str, str]] = {}
    unrecorded: list[tuple[str, str, int, int, str, str, str]] = []
    for finding in missing:
        kind, entry_id, step, line, where, piece, name = finding
        if known_drift(kind, entry_id, step, piece) is None:
            unrecorded.append(finding)
        else:
            recorded[(kind, entry_id, step, piece)] = finding
    stale = [key for key in KNOWN_DRIFT if key not in recorded]

    problems = bool(unrecorded or stale)

    if unrecorded:
        print("::error::a tutorial's `where` line sends the owner to a name "
              "neither app has. Read each one and either fix the wording or "
              "record it in KNOWN_DRIFT, with the reason it cannot be fixed "
              "here and where the fix belongs - a finding NOT recorded below "
              "exits 1:")
        for kind, entry_id, step, line, where, piece, name in sorted(
                unrecorded, key=lambda f: (f[0], f[1], f[2], f[5])):
            who = (f"the `{entry_id}` tutorial, step {step}" if kind == "tutorial"
                   else f"FAQ question {step}")
            print(f"  {shown}:{line}  {who} names `{piece}`")
            print(f"      its `where` line reads: {where}")
            if piece != name:
                print(f"      (the name to look for there is `{name}`)")
            print(f"      neither app's menus, headings, buttons, item keys or "
                  f"screens carry that name")

    if stale:
        print("::error::a name recorded in KNOWN_DRIFT was NOT reported by this "
              "run - delete the entry if the wording is fixed, or move it to "
              "where the line is now, because a stale entry is the one way this "
              "list could quietly absorb a real finding:")
        for kind, entry_id, step, piece in sorted(
                stale, key=lambda k: (k[0], k[1], k[2], k[3])):
            who = (f"the `{entry_id}` tutorial, step {step}" if kind == "tutorial"
                   else f"FAQ question {step}")
            print(f"  {who} no longer names `{piece}` - recorded, not reported")

    if recorded:
        # Printed whether or not the rest of the run is green, because the whole
        # point of a recorded name is that it stays visible. A recorded name
        # that is never printed is an ignore list with extra steps.
        print()
        print("these `where` lines name something the apps do not have. They are "
              "recorded in KNOWN_DRIFT, so they do not fail this check, and they "
              "are printed on every run so they cannot be forgotten:")
        for key in sorted(recorded, key=lambda k: (k[0], k[1], k[2], k[3])):
            kind, entry_id, step, piece = key
            _k, _i, _s, line, where, _piece, judged = recorded[key]
            who = (f"the `{entry_id}` tutorial, step {step}" if kind == "tutorial"
                   else f"FAQ question {step}")
            print(f"  {shown}:{line}  {who} names `{piece}`")
            print(f"      its `where` line reads: {where}")
            if piece != judged:
                print(f"      (the name to look for there is `{judged}`)")
            print(f"      cannot be fixed here: {KNOWN_DRIFT[key].reason}")
            print(f"      the fix belongs: {KNOWN_DRIFT[key].fix}")

    if verbose:
        print(f"  tutorials and FAQ read from: {catalogue}")
        print(f"  {chains_seen} of the {len(wheres)} `where` line(s) carry a "
              f"breadcrumb, and {len(wheres) - chains_seen} do not")
        print(f"  {checked} name-shaped piece(s) judged against {len(known)} "
              f"name(s) the apps have")
        print(f"  names read from: {MENU_JS.name}, every *.html under "
              f"{DESKTOP_SRC.name}/, every *.js `title:`, `*_LABEL`/`*_TITLE`, "
              f"`node(...)` text and WORDS/LABELS table there, {MENU_KT.name}, "
              f"{PLACES_KT.name}, {NAV_KT.name}, GroupHeading(...) under "
              f"ui/screens/, every `title = \"...\"` under {PHONE_UI.name}/ and "
              f"every `*_TITLE`/`*_LABEL`/`*_NAME` constant in the phone's code")

    if problems:
        return 1

    print(f"{len(wheres)} `where` line(s) read from "
          f"{catalogue.relative_to(REPO).as_posix() if catalogue.is_relative_to(REPO) else catalogue}; "
          f"{chains_seen} of them carry a breadcrumb, and every one of the "
          f"{checked} name(s) in those breadcrumbs is a name the apps really "
          f"have.")
    print("The names were matched exactly against the desktop's generated menu "
          "catalogue, its pages' headings and buttons and its modules' own "
          "labels, and the phone's menu catalogue, screen names, item keys, "
          "group headings and plate titles - no substring search and no fuzzy "
          "match.")
    if recorded:
        print(f"{len(recorded)} known drift(s) reported, each recorded in "
              f"KNOWN_DRIFT with its reason; a name NOT recorded there still "
              f"exits 1.")
    else:
        print("No recorded drift was reported by this run.")
    print("NOT checked, on purpose: a `where` line with no `->` in it (a "
          "sentence, where a name cannot be told from prose), and whether a real "
          "name is on the right screen or in the right app. A wrong name written "
          "either of those ways still passes this check.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
