#!/usr/bin/env python3
"""Regenerate docs/SOURCE-BUNDLE.md from the tree as it is right now.

The previous bundle was written by hand and went stale without saying so: it
described jarvis-client as "step 0, ~500 lines, no networking" long after that
module had grown a network layer, an audio stack and a voice loop. A reviewer
handed that document would have audited an app that no longer existed, and
would have had no way to tell.

So it is generated, from `git ls-files`, with the commit stamped at the top —
and anything that cannot be read as text is listed rather than silently
dropped, because "this file is not in the bundle" and "this file does not
exist" must not look the same to whoever reads it.
"""
import subprocess, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = "jarvis-client"

# Text we deliberately leave out, with the reason, printed into the document.
SKIP_SUFFIX = {
    ".png": "binary image",
    ".jar": "binary (the Gradle wrapper)",
    ".keystore": "binary, and a signing key",
}

LANG = {
    ".kt": "kotlin", ".kts": "kotlin", ".xml": "xml", ".json": "json",
    ".py": "python", ".yml": "yaml", ".yaml": "yaml", ".md": "markdown",
    ".pro": "text", ".properties": "properties", ".gitignore": "text",
}


def tracked(*paths):
    out = subprocess.run(["git", "ls-files", "--", *paths], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout
    return [p for p in out.split("\n") if p]


def main():
    sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout.strip()
    branch = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True, check=True).stdout.strip()

    files = tracked(MODULE) + tracked(".github/workflows", "keystore/README.md")
    included, skipped = [], []
    for f in sorted(files):
        ext = os.path.splitext(f)[1]
        if ext in SKIP_SUFFIX:
            skipped.append((f, SKIP_SUFFIX[ext]))
        else:
            included.append(f)

    lines = []
    w = lines.append
    w(f"# `{MODULE}` — every source file, in one document")
    w("")
    w(f"Commit `{sha}` on `{branch}`.")
    w("")
    w("Generated by `tools/gen_source_bundle.py`, not written by hand. The previous")
    w("version of this file was hand-written and went stale without saying so — it")
    w("described this module as \"step 0, no networking\" long after it had grown a")
    w("network layer, an audio stack and a voice loop.")
    w("")
    w(f"Contains the whole `{MODULE}` module, plus the CI workflows that build it,")
    w("because how a thing is tested is part of judging whether it works.")
    w("")
    w(f"**{len(included)} files included.**")
    if skipped:
        w("")
        w("Deliberately omitted, listed so their absence is visible rather than silent:")
        w("")
        for f, why in skipped:
            w(f"- `{f}` — {why}")
    w("")
    w("## Contents")
    w("")
    for f in included:
        w(f"- `{f}`")
    w("")
    w("---")
    w("")

    for f in included:
        path = os.path.join(ROOT, f)
        try:
            body = open(path, encoding="utf-8").read()
        except (UnicodeDecodeError, OSError) as e:
            w(f"## `{f}`")
            w("")
            w(f"*Could not be read as text: {e}*")
            w("")
            continue
        lang = LANG.get(os.path.splitext(f)[1], "")
        if os.path.basename(f) == "gradlew":
            lang = "bash"
        # A fence long enough that nothing inside the file can close it early.
        fence = "`" * max(4, max((len(m) for m in _runs(body)), default=3) + 1)
        w(f"## `{f}`")
        w("")
        w(f"{fence}{lang}")
        w(body.rstrip("\n"))
        w(fence)
        w("")

    out = os.path.join(ROOT, "docs", "SOURCE-BUNDLE.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    size = os.path.getsize(out)
    print(f"{out}: {len(included)} files, {size:,} bytes")


def _runs(text):
    """Every run of backticks in the text, so the fence can outrun the longest."""
    run, out = 0, []
    for ch in text:
        if ch == "`":
            run += 1
        else:
            if run:
                out.append("`" * run)
            run = 0
    if run:
        out.append("`" * run)
    return out


if __name__ == "__main__":
    sys.exit(main())
