#!/usr/bin/env python3
"""Writes the one table both apps' "can this model chat?" rule is held to.

    python3 tools/gen_model_chat_cases.py            # write both copies
    python3 tools/gen_model_chat_cases.py --check    # compare only

    jarvis-desktop/tests/fixtures/model-chat-cases.json
    jarvis-client/app/src/test/resources/contract/model-chat-cases.json

Play tester, 2026-09-27: Brain › Model offered "Use" on nomic-embed-text, an
embedding model - it only turns text into numbers for memory search, and
switching to it would leave Jarvis unable to answer anything. The desktop
was fixed first (commit 2aca75a, `jarvis-desktop/src/model-chat.js`), then
the phone (`net/ModelChat.kt`). Both apps apply the same rule and show the
same sentence; this table is what keeps them the same:

  * Ollama's own `capabilities` list wins when a row carries one: no
    "completion" in it means no chat (an empty list included).
  * Otherwise a BERT-family model cannot chat.
  * Otherwise the name decides: "embed", "minilm", or "bge" at the start of
    the name or after a non-letter means an embedding model (case ignored).
    The real `/api/models` sends bare names (gpu-offload.patch), so the name
    is usually all there is.

The backend has no rule of its own here to generate from, so the cases are
written out below by hand; `backend/test_model_chat_cases.py` checks both
copies are what this script makes, and each app's own test
(`tests/model-chat.mjs`, `ModelChatContractTest.kt`) runs its rule over them.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESKTOP = ROOT / "jarvis-desktop" / "tests" / "fixtures" / "model-chat-cases.json"
PHONE = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources" / "contract"
         / "model-chat-cases.json")
COPIES = (DESKTOP, PHONE)

#: Shown on a model's row instead of a "Use" button, word for word in both apps.
CANNOT_CHAT = "for memory search only - it cannot chat"

_NO = object()  # "the row carries no capabilities list" - the key is left out


def _case(ref, chats, family=None, capabilities=_NO):
    c = {"ref": ref}
    if family is not None:
        c["family"] = family
    if capabilities is not _NO:
        c["capabilities"] = capabilities
    c["chats"] = chats
    return c


CASES = [
    # Bare names, as the real /api/models sends them.
    _case("qwen3:8b", True),
    _case("llama3.1:8b", True),
    _case("qwen2.5-coder:7b", True),
    _case("gemma3:12b", True),
    _case("nomic-embed-text", False),
    _case("nomic-embed-text:latest", False),
    _case("Nomic-Embed-Text", False),
    _case("mxbai-embed-large", False),
    _case("snowflake-arctic-embed:335m", False),
    _case("granite-embedding:30m", False),
    _case("all-minilm", False),
    _case("paraphrase-multilingual-minilm", False),
    _case("bge-m3", False),
    _case("BGE-M3", False),
    _case("bge-large:335m", False),
    _case("hf.co/BAAI/bge-small-en", False),
    # "bge" inside a word is not the BGE family.
    _case("abge-chat", True),
    # The family decides when the name does not.
    _case("some-model", False, family="nomic-bert"),
    _case("another-model", False, family="BERT"),
    _case("qwen3:8b", True, family="qwen3"),
    # Ollama's own capabilities list wins over the name and the family.
    _case("qwen3:8b", True, capabilities=["completion", "tools"]),
    _case("my-embedder", False, capabilities=["embedding"]),
    _case("embed-chat-tuned", True, capabilities=["completion"]),
    _case("bert-chat", True, family="bert", capabilities=["completion"]),
    _case("llama3.1:8b", False, capabilities=[]),
]


def build() -> dict:
    return {
        "_comment": ("Generated by tools/gen_model_chat_cases.py. Do not edit by hand. "
                     "`chats`: whether Brain > Model offers \"Use\" on this row. A row "
                     "without `capabilities` carries no such list."),
        "cannot_chat": CANNOT_CHAT,
        "cases": CASES,
    }


def document() -> str:
    return json.dumps(build(), indent=1, ensure_ascii=False) + "\n"


def main() -> int:
    doc = document()
    if "--check" in sys.argv:
        stale = [p for p in COPIES
                 if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != doc]
        for p in stale:
            print(f"STALE {p.relative_to(ROOT)} - run python3 tools/gen_model_chat_cases.py")
        if not stale:
            print("model-chat-cases.json: both copies up to date")
        return 1 if stale else 0
    for p in COPIES:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(doc, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
