#!/usr/bin/env python3
"""Write the files for an outside (Gemini) audit of what changed since the
last one, split into six sessions, each a single Markdown file to attach.

    py -3 tools\\gen_gemini_bundles.py                 # since the last audit
    py -3 tools\\gen_gemini_bundles.py --since <commit>
    py -3 tools\\gen_gemini_bundles.py --out <folder>

Why six files and not one: docs/GEMINI-AUDIT.md section 1 - a model asked
to audit four languages at once spreads itself thin, and one past about
400k tokens reads shallowly. So each session is one part of Jarvis, kept
under that: the backend's safety core and its abilities (Python, the
patches, the install script), the desktop app's Rust, the desktop app's
windows (JavaScript and HTML), and the phone app's core and its screens
(Kotlin).

What goes in: every source file ADDED or CHANGED since `--since`, whole, as
it is now - a reviewer needs the whole file, not a diff. What stays out, and
is LISTED in each file with the reason, so "not in the bundle" never looks
like "does not exist": tests and their fixtures, generated data modules
(their first lines say "GENERATED by"), lock files, binaries and docs. The
prompt that goes with them is docs/GEMINI-AUDIT-2026-09-25.md.

Nothing is sent anywhere; this only writes files. It reads git, so run it
from inside the repository.
"""
import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: The commit whose fixes closed the last Gemini audit: "Fix seven real
#: findings from a Gemini audit, verified against source first (#10)",
#: 2026-09-20. Everything after it has not been read by an outside model.
LAST_AUDIT = "093caee"

def _backend(p):
    return (p.startswith("backend/") and (p.endswith(".py") or p.endswith(".patch")
                                          or p.endswith(".toml") or p.endswith(".txt"))) \
        or p == "scripts/apply-patches.ps1" or p == ".github/workflows/ci.yml"


#: Backend modules that are abilities the owner uses (voice, search, timers,
#: the calendar...), audited in their own session, apart from the safety
#: core (the agent, the gate, memory, learning, the patches, the installer).
ABILITIES = ("jarvis_voice", "jarvis_speech", "jarvis_wakeword", "jarvis_turn",
             "jarvis_big_model", "jarvis_second_card", "jarvis_f5", "jarvis_hardware",
             "jarvis_profiles", "jarvis_speed", "jarvis_power", "jarvis_standby",
             "jarvis_browser", "jarvis_ui_control", "jarvis_android", "jarvis_search",
             "jarvis_schedule", "jarvis_quick", "jarvis_briefing", "jarvis_backoff",
             "jarvis_calendar", "jarvis_email", "jarvis_home", "jarvis_notes",
             "jarvis_note_capture", "jarvis_wiki", "jarvis_skill", "jarvis_task",
             "jarvis_research", "jarvis_moment")


def _ability(p):
    return os.path.basename(p).startswith(ABILITIES) and p.endswith(".py") \
        and not p.startswith("backend/rebuilt/")


PHONE_SCREENS = ("/client/ui/", "/client/face/", "/client/voice/")


def _phone(p):
    return (p.startswith("jarvis-client/app/src/main/") and os.path.splitext(p)[1] in (".kt", ".xml")) \
        or p in ("jarvis-client/app/build.gradle.kts", "jarvis-client/app/proguard-rules.pro",
                 ".github/workflows/jarvis-client.yml")


SESSIONS = [
    ("1a-backend-safety", "The Python backend's safety core: the agent loop, the approval gate, "
     "memory and learning, the sensitive-topic check, the patches and the install script",
     lambda p: _backend(p) and not _ability(p)),
    ("1b-backend-abilities", "The Python backend's abilities: voice, web search, timers and the "
     "scheduler, the briefing, calendar, email, notes, the graphics-card lanes, computer control",
     lambda p: _backend(p) and _ability(p)),
    ("2-desktop-rust", "The desktop app's Rust (src-tauri) and its build",
     lambda p: p.startswith("jarvis-desktop/src-tauri/") and (
         p.endswith(".rs") or p.endswith("Cargo.toml") or p.endswith(".json"))
     or p == ".github/workflows/desktop-release.yml"),
    ("3-desktop-web", "The desktop app's windows (JavaScript, HTML, CSS)",
     lambda p: p.startswith("jarvis-desktop/src/") and os.path.splitext(p)[1] in (".js", ".html", ".css")),
    ("4a-phone-core", "The phone app's network, runtime, security, services and build",
     lambda p: _phone(p) and not any(x in p for x in PHONE_SCREENS)),
    ("4b-phone-screens", "The phone app's screens, the animated face, and voice",
     lambda p: _phone(p) and any(x in p for x in PHONE_SCREENS)),
]

LANG = {".py": "python", ".patch": "diff", ".ps1": "powershell", ".rs": "rust",
        ".js": "javascript", ".html": "html", ".css": "css", ".kt": "kotlin",
        ".kts": "kotlin", ".xml": "xml", ".json": "json", ".toml": "toml",
        ".yml": "yaml", ".txt": "text", ".pro": "text"}


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True,
                          check=True).stdout


def why_left_out(path):
    """The reason a changed file is not in a bundle, or "" to include it."""
    name = os.path.basename(path)
    if "/tests/" in path or "/src/test/" in path or name.startswith("test_") \
            or "/fixtures/" in path or "sensitive_cases/" in path or "_cases" in name:
        return "a test or test data"
    if name.startswith("_") and path.startswith("backend/"):
        return "test plumbing"
    if name in ("Cargo.lock",) or name.endswith(".lock"):
        return "a lock file (versions only)"
    if path.startswith("backend/patch-history/"):
        return "an earlier version of a patch, kept so the installer recognises it"
    if path.endswith(".py"):
        try:
            with open(os.path.join(ROOT, path), encoding="utf-8") as f:
                head = f.read(600)
        except (OSError, UnicodeDecodeError):
            return "not readable as text"
        if "GENERATED by" in head:
            return "generated data (numbers), made by a script in tools/"
    return ""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--since", default=LAST_AUDIT)
    ap.add_argument("--out", default=os.path.join(os.path.expanduser("~"), "jarvis-gemini-audit"))
    a = ap.parse_args()

    head = git("rev-parse", "--short", "HEAD").strip()
    branch = git("rev-parse", "--abbrev-ref", "HEAD").strip()
    base = git("rev-parse", "--short", a.since).strip()
    status = {}
    for line in git("diff", "--name-status", "--diff-filter=AM", a.since, "HEAD").splitlines():
        kind, path = line.split("\t", 1)
        status[path] = "NEW" if kind == "A" else "CHANGED"
    commits = len(git("rev-list", f"{a.since}..HEAD").split())

    os.makedirs(a.out, exist_ok=True)
    totals = []
    for key, title, wanted in SESSIONS:
        paths = sorted(p for p in status if wanted(p) and os.path.isfile(os.path.join(ROOT, p)))
        inc = [p for p in paths if not why_left_out(p)]
        out = [(p, why_left_out(p)) for p in paths if why_left_out(p)]
        body = []
        w = body.append
        w(f"# Jarvis audit bundle {key}: {title}")
        w("")
        w(f"Commit `{head}` on `{branch}`. Every file below was ADDED or CHANGED "
          f"after `{base}` (the last outside audit, 2026-09-20) - {commits} commits later. "
          "Each file is shown whole, as it is now, not as a diff.")
        w("")
        w(f"## The {len(inc)} files in this bundle")
        w("")
        for p in inc:
            w(f"- `{p}` - {status[p]}, {os.path.getsize(os.path.join(ROOT, p)) // 1024 + 1} KB")
        w("")
        w(f"## Changed but NOT in this bundle ({len(out)}), and why")
        w("")
        w("Listed so that \"not here\" never reads as \"does not exist\".")
        w("")
        for p, why in out:
            w(f"- `{p}` - {why}")
        if not out:
            w("- (none)")
        w("")
        for p in inc:
            with open(os.path.join(ROOT, p), encoding="utf-8", errors="replace") as f:
                text = f.read()
            fence = "````" if "```" in text else "```"
            w(f"---\n\n## FILE: `{p}` ({status[p]})\n")
            w(f"{fence}{LANG.get(os.path.splitext(p)[1], 'text')}")
            w(text.rstrip("\n"))
            w(fence)
            w("")
        dest = os.path.join(a.out, f"jarvis-audit-{key}.md")
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(body) + "\n")
        totals.append((dest, len(inc), os.path.getsize(dest)))

    print(f"Since {base} ({commits} commits), at {head} on {branch}:")
    for dest, n, size in totals:
        print(f"  {dest}  -  {n} files, {size // 1024} KB (about {size // 4000}k tokens)")
    print(f"The prompt to paste is docs/GEMINI-AUDIT-2026-09-25.md. The files are in {a.out}")


if __name__ == "__main__":
    sys.exit(main())
