#!/usr/bin/env python3
"""Writes jarvis-client/app/src/test/resources/contract/open-chat-cases.json:
the exact phrases the phone's local "open a chat" check must (and must not)
recognize, generated from the backend's own grammar - not hand-typed.

    python3 tools/gen_open_chat_cases.py            # write the file
    python3 tools/gen_open_chat_cases.py --check    # compare only

Cross-cutting audit finding #7 (2026-09-27): the phone's own
`net/OpenChatPhrase.kt` and the backend's `jarvis_quick.py` `_OPEN_CHAT`
grammar were two separately hand-maintained phrase lists with nothing tying
them together, and had already drifted - the phone recognized several
phrases ("open jarvis", "let's chat", "...chat screen") the backend's own
`/api/chat` intent matching does not, so saying one of those to the
floating avatar brought the app to the front, but typing or saying the
SAME words as an ordinary chat message would not have opened anything -
the exact inconsistency "unify them" was meant to close.

`MATCHES` is every "chat"-wording phrase the phone's own vocabulary uses
(it has no "Jarvis bar" concept - that is the desktop's window name, so the
backend's "jarvis bar" alternatives are left out here on purpose, not by
omission) - each one asserted against the REAL `jarvis_quick._OPEN_CHAT`
regex below, so this script fails loudly the day that regex ever stops
matching one of them. `NON_MATCHES` are the phrases the phone used to
recognize locally that the backend's grammar does not, plus a few ordinary
sentences - proof the phone's trimmed-down list does not overmatch either.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

import jarvis_quick as Q  # noqa: E402

PHONE = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources" / "contract"
         / "open-chat-cases.json")

#: Every "open/show/bring up a/the chat(window)?" combination the backend's
#: grammar accepts - the phone's own vocabulary (no "jarvis bar" wording).
MATCHES = [
    f"{verb} {article}chat{window}"
    for verb, article_options in (
        ("open", ("a ", "the ")),
        ("show me", ("a ", "the ")),
        ("show", ("", "the ")),
        ("bring up", ("a ", "the ")),
    )
    for article in article_options
    for window in ("", " window")
]

#: What the phone used to recognize on its own that the backend's grammar
#: does not, plus ordinary chat that must never be mistaken for this intent.
NON_MATCHES = [
    "open chat",
    "open the chat screen",
    "show me the chat screen",
    "show the chat screen",
    "open jarvis",
    "open the jarvis app",
    "open the app",
    "let's chat",
    "lets chat",
    "what's the weather",
    "open a document",
    "show me the calendar",
    "",
]


def build() -> dict:
    for phrase in MATCHES:
        assert Q._OPEN_CHAT.fullmatch(phrase), f"expected a match: {phrase!r}"
    for phrase in NON_MATCHES:
        assert not Q._OPEN_CHAT.fullmatch(phrase), f"expected NO match: {phrase!r}"
    return {
        "_comment": ("Generated by tools/gen_open_chat_cases.py from the real "
                     "jarvis_quick._OPEN_CHAT. Do not edit by hand."),
        "matches": MATCHES,
        "non_matches": NON_MATCHES,
    }


def document() -> str:
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    doc = document()
    if "--check" in sys.argv:
        if not PHONE.exists() or PHONE.read_text(encoding="utf-8") != doc:
            print(f"STALE {PHONE.relative_to(ROOT)} - run python3 tools/gen_open_chat_cases.py")
            return 1
        print("open-chat-cases.json: up to date")
        return 0
    PHONE.parent.mkdir(parents=True, exist_ok=True)
    PHONE.write_text(doc, encoding="utf-8", newline="\n")
    print(f"wrote {PHONE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
