#!/usr/bin/env python3
"""
Generates Palette.kt from jarvis-visual-spec.json.

The spec exports `argb` for exactly this purpose. Hand-transcribing 50 colours
produced three that were a digit off and sat behind a comment claiming they were
the spec's own, so this does the transcription mechanically and
SpecDriftTest.kt asserts the result still matches the JSON.

    python3 tools/gen_palette.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "jarvis-client/app/src/test/resources/jarvis-visual-spec.json"
OUT = ROOT / "jarvis-client/app/src/main/java/com/jarvis/client/face/Palette.kt"

spec = json.loads(SPEC.read_text())
colors = spec["palette"]["colors"]

FAMILIES = []
for c in colors:
    if c["family"] not in FAMILIES:
        FAMILIES.append(c["family"])

lines = [
    "package com.jarvis.client.face",
    "",
    "import androidx.compose.ui.graphics.Color",
    "",
    "/**",
    " * The spec's 50 colours: ten families of five steps.",
    " *",
    " * GENERATED by tools/gen_palette.py from",
    " * app/src/test/resources/jarvis-visual-spec.json. Do not edit by hand —",
    " * SpecDriftTest re-reads that JSON and will fail if these drift from it.",
    " *",
    " * Step 1 is the deepest and step 5 the palest. Names are the spec's own, so",
    " * `Palette.ice(4)` and the desktop's `ice-4` are the same colour by",
    " * construction rather than by somebody checking.",
    " */",
    "object Palette {",
    "",
]

for c in colors:
    kid = c["id"].replace("-", "_").upper()
    lines.append(f'    /** `{c["id"]}` — {c["name"]}. */')
    lines.append(f'    val {kid} = Color({c["argb"]})')
lines.append("")

lines.append("    /** Every colour by its spec id, e.g. `\"ice-4\"`. */")
lines.append("    val byId: Map<String, Color> = mapOf(")
for c in colors:
    kid = c["id"].replace("-", "_").upper()
    lines.append(f'        "{c["id"]}" to {kid},')
lines.append("    )")
lines.append("")

lines.append("    /** The ten family names, in the spec's order. */")
lines.append("    val families: List<String> = listOf(")
for f in FAMILIES:
    lines.append(f'        "{f}",')
lines.append("    )")
lines.append("")
lines.append("    /**")
lines.append("     * One family's five steps, deepest first.")
lines.append("     *")
lines.append("     * Used to walk a bound colour up or down its OWN family until it clears")
lines.append("     * a contrast floor. Walking toward white instead would desaturate the")
lines.append("     * hue, and the hue is the thing the user bound.")
lines.append("     */")
lines.append("    fun steps(family: String): List<Color> =")
lines.append("        (1..5).mapNotNull { byId[\"$family-$it\"] }")
lines.append("")
lines.append("    /** The family a colour belongs to, or null if it is not a palette colour. */")
lines.append("    fun familyOf(color: Color): String? =")
lines.append("        byId.entries.firstOrNull { it.value == color }?.key?.substringBeforeLast('-')")
lines.append("")
lines.append("    /** The step (1..5) a colour sits at, or null if it is not a palette colour. */")
lines.append("    fun stepOf(color: Color): Int? =")
lines.append("        byId.entries.firstOrNull { it.value == color }")
lines.append("            ?.key?.substringAfterLast('-')?.toIntOrNull()")
lines.append("}")
lines.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({len(colors)} colours, {len(FAMILIES)} families)")
