#!/usr/bin/env python3
"""Writes the approval card's words for both apps, and checks them.

    python3 tools/gen_card_words_cases.py            # write both copies
    python3 tools/gen_card_words_cases.py --check    # compare only

One card on every screen (the creativity audit, 2026-09-25): the same title,
the same label, the same button order and the same spoken lines in the
Jarvis bar, the widget, the HUD page and the phone. The words live in
backend/jarvis_card_words.py; the title a card shows is the notice's, made
by the real `notice_for` (approval-notice.patch, run the way
backend/test_approval_contract.py runs it). This writes them into

    jarvis-desktop/tests/fixtures/card-words-cases.json
    jarvis-client/app/src/test/resources/contract/card-words-cases.json

(byte-identical). The desktop's tests/card-words.mjs and the phone's
CardWordsContractTest read it, so neither app can word a card differently.

`fallback` is what an app shows for a row with NO notice (a backend older
than approval-notice.patch): both apps build it from the action's name the
same way the PC does for an action it has no phrase for.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

import jarvis_card_words as W  # noqa: E402
import test_approval_contract as C  # noqa: E402

DESKTOP = ROOT / "jarvis-desktop" / "tests" / "fixtures" / "card-words-cases.json"
PHONE = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources" / "contract"
         / "card-words-cases.json")
COPIES = (DESKTOP, PHONE)

#: Names with no phrase: how the fallback reads them. Odd shapes on purpose.
#: Strings only: a row's `action` is text, or absent (read as "").
UNKNOWN = ["frobnicate_widget", "", "   ", "a__b", "Weird-Name!!", "café_lights", "x" * 90]


#: The chat stream's status words during one spoken question, in order.
SCRIPTS = [
    ["approval", "approved"],
    ["approval", "denied"],
    ["thinking", "approval", "timed_out", "thinking"],
    ["approved"],
    ["approval", "approval", "working", "approved"],
    ["approval", "denied", "approval", "approved"],
    ["thinking", "working"],
    ["approval"],
    ["denied", "timed_out"],
]


def build() -> dict:
    notice_for = C.load_notice_for()
    titles = [{"action": a, "title": notice_for({"action": a})["title"]}
              for a in sorted(W.TITLES)]
    fallback = [{"action": a, "title": W.title_for(a)} for a in UNKNOWN]
    voice_script = [{"words": s, "says": W.voice_lines(s)} for s in SCRIPTS]
    return {
        "_comment": ("Generated by tools/gen_card_words_cases.py from "
                     "backend/jarvis_card_words.py and the real notice_for. "
                     "Do not edit by hand."),
        "kicker": W.KICKER,
        "buttons": list(W.BUTTONS),
        "no_action": W.NO_ACTION,
        "voice": dict(W.VOICE),
        "until_approved": W.UNTIL_APPROVED,
        "titles": titles,
        "fallback": fallback,
        "voice_script": voice_script,
    }


def document() -> str:
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    doc = document()
    if "--check" in sys.argv:
        bad = [p for p in COPIES
               if not p.exists() or p.read_text(encoding="utf-8") != doc]
        for p in bad:
            print(f"STALE {p.relative_to(ROOT)} - run python3 tools/gen_card_words_cases.py")
        if not bad:
            print("card-words-cases.json: both copies match")
        return 1 if bad else 0
    for p in COPIES:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(doc, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
