#!/usr/bin/env python3
"""Re-take `jarvis-backend/` from a backend folder, or check that it is current.

    py -3 tools/gen_base_from_backend.py --source "<the backend folder>"
    py -3 tools/gen_base_from_backend.py --source "<the backend folder>" --check

WHY THIS EXISTS

`jarvis-backend/` is the only complete copy of this program in this repository:
the folder a stranger clones and runs, and (before build step 3 of
`docs/UPDATER-REDESIGN.md` section 5) a copy that was taken BY HAND on
2026-10-06 and never re-taken. `jarvis-backend/README.md`'s follow-up 8 says
exactly this - "The base is not regenerated by a script ... one script that
re-takes it and fails on a difference would be the next step" - and this is
that script.

THE RULE IT FOLLOWS, which is the README's own "The exact rule, so it can be
re-taken", and nothing else:

    every top-level *.py in the live backend folder, EXCEPT
        test_*.py             (the tests are this repository's)
        patch_openjarvis.py   (a tool for a different project)
        spike_sandbox.py      (an experiment)
    plus these six files:
        jarvis_hud.html          from jarvis-desktop/src/
        jarvis-framework.toml    from backend/rebuilt/  - the TEMPLATE, never the live file
        requirements.lock        from backend/
        quiz_grader_cases.json   from backend/
        rust-crates.lock         from jarvis-desktop/src-tauri/Cargo.lock
        jarvis-visual-spec.json  the owner's own copy, which is what /api/visual-spec reads

Everything is written with LF line endings, which is this repository's rule
(`.gitattributes`), and read with UTF-8. `jarvis-backend/README.md` and
`jarvis-backend/.gitignore` are left exactly as they are: they are about the
folder, not part of the copy. `jarvis-backend/_where.py` is left as it is too -
it is a resource file this repository owns, not a copy of anything on the
owner's PC, and the two copies are deliberately different (the base's one
knows it is a base).

THE ONE EXCEPTION, and why it is here rather than left to a reader

`jarvis-backend/README.md`, "The one deliberate difference from the author's
file": the owner's live `jarvis_gate.py` writes four keys into the same dict
literal twice. CPython keeps the LAST one silently, so the earlier line is
dead, and `tools/check_literal_keys.py` reports every duplicate it can see.
The base was published with those earlier lines REMOVED and nothing else
changed. A copy re-taken from the owner's folder today would put them back -
and would then fail that check - so the rule is applied by this script: inside
one dict literal, a key written more than once keeps its LAST line and its
earlier lines are dropped, the same shape the README describes, generalised so
it is not four hard-coded line numbers that mean nothing on a file that has
moved since. Every drop is named in what this script prints, and `--check`
counts them, so the exception can never be quiet.

WHAT `--check` IS FOR

It is the half of build step 3 that "fails when it differs": on a machine that
has the backend folder, it re-derives the base in memory and compares it,
file by file, with the one committed here. Exit 0 means this repository's
`jarvis-backend/` is exactly what that folder produces; exit 1 names every file
that is not, in both directions (a copy that was edited here, and a live file
this repository has never seen). Both directions matter: one is a stale base,
the other is a base nobody can reproduce.

WHAT IT DOES NOT DO, plainly

It never writes to `--source`. It does not apply patches, so it knows nothing
about whether the folder it is given carries the whole stack: a base taken from
a half-patched folder is a faithful copy of a half-patched folder, and
`backend/test_base_matches_repo.py` is what notices that the repository's own
copies disagree with it. It does not delete a file the committed base has and
the source folder does not (a module removed from the program is a repository
decision, not a copy): it names every such file instead.

Standard library only. Runs anywhere; `--source` needs the owner's folder.
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: A top-level .py in the live folder this copy never takes.
#: (pattern, why) - the README's "What is not here", as a machine's rule.
NEVER_COPIED = (
    (re.compile(r"^test_.*\.py$"), "the tests are this repository's, and a base carries none"),
    (re.compile(r"^patch_openjarvis\.py$"), "a tool for a different project"),
    (re.compile(r"^spike_sandbox\.py$"), "an experiment"),
)

#: The files that come from THIS REPOSITORY rather than the live folder:
#: (name in the base, where it comes from, why).
#: `{repo}` is the repository root. The README's own table, in its own order.
BESIDE = (
    ("jarvis_hud.html", "{repo}/jarvis-desktop/src/jarvis_hud.html",
     "jarvis_hud.py serves HERE/jarvis_hud.html at \"/\", and it was never in the backend folder"),
    ("jarvis-framework.toml", "{repo}/backend/rebuilt/jarvis-framework.toml",
     "the TEMPLATE a new user needs, never the owner's live settings file"),
    ("requirements.lock", "{repo}/backend/requirements.lock",
     "jarvis_tool_updates.py, jarvis_backup.py, jarvis_pc_help.py read it"),
    ("quiz_grader_cases.json", "{repo}/backend/quiz_grader_cases.json",
     "eval_quiz_grader.py reads it"),
    ("rust-crates.lock", "{repo}/jarvis-desktop/src-tauri/Cargo.lock",
     "jarvis_tool_updates.py reads it"),
    ("jarvis-visual-spec.json", "{source}/jarvis-visual-spec.json",
     "the owner's own copy, which is what /api/visual-spec reads"),
)

#: Files the base folder carries that are NOT part of the copy: the folder's
#: own documents, and the one resource this repository owns.
NOT_PART_OF_THE_COPY = (
    ("README.md", "about the folder"),
    (".gitignore", "the second line of defence against his private files"),
    ("_where.py", "a resource this repository owns; the base's copy knows it is a base"),
)


def read_text(path: Path) -> str:
    """The file as text with LF endings, which is the only form compared."""
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def dropped_duplicate_keys(text: str) -> tuple:
    """(new text, [(key, line number), ...]) - one dict literal, one key.

    A key written twice in the same dict literal is silent in CPython, which
    keeps the LAST line; the earlier line is dead. This drops the earlier ones
    and returns the text without them, which is the one deliberate difference
    `jarvis-backend/README.md` records between the base and the owner's file.

    Only a LITERAL is touched: `d[k] = v` statements are how a program is
    supposed to fill a dict, and every one of them is left alone. A duplicate
    this cannot attribute to a literal (a syntax error, an f-string holding a
    brace) leaves the text exactly as it was - a copy that guessed would be
    worse than one that says it could not tell.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return text, []
    lines = text.splitlines(keepends=True)
    drop = {}          # 1-based line number -> key it wrote
    for node in ast.walk(tree):
        if not isinstance(node, ast.Dict):
            continue
        # key text -> the line numbers its KEY was written on, in order.
        at = {}
        for k in node.keys:
            if isinstance(k, ast.Constant) and isinstance(k.value, str):
                at.setdefault(k.value, []).append(k.lineno)
        for key, linenos in at.items():
            if len(linenos) < 2:
                continue
            # Keep the LAST line (CPython's own answer) and drop the earlier
            # ones - but only when each is one whole physical line, so nothing
            # is half-cut. A key written twice on ONE line, or an entry that
            # spans lines, is left alone rather than half-removed.
            for n in linenos[:-1]:
                if 1 <= n <= len(lines) and lines[n - 1].strip():
                    drop[n] = key
    if not drop:
        return text, []
    out = "".join(ln for i, ln in enumerate(lines, start=1) if i not in drop)
    try:
        ast.parse(out)
    except SyntaxError:
        # The drop would not compile, so it was the wrong edit. Leave the file
        # exactly as it arrived rather than write Python that will not run.
        return text, []
    return out, sorted((n, k) for n, k in drop.items())


def planned(source: Path, repo: Path) -> tuple:
    """(name -> text to write, [problems]) for one backend folder.

    Nothing is written here; the whole base is derived in memory first, so
    `--check` and a real run compare the same thing.
    """
    want = {}
    problems = []
    if not (source / "jarvis_hud.py").is_file():
        problems.append(f"{source} does not look like a backend folder: no jarvis_hud.py in it")
        return want, problems

    for p in sorted(source.glob("*.py")):
        skip = next((why for pat, why in NEVER_COPIED if pat.match(p.name)), None)
        if skip:
            continue
        text = read_text(p)
        text, dropped = dropped_duplicate_keys(text)
        want[p.name] = text
        for key, lineno in dropped:
            problems.append(f"{p.name}:{lineno}: dropped the earlier \"{key}\" line "
                            f"(written again later in the same dict literal)")

    for name, where, why in BESIDE:
        src = Path(where.format(repo=repo.as_posix(), source=source.as_posix()))
        if not src.is_file():
            problems.append(f"{name}: not found at {src} ({why})")
            continue
        want[name] = read_text(src)
    return want, problems


def compare(want: dict, base: Path) -> tuple:
    """(what differs, what the base has that this copy would not write)."""
    differ, extra = [], []
    for name, text in sorted(want.items()):
        theirs = base / name
        if not theirs.is_file():
            differ.append((name, "not in the base at all"))
        elif read_text(theirs) != text:
            differ.append((name, f"the base holds {theirs.stat().st_size} B, "
                                 f"this folder produces {len(text.encode('utf-8'))} B"))
    for p in sorted(base.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(base).as_posix()
        if rel in want or rel in [n for n, _ in NOT_PART_OF_THE_COPY]:
            continue
        extra.append(rel)
    return differ, extra


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Re-take jarvis-backend/ from a backend folder, or check that it is current.")
    ap.add_argument("--source", required=True,
                    help="the backend folder holding jarvis_hud.py (only ever READ)")
    ap.add_argument("--base", default=str(REPO / "jarvis-backend"),
                    help="the folder this writes to (default: this repository's jarvis-backend/)")
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 and name every file that differs")
    args = ap.parse_args(argv)

    source = Path(args.source).resolve()
    base = Path(args.base).resolve()
    want, problems = planned(source, REPO)
    if problems and not want:
        for p in problems:
            print(f"FAIL  {p}")
        return 1

    print(f"Source  : {source}")
    print(f"Base    : {base}")
    print(f"Rule    : every top-level *.py except the tests, patch_openjarvis.py and "
          f"spike_sandbox.py, plus {len(BESIDE)} files this repository owns")
    print(f"Planned : {len(want)} file(s)")
    for p in problems:
        print(f"        {p}")

    if args.check:
        differ, extra = compare(want, base)
        if not base.is_dir():
            print(f"FAIL  {base} is not a folder")
            return 1
        if extra:
            print("")
            print(f"FAIL  {len(extra)} file(s) are in the base and this copy would not write them:")
            for rel in extra:
                print(f"        {rel}")
        if differ:
            print("")
            print(f"FAIL  {len(differ)} file(s) differ from what this folder produces:")
            for name, why in differ:
                print(f"        {name} - {why}")
        if differ or extra:
            print("")
            print("The base is NOT what this backend folder produces. Nothing was written.")
            print("Re-take it with the same command without --check.")
            return 1
        print("")
        print(f"ok    all {len(want)} file(s) are exactly what this backend folder produces")
        return 0

    if not base.is_dir():
        print(f"FAIL  {base} is not a folder")
        return 1
    written, unchanged = 0, 0
    for name, text in sorted(want.items()):
        dest = base / name
        if dest.is_file() and read_text(dest) == text:
            unchanged += 1
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(text.encode("utf-8"))
        written += 1
        print(f"        wrote {name}")
    differ, extra = compare(want, base)
    print("")
    if extra:
        print(f"Note    : {len(extra)} file(s) are in the base and this copy does not write them.")
        print("          A module removed from the program is a repository decision, so none of")
        print("          these was deleted:")
        for rel in extra:
            print(f"            {rel}")
    print(f"Wrote {written}, left {unchanged} unchanged.")
    if differ:
        print(f"FAIL  {len(differ)} file(s) still differ after writing (a lock, or a read-only file):")
        for name, why in differ:
            print(f"        {name} - {why}")
        return 1
    print("ok    the base is now what this backend folder produces")
    return 0


if __name__ == "__main__":
    sys.exit(main())
