#!/usr/bin/env python3
"""Writes the shared table for the headless browser's settings block, for both
apps, and checks it.

    python3 tools/gen_browser_cases.py            # write both copies
    python3 tools/gen_browser_cases.py --check    # compare only

The headless browser (Obscura; the owner's decision of 2026-09-29, JARVIS-API
section 97) is decided on the PC (backend/jarvis_browser_engine.py). Both apps
show its setting - the switch, which browser Jarvis uses by default, the install
status and the one PowerShell line - and must say exactly the same words:

  words     the fixed words (title, detail, switch, the three modes and their
            help, the honest stealth line, the off and waiting lines, the
            install steps)
  panels    what each app shows for one GET /api/browser/engine answer, as
            `panel()` in jarvis_browser_engine.py decides it
  modes     the three mode names, in order

The words come from jarvis_browser_engine.py itself, so an app cannot word them
differently. This writes the SAME file into

    jarvis-desktop/tests/fixtures/browser-engine-cases.json
    jarvis-client/app/src/test/resources/contract/browser-engine-cases.json

(byte-identical). The desktop's tests/browser-engine.mjs runs every case through
src/browser-engine-rules.js, the phone's BrowserEngineTest through
net/BrowserEngine.kt, and backend/test_browser_engine.py checks both copies are
current.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

import jarvis_browser_engine as E  # noqa: E402

DESKTOP = ROOT / "jarvis-desktop" / "tests" / "fixtures" / "browser-engine-cases.json"
PHONE = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources" / "contract"
         / "browser-engine-cases.json")
COPIES = (DESKTOP, PHONE)

_LINE = ("$d = \"$env:USERPROFILE\\.openjarvis\\obscura\"; New-Item -ItemType Directory -Force -Path "
         "$d | Out-Null; Invoke-WebRequest -Uri 'https://example.invalid/obscura.zip' -OutFile "
         "\"$d\\obscura.zip\"; (Get-FileHash -Algorithm SHA256 -LiteralPath \"$d\\obscura.zip\").Hash")
_INSTALLED = "Installed and checked (version 0.1.0, last checked 29 Sep 2026)."


def _payload(**kw):
    base = {"obscura": False, "waiting": False, "mode": "auto", "status_line": "",
            "install_line": _LINE}
    base.update(kw)
    return base


PAYLOADS = [
    ("off, not installed", _payload(
        line=E.state_line(enabled=False, waiting=False, ready_now=False, not_ready=""),
        status_line="Obscura is not installed on this PC yet.")),
    ("its card is waiting", _payload(
        waiting=True, line=E.state_line(enabled=False, waiting=True, ready_now=False, not_ready=""),
        status_line="Obscura is not installed on this PC yet.")),
    ("on but not installed", _payload(
        obscura=True,
        line=E.state_line(enabled=True, waiting=False, ready_now=False,
                          not_ready=E.OB.WHY["not_installed"]),
        status_line="Obscura is not installed on this PC yet.")),
    ("on, installed and checked, Automatic", _payload(
        obscura=True,
        line=E.state_line(enabled=True, waiting=False, ready_now=True, not_ready=""),
        status_line=_INSTALLED)),
    ("on, installed, the owner's default is Headless", _payload(
        obscura=True, mode="headless",
        line=E.state_line(enabled=True, waiting=False, ready_now=True, not_ready=""),
        status_line=_INSTALLED)),
    ("on but the file changed since it was checked", _payload(
        obscura=True, mode="visible",
        line=E.state_line(enabled=True, waiting=False, ready_now=False,
                          not_ready=E.OB.WHY["changed"]),
        status_line=("Installed, but the file has changed since it was checked - Jarvis will not "
                     "start it until you run the install line again."))),
    ("a card is waiting while it is somehow already on", _payload(
        obscura=True, waiting=True, line="", status_line="")),
    ("an unknown mode shows as Automatic", _payload(mode="stealthy", line="")),
    ("off and the PC sent no words", {"obscura": False}),
    ("an answer that is not a status", {"waiting": True}),
    ("not an object", None),
]


def document() -> str:
    doc = {
        "_comment": ("Generated by tools/gen_browser_cases.py from backend/jarvis_browser_engine.py. "
                     "Do not edit by hand. The owner's decision of 2026-09-29: Jarvis may use a "
                     "headless browser (Obscura, stealth on) for plain web reading, off by "
                     "default, on is one approval card."),
        "words": E.WORDS,
        "modes": list(E.MODES),
        "default_mode": E.DEFAULT_MODE,
        "panels": [{"name": name, "payload": payload, "want": E.panel(payload)}
                   for name, payload in PAYLOADS],
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main(argv) -> int:
    text = document()
    if "--check" in argv:
        stale = [p for p in COPIES if not p.exists() or p.read_text(encoding="utf-8") != text]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)} - run python3 tools/gen_browser_cases.py")
        if not stale:
            print("browser-engine-cases.json is current in both apps")
        return 1 if stale else 0
    for p in COPIES:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
