#!/usr/bin/env python3
"""Writes "Things you can say"'s contract file for both apps, and checks it.

    python3 tools/gen_sayable_cases.py            # write both copies
    python3 tools/gen_sayable_cases.py --check    # compare only

What GET /api/sayable really answers (backend/jarvis_sayable.py), made by the
real code - nothing is written by hand:

    jarvis-desktop/tests/fixtures/sayable-cases.json
    jarvis-client/app/src/test/resources/contract/sayable-cases.json

(byte-identical). The desktop's tests/sayable.mjs and the phone's
SayableContractTest read it, so neither app can carry a different list.

Unlike reach-cases.json (a live, per-PC settings list), this list is fixed
text with no settings behind it - the same shape as
tools/gen_card_words_cases.py's approval-card words - so both apps hold a
plain, hardcoded copy (sayable.js, Sayable.kt) rather than fetching it live;
this fixture is what proves those hardcoded copies have not drifted from the
backend's own words.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

import jarvis_sayable as S  # noqa: E402

DESKTOP = ROOT / "jarvis-desktop" / "tests" / "fixtures" / "sayable-cases.json"
PHONE = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources" / "contract"
         / "sayable-cases.json")
COPIES = (DESKTOP, PHONE)


def build() -> dict:
    v = S.view()
    return {
        "_comment": ("Generated by tools/gen_sayable_cases.py from "
                     "backend/jarvis_sayable.py. Do not edit by hand."),
        "title": v["title"],
        "detail": v["detail"],
        "footer": v["footer"],
        "sentences": v["sentences"],
        "walkthrough_examples": v["walkthrough_examples"],
        "help_title": v["help_title"],
        "help_body": v["help_body"],
    }


def document() -> str:
    return json.dumps(build(), indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    doc = document()
    if "--check" in sys.argv:
        bad = [p for p in COPIES
               if not p.exists() or p.read_text(encoding="utf-8") != doc]
        for p in bad:
            print(f"STALE {p.relative_to(ROOT)} - run python3 tools/gen_sayable_cases.py")
        if not bad:
            print("sayable-cases.json: both copies match")
        return 1 if bad else 0
    for p in COPIES:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(doc, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
