#!/usr/bin/env python3
"""Generate both apps' copies of the animal faces from one source.

The red panda is drawn by a single shader, `jarvis-desktop/critters/
redpanda.sksl`. The desktop draws with WebGL2 (GLSL) and the phone with
android.graphics.RuntimeShader (AGSL); the two languages agree on almost
everything except the names of their vector types, so the source is written
with AGSL's names and the desktop copy gets a handful of `#define`s on top.
Each app then adds its own few-line `main`, because the two differ in how a
pixel's position arrives.

It also writes the POSE fixture. The panda's body language is worked out
once a frame by `jarvis-desktop/src/critter-pose.js` on the desktop and by a
line-for-line Kotlin copy on the phone. This runs the JavaScript under node at
fixed moments and saves what it returns; the phone's `CritterPoseTest` fails
if its Kotlin copy disagrees, so the two cannot drift apart quietly.

    python3 tools/gen_critters.py          # write all three
    python3 tools/gen_critters.py --check  # exit 1 if any is out of date

`jarvis-desktop/tests/faces.mjs` runs `--check`.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "jarvis-desktop" / "critters" / "redpanda.sksl"
POSE_JS = ROOT / "jarvis-desktop" / "src" / "critter-pose.js"
OUT_JS = ROOT / "jarvis-desktop" / "src" / "critters-gen.js"
OUT_KT = (ROOT / "jarvis-client" / "app" / "src" / "main" / "java" / "com" / "jarvis"
          / "client" / "face" / "CritterShaders.kt")
OUT_GOLDEN = (ROOT / "jarvis-client" / "app" / "src" / "test" / "resources"
              / "critter-pose-golden.json")

GLSL_HEAD = """#version 300 es
precision highp float;
#define float2 vec2
#define float3 vec3
#define float4 vec4
#define half3 vec3
#define half4 vec4
"""

GLSL_MAIN = """
uniform vec2 uRes;
uniform vec3 uBg;
out vec4 oCol;
void main() {
    // gl_FragCoord counts y UP the screen, which is what critter() wants.
    vec2 p = (gl_FragCoord.xy - 0.5 * uRes) / min(uRes.x, uRes.y) * 2.0;
    vec4 c = critter(p);
    oCol = vec4(uBg * (1.0 - c.a) + c.rgb, 1.0);
}
"""

AGSL_MAIN = """
uniform float2 uCenter;
uniform float uR;
half4 main(float2 fragCoord) {
    // fragCoord counts y DOWN the screen; critter() wants it up.
    float2 p = (fragCoord - uCenter) / uR;
    p.y = -p.y;
    return half4(critter(p));
}
"""

# The moments the pose fixture samples: every state, blended and settled,
# with and without sound and a pointer, at clock values that land on a
# blink, a wave, a breath.
STATES = ["idle", "listening", "thinking", "speaking", "approval", "standby", "error", "banked"]


def golden_cases():
    cases = []
    for i, s in enumerate(STATES):
        for t in (0.0, 1.37, 4.43 + i * 0.11, 12.9):
            cases.append({"state": s, "prev": s, "since": 5.0, "t": t, "amp": 0.0, "look": {}})
        cases.append({"state": s, "prev": STATES[(i + 3) % 8], "since": 0.21, "t": 7.7, "amp": 0.6,
                      "look": {"x": 0.4, "y": -0.3, "w": 0.8}})
    # The blink itself, caught closing, shut and opening. The first blink
    # lands at 0.975 s (critter-pose.js's hash of period 0) and lasts 0.15 s;
    # the second at 4.568 s.
    for t in (1.0, 1.05, 1.1, 4.6):
        cases.append({"state": "idle", "prev": "idle", "since": 9.0, "t": t, "amp": 0.0, "look": {}})
    return cases


NODE = r"""
require(process.argv[1]);
const C = globalThis.CritterPose;
const cases = JSON.parse(require('fs').readFileSync(0, 'utf8'));
const out = cases.map(c => ({
  ...c,
  uniforms: C.uniforms(C.pose(c.state, c.prev, c.since, c.t, c.amp, c.look)),
}));
// Six decimals: the Kotlin copy runs in 32-bit floats and is checked to
// within a thousandth, so more digits would only be noise in the diff.
process.stdout.write(JSON.stringify(out, (k, v) =>
  typeof v === 'number' ? Math.round(v * 1e6) / 1e6 : v, 1) + '\n');
"""


def build():
    body = SRC.read_text(encoding="utf-8")
    glsl = GLSL_HEAD + body + GLSL_MAIN
    agsl = body + AGSL_MAIN
    if '"""' in agsl or "$" in agsl:
        sys.exit("redpanda.sksl must not contain a triple quote or a dollar sign: "
                 "both break a Kotlin raw string")

    js = (
        "// GENERATED by tools/gen_critters.py from jarvis-desktop/critters/*.sksl.\n"
        "// Do not edit: edit the .sksl and re-run `python3 tools/gen_critters.py`.\n"
        "window.JARVIS_CRITTERS = Object.freeze({\n"
        f"  redpanda: {json.dumps(glsl)},\n"
        "});\n"
    )
    kt = (
        "// GENERATED by tools/gen_critters.py from jarvis-desktop/critters/*.sksl.\n"
        "// Do not edit: edit the .sksl and re-run `python3 tools/gen_critters.py`.\n"
        "package com.jarvis.client.face\n\n"
        "/** The animal faces' AGSL, one shared source with the desktop's GLSL. */\n"
        "internal object CritterShaders {\n"
        f'    const val RED_PANDA = """{agsl}"""\n'
        "}\n"
    )
    res = subprocess.run(["node", "-e", NODE, str(POSE_JS)], input=json.dumps(golden_cases()),
                         capture_output=True, text=True, check=True)
    return {OUT_JS: js, OUT_KT: kt, OUT_GOLDEN: res.stdout}


def main():
    check = "--check" in sys.argv
    stale = []
    for path, text in build().items():
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == text:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text, encoding="utf-8")
            print("wrote", path.relative_to(ROOT))
    if stale:
        print("out of date - run `python3 tools/gen_critters.py`:\n  " + "\n  ".join(stale))
        sys.exit(1)


if __name__ == "__main__":
    main()
