#!/usr/bin/env python3
"""Write the files for an outside (Gemini) audit of what changed since the
last one, split into sessions, each a single Markdown file to attach.

    py -3 tools\\gen_gemini_bundles.py                 # since the last audit
    py -3 tools\\gen_gemini_bundles.py --since <commit>
    py -3 tools\\gen_gemini_bundles.py --out <folder>
    py -3 tools\\gen_gemini_bundles.py --budget 300    # smaller files (k tokens)

Why several files and not one: docs/GEMINI-AUDIT.md section 1 - a model
asked to audit four languages at once spreads itself thin, and one past
about 400k tokens reads shallowly. So each session is one part of Jarvis:
the backend's safety core and its abilities (Python, the patches, the
install script), the desktop app's Rust, the desktop app's windows
(JavaScript and HTML), the phone app's core and its screens (Kotlin), and
the tools and build files. A part that would still be bigger than
`--budget` (400k tokens by default) is split again, by folder, into
"part 1 of N" files, so no single file is read shallowly.

What goes in: every source file ADDED or CHANGED since `--since`, whole, as
it is now - a reviewer needs the whole file, not a diff. What stays out, and
is LISTED in each file with the reason, so "not in the bundle" never looks
like "does not exist": tests and their fixtures, generated data modules
(their first lines say "GENERATED by"), lock files, binaries and docs. The
prompt that goes with them is docs/GEMINI-AUDIT-2026-09-28.md.

Nothing is sent anywhere; this only writes files. It reads git, so run it
from inside the repository.
"""
import argparse
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: The commit whose fixes closed the last Gemini audit: "Fix seven real
#: findings from a Gemini audit, verified against source first (#10)",
#: 2026-09-20. Everything after it has not been read by an outside model.
LAST_AUDIT = "093caee"

def _backend(p):
    return (p.startswith("backend/") and (p.endswith(".py") or p.endswith(".patch")
                                          or p.endswith(".toml") or p.endswith(".txt")
                                          or p.endswith(".Modelfile"))) \
        or p == "scripts/apply-patches.ps1" or p == ".github/workflows/ci.yml" \
        or (p.startswith("server/") and p.endswith(".py"))


#: The backend's SAFETY CORE: the modules where a mistake would break one
#: of the five rules - the agent loop, the approval gate and what asks
#: first, memory and learning, the sensitive-topic and private-text checks,
#: the token and owner checks, the network reach rules. Every other
#: jarvis_*.py module is an ability the owner uses (voice, search, timers,
#: chatbots, faces...) and goes in its own session. Listed this way round
#: (safety core named, abilities by default) because abilities are what
#: new work mostly adds: a new ability can never land in the core unseen,
#: and the core list only changes when the safety design does.
SAFETY_CORE = ("jarvis_agent", "jarvis_gate", "jarvis_asks_first", "jarvis_auto_learn",
               "jarvis_learning_switch", "jarvis_intake", "jarvis_entities",
               "jarvis_sensitive", "jarvis_scrub", "jarvis_mail_mask", "jarvis_paste_guard",
               "jarvis_owner_check", "jarvis_token_store", "jarvis_card_words",
               "jarvis_claims", "jarvis_tidy", "jarvis_forget_range", "jarvis_past",
               "jarvis_chat_log", "jarvis_local_http", "jarvis_reach", "jarvis_child_env",
               "jarvis_owned_tables", "jarvis_settings_registry", "jarvis_stop_all",
               "jarvis_plan", "jarvis_sources", "jarvis_backup", "jarvis_memory",
               "jarvis_router", "jarvis_hud")


def _ability(p):
    name = os.path.basename(p)
    return p.startswith("backend/") and name.startswith("jarvis_") and p.endswith(".py") \
        and not name.startswith(SAFETY_CORE) and not p.startswith("backend/rebuilt/")


PHONE_SCREENS = ("/client/ui/", "/client/face/", "/client/voice/")


def _phone(p):
    return (p.startswith("jarvis-client/app/src/main/") and os.path.splitext(p)[1] in (".kt", ".xml")) \
        or p in ("jarvis-client/app/build.gradle.kts", "jarvis-client/app/proguard-rules.pro",
                 ".github/workflows/jarvis-client.yml")


SESSIONS = [
    ("1a-backend-safety", "The Python backend's safety core: the agent loop, the approval gate, "
     "memory and learning, the sensitive-topic check, the patches and the install script",
     lambda p: _backend(p) and not _ability(p)),
    ("1b-backend-abilities", "The Python backend's abilities: voice, web search, timers and the "
     "scheduler, the briefing, calendar, email, notes, the graphics-card lanes, computer control",
     lambda p: _backend(p) and _ability(p)),
    ("2-desktop-rust", "The desktop app's Rust (src-tauri) and its build",
     lambda p: p.startswith("jarvis-desktop/src-tauri/") and (
         p.endswith(".rs") or p.endswith("Cargo.toml") or p.endswith(".json")
         or p.endswith(".toml") or p.endswith(".js"))
     or p == ".github/workflows/desktop-release.yml"),
    ("3-desktop-web", "The desktop app's windows (JavaScript, HTML, CSS, shaders)",
     lambda p: p.startswith("jarvis-desktop/src/")
     and os.path.splitext(p)[1] in (".js", ".html", ".css", ".glsl")),
    ("4a-phone-core", "The phone app's network, runtime, security, services and build",
     lambda p: _phone(p) and not any(x in p for x in PHONE_SCREENS)),
    ("4b-phone-screens", "The phone app's screens, the animated face, and voice",
     lambda p: _phone(p) and any(x in p for x in PHONE_SCREENS)),
    ("5-tools-and-build", "The repository's own tools and build: generators, checkers, the "
     "tool and model tryouts, helper scripts and the other CI workflows",
     lambda p: (p.startswith("tools/") and os.path.splitext(p)[1] in (".py", ".ps1", ".sh"))
     or (p.startswith("scripts/") and p != "scripts/apply-patches.ps1"
         and os.path.splitext(p)[1] in (".ps1", ".py", ".sh"))
     or p.endswith(".ps1") and "/" not in p
     or (p.startswith(".github/workflows/") and p not in (
         ".github/workflows/ci.yml", ".github/workflows/desktop-release.yml",
         ".github/workflows/jarvis-client.yml"))
     or (p.startswith("jarvis-desktop/scripts/") and os.path.splitext(p)[1] in (".py", ".mjs", ".js", ".ps1"))),
]

#: Backend files that are test harnesses rather than Jarvis itself: they
#: only run the tests, grade answers or stand in for a real server.
TEST_HARNESSES = ("eval_", "selftest", "run_suites", "fake_mcp_server", "grade-peers",
                  "jarvis_live_photo_test")

LANG = {".py": "python", ".patch": "diff", ".ps1": "powershell", ".rs": "rust",
        ".js": "javascript", ".html": "html", ".css": "css", ".kt": "kotlin",
        ".kts": "kotlin", ".xml": "xml", ".json": "json", ".toml": "toml",
        ".yml": "yaml", ".txt": "text", ".pro": "text"}


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True,
                          check=True).stdout


def why_left_out(path):
    """The reason a changed file is not in a bundle, or "" to include it."""
    name = os.path.basename(path)
    if "/tests/" in path or "/src/test/" in path or "/androidTest/" in path \
            or name.startswith("test_") \
            or "/fixtures/" in path or "sensitive_cases/" in path or "_cases" in name:
        return "a test or test data"
    if name.startswith("_") and path.startswith("backend/"):
        return "test plumbing"
    if path.startswith("backend/") and name.startswith(TEST_HARNESSES):
        return "a test harness (runs or grades the tests, not part of Jarvis itself)"
    if name in ("Cargo.lock",) or name.endswith(".lock"):
        return "a lock file (versions only)"
    if "/permissions/autogenerated/" in path or "/gen/schemas/" in path:
        return "generated by Tauri's own build (one file per command, no logic)"
    if path.startswith("backend/patch-history/"):
        return "an earlier version of a patch, kept so the installer recognises it"
    # Any text file, not only Python: the face shapes (critters-gen.js,
    # faces-spec.js, CritterShaders.kt) are generated too.
    try:
        with open(os.path.join(ROOT, path), encoding="utf-8") as f:
            head = f.read(600)
    except (OSError, UnicodeDecodeError):
        return "not readable as text"
    if "GENERATED by" in head or "GENERATED BY" in head or "Generated by tools/" in head:
        return "generated data, made by a script in tools/ (the script itself is in bundle 5)"
    return ""


def split(paths, budget):
    """Cut one session's files into parts of at most `budget` characters,
    keeping a folder's files together where possible (files stay in path
    order, so neighbours share a folder). A single file bigger than the
    budget gets a part of its own."""
    parts, cur, size = [], [], 0
    for p in paths:
        n = os.path.getsize(os.path.join(ROOT, p))
        if cur and size + n > budget:
            parts.append(cur)
            cur, size = [], 0
        cur.append(p)
        size += n
    if cur:
        parts.append(cur)
    return parts


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--since", default=LAST_AUDIT)
    ap.add_argument("--out", default=os.path.join(os.path.expanduser("~"), "jarvis-gemini-audit"))
    ap.add_argument("--budget", type=int, default=400,
                    help="largest file, in thousands of tokens (default 400)")
    a = ap.parse_args()
    # About four characters to a token for code; leave room for the headers.
    budget = a.budget * 1000 * 4 - 40_000

    head = git("rev-parse", "--short", "HEAD").strip()
    branch = git("rev-parse", "--abbrev-ref", "HEAD").strip()
    base = git("rev-parse", "--short", a.since).strip()
    base_date = git("log", "-1", "--format=%cs", a.since).strip()
    status = {}
    for line in git("diff", "--name-status", "--diff-filter=AM", a.since, "HEAD").splitlines():
        kind, path = line.split("\t", 1)
        status[path] = "NEW" if kind == "A" else "CHANGED"
    commits = len(git("rev-list", f"{a.since}..HEAD").split())

    os.makedirs(a.out, exist_ok=True)
    totals = []
    placed = set()
    jobs = []
    for key, title, wanted in SESSIONS:
        paths = sorted(p for p in status if wanted(p) and os.path.isfile(os.path.join(ROOT, p)))
        placed.update(paths)
        inc_all = [p for p in paths if not why_left_out(p)]
        out = [(p, why_left_out(p)) for p in paths if why_left_out(p)]
        parts = split(inc_all, budget) or [[]]
        for i, inc in enumerate(parts, 1):
            k = key if len(parts) == 1 else f"{key}-part{i}-of-{len(parts)}"
            t = title if len(parts) == 1 else f"{title} (part {i} of {len(parts)})"
            jobs.append((k, t, inc, out if i == 1 else []))
    # Changed source files no session claims: listed in the first bundle,
    # so "not in any bundle" is never silent.
    SOURCE = (".py", ".patch", ".ps1", ".rs", ".js", ".mjs", ".html", ".css", ".kt",
              ".kts", ".xml", ".toml", ".yml", ".sh", ".glsl")
    orphans = sorted(p for p in status if p not in placed
                     and not p.startswith(("videos/", "docs/", "brag-output/"))
                     and os.path.splitext(p)[1] in SOURCE and not why_left_out(p)
                     and os.path.isfile(os.path.join(ROOT, p)))
    for n, (key, title, inc, out) in enumerate(jobs):
        body = []
        w = body.append
        w(f"# Jarvis audit bundle {key}: {title}")
        w("")
        w(f"Commit `{head}` on `{branch}`. Every file below was ADDED or CHANGED "
          f"after `{base}` (the last outside audit, {base_date}) - {commits} commits later. "
          "Each file is shown whole, as it is now, not as a diff.")
        w("")
        w(f"## The {len(inc)} files in this bundle")
        w("")
        for p in inc:
            w(f"- `{p}` - {status[p]}, {os.path.getsize(os.path.join(ROOT, p)) // 1024 + 1} KB")
        w("")
        w(f"## Changed but NOT in this bundle ({len(out)}), and why")
        w("")
        w("Listed so that \"not here\" never reads as \"does not exist\".")
        w("")
        for p, why in out:
            w(f"- `{p}` - {why}")
        if not out:
            w("- (none, or listed in part 1 of this session)")
        if n == 0 and orphans:
            w("")
            w(f"## Changed source files in NO bundle ({len(orphans)})")
            w("")
            w("No session claims these (a new folder, or a file type the sessions do not "
              "cover). Ask for any you want to see.")
            w("")
            for p in orphans:
                w(f"- `{p}`")
        w("")
        for p in inc:
            with open(os.path.join(ROOT, p), encoding="utf-8", errors="replace") as f:
                text = f.read()
            fence = "````" if "```" in text else "```"
            w(f"---\n\n## FILE: `{p}` ({status[p]})\n")
            w(f"{fence}{LANG.get(os.path.splitext(p)[1], 'text')}")
            w(text.rstrip("\n"))
            w(fence)
            w("")
        dest = os.path.join(a.out, f"jarvis-audit-{key}.md")
        with open(dest, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(body) + "\n")
        totals.append((dest, len(inc), os.path.getsize(dest)))

    print(f"Since {base} ({commits} commits), at {head} on {branch}:")
    for dest, n, size in totals:
        print(f"  {dest}  -  {n} files, {size // 1024} KB (about {size // 4000}k tokens)")
    if orphans:
        print(f"  ({len(orphans)} changed source files are in no bundle - listed in the first one)")
    print(f"The prompt to paste is docs/GEMINI-AUDIT-2026-09-28.md. The files are in {a.out}")


if __name__ == "__main__":
    sys.exit(main())
