#!/usr/bin/env python3
"""Writes backend/jarvis_wakebank.py: other voices saying "hey Jarvis", as the
numbers the owner's wake-word verifier is trained against.

    python3 tools/gen_wakebank.py <piper-voice-dir> <wakeword-model-dir> [speakers]

WHY. The verifier (backend/jarvis_wakeword.py, build_verifier) learns the
owner's "hey Jarvis" from the "Train my voice" sentences. Trained on the
owner alone it still let most OTHER voices through - it had never heard
another voice say the phrase. So it is also shown a bank of other voices
saying it, marked "not the owner". This script makes that bank.

WHERE THE VOICES COME FROM. Piper's LibriTTS-R voice (904 speakers,
`vits-piper-en_US-libritts_r-medium` from the sherpa-onnx releases:
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/
vits-piper-en_US-libritts_r-medium.tar.bz2, SHA-256
10DC268F3E371696D721486123E2705A9FC1FAA113491979FDE4D88DBA1F1B1C), run by
sherpa-onnx. Speakers 0..N-1 each say "Hey Jarvis, what is the time?" and
"Hey Jarvis." at a random speed and loudness. Synthetic voices, not people:
no recording of anyone is involved or shipped.

WHAT IS SHIPPED. Not audio. For each clip, the openWakeWord embeddings
(96 numbers per 80 ms) around the moments its "hey jarvis" model scored at
least MIN_SCORE, at most MAX_WINDOWS such moments. The verifier looks at
windows of 16 consecutive embeddings; consecutive windows share 15 of
their 16, so storing the run of embeddings once instead of each window
separately is about six times smaller. 8 bits per number, one scale per
embedding dimension. Base64 in a Python file, so apply-patches.ps1 ships
it like any other module.

Needs sherpa-onnx, onnxruntime and numpy. Deterministic for a given set of
model files.
"""
import base64
import random
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "backend"))

PHRASES = ("Hey Jarvis, what is the time?", "Hey Jarvis.")
MIN_SCORE = 0.3
MAX_WINDOWS = 10


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    voice, wake = Path(sys.argv[1]), Path(sys.argv[2])
    speakers = int(sys.argv[3]) if len(sys.argv) > 3 else 150
    import sherpa_onnx
    import jarvis_wakeword as W
    W.model_dir = lambda: wake
    models = W._load()
    if models is None:
        print("the wake-word models did not load from", wake)
        return 1
    tts = sherpa_onnx.OfflineTts(sherpa_onnx.OfflineTtsConfig(model=sherpa_onnx.OfflineTtsModelConfig(
        vits=sherpa_onnx.OfflineTtsVitsModelConfig(
            model=str(voice / "en_US-libritts_r-medium.onnx"), tokens=str(voice / "tokens.txt"),
            data_dir=str(voice / "espeak-ng-data")),
        num_threads=4)))
    rng = random.Random(0)
    runs, offsets = [], []
    for sid in range(speakers):
        for text in PHRASES:
            a = tts.generate(text, sid=sid, speed=rng.choice((0.9, 1.0, 1.1)))
            x = np.asarray(a.samples, np.float32)
            if not len(x):
                continue
            x = W.to_16k(x, a.sample_rate)
            x = x / (float(np.abs(x).max()) or 1.0) * rng.uniform(0.3, 0.9)
            x = np.concatenate([np.zeros(4000, np.float32), x, np.zeros(4000, np.float32)])
            scores, windows = W._clip_steps(models, x, 16000)
            keep = [int(i) for i in np.argsort(scores)[::-1][:MAX_WINDOWS]
                    if scores[i] >= MIN_SCORE]
            if not keep:
                continue
            first, last = min(keep), max(keep)
            rows = [np.asarray(windows[first], np.float32)]
            rows += [np.asarray(windows[i], np.float32)[-1:] for i in range(first + 1, last + 1)]
            runs.append(np.concatenate(rows))
            offsets.append(sorted(i - first for i in keep))
    emb = np.concatenate(runs)
    scale = (np.abs(emb).max(axis=0) / 127.0 + 1e-12).astype(np.float32)
    q = np.clip(np.round(emb / scale), -127, 127).astype(np.int8)
    count = sum(len(o) for o in offsets)
    out = HERE.parent / "backend" / "jarvis_wakebank.py"
    b64 = base64.b64encode(q.tobytes()).decode()
    lines = [b64[i:i + 100] for i in range(0, len(b64), 100)]
    clips = [[len(r), o] for r, o in zip(runs, offsets)]
    out.write_text(
        '"""jarvis_wakebank.py - other voices saying "hey Jarvis", as numbers.\n\n'
        "GENERATED by tools/gen_wakebank.py - do not edit by hand; run that\n"
        "script to remake it. Shipped whole beside jarvis_hud.py\n"
        "(apply-patches.ps1 copies it); read only by jarvis_wakeword.build_verifier.\n\n"
        f"{count} windows of openWakeWord embeddings from {len(runs)} clips of synthetic\n"
        "Piper LibriTTS-R voices saying \"hey Jarvis\" (16 x 96 numbers per\n"
        "window, stored as runs of embeddings, 8 bits per number). Not audio,\n"
        "and no real person's voice. The verifier is trained to say \"not the\n"
        "owner\" to these. Licences: THIRD-PARTY-NOTICES.txt (LibriTTS-R is\n"
        "CC BY 4.0; the embedding model is openWakeWord's, CC BY-NC-SA 4.0).\n"
        '"""\n'
        "import base64\n\n"
        f"COUNT = {count}\n"
        "#: [embeddings in the run, [window offsets in it]] per clip.\n"
        f"CLIPS = {clips!r}\n"
        f"SCALE = {[float(v) for v in scale]!r}\n"
        "EMBEDDINGS = (\n" + "\n".join(f'    "{l}"' for l in lines) + "\n)\n\n\n"
        "def windows():\n"
        '    """float32 array, COUNT x 1536: each a window of 16 embeddings,\n'
        "    flattened. numpy is imported here, not at the top, so importing this\n"
        '    module never fails where numpy is missing."""\n'
        "    import numpy as np\n"
        '    q = np.frombuffer(base64.b64decode("".join(EMBEDDINGS)), dtype=np.int8)\n'
        "    emb = q.reshape(-1, 96).astype(np.float32) * np.asarray(SCALE, dtype=np.float32)\n"
        "    out, at = [], 0\n"
        "    for rows, offsets in CLIPS:\n"
        "        for o in offsets:\n"
        "            out.append(emb[at + o:at + o + 16].reshape(-1))\n"
        "        at += rows\n"
        "    return np.stack(out)\n",
        encoding="utf-8")
    print(f"wrote {out}: {count} windows from {len(runs)} clips, "
          f"{out.stat().st_size // 1024} KiB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
