"""Writes index.html (landscape, 30 s) and vertical.html (upright, 15 s).

Both cuts share the scene markup, so it lives here once. Edit this file,
then run:  python3 tools/build_html.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEAD = '''<!doctype html>
<html lang="en">
  <!-- Generated by tools/build_html.py: edit that, not this. -->
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={w}, height={h}" />
    <title>{title}</title>
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/{timing}.js"></script>
    <script src="assets/{audio}.js"></script>
    <script src="assets/reactor.js" charset="utf-8"></script>
    <link rel="stylesheet" href="assets/film.css" />
{extra}  </head>
  <body class="{cls}">
    <svg width="0" height="0" style="position: absolute" aria-hidden="true">
      <filter id="rgbsplit" x="-4%" y="-4%" width="108%" height="108%" color-interpolation-filters="sRGB">
        <feColorMatrix in="SourceGraphic" type="matrix" values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" result="r" />
        <feOffset id="rgb-r" in="r" dx="0" dy="0" result="ro" />
        <feColorMatrix in="SourceGraphic" type="matrix" values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0" result="g" />
        <feColorMatrix in="SourceGraphic" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0" result="b" />
        <feOffset id="rgb-b" in="b" dx="0" dy="0" result="bo" />
        <feBlend in="ro" in2="g" mode="screen" result="rg" />
        <feBlend in="rg" in2="bo" mode="screen" />
      </filter>
    </svg>
'''

FINGERPRINT = '''<svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="54" class="track" /><circle cx="60" cy="60" r="54" class="ring" id="fp-ring" />
                  <g class="print"><path d="M40 74c0-14 9-24 20-24s20 10 20 24" /><path d="M47 82c-1-4-1-8-1-10 0-9 6-15 14-15s14 6 14 15c0 5-1 9-3 13" />
                  <path d="M54 88c-1-5-1-11-1-15 0-5 3-8 7-8s7 3 7 8c0 7-1 12-3 16" /><path d="M60 72c0 7 0 13-2 19" /><path d="M34 62c4-12 14-20 26-20s22 8 26 20" /></g></svg>'''

PHONE_TELL = '''          <!-- Redrawn Android phone. The notification's words are jarvis-client's own:
               Schedule.kt TELLME_TITLE "Tell me when", the backend's "An email from Alex arrived."
               and ScheduleNotifier.kt's "Stop" action on the "Alarms and urgent alerts" channel. -->
          <div class="phone" id="phone-t">
            <div class="ringw" id="ring-a"></div><div class="ringw" id="ring-b"></div>
            <div class="scr"><div class="sb"><span>12:30</span><i class="cam"></i><span>▾ ▮</span></div>
              <div class="clock">12:30</div>
              <div class="notif" id="notif-t"><div class="app"><b>Jarvis</b> · Alarms and urgent alerts</div>
                <div class="ti">Tell me when</div><div class="tx">An email from Alex arrived.</div><div class="act">Stop</div></div>
            </div>
          </div>
'''

PHONE_STOP = '''          <!-- Redrawn Android phone: HomeScreen.kt's red "Stop everything" button and its hint, word for word. -->
          <div class="phone" id="phone-s">
            <div class="scr"><div class="sb"><span>12:30</span><i class="cam"></i><span>▾ ▮</span></div>
              <div class="redbtn">Stop everything</div>
              <div class="redhint">Stops Jarvis talking and anything it is doing on the PC or this phone. Asks nothing first; approves nothing.</div>
            </div>
          </div>
'''

PHONE_FINGER = '''          <!-- Android's own fingerprint sheet (BiometricGate.kt): the card's title, then its "why"
               (email-send.patch's risk line). Fingerprint or PIN is the default. -->
          <div class="phone" id="phone-f">
            <div class="scr"><div class="sb"><span>12:30</span><i class="cam"></i><span>▾ ▮</span></div>
              <div class="sheet"><div class="st">Jarvis wants to send an email</div>
                <div class="ss">sends the email shown on the card from your own account, to exactly the people it lists; once sent it cannot be taken back</div>
                ''' + FINGERPRINT + '''
                <div class="pin">Use PIN</div></div>
            </div>
          </div>
'''

HELLO = '''          <!-- Drawn Windows Hello prompt. Its message is jarvis_owner_check.approval_message():
               the card's title, then the risk table's "why" for send_email. -->
          <div id="hello"><div class="hd">Windows Security</div><div class="big">Making sure it’s you</div>
            <div class="msg">Jarvis wants to send an email<br />sends the email shown on the card from your own account, to exactly the people it lists; once sent it cannot be taken back</div>
            <div class="face"><svg viewBox="0 0 70 70" fill="none" stroke="#6fe3ff" stroke-width="3"><rect x="6" y="6" width="58" height="58" rx="14" /><circle cx="25" cy="29" r="3" /><circle cx="45" cy="29" r="3" /><path d="M24 46c6 6 16 6 22 0" /></svg>Windows Hello</div>
          </div>
'''

KEYS = '''          <div class="keys"><span class="key" id="key-alt">ALT</span><span class="plus">+</span><span class="key" id="key-shift">SHIFT</span><span class="plus">+</span><span class="key x" id="key-x">X</span></div>
'''

TOAST = '''          <!-- Drawn Windows notification. Title and text are the desktop's own (hotkeys.rs "Stop everything";
               commands.rs "Stopped speaking. " + jarvis_stop_all.py's message for an answer in progress). -->
          <div id="toast"><div class="ap">Jarvis</div><div class="ti">Stop everything</div>
            <div class="tx">Stopped speaking. Stopped everything. The answer being written now uses no more tools, even if you approve a card it raised.</div></div>
'''

OUTRO = '''        <section id="s8" class="clip" data-start="{start}" data-duration="{dur}" data-track-index="6">
          <div id="scrim" class="layer"></div>
          <div class="outro mach">
            <div class="gt glow-ink" id="o1" data-text="YOUR ASSISTANT."></div>
            <div class="gt glow-ink" id="o2" data-text="YOUR PC."></div>
            <div class="gt glow-ink" id="o3" style="color: #c7b8ff" data-text="YOUR RULES."></div>
          </div>
{ready}          <div id="wordmark">JARVIS</div>
        </section>
'''

HUD = '''      <div id="scan" class="layer"></div>
      <div id="grain" class="layer"><div class="tex"></div></div>
      <div id="vignette" class="layer"></div>
      <div id="hud" class="layer">
        <svg class="br tl0" viewBox="0 0 64 64"><path d="M2 62 L2 2 L62 2" /></svg>
        <svg class="br tr0" viewBox="0 0 64 64"><path d="M2 2 L62 2 L62 62" /></svg>
        <svg class="br bl0" viewBox="0 0 64 64"><path d="M2 2 L2 62 L62 62" /></svg>
        <svg class="br br0" viewBox="0 0 64 64"><path d="M2 62 L62 62 L62 2" /></svg>
        <div class="hud-t" id="hud-a">JARVIS // LOCAL-FIRST · V4</div>
        <div class="hud-t" id="hud-ctx"></div>
        <div class="hud-t" id="hud-r"><i id="hud-dot"></i><span id="hud-state"></span></div>
        <div class="hud-t" id="hud-beat"></div>
        <div class="hud-t" id="hud-tc"></div>
      </div>
      <div id="cap"><b id="cap-who"></b><span id="cap-text"></span></div>
      <div id="flash" class="layer"></div>
      <div id="fade" class="layer"></div>
'''

CAMERA_OPEN = '''      <div id="bg" class="layer"></div>
      <div id="camera" class="layer"><div id="push" class="layer"><div id="punch" class="layer"><div id="shake" class="layer">
        <!-- The reactor: jarvis-desktop/src/faces.html, drawn every frame. -->
        <div id="hero-wrap"><canvas id="hero" width="1400" height="1400"></canvas></div>
'''
CAMERA_CLOSE = '''      </div></div></div></div>
'''


def land():
    s = HEAD.format(w=1920, h=1080, title="Jarvis v4: Cutting-edge, and it still asks first", timing="timing",
                    audio="audio-data", extra="", cls="land")
    s += '''    <div id="root" data-composition-id="jarvis-brag-v4" data-start="0" data-width="1920" data-height="1080" data-duration="30">
''' + CAMERA_OPEN + '''
        <div id="flare-host" data-composition-id="vfx-anamorphic-flare" data-composition-src="compositions/vfx-anamorphic-flare.html"
             data-variable-values='{"tint":"#8a7bff","backdrop":"#04070c","intensity":9,"streakLength":1.8,"emitters":90,"timeScale":0.6}'
             style="filter: grayscale(1) sepia(0.7) hue-rotate(208deg) saturate(3.2) brightness(1.05)"
             data-start="25.5" data-duration="4.5" data-track-index="1" data-width="1920" data-height="1080"></div>

        <section id="s0" class="clip" data-start="0" data-duration="2" data-track-index="3">
          <div class="center-x line mach"><div class="gt glow-ink" id="edge" data-text="CUTTING-EDGE."></div></div>
        </section>

        <!-- 1: it lives on your PC -->
        <section id="s1" class="clip" data-start="2" data-duration="3.5" data-track-index="3">
          <!-- Real capture: the desktop widget (widget.html), its LOCAL badge. -->
          <img class="shot" id="local-shot" src="assets/ui/widget-local.png" alt="" />
          <div id="room"><svg viewBox="0 0 780 780"><circle cx="390" cy="390" r="380" fill="none" stroke="#6fe3ff" stroke-width="3" stroke-opacity="0.8" />
            <circle cx="390" cy="390" r="366" fill="none" stroke="#6fe3ff" stroke-width="1" stroke-opacity="0.3" stroke-dasharray="4 14" /></svg></div>
          <div class="rtag" id="tag-email">EMAIL</div><div class="rtag" id="tag-files">FILES</div><div class="rtag" id="tag-mem">MEMORIES</div>
          <div id="room-label">HANDLED BY THE AI ON YOUR PC</div>
          <div class="tl" id="tl-local"><i>LOCAL AI MODEL</i> · YOUR EMAIL, FILES AND MEMORIES ARE HANDLED ONLY BY IT</div>
          <div class="tl" id="tl-net">PHONE ↔ PC OVER YOUR PRIVATE NETWORK · NEVER A PUBLIC TUNNEL</div>
        </section>

        <!-- 2: focus -->
        <section id="s2" class="clip" data-start="5.5" data-duration="4" data-track-index="3">
          <div class="tl" id="tl-focus"><i>WATCHES THE PC ONLY</i> · KEEPS COUNTS, NEVER WHAT IT SAW</div>
          <div class="chip" id="in-front">IN FRONT ▸ YOUTUBE</div>
          <!-- Real captures: Brain › Work › "Focus session" (brain.js), running, then its report card. -->
          <img class="shot" id="focus-run" src="assets/ui/focus-running.png" alt="" />
          <img class="shot" id="focus-rep" src="assets/ui/focus-report.png" alt="" />
        </section>

        <!-- 3: tell me when -->
        <section id="s3" class="clip" data-start="9.5" data-duration="3" data-track-index="3">
          <div class="tl" id="tl-tell"><i>ONE YES TO SET UP</i> · URGENT RINGS UNTIL YOU LOOK · NEVER REPLIES</div>
          <!-- Real capture: the quick-ask approval card, its text from jarvis_tellme's own describe. -->
          <img class="shot" id="tell-card" src="assets/ui/tellme-card.png" alt="" />
          <div class="chip" id="tell-ok">✓ APPROVED</div>
''' + PHONE_TELL + '''        </section>

        <!-- 4: stop everything -->
        <section id="s4" class="clip" data-start="12.5" data-duration="2.5" data-track-index="3">
          <div class="tl" id="tl-stop"><i>ALT+SHIFT+X</i> · STOPS TALKING · HALTS BEFORE ITS NEXT STEP</div>
''' + KEYS + TOAST + '''        </section>

        <!-- 5: and it still asks first -->
        <section id="s5" class="clip" data-start="15" data-duration="4" data-track-index="3">
          <div class="center-x line mach"><div class="gt glow-ink" id="asks" data-text="AND IT STILL ASKS FIRST."></div></div>
          <div class="chip" id="ready-mail">READY · EMAIL SENDING IS OFF UNTIL YOU TURN IT ON</div>
          <!-- Real capture: the quick-ask approval card, its text from jarvis_email_send.describe(). -->
          <img class="shot" id="mail-card" src="assets/ui/email-card.png" alt="" />
''' + HELLO + '''          <div class="chip" id="approved">✓ APPROVED</div>
          <div class="tl" id="tl-asks"><i>WINDOWS HELLO ON THE PC</i> · FINGERPRINT OR PIN ON THE PHONE · NO “ALWAYS ALLOW”</div>
        </section>

        <!-- 6: instant answers -->
        <section id="s6" class="clip" data-start="19" data-duration="3" data-track-index="3">
          <div class="tl" id="tl-instant"><i>ANSWERED WITHOUT THE AI MODEL</i> · WORKS WHILE IT SLEEPS</div>
          <div class="chip" id="asleep">AI MODEL ▸ ASLEEP</div>
          <!-- Real capture: the quick-ask bar, the reply and "Done - answered on this PC without the AI model." -->
          <img class="shot" id="timer-shot" src="assets/ui/timer.png" alt="" />
        </section>

        <!-- 7: it learns you -->
        <section id="s7" class="clip" data-start="22" data-duration="3.5" data-track-index="3">
          <div class="tl" id="tl-learn"><i>LEARNS FROM YOUR OWN WORDS ONLY</i> · SENSITIVE TOPICS WAIT FOR YOUR YES</div>
          <!-- Real captures: Brain › Memory, "Saved automatically" (Forget, Erase the words), "Waiting for you". -->
          <div class="shot" id="mem-saved"><img src="assets/ui/memory-saved.png" alt="" style="display:block;width:100%" /><div class="press" id="press-erase"></div></div>
          <img class="shot" id="mem-sens" src="assets/ui/memory-sensitive.png" alt="" />
        </section>

''' + OUTRO.format(start=25.5, dur=4.5, ready='          <div class="tl" id="tl-ready">READY FOR A SECOND GRAPHICS CARD ▸ LONGER CONVERSATIONS · PICTURES</div>\n') + CAMERA_CLOSE + HUD + '''
      <audio id="score" src="assets/music/score.mp3" data-start="0" data-duration="30" data-track-index="20" data-volume="1"></audio>
    </div>

    <script src="assets/film.js"></script>
    <script>
      (function () {
        var H = window.TIMING.hits;
        FILM.run({
          id: "jarvis-brag-v4", dur: 30, H: H,
          hero: [[0, "standby"], [0.9, "thinking"], [2, "idle"], [6.9, "speaking"], [8.2, "idle"], [19, "standby"], [25.5, "thinking"]],
          // [start, end, x, y, scale from, scale to, opacity]
          frames: [[0, 2, 0, -60, 0.9, 0.98, 1], [2, 5.5, 330, 0, 0.42, 0.45, 1], [6.9, 8.2, 520, 60, 0.42, 0.44, 1],
                   [12.5, 15, 0, 40, 0.95, 0.98, 0.3], [19, 22, -560, 40, 0.55, 0.58, 1], [25.5, 30, 0, 0, 1.25, 1.45, 1]],
          drift: [[0, 2], [2, 5.5], [5.5, 9.5], [9.5, 12.5], [15, 19], [19, 22], [22, 25.5], [25.5, 30]],
          hits: [["edge", 1], ["local", 0.6], ["focus", 0.6], ["report", 0.7], ["tell", 0.6], ["ring", 0.3], ["stop", 1], ["toast", 0.3],
                 ["asks", 0.6], ["asksLine", 0.9], ["hello", 0.4], ["ok", 0.35], ["instant", 0.6], ["answer", 0.35],
                 ["learn", 0.6], ["sensitive", 0.4], ["outro", 1], ["pc", 0.7], ["rules", 0.9], ["logo", 0.35]],
          context: [[0, "HOST ▸ YOUR PC"], [2, "MODEL ▸ LOCAL · ON YOUR GRAPHICS CARD"], [5.5, "FOCUS ▸ WATCHING THE PC ONLY"],
                    [9.5, "TELL ME WHEN ▸ ONE CARD TO SET UP"], [12.5, "STOP EVERYTHING ▸ ALT+SHIFT+X"], [15, "APPROVAL ▸ REQUIRED · NEVER AUTOMATIC"],
                    [19, "QUICK ANSWER ▸ NO AI MODEL"], [22, "MEMORY ▸ FROM YOUR OWN WORDS"], [25.5, "JARVIS ▸ YOUR ASSISTANT"]],
          beats: [[0, "00 / 07  ·  CUTTING-EDGE"], [2, "01 / 07  ·  LOCAL"], [5.5, "02 / 07  ·  FOCUS"], [9.5, "03 / 07  ·  TELL ME WHEN"],
                  [12.5, "04 / 07  ·  STOP"], [15, "05 / 07  ·  ASKS FIRST"], [19, "06 / 07  ·  INSTANT"], [22, "07 / 07  ·  LEARNS YOU"], [25.5, "JARVIS  ·  V4"]],
          caps: [[5.6, 6.95, "you", "Focus for 30 minutes.", 0.5], [7.0, 8.3, "jarvis", "YouTube can wait.", 0.4],
                 [9.6, 11.4, "you", "Tell me when an email from Alex arrives. Urgently.", 0.9], [19.1, 20.6, "you", "Set a timer for 10 minutes.", 0.5]]
        });
      })();
    </script>
  </body>
</html>
'''
    return s


def tall():
    s = HEAD.format(w=1080, h=1920, title="Jarvis v4 (upright)", timing="timing-vertical", audio="audio-data-vertical",
                    extra='    <link rel="stylesheet" href="assets/film-tall.css" />\n', cls="tall")
    s += '''    <!-- The 15 s upright cut: the same scenes re-laid-out for a phone held upright. Words stay out of
         the top 200 px and the bottom 300 px, where short-video apps draw their own buttons. -->
    <div id="root" data-composition-id="jarvis-brag-v4-vertical" data-start="0" data-width="1080" data-height="1920" data-duration="15">
''' + CAMERA_OPEN + '''
        <section id="s0" class="clip" data-start="0" data-duration="1.2" data-track-index="3">
          <div class="center-x line mach"><div class="gt glow-ink" id="edge" data-text="CUTTING-EDGE."></div></div>
        </section>
        <section id="s2" class="clip" data-start="1.2" data-duration="2.8" data-track-index="3">
          <div class="tl" id="tl-focus"><i>WATCHES THE PC ONLY</i><br />KEEPS COUNTS, NEVER WHAT IT SAW</div>
          <div class="chip" id="in-front">IN FRONT ▸ YOUTUBE</div>
          <img class="shot" id="focus-run" src="assets/ui/focus-running.png" alt="" />
          <img class="shot" id="focus-rep" src="assets/ui/focus-report.png" alt="" />
        </section>
        <section id="s3" class="clip" data-start="4" data-duration="2.3" data-track-index="3">
          <div class="tl" id="tl-tell"><i>ONE YES TO SET UP</i><br />RINGS UNTIL YOU LOOK · NEVER REPLIES</div>
          <img class="shot" id="tell-card" src="assets/ui/tellme-card.png" alt="" />
          <div class="chip" id="tell-ok">✓ APPROVED</div>
''' + PHONE_TELL + '''        </section>
        <section id="s4" class="clip" data-start="6.3" data-duration="1.7" data-track-index="3">
          <div class="tl" id="tl-stop"><i>ALT+SHIFT+X</i><br />HALTS BEFORE ITS NEXT STEP</div>
''' + KEYS + TOAST + '''        </section>
        <section id="s5" class="clip" data-start="8" data-duration="3.2" data-track-index="3">
          <div class="center-x line mach"><div class="gt glow-ink" id="asks" data-text="IT STILL ASKS FIRST."></div></div>
          <div class="chip" id="ready-mail">READY · EMAIL SENDING IS OFF UNTIL YOU TURN IT ON</div>
          <img class="shot" id="mail-card" src="assets/ui/email-card.png" alt="" />
''' + PHONE_FINGER + '''          <div class="chip" id="approved">✓ APPROVED</div>
          <div class="tl" id="tl-asks"><i>FINGERPRINT OR PIN</i> · NO “ALWAYS ALLOW”</div>
        </section>
''' + OUTRO.format(start=11.2, dur=3.8, ready='') + CAMERA_CLOSE + HUD + '''
      <audio id="score" src="assets/music/score-vertical.mp3" data-start="0" data-duration="15" data-track-index="20" data-volume="1"></audio>
    </div>

    <script src="assets/film.js"></script>
    <script>
      (function () {
        var H = window.TIMING.hits;
        FILM.run({
          id: "jarvis-brag-v4-vertical", dur: 15, H: H,
          hero: [[0, "standby"], [0.15, "thinking"], [1.2, "idle"], [2.2, "speaking"], [3.0, "idle"], [11.2, "thinking"]],
          frames: [[0, 1.2, 0, 80, 0.9, 0.96, 1], [6.3, 8, 0, 60, 0.95, 0.98, 0.3], [11.2, 15, 0, 180, 0.85, 0.95, 1]],
          drift: [[0, 1.2], [1.2, 4], [4, 6.3], [8, 11.2], [11.2, 15]],
          hits: [["edge", 1], ["focus", 0.6], ["report", 0.7], ["tell", 0.6], ["ring", 0.3], ["stop", 1], ["toast", 0.3],
                 ["asks", 0.6], ["asksLine", 0.9], ["ok", 0.35], ["outro", 1], ["pc", 0.7], ["rules", 0.9], ["logo", 0.35]],
          context: [[0, "HOST ▸ YOUR PC"], [1.2, "FOCUS ▸ PC ONLY"], [4, "TELL ME WHEN"], [6.3, "STOP EVERYTHING"], [8, "APPROVAL ▸ REQUIRED"], [11.2, "JARVIS"]],
          beats: [[0, "CUTTING-EDGE"], [1.2, "01 · FOCUS"], [4, "02 · TELL ME WHEN"], [6.3, "03 · STOP"], [8, "04 · ASKS FIRST"], [11.2, "JARVIS · V4"]],
          caps: [[1.25, 2.15, "you", "Focus for 30 minutes.", 0.4], [2.2, 3.0, "jarvis", "YouTube can wait.", 0.3],
                 [4.05, 5.3, "you", "Tell me when an email from Alex arrives. Urgently.", 0.7]]
        });
      })();
    </script>
  </body>
</html>
'''
    return s


(ROOT / "index.html").write_text(land(), encoding="utf-8")
(ROOT / "vertical.html").write_text(tall(), encoding="utf-8")
print("wrote index.html and vertical.html")
