#!/usr/bin/env python3
"""Turn `jarvis-visual-spec.json` into a script the Faces window can load.

The reactor kit was written with the spec pasted inline as `const SPEC = {…}`.
That was the right call for a single-file reference page and the wrong one for
the app: the pasted copy had gone stale — seven states where the live spec has
eight, so `banked` could not be bound at all — and nothing could have told
anyone, because two hand-maintained copies of the same data do not complain.

So the JSON stays the single source and this generates the script tag from it.
A plain `<script src>` is evaluated synchronously before the renderer runs,
which means the kit's 3,800 lines of drawing code need no restructuring into
something that can await a fetch.

`tests/faces.mjs` regenerates this and fails if what is committed differs, so
the two cannot drift again.

    python3 scripts/build-faces-spec.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "src" / "jarvis-visual-spec.json"
OUT = HERE.parent / "src" / "faces-spec.js"

BANNER = """\
// GENERATED by scripts/build-faces-spec.py from jarvis-visual-spec.json.
// Do not edit: edit the JSON and re-run `npm run faces:spec`.
//
// This exists so the Faces window and the Rust tray read one spec rather than
// two. `spec.rs` compiles the same JSON in with `include_str!`; the kit this
// window came from had its own pasted copy, which had drifted to seven states
// against the live eight.
"""


def main() -> None:
    spec = json.loads(SRC.read_text(encoding="utf-8"))
    # Sorted keys and a stable indent so the generated file only changes when
    # the spec does — otherwise every run is a diff and the drift test is noise.
    body = json.dumps(spec, indent=2, sort_keys=True, ensure_ascii=False)
    OUT.write_text(
        f"{BANNER}window.JARVIS_SPEC = Object.freeze({body});\n", encoding="utf-8"
    )
    states = [s["id"] for s in spec["states"]]
    print(f"{OUT.name}: {len(spec['faces'])} faces, {len(spec['patterns'])} patterns, "
          f"{len(states)} states ({', '.join(states)})")


if __name__ == "__main__":
    main()
