// Builds composition/assets/reactor.js from the shipped desktop renderer.
// Everything between the markers is copied verbatim from faces.html; only the
// driver at the bottom is new, and it exists to make the faces seekable.
import fs from "node:fs";

const [, , facesPath, specPath, outPath] = process.argv;
const L = fs.readFileSync(facesPath, "utf8").split("\n");
const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));

const lines = (a, b) => L.slice(a - 1, b).join("\n");
const findLine = (re, from = 1) => {
  for (let i = from - 1; i < L.length; i++) if (re.test(L[i])) return i + 1;
  throw new Error("not found: " + re);
};

// Shared maths: TAU .. fresnel (stops before the inline HDRI data URI).
const helpersStart = findLine(/^const TAU = Math\.PI \* 2;/);
const fresnelStart = findLine(/^function fresnel\(/);
const helpersEnd = findLine(/^}/, fresnelStart);
// Icosphere for Geodesic.
const icoStart = findLine(/^const ICO = \(\(\) => \{/);
const icoEnd = findLine(/^}\)\(\);/, icoStart);
// Colour resolver block: hsl2hex .. end of resolve().
const hslStart = findLine(/^function hsl2hex\(/);
const resolveStart = findLine(/^function resolve\(bind, t, amp, seed\)/);
const resolveEnd = findLine(/^}/, resolveStart);

function theme(id) {
  const idLine = findLine(new RegExp(`^  id:"${id}"`));
  if (L[idLine - 2].trim() !== "{") throw new Error("theme open brace missing for " + id);
  const end = findLine(/^},?\s*$/, idLine);
  return lines(idLine - 1, end).replace(/,\s*$/, "");
}

const FACES = ["arc", "orbit", "geodesic", "rime", "fullerene", "spiral", "orbital"];

// Only what resolve() reads: palette colours, patterns, per-state defaults, flash limits.
const miniSpec = {
  palette: { colors: spec.palette.colors.map(c => ({ id: c.id, family: c.family, hex: c.hex })) },
  patterns: spec.patterns,
  states: spec.states.map(s => ({ id: s.id, default: s.default })),
  limits: spec.limits ? { flash: spec.limits.flash } : undefined,
  approval_clock_s: spec.state_transforms?.approval_clock_s,
};

const out = `/* Jarvis reactor faces, lifted from jarvis-desktop/src/faces.html.
 * Generated by extract-reactor.mjs. Do not edit the verbatim blocks by hand;
 * regenerate instead. Faces: ${FACES.join(", ")}. */
(function(){
"use strict";
const SPEC = ${JSON.stringify(miniSpec)};

/* ---- verbatim: faces.html ${helpersStart}-${helpersEnd} ---- */
${lines(helpersStart, helpersEnd)}

/* ---- verbatim: faces.html ${icoStart}-${icoEnd} ---- */
${lines(icoStart, icoEnd)}

/* ---- stand-ins for the shell globals the faces read ---- */
const HUD = { amp:0, bass:0, mid:0, treble:0, beat:0, raw:0 };
// drawSurface() publishes the resolved colours here as [hot, dim, mid].
let PC = ["#6fe3ff", "#1d5f7a", "#46a1bd"];
let GPUPX = 512, GPUOK = false, BATCH_OK = false, BATCH_TRIED = false, GPU_TOUCHED = false;
// No GPU in the render: every face takes its own canvas path, exactly as it
// does in the kit when WebGL is unavailable.
const PTS = { begin(){ return false; }, get active(){ return false; }, add(){}, flush(){ return false; } };
const CMAP = {};
SPEC.palette.colors.forEach(c => CMAP[c.id] = c.hex);
const hexOf = id => CMAP[id] || id || "#6fe3ff";

/* ---- verbatim: faces.html ${hslStart}-${resolveEnd} ---- */
${lines(hslStart, resolveEnd)}

/* ---- verbatim: the faces ---- */
const THEMES = [
${FACES.map(theme).join(",\n\n")}
];

/* ---- driver: new. Makes a face a pure function of timeline time. ---- */
const THEME = {}; THEMES.forEach(t => THEME[t.id] = t);
const BIND = {}; SPEC.states.forEach(s => BIND[s.id] = s.default);
const BG = "#04070c";

function seedOf(str){ let h = 2166136261; for (const ch of str) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; }
function prng(seed){ let a = seed >>> 0; return function(){ a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }

// Same as faces.html withOverride(): the bound state colour replaces the face's
// own hot/dim slots for the duration of one draw.
const HOT_KEY = /^(hot|a)$/, DIM_KEY = /^(col|glow|b)$/;
function withOverride(th, state, col, fn){
  const st = th.st && th.st[state];
  if(!st || !col){ fn(); return; }
  const keys = Object.keys(st).filter(k => typeof st[k] === "string" && /^#[0-9a-f]{6}$/i.test(st[k]));
  const saved = keys.map(k => st[k]);
  const mid = mix(col.a, col.b, .5);
  keys.forEach(k => { st[k] = HOT_KEY.test(k) ? col.a : DIM_KEY.test(k) ? col.b : mid; });
  try { fn(); } finally { keys.forEach((k, i) => st[k] = saved[i]); }
}

const GLOW = new Map();
function glow(g, w, h, hex, strength){
  const q = parseCol(hex).map(v => Math.round(v / 17) * 17);
  const key = q.join(",") + "|" + w;
  let c = GLOW.get(key);
  if(!c){
    const px = Math.min(512, Math.round(Math.min(w, h) * 0.92 / 32) * 32);
    c = document.createElement("canvas"); c.width = c.height = px;
    const gg = c.getContext("2d"), r = px / 2, col = "rgb(" + q.join(",") + ")";
    const gr = gg.createRadialGradient(r, r, 0, r, r, r);
    gr.addColorStop(0, rgba(col, .55)); gr.addColorStop(.35, rgba(col, .22));
    gr.addColorStop(.7, rgba(col, .06)); gr.addColorStop(1, rgba(col, 0));
    gg.fillStyle = gr; gg.fillRect(0, 0, px, px);
    if(GLOW.size > 48) GLOW.clear();
    GLOW.set(key, c);
  }
  const size = Math.min(w, h) * 0.92;
  g.save(); g.globalCompositeOperation = "lighter"; g.globalAlpha = Math.min(1, strength);
  g.drawImage(c, (w - size) / 2, (h - size) / 2, size, size); g.restore();
}

// The approval "waiting clock" and knock ring, from faces.html drawStateOverlay().
const CLOCK_S = SPEC.approval_clock_s || 8;
function waitingClock(g, w, h, age, col){
  const cx = w / 2, cy = h / 2, R = Math.min(w, h) * 0.44;
  const lead = Math.min(1, age / 0.22);
  const frac = Math.min(1, 0.12 * lead + (Math.max(0, age - 0.22) / CLOCK_S) * 0.88);
  g.save();
  g.globalAlpha = 0.35; g.strokeStyle = col.b; g.lineWidth = Math.max(1, w * 0.004);
  g.beginPath(); g.arc(cx, cy, R * 0.95, 0, TAU); g.stroke();
  g.globalAlpha = 0.9; g.strokeStyle = col.a; g.lineWidth = Math.max(1.5, w * 0.010); g.lineCap = "round";
  g.beginPath(); g.arc(cx, cy, R * 0.95, -Math.PI / 2, -Math.PI / 2 + frac * TAU); g.stroke();
  const k = (age % 1.6) / 0.4;
  if(k <= 1){
    const e = 1 - Math.pow(1 - k, 3);
    g.globalAlpha = (1 - e) * 0.55; g.strokeStyle = col.a; g.lineWidth = Math.max(1, w * 0.008 * (1 - e * 0.5));
    g.beginPath(); g.arc(cx, cy, R * (0.12 + e * 0.82), 0, TAU); g.stroke();
  }
  g.restore();
}

// Motion tables: approval/standby/banked borrow idle, error borrows thinking.
const MOTION = { approval:"idle", standby:"idle", banked:"idle", error:"thinking" };

function surface(canvas, faceId){
  const th = THEME[faceId];
  if(!th) throw new Error("no face " + faceId);
  // One instance per canvas: faces cache geometry on \`this\`, keyed to size.
  const inst = Object.create(th);
  return { canvas, g: canvas.getContext("2d"), th: inst, id: faceId };
}

/* o: { t, phase, state, amp, beat, col, glow, clear, fxAge, quality, yaw, pitch, zoom } */
function draw(s, o){
  const g = s.g, w = s.canvas.width, h = s.canvas.height;
  const state = o.state || "idle";
  const motion = (s.th.st && s.th.st[state]) ? state : (MOTION[state] || "idle");
  const col = o.col || resolve(BIND[state] || BIND.idle, o.t || 0, o.amp || 0, 0);
  VIEW = { yaw: o.yaw || 0, pitch: o.pitch || 0, zoom: o.zoom || 1 };
  TOUCH = { x:0, y:0, on:0, hover:0, f:0 };
  PHASE = o.phase || 0;
  QUALITY = o.quality || 1;
  DEPTH_GAIN = 1.6;
  HUD.amp = o.amp || 0; HUD.beat = o.beat || 0;
  PC = [col.a, col.b, mix(col.a, col.b, .5)];
  g.setTransform(1,0,0,1,0,0);
  if(o.clear !== false){ g.globalAlpha = 1; g.globalCompositeOperation = "source-over"; g.fillStyle = BG; g.fillRect(0, 0, w, h); }
  if(o.glow) glow(g, w, h, col.a, o.glow);
  const rnd = Math.random;
  Math.random = prng(seedOf(s.id));
  try {
    withOverride(s.th, motion, col, () => {
      g.save(); s.th.draw(g, w, h, o.t || 0, motion, o.amp || 0); g.restore();
    });
  } finally { Math.random = rnd; }
  g.globalAlpha = 1; g.globalCompositeOperation = "source-over";
  if(state === "approval") waitingClock(g, w, h, o.fxAge || 0, col);
  return col;
}

function colours(state, t, amp){ return resolve(BIND[state] || BIND.idle, t, amp || 0, 0); }
function speedOf(faceId, state){
  const th = THEME[faceId], m = (th.st && th.st[state]) ? state : (MOTION[state] || "idle");
  return (th.st && th.st[m] && typeof th.st[m].sp === "number") ? th.st[m].sp : 1;
}

window.REACTOR = { surface, draw, colours, speedOf, mix, lift, rgba, BG, faces: THEMES.map(t => ({ id: t.id, name: t.name, geo: t.geo })) };
})();
`;
fs.writeFileSync(outPath, out);
console.log("wrote", outPath, out.length, "bytes;", "helpers", helpersStart + "-" + helpersEnd, "ico", icoStart + "-" + icoEnd, "resolve", hslStart + "-" + resolveEnd);
